-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2016
-- Author: Juan Castillo
-- ALTER date: 22/01/2016
-- Description: Obtiene la secuencia en base a la clave recibida
-- =============================================
-- =============================================

CREATE PROCEDURE [ADM].[SP_OBTIENE_SECUENCIA]
		@P_NO_SECUENCIA NVARCHAR(20) OUTPUT,
		@POUT_CLAVE_RETORNO          NVARCHAR(40) OUT,    --APLICA PARA REGRESAR UN NÚMERO DE (ERROR, ERROR CONTROLADO, O IDENTIFICADOR)
		@POUT_MENSAJE_RETORNO        NVARCHAR(200) OUT,   --APLICA PARA REGRESAR EL TEXTO A MOSTRAR EN LA APLICACIÓN (ERROR, MENSAJE CONTROLADO)
		@P_CL_SECUENCIA NVARCHAR(30),
		@P_ID_EMPRESA UNIQUEIDENTIFIER
AS     
 BEGIN  		 
	SET @P_NO_SECUENCIA=(
		SELECT TOP 1
			ISNULL(CS.CL_PREFIJO, '')
			+ RIGHT(REPLICATE('0', NO_DIGITOS) + CAST(NO_ULTIMO_VALOR AS NVARCHAR(20)), NO_DIGITOS)
			+ ISNULL(CS.CL_SUFIJO, '')
		FROM ADM.C_SECUENCIA CS WHERE CL_SECUENCIA = @P_CL_SECUENCIA 
	)
          
	UPDATE ADM.C_SECUENCIA SET NO_ULTIMO_VALOR = NO_ULTIMO_VALOR + 1 WHERE CL_SECUENCIA = @P_CL_SECUENCIA;								           
 END
