-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Jesús Vázquez Pereyra
-- CREATE date: 10/11/2015
-- Description: Obtiene los datos de la tabla C_CAMPO_ADICIONAL 
-- =============================================
CREATE PROCEDURE [ADM].[SPE_OBTIENE_C_CAMPO_ADICIONAL_XML]  
    @PIN_XML_SEARCH AS xml
	,@PIN_ID_CAMPO AS int = NULL
	, @PIN_CL_CAMPO AS nvarchar(32) = NULL
	, @PIN_NB_CAMPO AS nvarchar(100) = NULL
	, @PIN_DS_CAMPO AS nvarchar(200) = NULL
	, @PIN_FG_REQUERIDO AS bit = NULL
	, @PIN_NO_VALOR_DEFECTO AS nvarchar(200) = NULL
	, @PIN_CL_TIPO_DATO AS nvarchar(20) = NULL
	, @PIN_CL_DIMENSION AS nvarchar(20) = NULL
	, @PIN_CL_TABLA_REFERENCIA AS nvarchar(50) = NULL
	, @PIN_CL_ESQUEMA_REFERENCIA AS nvarchar(10) = NULL
	, @PIN_FG_MOSTRAR AS bit = NULL
	, @PIN_ID_CATALOGO_LIST AS int = NULL
	, @PIN_FG_ADICIONAL AS bit = NULL
	
AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT 
		a.[ID_CAMPO]
		, a.[CL_CAMPO]
		, CONCAT (x.id,'_',CL_CAMPO) AS CL_TABLE_CAMPO
		,a. [NB_CAMPO]
		, a.[DS_CAMPO]
		, a.[FG_REQUERIDO]
		, a.[NO_VALOR_DEFECTO]
		, a.[CL_TIPO_DATO]
		, a.[CL_DIMENSION]
		, a.[CL_TABLA_REFERENCIA]
		, a.[CL_ESQUEMA_REFERENCIA]
		, a.[FG_MOSTRAR]
		, a.[ID_CATALOGO_LIST]
		, a.[FG_ADICIONAL]
	FROM ADM.C_CAMPO_ADICIONAL as a

	inner join (select   m.c.value('@ID', 'NVARCHAR(max)') as id FROM @PIN_XML_SEARCH.nodes('/root/row1/value') as m(c))AS x 
	ON x.id = A.[CL_TABLA_REFERENCIA]
	WHERE (@PIN_ID_CAMPO IS NULL OR (@PIN_ID_CAMPO IS NOT NULL AND [ID_CAMPO] = @PIN_ID_CAMPO))
			 AND (@PIN_CL_CAMPO IS NULL OR (@PIN_CL_CAMPO IS NOT NULL AND [CL_CAMPO] = @PIN_CL_CAMPO))
			 AND (@PIN_NB_CAMPO IS NULL OR (@PIN_NB_CAMPO IS NOT NULL AND [NB_CAMPO] = @PIN_NB_CAMPO))
			 AND (@PIN_DS_CAMPO IS NULL OR (@PIN_DS_CAMPO IS NOT NULL AND [DS_CAMPO] = @PIN_DS_CAMPO))
			 AND (@PIN_FG_REQUERIDO IS NULL OR (@PIN_FG_REQUERIDO IS NOT NULL AND [FG_REQUERIDO] = @PIN_FG_REQUERIDO))
			 AND (@PIN_NO_VALOR_DEFECTO IS NULL OR (@PIN_NO_VALOR_DEFECTO IS NOT NULL AND [NO_VALOR_DEFECTO] = @PIN_NO_VALOR_DEFECTO))
			 AND (@PIN_CL_TIPO_DATO IS NULL OR (@PIN_CL_TIPO_DATO IS NOT NULL AND [CL_TIPO_DATO] = @PIN_CL_TIPO_DATO))
			 AND (@PIN_CL_DIMENSION IS NULL OR (@PIN_CL_DIMENSION IS NOT NULL AND [CL_DIMENSION] = @PIN_CL_DIMENSION))
			 AND (@PIN_CL_TABLA_REFERENCIA IS NULL OR (@PIN_CL_TABLA_REFERENCIA IS NOT NULL AND [CL_TABLA_REFERENCIA] = @PIN_CL_TABLA_REFERENCIA))
			 AND (@PIN_CL_ESQUEMA_REFERENCIA IS NULL OR (@PIN_CL_ESQUEMA_REFERENCIA IS NOT NULL AND [CL_ESQUEMA_REFERENCIA] = @PIN_CL_ESQUEMA_REFERENCIA))
			 AND (@PIN_FG_MOSTRAR IS NULL OR (@PIN_FG_MOSTRAR IS NOT NULL AND [FG_MOSTRAR] = @PIN_FG_MOSTRAR))
			 AND (@PIN_ID_CATALOGO_LIST IS NULL OR (@PIN_ID_CATALOGO_LIST IS NOT NULL AND [ID_CATALOGO_LIST] = @PIN_ID_CATALOGO_LIST))
			 AND (@PIN_FG_ADICIONAL IS NULL OR (@PIN_FG_ADICIONAL IS NOT NULL AND [FG_ADICIONAL] = @PIN_FG_ADICIONAL))
			 AND (@PIN_FG_ADICIONAL IS NULL OR (@PIN_FG_ADICIONAL IS NOT NULL AND [FG_ADICIONAL] = @PIN_FG_ADICIONAL))
			

		/*	EXECUTE [ADM].[SPE_OBTIENE_C_CAMPO_ADICIONAL_XML]  '
<root>
  <row1>
    <value ID="C_ESCOLARIDAD" ></value>
	<value ID="[C_COMPETENCIA]"></value>
  </row1>
</root>
',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
*/