
-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Abraham Ramirez
-- CREATE date: 21/09/2015
-- Description: Obtiene los datos de la tabla C_AREA_INTERES 
-- =============================================
CREATE PROCEDURE [ADM].[SPE_OBTIENE_C_AREA_INTERES] 
	@PIN_ID_AREA_INTERES AS int = NULL
	, @PIN_CL_AREA_INTERES AS nvarchar(20) = NULL
	, @PIN_NB_AREA_INTERES AS nvarchar(200) = NULL
	, @PIN_FG_ACTIVO AS bit = NULL
	
AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT 
		[ID_AREA_INTERES]
		, [CL_AREA_INTERES]
		, [NB_AREA_INTERES]
		, [FG_ACTIVO]
		,(CASE WHEN FG_ACTIVO=1 THEN 'Si'
			WHEN FG_ACTIVO=0 THEN 'No'
		END)AS NB_ACTIVO
		,'' as DS_FILTRO
	FROM ADM.C_AREA_INTERES
	WHERE (@PIN_ID_AREA_INTERES IS NULL OR (@PIN_ID_AREA_INTERES IS NOT NULL AND [ID_AREA_INTERES] = @PIN_ID_AREA_INTERES))
			 AND (@PIN_CL_AREA_INTERES IS NULL OR (@PIN_CL_AREA_INTERES IS NOT NULL AND [CL_AREA_INTERES] = @PIN_CL_AREA_INTERES))
			 AND (@PIN_NB_AREA_INTERES IS NULL OR (@PIN_NB_AREA_INTERES IS NOT NULL AND [NB_AREA_INTERES] = @PIN_NB_AREA_INTERES))
			 AND (@PIN_FG_ACTIVO IS NULL OR (@PIN_FG_ACTIVO IS NOT NULL AND [FG_ACTIVO] = @PIN_FG_ACTIVO))
			
