-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Juan De Dios Pérez Pedroza
-- CREATE date: 23/11/2015
-- Description: Obtiene los datos de la tabla C_COMPETENCIA_NIVEL 
-- =============================================
CREATE PROCEDURE ADM.SPE_OBTIENE_C_COMPETENCIA_NIVEL 
	@PIN_ID_NIVEL_COMPETENCIA AS int = NULL
	, @PIN_CL_NIVEL_COMPETENCIA AS nvarchar(20) = NULL
	, @PIN_NB_NIVEL_COMPETENCIA AS nvarchar(100) = NULL
	, @PIN_DS_NIVEL_COMPETENCIA_PUESTO AS nvarchar(200) = NULL
	, @PIN_DS_NIVEL_COMPETENCIA_PERSONA AS nvarchar(200) = NULL
	, @PIN_NO_VALOR_NIVEL AS decimal(10,2) = NULL
	, @PIN_ID_COMPETENCIA AS int = NULL
	
AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT 
		[ID_NIVEL_COMPETENCIA]
		, [CL_NIVEL_COMPETENCIA]
		, [NB_NIVEL_COMPETENCIA]
		, [DS_NIVEL_COMPETENCIA_PUESTO]
		, [DS_NIVEL_COMPETENCIA_PERSONA]
		, [NO_VALOR_NIVEL]
		, [ID_COMPETENCIA]
		
		,'' as DS_FILTRO
	FROM ADM.C_COMPETENCIA_NIVEL
	WHERE (@PIN_ID_NIVEL_COMPETENCIA IS NULL OR (@PIN_ID_NIVEL_COMPETENCIA IS NOT NULL AND [ID_NIVEL_COMPETENCIA] = @PIN_ID_NIVEL_COMPETENCIA))
			 AND (@PIN_CL_NIVEL_COMPETENCIA IS NULL OR (@PIN_CL_NIVEL_COMPETENCIA IS NOT NULL AND [CL_NIVEL_COMPETENCIA] = @PIN_CL_NIVEL_COMPETENCIA))
			 AND (@PIN_NB_NIVEL_COMPETENCIA IS NULL OR (@PIN_NB_NIVEL_COMPETENCIA IS NOT NULL AND [NB_NIVEL_COMPETENCIA] = @PIN_NB_NIVEL_COMPETENCIA))
			 AND (@PIN_DS_NIVEL_COMPETENCIA_PUESTO IS NULL OR (@PIN_DS_NIVEL_COMPETENCIA_PUESTO IS NOT NULL AND [DS_NIVEL_COMPETENCIA_PUESTO] = @PIN_DS_NIVEL_COMPETENCIA_PUESTO))
			 AND (@PIN_DS_NIVEL_COMPETENCIA_PERSONA IS NULL OR (@PIN_DS_NIVEL_COMPETENCIA_PERSONA IS NOT NULL AND [DS_NIVEL_COMPETENCIA_PERSONA] = @PIN_DS_NIVEL_COMPETENCIA_PERSONA))
			 AND (@PIN_NO_VALOR_NIVEL IS NULL OR (@PIN_NO_VALOR_NIVEL IS NOT NULL AND [NO_VALOR_NIVEL] = @PIN_NO_VALOR_NIVEL))
			 AND (@PIN_ID_COMPETENCIA IS NULL OR (@PIN_ID_COMPETENCIA IS NOT NULL AND [ID_COMPETENCIA] = @PIN_ID_COMPETENCIA))
			
