-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Margarita Salcedo
-- CREATE date: 14/12/2015
-- Description: Obtiene los datos de la tabla K_SOLICITUD 
-- =============================================
CREATE PROCEDURE [ADM].[SPE_OBTIENE_EMPLEADO] 
	 @PIN_ID_EMPLEADO AS int = NULL

	
AS   
BEGIN
--ONE STEP--------------------------------------------
	DECLARE 
	   
       @ID_PUESTO AS INT
      ,@ID_CANDIDATO AS INT
      ,@ID_EMPRESA AS INT
	  ,@CL_EMPLEADO AS NVARCHAR(20)
	  ,@NB_EMPLEADO_COMPLETO AS NVARCHAR(200)
	  ,@XML_EMPRESAS AS XML
	  ,@XML_CANDIDATOS AS XML
	  ,@XML_PUESTOS AS XML
	  ,@XML_CATALOGOS AS XML
----------------------------------------------------

--SECOND STEP---------------------------------------- 
		SELECT
		  @ID_PUESTO= ME.[ID_PUESTO]  
		, @ID_CANDIDATO= ME.[ID_CANDIDATO] 
		, @ID_EMPRESA= ME.[ID_EMPRESA] 
		, @CL_EMPLEADO = ME.CL_EMPLEADO
		, @NB_EMPLEADO_COMPLETO= CONCAT ( ME.[NB_EMPLEADO], ' ',ME.[NB_APELLIDO_PATERNO],' ' , ME.[NB_APELLIDO_MATERNO] )
		
		FROM ADM.M_EMPLEADO AS ME
			LEFT OUTER JOIN ADM.M_PUESTO AS MP ON MP.ID_PUESTO =ME.ID_PUESTO
			LEFT OUTER JOIN ADM.C_CANDIDATO AS CC ON CC.ID_CANDIDATO =ME.ID_CANDIDATO
			LEFT OUTER JOIN ADM.C_EMPRESA AS CE ON CE.ID_EMPRESA =ME.ID_EMPRESA
		WHERE ME.ID_EMPLEADO = @PIN_ID_EMPLEADO
----THIRD STEP-----------------------------------------------		
	SET @XML_CANDIDATOS = (
		SELECT 
		  CC.[NB_CANDIDATO] + ' ' + CC.[NB_APELLIDO_PATERNO] + ' ' + CC.[NB_APELLIDO_MATERNO] AS "@NB_CANDIDATO"
		, CC.[CL_GENERO] AS "@CL_GENERO"
		, CC.[CL_RFC] AS "@CL_RFC"
		, CC.[CL_CURP] AS "@CL_CURP"
		, CC.[CL_ESTADO_CIVIL] AS "@CL_ESTADO_CIVIL"
		, CC.[NB_CONYUGUE] AS "@NB_CONYUGUE"
		, CC.[CL_NSS] AS "@CL_NSS"
		, CC.[CL_TIPO_SANGUINEO] AS "@CL_TIPO_SANGUINEO"
		, CC.[NB_PAIS] AS "@NB_PAIS"
		, CC.[NB_ESTADO] AS "@NB_ESTADO"
		, CC.[NB_MUNICIPIO] AS "@NB_MUNICIPIO"
		, CC.[NB_COLONIA] AS "@NB_COLONIA"
		, CC.[NB_CALLE] AS "@NB_CALLE"
		, CC.[NO_INTERIOR] AS "@NO_INTERIOR"
		, CC.[NO_EXTERIOR] AS "@NO_EXTERIOR"
		, CC.[CL_CODIGO_POSTAL] AS "@CL_CODIGO_POSTAL"
		, CC.[CL_CORREO_ELECTRONICO] AS "@CL_CORREO_ELECTRONICO"
		, CC.[FE_NACIMIENTO] AS "@FE_NACIMIENTO"
		, CC.[DS_LUGAR_NACIMIENTO] AS "@DS_LUGAR_NACIMIENTO"
		, CC.[MN_SUELDO] AS "@MN_SUELDO"
		, CC.[CL_NACIONALIDAD] AS "@CL_NACIONALIDAD"
		, CC.[DS_NACIONALIDAD] AS "@DS_NACIONALIDAD"
		, CC.[NB_LICENCIA] AS "@NB_LICENCIA"
		, CC.[DS_VEHICULO] AS "@DS_VEHICULO"
		, CC.[CL_CARTILLA_MILITAR] AS "@CL_CARTILLA_MILITAR"
		, CC.[CL_CEDULA_PROFESIONAL] AS "@CL_CEDULA_PROFESIONAL"
		--, CC.[XML_TELEFONOS] AS "@XML_TELEFONOS"
		--, CC.[XML_INGRESOS] AS "@XML_INGRESOS"
		--, CC.[XML_EGRESOS] AS "@XML_EGRESOS"
		--, CC.[XML_PATRIMONIO] AS "@XML_PATRIMONIO"
		, CC.[DS_DISPONIBILIDAD] AS "@DS_DISPONIBILIDAD"
		, CC.[CL_DISPONIBILIDAD_VIAJE] AS "@CL_DISPONIBILIDAD_VIAJE"
		--, CC.[XML_PERFIL_RED_SOCIAL] AS "@XML_PERFIL_RED_SOCIAL"
		, CC.[DS_COMENTARIO] AS "@DS_COMENTARIO"
		, CC.[FG_ACTIVO] AS "@FG_ACTIVO"

		FROM ADM.C_CANDIDATO CC
		WHERE (@ID_CANDIDATO IS NULL OR (@ID_CANDIDATO IS NOT NULL AND CC.ID_CANDIDATO = @ID_CANDIDATO))
		FOR XML PATH ('CANDIDATO'), ROOT ('CANDIDATOS')
	)



	SET @XML_EMPRESAS = (
		SELECT 
          CE.CL_EMPRESA AS "@CL_EMPRESA"
		, CE.NB_EMPRESA AS "@NB_EMPRESA"
		, CE.NB_RAZON_SOCIAL AS "@NB_RAZON_SOCIAL"
		FROM ADM.C_EMPRESA CE
		WHERE (@ID_EMPRESA IS NULL OR (@ID_EMPRESA IS NOT NULL AND CE.ID_EMPRESA = @ID_EMPRESA))
		FOR XML PATH ('EMPRESA'), ROOT ('EMPRESAS')
	)



	SET @XML_PUESTOS = (
		SELECT 
		  MP.FG_ACTIVO AS "@FG_ACTIVO"
		, (CASE WHEN MP.[FG_ACTIVO] =1 THEN 'Sí' WHEN MP.[FG_ACTIVO] =0 THEN 'No' END)  AS "@NB_ACTIVO"
		, MP.FE_INACTIVO  AS "@FE_INACTIVO"
		, MP.CL_PUESTO AS "@CL_PUESTO"
		, MP.NB_PUESTO AS "@NB_PUESTO"
		--, MP.ID_PUESTO_JEFE AS "@ID_PUESTO_JEFE"
		, MP.ID_DEPARTAMENTO AS "@ID_DEPARTAMENTO"
		--, MP.XML_CAMPOS_ADICIONALES AS "@XML_CAMPOS_ADICIONALES"
		, MP.ID_BITACORA AS "@ID_BITACORA"
	   
	   FROM ADM.M_PUESTO MP
	   LEFT OUTER JOIN ADM.M_DEPARTAMENTO MD ON MD.ID_DEPARTAMENTO = MP.ID_DEPARTAMENTO
	   WHERE (@ID_PUESTO IS NULL OR (@ID_PUESTO IS NOT NULL AND MP.ID_PUESTO = @ID_PUESTO))
		FOR XML PATH ('PUESTO'), ROOT ('PUESTOS')
		
	)

	---------------------------------------------------------

---FOURTH STEP----------------------------------------------------
       SET @XML_CATALOGOS = (
		SELECT @XML_CANDIDATOS
			, @XML_EMPRESAS
			, @XML_PUESTOS
		FOR XML PATH ('CATALOGOS')
	)
	--------------------------------------------------------------
--FIFTH STEP------------------------------------------------------
		SELECT 
	     @ID_PUESTO AS ID_PUESTO
        ,@ID_CANDIDATO AS ID_CANDIDATO
		,@ID_EMPRESA AS ID_EMPRESA
		,@CL_EMPLEADO AS CL_EMPLEADO
		,@NB_EMPLEADO_COMPLETO AS NB_EMPLEADO_COMPLETO
		, @XML_CATALOGOS AS XML_CATALOGOS
------------------------------------------------------------------
END

--SIXTH STEP-------------------------------------
--EXECUTE [ADM].[SPE_OBTIENE_EMPLEADO] 1