-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Gabriel Vázquez Torres
-- CREATE date: 06/01/2016
-- Description: Obtiene los datos de la tabla C_CAMPO_ADICIONAL 
-- =============================================
CREATE PROCEDURE [ADM].[SPE_OBTIENE_CAMPO_ADICIONAL_XML]
	@PIN_CL_TABLA_REFERENCIA AS nvarchar(50) = NULL
AS
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	DECLARE @XML_CAMPOS_ADICIONALES AS XML

	SET @XML_CAMPOS_ADICIONALES = (
		SELECT 
			CASE 
				WHEN ID_CATALOGO_LIST <> 0 THEN 'COMBOBOX'
				WHEN ID_CATALOGO_LIST = 0 THEN 'TEXTBOX'
			END AS '@CL_TIPO',
			FG_REQUERIDO AS '@FG_REQUERIDO',
			FG_MOSTRAR AS '@FG_HABILITADO',
			CL_CAMPO AS '@ID_CAMPO',
			CL_DIMENSION AS '@NO_LONGUITUD',
			NB_CAMPO AS '@NB_CAMPO',
			DS_CAMPO AS '@NB_TOOLTIP',
			(
				SELECT 
					cv.CL_CATALOGO_VALOR AS '@NB_VALOR',
					cv.NB_CATALOGO_VALOR AS '@NB_TEXTO'
				FROM ADM.C_CATALOGO_VALOR cv
				WHERE cv.ID_CATALOGO_LISTA = ca.ID_CATALOGO_LIST
				FOR XML PATH('ITEM'), TYPE, ROOT('ITEMS')
			) 
		FROM ADM.C_CAMPO_ADICIONAL ca
		WHERE CL_TABLA_REFERENCIA = @PIN_CL_TABLA_REFERENCIA AND FG_ADICIONAL = 1
		FOR XML PATH('CAMPO'), ROOT('CAMPOS_ADICIONLAES')
	)

	SELECT ISNULL(@XML_CAMPOS_ADICIONALES,'<CAMPOS_ADICIONALES></CAMPOS_ADICIONALES>') AS XML_CAMPOS_ADICIONALES

		/*	EXECUTE [ADM].[SPE_OBTIENE_C_CAMPO_ADICIONAL_XML]  '
<root>
  <row1>
    <value ID="C_ESCOLARIDAD" ></value>
	<value ID="[C_COMPETENCIA]"></value>
  </row1>
</root>
',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
*/