-- =============================================
-- Proyecto: Sigein 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Daniela Sanchez
-- CREATE date: 18/12/2015
-- Description: Obtiene los centros administrativos
-- =============================================

CREATE PROCEDURE [ADM].[SPE_OBTIENE_CENTROS_ADMVOS]
	@PIN_ID_CENTRO_ADMVO AS Uniqueidentifier = NULL,
	@PIN_NB_MUNICIPIO AS nvarchar(100) = NULL,
	@PIN_CL_ESTADO AS nvarchar(10) = NULL,
	@PIN_CL_CODIGO_POSTAL AS nvarchar(10)= NULL,
	@PIN_CL_ZONA_ECONOMICA AS nchar (1)= NULL,
	@PIN_CL_MUNICIPIO AS nvarchar (10)= NULL


AS   
	SELECT 
	ID_CENTRO_ADMVO
      ,CL_CLIENTE
      ,ID_REGISTRO_PATRONAL
      ,CL_CENTRO_ADMVO
      ,NB_CENTRO_ADMVO
      ,NB_CALLE
      ,NB_NO_EXTERIOR
      ,NB_NO_INTERIOR
      ,CL_MUNICIPIO
      ,NB_COLONIA
      ,NB_MUNICIPIO
      ,CL_ESTADO
	  ,NB_ESTADO
      ,CL_CODIGO_POSTAL
      ,CL_ZONA_ECONOMICA

	  ,concat(NB_CALLE,' ',NB_NO_EXTERIOR,' ',NB_NO_INTERIOR,' ', NB_COLONIA, ' ') AS DOMICILIO
		
	 FROM ADM.C_CENTRO_ADMVO AS CA
	WHERE (@PIN_ID_CENTRO_ADMVO IS NULL OR (@PIN_ID_CENTRO_ADMVO IS NOT NULL AND CA.ID_CENTRO_ADMVO =@PIN_ID_CENTRO_ADMVO )
	   AND @PIN_NB_MUNICIPIO IS NULL OR (@PIN_NB_MUNICIPIO IS NOT NULL AND CA.NB_MUNICIPIO =@PIN_NB_MUNICIPIO )
	   AND @PIN_CL_ESTADO IS NULL OR (@PIN_CL_ESTADO IS NOT NULL AND CA.CL_ESTADO =@PIN_CL_ESTADO )
	   AND @PIN_CL_CODIGO_POSTAL IS NULL OR (@PIN_CL_CODIGO_POSTAL IS NOT NULL AND CA.CL_CODIGO_POSTAL = @PIN_CL_CODIGO_POSTAL )
	   AND @PIN_CL_ZONA_ECONOMICA IS NULL OR (@PIN_CL_ZONA_ECONOMICA IS NOT NULL AND CA.CL_ZONA_ECONOMICA = @PIN_CL_ZONA_ECONOMICA )
	   AND @PIN_CL_MUNICIPIO IS NULL OR (@PIN_CL_MUNICIPIO IS NOT NULL AND CA.CL_MUNICIPIO = @PIN_CL_MUNICIPIO ))

	  -- EXECUTE  ADM.SPE_OBTIENE_C_CENTRO_ADMVO