-- =============================================
-- Proyecto: Sigein 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Julio Díaz
-- CREATE date: 5/12/2015
-- Description: Obtiene la autenticación del usuario
-- =============================================

CREATE PROCEDURE [ADM].[SPE_OBTIENE_USUARIO_AUTENTICACION]
	@PIN_CL_USUARIO AS NVARCHAR(50) = NULL
	,@PIN_CL_PASSWORD AS NVARCHAR(50) = NULL
	,@PIN_CL_AUTENTICACION AS NVARCHAR(50) = NULL
AS   
BEGIN
	DECLARE @CL_AUTENTICACION NVARCHAR(50) = @PIN_CL_AUTENTICACION
		, @XML_AUTORIZACION XML

	;WITH T_USUARIO AS (
		SELECT CU.CL_USUARIO
			, CU.NB_USUARIO
			, CU.NB_PASSWORD
			, CU.NB_CORREO_ELECTRONICO
			, CU.FG_ACTIVO
			, CR.ID_ROL
			, CR.NB_ROL
		FROM ADM.C_USUARIO CU
			INNER JOIN ADM.C_ROL CR
				ON CU.ID_ROL = CR.ID_ROL
		WHERE CU.CL_USUARIO = @PIN_CL_USUARIO
	)

	SELECT @CL_AUTENTICACION AS CL_AUTENTICACION
		, @XML_AUTORIZACION AS XML_AUTORIZACION
		, TU.CL_USUARIO
		, TU.NB_USUARIO
		, TU.NB_PASSWORD
		, TU.NB_CORREO_ELECTRONICO
		, TU.FG_ACTIVO
		, TU.NB_ROL
		, CONVERT(XML, ( 
			SELECT SF.CL_FUNCION AS '@CL_FUNCION'
				, SF.CL_TIPO_FUNCION AS '@CL_TIPO_FUNCION'
				, SF.ID_FUNCION AS '@ID_FUNCION'
				, SF.ID_FUNCION_PADRE AS '@ID_FUNCION_PADRE'
				, SF.NB_FUNCION AS '@NB_FUNCION'
				, SF.NB_URL AS '@NB_URL'
				, SF.NO_ORDEN AS '@NO_ORDEN'
				, SF.XML_CONFIGURACION
			FROM ADM.S_FUNCION SF
				INNER JOIN ADM.C_ROL_FUNCION CRF
					ON SF.ID_FUNCION = CRF.ID_FUNCION
				INNER JOIN T_USUARIO TU
					ON TU.ID_ROL = CRF.ID_ROL
			FOR XML PATH ('FUNCION'), ROOT('FUNCIONES')
		)) AS XML_DATA
	FROM T_USUARIO TU


END