-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Margarita Salcedo
-- CREATE date: 14/11/2015
-- Description: Obtiene los datos de la tabla C_PLANTILLA_FORMULARIO 
-- =============================================
-- 26/02/2016 JDR Se cambia de esquema el procedimiento a ADM y se agrega a la proyección el campo FG_GENERAL_CL
-- =============================================
CREATE PROCEDURE ADM.SPE_OBTIENE_C_PLANTILLA_FORMULARIO 
	@PIN_ID_PLANTILLA_SOLICITUD AS int = NULL
	, @PIN_NB_PLANTILLA_SOLICITUD AS nvarchar(20) = NULL
	, @PIN_DS_PLANTILLA_SOLICITUD AS nvarchar(100) = NULL
	, @PIN_CL_FORMULARIO AS nvarchar(20) = NULL
	, @PIN_FG_GENERAL AS bit = NULL
	
AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT 
		ID_PLANTILLA_SOLICITUD
		, NB_PLANTILLA_SOLICITUD
		, DS_PLANTILLA_SOLICITUD
		, CL_FORMULARIO
		, FG_GENERAL
		, CASE WHEN FG_GENERAL = 1 THEN 'Sí' ELSE 'No' END AS FG_GENERAL_CL
		, XML_PLANTILLA_SOLICITUD
	FROM ADM.C_PLANTILLA_FORMULARIO
	WHERE (@PIN_ID_PLANTILLA_SOLICITUD IS NULL OR (@PIN_ID_PLANTILLA_SOLICITUD IS NOT NULL AND ID_PLANTILLA_SOLICITUD = @PIN_ID_PLANTILLA_SOLICITUD))
			 AND (@PIN_NB_PLANTILLA_SOLICITUD IS NULL OR (@PIN_NB_PLANTILLA_SOLICITUD IS NOT NULL AND NB_PLANTILLA_SOLICITUD = @PIN_NB_PLANTILLA_SOLICITUD))
			 AND (@PIN_DS_PLANTILLA_SOLICITUD IS NULL OR (@PIN_DS_PLANTILLA_SOLICITUD IS NOT NULL AND DS_PLANTILLA_SOLICITUD = @PIN_DS_PLANTILLA_SOLICITUD))
			 AND (@PIN_CL_FORMULARIO IS NULL OR (@PIN_CL_FORMULARIO IS NOT NULL AND CL_FORMULARIO = @PIN_CL_FORMULARIO))
			 AND (@PIN_FG_GENERAL IS NULL OR (@PIN_FG_GENERAL IS NOT NULL AND FG_GENERAL = @PIN_FG_GENERAL))
			
