-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Abraham Ramirez
-- CREATE date: 21/09/2015
-- Description: Obtiene los datos de la tabla C_PUESTO_RELACIONADO 
-- =============================================
CREATE PROCEDURE ADM.SPE_OBTIENE_C_PUESTO_RELACIONADO 
	@PIN_ID_PUESTO AS int = NULL
	, @PIN_ID_PUESTO_RELACIONADO AS int = NULL
	, @PIN_CL_TIPO_RELACION AS nvarchar(20) = NULL
	, @PIN_DS_PUESTO_RELACIONADO AS nvarchar(500) = NULL
	
AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT 
		[ID_PUESTO]
		, [ID_PUESTO_RELACIONADO]
		, [CL_TIPO_RELACION]
		, [DS_PUESTO_RELACIONADO]
		,'' as DS_FILTRO
	FROM ADM.C_PUESTO_RELACIONADO
	WHERE (@PIN_ID_PUESTO IS NULL OR (@PIN_ID_PUESTO IS NOT NULL AND [ID_PUESTO] = @PIN_ID_PUESTO))
			 AND (@PIN_ID_PUESTO_RELACIONADO IS NULL OR (@PIN_ID_PUESTO_RELACIONADO IS NOT NULL AND [ID_PUESTO_RELACIONADO] = @PIN_ID_PUESTO_RELACIONADO))
			 AND (@PIN_CL_TIPO_RELACION IS NULL OR (@PIN_CL_TIPO_RELACION IS NOT NULL AND [CL_TIPO_RELACION] = @PIN_CL_TIPO_RELACION))
			 AND (@PIN_DS_PUESTO_RELACIONADO IS NULL OR (@PIN_DS_PUESTO_RELACIONADO IS NOT NULL AND [DS_PUESTO_RELACIONADO] = @PIN_DS_PUESTO_RELACIONADO))
			
