-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Margarita Salcedo
-- CREATE date: 21/09/2015
-- Description: Obtiene los datos de la tabla C_RESPUESTA 
-- =============================================
CREATE PROCEDURE ADM.SPE_OBTIENE_C_RESPUESTA 
	@PIN_ID_RESPUESTA AS int = NULL
	, @PIN_CL_RESPUESTA AS nvarchar(32) = NULL
	, @PIN_NB_RESPUESTA AS nvarchar(100) = NULL
	, @PIN_DS_RESPUESTA AS nvarchar(200) = NULL
	, @PIN_NO_VALOR AS decimal(8,3) = NULL
	, @PIN_FG_ACTIVO AS bit = NULL
	
AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT 
		[ID_RESPUESTA]
		, [CL_RESPUESTA]
		, [NB_RESPUESTA]
		, [DS_RESPUESTA]
		, [NO_VALOR]
		, [FG_ACTIVO]
		,'' as DS_FILTRO
	FROM ADM.C_RESPUESTA
	WHERE (@PIN_ID_RESPUESTA IS NULL OR (@PIN_ID_RESPUESTA IS NOT NULL AND [ID_RESPUESTA] = @PIN_ID_RESPUESTA))
			 AND (@PIN_CL_RESPUESTA IS NULL OR (@PIN_CL_RESPUESTA IS NOT NULL AND [CL_RESPUESTA] = @PIN_CL_RESPUESTA))
			 AND (@PIN_NB_RESPUESTA IS NULL OR (@PIN_NB_RESPUESTA IS NOT NULL AND [NB_RESPUESTA] = @PIN_NB_RESPUESTA))
			 AND (@PIN_DS_RESPUESTA IS NULL OR (@PIN_DS_RESPUESTA IS NOT NULL AND [DS_RESPUESTA] = @PIN_DS_RESPUESTA))
			 AND (@PIN_NO_VALOR IS NULL OR (@PIN_NO_VALOR IS NOT NULL AND [NO_VALOR] = @PIN_NO_VALOR))
			 AND (@PIN_FG_ACTIVO IS NULL OR (@PIN_FG_ACTIVO IS NOT NULL AND [FG_ACTIVO] = @PIN_FG_ACTIVO))
			
