-- =============================================
-- Proyecto: Sigein 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Juan Pérez
-- CREATE date: 05/12/2015
-- Description: Obtiene los generos. las escolaridades del empleado, empleado y puestos
-- =============================================

CREATE PROCEDURE [ADM].[SPE_OBTIENE_K_REQUISICION_CANDIDATO]
				
		 @PIN_ID_CANDIDATO AS INT =NULL
	AS   
	BEGIN
	DECLARE 
	      @PIN_ID_EMPLEADO INT
	    , @XML_CANDIDATOS XML
		, @XML_K_AREAS_INTERES XML
		, @XML_EMPLEADO_COMPETENCIAS XML
		, @XML_EMPLEADO_ESCOLARIDADES XML



	SET @XML_CANDIDATOS = (
	SELECT  
	       -- @PIN_ID_EMPLEADO = ME.ID_EMPLEADO ,
			CC.ID_CANDIDATO AS "@ID_CANDIDATO"
      ,		CC.NB_CANDIDATO + ' ' + CC.NB_APELLIDO_PATERNO + ' ' + CC.NB_APELLIDO_MATERNO AS "@NB_CANDIDATO"
	  ,	    CC.FG_ACTIVO AS "@FG_ACTIVO"
	  ,		DBO.F_OBTENER_EDAD(CC.FE_NACIMIENTO) AS "@NO_EDAD"

	  ,	    ME.ID_EMPLEADO AS "@ID_EMPLEADO" 
	  ,	    ME.NB_EMPLEADO + ' ' + ME.NB_APELLIDO_PATERNO + ' ' + ME.NB_APELLIDO_MATERNO AS "@NB_EMPLEADO"
	  ,		ME.CL_CORREO_ELECTRONICO AS "@CL_CORREO_ELECTRONICO" 
	  ,	    ME.CL_EMPLEADO AS "@CL_EMPLEADO" 

			FROM ADM.C_CANDIDATO CC
            JOIN ADM.M_EMPLEADO AS ME ON ME.ID_CANDIDATO = CC.ID_CANDIDATO
			WHERE( @PIN_ID_CANDIDATO IS NULL OR ( @PIN_ID_CANDIDATO IS NOT NULL AND CC.[ID_CANDIDATO] =  @PIN_ID_CANDIDATO)) 
			FOR XML PATH ('CANDIDATO'), ROOT ('CANDIDATOS')
							)

		SET @XML_EMPLEADO_COMPETENCIAS = (
	    SELECT  
				KE.ID_EMPLEADO_COMPETENCIA AS "@ID_EMPLEADO_COMPETENCIA" 
		  ,		KE.ID_EMPLEADO AS "@ID_EMPLEADO" 
		  ,		KE.ID_COMPETENCIA AS "@ID_COMPETENCIA"
		  ,		KE.NO_CALIFICACION AS "@NO_CALIFICACION"
		  ,		KE.FE_CREACION AS "@FE_CREACION"

		  ,		C_COMP.CL_CLASIFICACION AS "@CL_CLASIFICACION"
		  ,		C_COMP.CL_COMPETENCIA AS "@CL_COMPETENCIA"
		  ,		C_COMP.CL_TIPO_COMPETENCIA AS "@CL_TIPO_COMPETENCIA"
		  ,		C_COMP.DS_COMPETENCIA AS "@DS_COMPETENCIA"
		  ,		C_COMP.NB_COMPETENCIA AS "@NB_COMPETENCIA"
		  
		FROM ADM.K_EMPLEADO_COMPETENCIA KE 
		LEFT OUTER JOIN ADM.C_COMPETENCIA AS C_COMP ON C_COMP.ID_COMPETENCIA = KE.ID_COMPETENCIA
		WHERE( @PIN_ID_CANDIDATO IS NULL OR 
		(KE.[ID_EMPLEADO] IN 
		(SELECT ME.ID_EMPLEADO FROM ADM.C_CANDIDATO AS CCA 
		JOIN ADM.M_EMPLEADO ME ON ME.ID_CANDIDATO = CCA.ID_CANDIDATO
		WHERE CCA.ID_CANDIDATO= @PIN_ID_CANDIDATO)
		)   )
		   
		FOR XML PATH ('EMPLEADO_COMPETENCIA'), ROOT ('EMPLEADOS_COMPETENCIAS')
	)


	     SET  @XML_K_AREAS_INTERES = (
	     SELECT  
			KAI.ID_CANDIDATO_AREA_INTERES AS "@ID_CANDIDATO_AREA_INTERES" 
		  ,	KAI.ID_CANDIDATO AS "@ID_CANDIDATO" 
		  ,	KAI.ID_AREA_INTERES AS "@ID_AREA_INTERES" 
		  ,	KAI.FE_CREACION AS "@FE_CREACION" 
		  , CAI.CL_AREA_INTERES AS "@CL_AREA_INTERES"
		  , CAI.NB_AREA_INTERES AS "@NB_AREA_INTERES"
		 FROM ADM.K_AREA_INTERES KAI
		 LEFT OUTER JOIN ADM.C_AREA_INTERES AS CAI ON CAI.ID_AREA_INTERES = KAI.ID_AREA_INTERES
	     WHERE( @PIN_ID_CANDIDATO IS NULL OR ( @PIN_ID_CANDIDATO IS NOT NULL AND KAI.[ID_CANDIDATO] =  @PIN_ID_CANDIDATO)) 
		 FOR XML PATH ('AREA_INTERES'), ROOT ('AREAS_INTERES')
	)

	     SET  @XML_EMPLEADO_ESCOLARIDADES = (
	     SELECT  
			CEE.ID_EMPLEADO_ESCOLARIDAD AS "@ID_EMPLEADO_ESCOLARIDAD"
       ,	CEE.ID_EMPLEADO AS "@ID_EMPLEADO" 
       ,	CEE.ID_CANDIDATO AS "@ID_CANDIDATO"
	   --,	CEE.CL_INSTITUCION AS "@CL_INSTITUCION"
       ,	CEE.NB_INSTITUCION AS "@NB_INSTITUCION" 
       ,	CEE.FE_PERIODO_INICIO AS "@FE_PERIODO_INICIO"
	   ,	CEE.FE_PERIODO_FIN AS "@FE_PERIODO_FIN" 
       ,	CEE.CL_ESTADO_ESCOLARIDAD AS "@CL_ESTADO_ESCOLARIDAD"
	   ,	C_ESC.CL_NIVEL_ESCOLARIDAD AS "@CL_NIVEL_ESCOLARIDAD"
	   ,    C_ESC.CL_INSTITUCION  AS "@CL_INSTITUCION"
	   ,	C_ESC.NB_ESCOLARIDAD AS "@NB_ESCOLARIDAD"
	   ,	C_ESC.DS_ESCOLARIDAD AS "@DS_ESCOLARIDAD"
			FROM IDP.C_EMPLEADO_ESCOLARIDAD CEE
			LEFT OUTER JOIN ADM.C_ESCOLARIDAD AS C_ESC ON C_ESC.ID_ESCOLARIDAD = CEE.ID_ESCOLARIDAD
		    WHERE( @PIN_ID_CANDIDATO IS NULL OR ( @PIN_ID_CANDIDATO IS NOT NULL AND CEE.[ID_CANDIDATO] =  @PIN_ID_CANDIDATO)) 
			FOR XML PATH ('EMPLEADO_ESCOLARIDAD'), ROOT ('EMPLEADOS_ESCOLARIDAD')
	)

	SELECT
	      @PIN_ID_CANDIDATO  AS ID_CANDIDATO
		, @XML_CANDIDATOS AS XML_CANDIDATOS
		, @XML_K_AREAS_INTERES AS XML_K_AREA_INTERES
		, @XML_EMPLEADO_COMPETENCIAS AS XML_EMPLEADOS_COMPETENCIAS
		, @XML_EMPLEADO_ESCOLARIDADES AS XML_EMPLEADOS_ESCOLARIDADES
	END


--EXECUTE [ADM].[SPE_OBTIENE_K_REQUISICION_CANDIDATO] 2