-- =============================================
-- Proyecto: Sigein 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Daniela Sanchez
-- CREATE date: 28/12/2015
-- Description: Obtiene los centros operativos
-- =============================================

CREATE PROCEDURE [ADM].[SPE_OBTIENE_CENTROS_OPTVOS]
	@PIN_ID_CENTRO_OPTVO AS Uniqueidentifier = NULL,
	@PIN_CL_CENTRO_OPTVO AS nvarchar(10) = NULL,
	@PIN_NB_CENTRO_OPTVO AS nvarchar(100)=NULL,
	@PIN_NB_MUNICIPIO AS nvarchar(100) = NULL,
	@PIN_CL_ESTADO AS nvarchar(10) = NULL,
	@PIN_CL_MUNICIPIO AS nvarchar(10) = NULL,
	@PIN_CL_CODIGO_POSTAL AS nvarchar(10)= NULL

AS   
	SELECT 
	ID_CENTRO_OPTVO
      ,CL_CLIENTE
      ,CL_CENTRO_OPTVO
      ,NB_CENTRO_OPTVO
      ,NB_CALLE
      ,NB_NO_EXTERIOR
      ,NB_NO_INTERIOR
      ,NB_COLONIA    
      ,CL_ESTADO
	  ,NB_ESTADO
	  ,CL_MUNICIPIO
	  ,NB_MUNICIPIO
      ,CL_CODIGO_POSTAL
	  ,concat(NB_CALLE,' ',NB_NO_EXTERIOR,' ',NB_NO_INTERIOR,' ', NB_COLONIA, ' ') AS DOMICILIO
		
	 FROM ADM.C_CENTRO_OPTVO AS CO
	WHERE (@PIN_ID_CENTRO_OPTVO IS NULL OR (@PIN_ID_CENTRO_OPTVO IS NOT NULL AND CO.ID_CENTRO_OPTVO = @PIN_ID_CENTRO_OPTVO)
	AND @PIN_CL_CENTRO_OPTVO IS NULL OR (@PIN_CL_CENTRO_OPTVO IS NOT NULL AND CO.CL_CENTRO_OPTVO = @PIN_CL_CENTRO_OPTVO)
	AND @PIN_NB_CENTRO_OPTVO IS NULL OR (@PIN_NB_CENTRO_OPTVO IS NOT NULL AND CO.NB_CENTRO_OPTVO = @PIN_NB_CENTRO_OPTVO)
	AND @PIN_NB_MUNICIPIO IS NULL OR (@PIN_NB_MUNICIPIO IS NOT NULL AND CO.NB_MUNICIPIO = @PIN_NB_MUNICIPIO)
	AND @PIN_CL_ESTADO IS NULL OR (@PIN_CL_ESTADO IS NOT NULL AND CO.CL_ESTADO = @PIN_CL_ESTADO)
	AND @PIN_CL_CODIGO_POSTAL IS NULL OR (@PIN_CL_CODIGO_POSTAL IS NOT NULL AND CO.CL_CODIGO_POSTAL = @PIN_CL_CODIGO_POSTAL)  
	AND @PIN_CL_MUNICIPIO IS NULL OR (@PIN_CL_MUNICIPIO IS NOT NULL AND CO.CL_MUNICIPIO = @PIN_CL_MUNICIPIO))  
	  
	  
	  -- EXECUTE  ADM.SPE_OBTIENE_CENTROS_OPTVOS
