-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Margarita Salcedo
-- CREATE date: 21/09/2015
-- Description: Obtiene los datos de la tabla K_CUESTIONARIO_PREGUNTA 
-- =============================================
CREATE PROCEDURE ADM.SPE_OBTIENE_K_CUESTIONARIO_PREGUNTA 
	@PIN_ID_CUESTIONARIO_PREGUNTA AS int = NULL
	, @PIN_ID_CUESTIONARIO AS int = NULL
	, @PIN_ID_PREGUNTA AS int = NULL
	, @PIN_NB_PREGUNTA AS nvarchar(100) = NULL
	, @PIN_NB_RESPUESTA AS nvarchar(100) = NULL
	, @PIN_NO_VALOR_RESPUESTA AS decimal(8,3) = NULL
	
AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT 
		[ID_CUESTIONARIO_PREGUNTA]
		, [ID_CUESTIONARIO]
		, [ID_PREGUNTA]
		, [NB_PREGUNTA]
		, [NB_RESPUESTA]
		, [NO_VALOR_RESPUESTA]
		,'' as DS_FILTRO
	FROM ADM.K_CUESTIONARIO_PREGUNTA
	WHERE (@PIN_ID_CUESTIONARIO_PREGUNTA IS NULL OR (@PIN_ID_CUESTIONARIO_PREGUNTA IS NOT NULL AND [ID_CUESTIONARIO_PREGUNTA] = @PIN_ID_CUESTIONARIO_PREGUNTA))
			 AND (@PIN_ID_CUESTIONARIO IS NULL OR (@PIN_ID_CUESTIONARIO IS NOT NULL AND [ID_CUESTIONARIO] = @PIN_ID_CUESTIONARIO))
			 AND (@PIN_ID_PREGUNTA IS NULL OR (@PIN_ID_PREGUNTA IS NOT NULL AND [ID_PREGUNTA] = @PIN_ID_PREGUNTA))
			 AND (@PIN_NB_PREGUNTA IS NULL OR (@PIN_NB_PREGUNTA IS NOT NULL AND [NB_PREGUNTA] = @PIN_NB_PREGUNTA))
			 AND (@PIN_NB_RESPUESTA IS NULL OR (@PIN_NB_RESPUESTA IS NOT NULL AND [NB_RESPUESTA] = @PIN_NB_RESPUESTA))
			 AND (@PIN_NO_VALOR_RESPUESTA IS NULL OR (@PIN_NO_VALOR_RESPUESTA IS NOT NULL AND [NO_VALOR_RESPUESTA] = @PIN_NO_VALOR_RESPUESTA))
			
