-- =============================================
-- Proyecto: Sigein 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Margarita Salcedo
-- CREATE date: 14/09/2015
-- Description: Obtiene los C_COMPETENCIA 
-- =============================================
--JVP 07/10/2015 Se le agrega los compos de descripcion y nombre de tipo de competencia
-- =============================================
CREATE PROCEDURE [ADM].[SPE_OBTIENE_C_COMPETENCIA] 
	    @PIN_ID_COMPETENCIA AS int= NULL,
        @PIN_CL_COMPETENCIA AS nvarchar(32) = NULL,
        @PIN_NB_COMPETENCIA AS nvarchar(200) = NULL,
        @PIN_DS_COMPETENCIA AS nvarchar(200) = NULL,
        @PIN_CL_TIPO_COMPETENCIA AS nvarchar(20) = NULL,
        @PIN_CL_CLASIFICACION AS nvarchar(200) = NULL,
        @PIN_FG_ACTIVO AS bit = NULL,
        @PIN_XML_CAMPOS_ADICIONALES AS xml = NULL

AS   
	SELECT 
			C.[ID_COMPETENCIA],
			C.[CL_COMPETENCIA],
			C.[NB_COMPETENCIA],
			C.[DS_COMPETENCIA],
			C.[CL_TIPO_COMPETENCIA],
			C.[CL_CLASIFICACION],
			C.[FG_ACTIVO],
			(CASE WHEN C.[FG_ACTIVO] =1 THEN 'Sí'
			      WHEN C.[FG_ACTIVO] =1 THEN 'No' END ) AS NB_ACTIVO,
			C.[XML_CAMPOS_ADICIONALES],
			TP.DS_TIPO_COMPETENCIA,
			TP.NB_TIPO_COMPETENCIA,
			CC.NB_CLASIFICACION_COMPETENCIA,
			CC.DS_CLASIFICACION_COMPETENCIA,
			CN0.DS_NIVEL_COMPETENCIA_PUESTO AS DS_NIVEL_COMPETENCIA_PUESTO_N0,
			CN0.DS_NIVEL_COMPETENCIA_PERSONA  AS DS_NIVEL_COMPETENCIA_PERSONA_N0,
			CN1.DS_NIVEL_COMPETENCIA_PUESTO AS DS_NIVEL_COMPETENCIA_PUESTO_N1,
			CN1.DS_NIVEL_COMPETENCIA_PERSONA  AS DS_NIVEL_COMPETENCIA_PERSONA_N1,
			CN2.DS_NIVEL_COMPETENCIA_PUESTO AS DS_NIVEL_COMPETENCIA_PUESTO_N2,
			CN2.DS_NIVEL_COMPETENCIA_PERSONA  AS DS_NIVEL_COMPETENCIA_PERSONA_N2,
			CN3.DS_NIVEL_COMPETENCIA_PUESTO AS DS_NIVEL_COMPETENCIA_PUESTO_N3,
			CN3.DS_NIVEL_COMPETENCIA_PERSONA  AS DS_NIVEL_COMPETENCIA_PERSONA_N3,
			CN4.DS_NIVEL_COMPETENCIA_PUESTO AS DS_NIVEL_COMPETENCIA_PUESTO_N4,
			CN4.DS_NIVEL_COMPETENCIA_PERSONA  AS DS_NIVEL_COMPETENCIA_PERSONA_N4,
			CN5.DS_NIVEL_COMPETENCIA_PUESTO AS DS_NIVEL_COMPETENCIA_PUESTO_N5,
			CN5.DS_NIVEL_COMPETENCIA_PERSONA  AS DS_NIVEL_COMPETENCIA_PERSONA_N5
			,'' as DS_FILTRO
	FROM ADM.C_COMPETENCIA AS C
	LEFT OUTER JOIN ADM.S_TIPO_COMPETENCIA  AS TP ON TP.CL_TIPO_COMPETENCIA = C.CL_TIPO_COMPETENCIA 
	LEFT OUTER JOIN ADM.C_CLASIFICACION_COMPETENCIA  AS cc  ON cc.CL_CLASIFICACION = C.CL_CLASIFICACION
	LEFT OUTER JOIN ADM.C_COMPETENCIA_NIVEL AS CN0 ON CN0.ID_COMPETENCIA = C.ID_COMPETENCIA AND CN0.NO_VALOR_NIVEL = 0
	LEFT OUTER JOIN ADM.C_COMPETENCIA_NIVEL AS CN1 ON CN1.ID_COMPETENCIA = C.ID_COMPETENCIA AND CN1.NO_VALOR_NIVEL = 1
	LEFT OUTER JOIN ADM.C_COMPETENCIA_NIVEL AS CN2 ON CN2.ID_COMPETENCIA = C.ID_COMPETENCIA AND CN2.NO_VALOR_NIVEL = 2
	LEFT OUTER JOIN ADM.C_COMPETENCIA_NIVEL AS CN3 ON CN3.ID_COMPETENCIA = C.ID_COMPETENCIA AND CN3.NO_VALOR_NIVEL = 3
	LEFT OUTER JOIN ADM.C_COMPETENCIA_NIVEL AS CN4 ON CN4.ID_COMPETENCIA = C.ID_COMPETENCIA AND CN4.NO_VALOR_NIVEL = 4
	LEFT OUTER JOIN ADM.C_COMPETENCIA_NIVEL AS CN5 ON CN5.ID_COMPETENCIA = C.ID_COMPETENCIA AND CN5.NO_VALOR_NIVEL = 5
		
	WHERE (@PIN_ID_COMPETENCIA IS NULL OR (@PIN_ID_COMPETENCIA IS NOT NULL AND C.[ID_COMPETENCIA] = @PIN_ID_COMPETENCIA)) AND 
			(@PIN_CL_COMPETENCIA IS NULL OR (@PIN_CL_COMPETENCIA IS NOT NULL AND C.[CL_COMPETENCIA] = @PIN_CL_COMPETENCIA)) AND 
			(@PIN_NB_COMPETENCIA IS NULL OR (@PIN_NB_COMPETENCIA IS NOT NULL AND C.[NB_COMPETENCIA] = @PIN_NB_COMPETENCIA)) AND 
			(@PIN_DS_COMPETENCIA IS NULL OR (@PIN_DS_COMPETENCIA IS NOT NULL AND C.[DS_COMPETENCIA] = @PIN_DS_COMPETENCIA)) AND 
			(@PIN_CL_TIPO_COMPETENCIA IS NULL OR (@PIN_CL_TIPO_COMPETENCIA IS NOT NULL AND C.[CL_TIPO_COMPETENCIA] = @PIN_CL_TIPO_COMPETENCIA)) AND 
			(@PIN_CL_CLASIFICACION IS NULL OR (@PIN_CL_CLASIFICACION IS NOT NULL AND C.[CL_CLASIFICACION] = @PIN_CL_CLASIFICACION)) AND 
			(@PIN_FG_ACTIVO IS NULL OR (@PIN_FG_ACTIVO IS NOT NULL AND C.[FG_ACTIVO] = @PIN_FG_ACTIVO)) 

