-- =============================================
-- Proyecto: Sigein 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Margarita Salcedo
-- CREATE date: 14/09/2015
-- Description: Obtiene los M_PUESTO 
-- =============================================
--jvp 23/10/2015 SE LE AGREGA LOS CAMPOS RELACIONADOS CON LA TABLA DE PUESTOS PENDIENTE PUESTO RELACIONADO
-- =============================================
CREATE  PROCEDURE [ADM].[SPE_OBTIENE_M_PUESTO] 
	--M_PUESTO
	  @PIN_ID_PUESTO AS int = NULL
	, @PIN_FG_ACTIVO AS bit = NULL
	, @PIN_FE_INACTIVO AS datetime = NULL
	, @PIN_CL_PUESTO AS nvarchar(20) = NULL
	, @PIN_NB_PUESTO AS nvarchar(100) = NULL
	, @PIN_ID_DEPARTAMENTO AS int = NULL
	, @PIN_XML_CAMPOS_ADICIONALES AS xml = NULL
	, @PIN_ID_BITACORA AS int = NULL
	, @PIN_NO_EDAD_MINIMA AS tinyint = NULL
	, @PIN_NO_EDAD_MAXIMA AS tinyint = NULL
	, @PIN_CL_GENERO AS nvarchar(20) = NULL
	, @PIN_CL_ESTADO_CIVIL AS nvarchar(20) = NULL
	, @PIN_XML_REQUERIMIENTOS AS xml = NULL
	, @PIN_XML_OBSERVACIONES AS xml = NULL
	, @PIN_XML_RESPONSABILIDAD AS xml = NULL
	, @PIN_XML_AUTORIDAD AS xml = NULL
	, @PIN_XML_CURSOS_ADICIONALES AS xml = NULL
	, @PIN_XML_MENTOR AS xml = NULL
	, @PIN_CL_TIPO_PUESTO AS nvarchar(20) = NULL
	, @PIN_ID_CENTRO_ADMINISTRATIVO AS UNIQUEIDENTIFIER = NULL
	, @PIN_ID_CENTRO_OPERATIVO AS UNIQUEIDENTIFIER = NULL
	, @PIN_ID_PAQUETE_PRESTACIONES AS int = NULL

     ---M_DEPARTAMENTO
	, @PIN_NB_DEPARTAMENTO AS nvarchar(100) = NULL
	, @PIN_CL_DEPARTAMENTO AS nvarchar(30) = NULL

AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT 
	    --M_PUESTO
		P.[ID_PUESTO]
		, P.[FG_ACTIVO]
		,(CASE WHEN P.[FG_ACTIVO] =1 THEN 'Sí'
		       WHEN P.[FG_ACTIVO] =0 THEN 'No'
			   END) AS NB_ACTIVO
		, P.[FE_INACTIVO]
		, P.[CL_PUESTO]
		, P.[NB_PUESTO]
		, P.[ID_DEPARTAMENTO]
		, P.[XML_CAMPOS_ADICIONALES]
		, P.[ID_BITACORA]
		, P.[NO_EDAD_MINIMA]
		, P.[NO_EDAD_MAXIMA]
		, P.[CL_GENERO]
		, P.[CL_ESTADO_CIVIL]
		, P.[XML_REQUERIMIENTOS]
		, P.[XML_OBSERVACIONES]
		, P.[XML_RESPONSABILIDAD]
		, P.[XML_AUTORIDAD]
		, P.[XML_CURSOS_ADICIONALES]
		, P.[XML_MENTOR]
		, P.[CL_TIPO_PUESTO]
		, P.[ID_CENTRO_ADMINISTRATIVO]
		, P.[ID_CENTRO_OPERATIVO]
		, P.[ID_PAQUETE_PRESTACIONES]
		
		--M_DEPARTAMENTO
		, D.NB_DEPARTAMENTO
		, D.CL_DEPARTAMENTO

		, P.CL_PUESTO+' '+P.NB_PUESTO  as DS_FILTRO
		--PUESTO RELACION 
		--,'' as CL_TIPO_RELACION
		, isnull(CPR.CL_TIPO_RELACION,'') AS CL_TIPO_RELACION
		
	FROM ADM.M_PUESTO AS P
	INNER JOIN ADM.M_DEPARTAMENTO AS D ON D.ID_DEPARTAMENTO = P.ID_DEPARTAMENTO
	LEFT OUTER JOIN  ADM.C_PUESTO_RELACIONADO  AS CPR ON CPR.ID_PUESTO  =  P.ID_PUESTO AND CPR.CL_TIPO_RELACION = 'JEFE'
	WHERE  (@PIN_ID_PUESTO IS NULL OR (@PIN_ID_PUESTO IS NOT NULL AND P.[ID_PUESTO] = @PIN_ID_PUESTO))
			 AND (@PIN_FG_ACTIVO IS NULL OR (@PIN_FG_ACTIVO IS NOT NULL AND P.[FG_ACTIVO] = @PIN_FG_ACTIVO))
			 AND (@PIN_FE_INACTIVO IS NULL OR (@PIN_FE_INACTIVO IS NOT NULL AND P.[FE_INACTIVO] = @PIN_FE_INACTIVO))
			 AND (@PIN_CL_PUESTO IS NULL OR (@PIN_CL_PUESTO IS NOT NULL AND P.[CL_PUESTO] = @PIN_CL_PUESTO))
			 AND (@PIN_NB_PUESTO IS NULL OR (@PIN_NB_PUESTO IS NOT NULL AND P.[NB_PUESTO] = @PIN_NB_PUESTO))			 
			 AND (@PIN_ID_DEPARTAMENTO IS NULL OR (@PIN_ID_DEPARTAMENTO IS NOT NULL AND P.[ID_DEPARTAMENTO] = @PIN_ID_DEPARTAMENTO))
			-- AND (@PIN_XML_CAMPOS_ADICIONALES IS NULL OR (@PIN_XML_CAMPOS_ADICIONALES IS NOT NULL AND [XML_CAMPOS_ADICIONALES] = @PIN_XML_CAMPOS_ADICIONALES))
			 AND (@PIN_ID_BITACORA IS NULL OR (@PIN_ID_BITACORA IS NOT NULL AND P.[ID_BITACORA] = @PIN_ID_BITACORA))
			 AND (@PIN_NO_EDAD_MINIMA IS NULL OR (@PIN_NO_EDAD_MINIMA IS NOT NULL AND P.[NO_EDAD_MINIMA] = @PIN_NO_EDAD_MINIMA))
			 AND (@PIN_NO_EDAD_MAXIMA IS NULL OR (@PIN_NO_EDAD_MAXIMA IS NOT NULL AND P.[NO_EDAD_MAXIMA] = @PIN_NO_EDAD_MAXIMA))
			 AND (@PIN_CL_GENERO IS NULL OR (@PIN_CL_GENERO IS NOT NULL AND P.[CL_GENERO] = @PIN_CL_GENERO))
			 AND (@PIN_CL_ESTADO_CIVIL IS NULL OR (@PIN_CL_ESTADO_CIVIL IS NOT NULL AND P.[CL_ESTADO_CIVIL] = @PIN_CL_ESTADO_CIVIL))
			-- AND (@PIN_XML_REQUERIMIENTOS IS NULL OR (@PIN_XML_REQUERIMIENTOS IS NOT NULL AND [XML_REQUERIMIENTOS] = @PIN_XML_REQUERIMIENTOS))
			-- AND (@PIN_XML_OBSERVACIONES IS NULL OR (@PIN_XML_OBSERVACIONES IS NOT NULL AND [XML_OBSERVACIONES] = @PIN_XML_OBSERVACIONES))
			-- AND (@PIN_XML_RESPONSABILIDAD IS NULL OR (@PIN_XML_RESPONSABILIDAD IS NOT NULL AND [XML_RESPONSABILIDAD] = @PIN_XML_RESPONSABILIDAD))
			-- AND (@PIN_XML_AUTORIDAD IS NULL OR (@PIN_XML_AUTORIDAD IS NOT NULL AND [XML_AUTORIDAD] = @PIN_XML_AUTORIDAD))
			-- AND (@PIN_XML_CURSOS_ADICIONALES IS NULL OR (@PIN_XML_CURSOS_ADICIONALES IS NOT NULL AND [XML_CURSOS_ADICIONALES] = @PIN_XML_CURSOS_ADICIONALES))
			-- AND (@PIN_XML_MENTOR IS NULL OR (@PIN_XML_MENTOR IS NOT NULL AND [XML_MENTOR] = @PIN_XML_MENTOR))
			 AND (@PIN_CL_TIPO_PUESTO IS NULL OR (@PIN_CL_TIPO_PUESTO IS NOT NULL AND P.[CL_TIPO_PUESTO] = @PIN_CL_TIPO_PUESTO))
			 AND (@PIN_ID_CENTRO_ADMINISTRATIVO IS NULL OR (@PIN_ID_CENTRO_ADMINISTRATIVO IS NOT NULL AND P.[ID_CENTRO_ADMINISTRATIVO] = @PIN_ID_CENTRO_ADMINISTRATIVO))
			 AND (@PIN_ID_CENTRO_OPERATIVO IS NULL OR (@PIN_ID_CENTRO_OPERATIVO IS NOT NULL AND P.[ID_CENTRO_OPERATIVO] = @PIN_ID_CENTRO_OPERATIVO))
			 AND (@PIN_ID_PAQUETE_PRESTACIONES IS NULL OR (@PIN_ID_PAQUETE_PRESTACIONES IS NOT NULL AND P.[ID_PAQUETE_PRESTACIONES] = @PIN_ID_PAQUETE_PRESTACIONES))
			 AND (@PIN_NB_DEPARTAMENTO IS NULL OR (@PIN_NB_DEPARTAMENTO IS NOT NULL AND D.NB_DEPARTAMENTO = @PIN_NB_DEPARTAMENTO))
			 AND (@PIN_CL_DEPARTAMENTO IS NULL OR (@PIN_CL_DEPARTAMENTO IS NOT NULL AND D.CL_DEPARTAMENTO = @PIN_CL_DEPARTAMENTO))
	
	--PRUEBAS EJECUTAR EL SP FHP		
	--EXECUTE ADM.SPE_OBTIENE_M_PUESTO