-- =============================================
-- Proyecto: Sigein 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Julio Díaz
-- CREATE date: 20/11/2015
-- Description: Obtiene los usuarios del sistema
-- =============================================

CREATE PROCEDURE [ADM].[SPE_OBTIENE_USUARIOS]
        @PIN_CL_USUARIO AS nvarchar(50) = NULL
AS   
	SELECT CU.CL_USUARIO
		, CU.NB_USUARIO
		, CU.NB_CORREO_ELECTRONICO
		, CASE WHEN CU.FG_ACTIVO = 1 THEN 'Sí' ELSE 'No' END AS FG_ACTIVO
		, CR.NB_ROL
		, ME.NB_EMPLEADO
		, MD.NB_DEPARTAMENTO
		, MP.NB_PUESTO
	FROM ADM.C_USUARIO CU
		LEFT JOIN ADM.C_ROL CR
			ON CU.ID_ROL = CR.ID_ROL
		LEFT JOIN ADM.M_EMPLEADO ME
			ON CU.ID_EMPLEADO = ME.ID_EMPLEADO
		LEFT JOIN ADM.M_PUESTO MP
			ON ME.ID_PUESTO = MP.ID_DEPARTAMENTO
		LEFT JOIN ADM.M_DEPARTAMENTO MD
			ON MP.ID_DEPARTAMENTO = MD.ID_DEPARTAMENTO
	WHERE (@PIN_CL_USUARIO IS NULL OR (@PIN_CL_USUARIO IS NOT NULL AND CU.CL_USUARIO = @PIN_CL_USUARIO))
