-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Julio Díaz
-- CREATE date: 13/11/2015
-- Description: Obtiene los datos de los empleados
-- =============================================
CREATE PROCEDURE [ADM].[SPE_OBTIENE_EMPLEADOS] 
	
AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT  
	      ME.ID_EMPLEADO AS M_EMPLEADO_ID_EMPLEADO					--00000000000
		, ME.CL_EMPLEADO AS M_EMPLEADO_CL_EMPLEADO					--00000000000
		, CONCAT ( ME.NB_EMPLEADO, ' ',ME.NB_APELLIDO_PATERNO,' ' , ME.NB_APELLIDO_MATERNO )AS M_EMPLEADO_NB_EMPLEADO_COMPLETO
		, ME.NB_EMPLEADO AS M_EMPLEADO_NB_EMPLEADO
		, ME.NB_APELLIDO_PATERNO AS M_EMPLEADO_NB_APELLIDO_PATERNO
		, ME.NB_APELLIDO_MATERNO AS M_EMPLEADO_NB_APELLIDO_MATERNO
		, ME.CL_ESTADO_EMPLEADO AS M_EMPLEADO_CL_ESTADO_EMPLEADO
		, ME.CL_GENERO AS M_EMPLEADO_CL_GENERO
		, ME.CL_ESTADO_CIVIL AS M_EMPLEADO_CL_ESTADO_CIVIL
		, ME.NB_CONYUGUE AS M_EMPLEADO_NB_CONYUGUE
		, ME.CL_RFC AS M_EMPLEADO_CL_RFC
		, ME.CL_CURP AS M_EMPLEADO_CL_CURP
		, ME.CL_NSS AS M_EMPLEADO_CL_NSS
		, ME.CL_TIPO_SANGUINEO AS M_EMPLEADO_CL_TIPO_SANGUINEO
		, ME.CL_NACIONALIDAD AS M_EMPLEADO_CL_NACIONALIDAD
		, ME.NB_PAIS AS M_EMPLEADO_NB_PAIS
		, ME.NB_ESTADO AS M_EMPLEADO_NB_ESTADO
		, ME.NB_MUNICIPIO AS M_EMPLEADO_NB_MUNICIPIO
		, ME.NB_COLONIA AS M_EMPLEADO_NB_COLONIA
		, ME.NB_CALLE AS M_EMPLEADO_NB_CALLE
		, ME.NO_INTERIOR AS M_EMPLEADO_NO_INTERIOR
		, ME.NO_EXTERIOR AS M_EMPLEADO_NO_EXTERIOR
		, ME.CL_CODIGO_POSTAL AS M_EMPLEADO_CL_CODIGO_POSTAL
		, ME.XML_TELEFONOS AS M_EMPLEADO_XML_TELEFONOS---------0000000000000000000000000 REVISAR COMO SE MOSTRARÁN
		, ME.CL_CORREO_ELECTRONICO AS M_EMPLEADO_CL_CORREO_ELECTRONICO
		, ME.FG_ACTIVO AS M_EMPLEADO_ACTIVO ---------------------000000000000000000000000000000000 CAMBIAR A 'SI'/'NO'
		, ME.FE_NACIMIENTO AS M_EMPLEADO_FE_NACIMIENTO
		, ME.DS_LUGAR_NACIMIENTO AS M_EMPLEADO_DS_LUGAR_NACIMIENTO
		, ME.FE_ALTA AS M_EMPLEADO_FE_ALTA
		, ME.FE_BAJA  AS M_EMPLEADO_FE_BAJA
		, ME.ID_PUESTO AS M_EMPLEADO_ID_PUESTO ---------------------------XXXXXXXXXXXXXXXXXXX
		, ME.MN_SUELDO AS M_EMPLEADO_MN_SUELDO
		, ME.MN_SUELDO_VARIABLE AS M_EMPLEADO_MN_SUELDO_VARIABLE
		, ME.DS_SUELDO_COMPOSICION AS M_EMPLEADO_DS_SUELDO_COMPOSICION
		, ME.ID_CANDIDATO AS M_EMPLEADO_ID_CANDIDATO
		, ME.XML_CAMPOS_ADICIONALES AS M_EMPLEADO_XML_CAMPOS_ADICIONALES ----------00000000000000000000 REVISAR COMO MOSTRARLOS
		, ME.ID_EMPRESA AS M_EMPLEADO_ID_EMPRESA  ---------------------------XXXXXXXXXXXXXXXXXXX

		------------M_PUESTO----------------
		, MP.FG_ACTIVO AS M_PUESTO_ACTIVO ---------------------------XXXXXXXXXXXXXXXXXXX
		, MP.FE_INACTIVO  AS M_PUESTO_FE_INACTIVO ---------------------------XXXXXXXXXXXXXXXXXXX
		, MP.CL_PUESTO AS M_PUESTO_CL_PUESTO
		, MP.NB_PUESTO AS M_PUESTO_NB_PUESTO
		--, MP.ID_PUESTO_JEFE AS M_PUESTO_ID_PUESTO_JEFE ---------------------------OOOOOOOOOOOOO REVISAR SI SE EMPLEARÁ EN EL GRID
		, MP.ID_DEPARTAMENTO AS M_PUESTO_ID_DEPARTAMENTO ---------------------------XXXXXXXXXXXXXXXXXXX
		, MP.XML_CAMPOS_ADICIONALES AS M_PUESTO_XML_CAMPOS_ADICIONALES ----------00000000000000000000 REVISAR COMO MOSTRARLOS
		, MP.ID_BITACORA AS M_PUESTO_ID_BITACORA ---------------------------XXXXXXXXXXXXXXXXXXX
				
		---------------------------------
		-----------C_EMPRESA
		, CE.CL_EMPRESA AS C_EMPRESA_CL_EMPRESA
		, CE.NB_EMPRESA AS C_EMPRESA_NB_EMPRESA
		, CE.NB_RAZON_SOCIAL AS C_EMPRESA_NB_RAZON_SOCIAL

		-------------------------------------------
		---------------M_DEPARTAMENTO
		, MD.FG_ACTIVO AS M_DEPARTAMENTO_ACTIVO ---------------------------XXXXXXXXXXXXXXXXXXX
		, MD.FE_INACTIVO AS M_DEPARTAMENTO_FE_INACTIVO ---------------------------XXXXXXXXXXXXXXXXXXX
		, MD.CL_DEPARTAMENTO AS M_DEPARTAMENTO_CL_DEPARTAMENTO
		, MD.NB_DEPARTAMENTO AS M_DEPARTAMENTO_NB_DEPARTAMENTO
		, MD.XML_CAMPOS_ADICIONALES AS M_DEPARTAMENTO_XML_CAMPOS_ADICIONALES ----------00000000000000000000 REVISAR COMO MOSTRARLOS

	FROM ADM.M_EMPLEADO AS ME
		LEFT JOIN ADM.M_PUESTO AS MP 
			ON MP.ID_PUESTO =ME.ID_PUESTO
		LEFT JOIN ADM.C_EMPRESA AS CE 
			ON CE.ID_EMPRESA =ME.ID_EMPRESA
		LEFT JOIN ADM.M_DEPARTAMENTO AS MD 
			ON MP.ID_DEPARTAMENTO =MD.ID_DEPARTAMENTO

