-- =============================================
-- Proyecto: Sigein 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Juan Pérez
-- CREATE date: 05/12/2015
-- Description: Obtiene los generos. las escolaridades del empleado, empleado y puestos
-- =============================================

CREATE PROCEDURE [ADM].[SPE_OBTIENE_C_NOTIFICAR_REQUISICION]

AS   
BEGIN
  DECLARE 
  	    @IdCatalogoGenero int
	    ,@XmlDatoConfiguracion XML
	--TABLAS
		, @XML_DEPARTAMENTOS XML
		, @XML_C_ESCOLARIDAD XML
		, @XML_C_NIVEL_ESCOLARIDADES XML
		, @XML_CATALOGO_LISTA XML
		, @XML_CATALOGO_VALOR XML

	SET @XML_DEPARTAMENTOS = (
	SELECT  
	    MD.ID_DEPARTAMENTO AS "@ID_DEPARTAMENTO"
      , MD.FG_ACTIVO AS "@FG_ACTIVO"
      , MD.CL_DEPARTAMENTO AS "@CL_DEPARTAMENTO" 
      , MD.NB_DEPARTAMENTO AS "@NB_DEPARTAMENTO"
		FROM ADM.M_DEPARTAMENTO MD
		FOR XML PATH ('DEPARTAMENTO'), ROOT ('DEPARTAMENTOS')
	)

		SET @XML_C_ESCOLARIDAD = (
	SELECT  
	   CE.ID_ESCOLARIDAD AS "@ID_ESCOLARIDAD" 
      ,CE.NB_ESCOLARIDAD AS "@NB_ESCOLARIDAD" 
      ,CE.DS_ESCOLARIDAD AS "@DS_ESCOLARIDAD" 
      ,CE.CL_NIVEL_ESCOLARIDAD AS "@CL_NIVEL_ESCOLARIDAD" 
		FROM ADM.C_ESCOLARIDAD CE
		FOR XML PATH ('ESCOLARIDAD'), ROOT ('ESCOLARIDADES')
	)

		SET @XML_C_NIVEL_ESCOLARIDADES = (
	SELECT  
	   CN.ID_NIVEL_ESCOLARIDAD AS "@ID_NIVEL_ESCOLARIDAD" 
      ,CN.CL_NIVEL_ESCOLARIDAD AS "@CL_NIVEL_ESCOLARIDAD" 
      ,CN.DS_NIVEL_ESCOLARIDAD AS "@DS_NIVEL_ESCOLARIDAD"
	  ,CN.CL_TIPO_ESCOLARIDAD AS "@CL_TIPO_ESCOLARIDAD"
		FROM ADM.C_NIVEL_ESCOLARIDAD CN
		FOR XML PATH ('NIVEL_ESCOLARIDAD'), ROOT ('NIVEL_ESCOLARIDADES')
	)




		SELECT 
			  @XmlDatoConfiguracion = ADM.S_CONFIGURACION.XML_CONFIGURACION 
			  FROM
				 ADM.S_CONFIGURACION
				 ------------------------------------------------
		SELECT 
		   @IdCatalogoGenero  = T.C.value('@ID_CATALOGO', 'int')
		 FROM 
		   @XmlDatoConfiguracion.nodes('/CONFIGURACIONES/CATALOGOS/GENERO') T(C)


	     SET  @XML_CATALOGO_LISTA = (
	     SELECT  
	   CC.ID_CATALOGO_LISTA AS "@ID_CATALOGO_LISTA" 
      ,CC.NB_CATALOGO_LISTA AS "@NB_CATALOGO_LISTA" 
      ,CC.DS_CATALOGO_LISTA AS "@DS_CATALOGO_LISTA" 
      ,CC.ID_CATALOGO_TIPO AS "@ID_CATALOGO_TIPO" 
		FROM ADM.C_CATALOGO_LISTA CC

		FOR XML PATH ('CATALOGO_LISTA'), ROOT ('CATALOGO_LISTAS')
	)
	     SET  @XML_CATALOGO_VALOR = (
	     SELECT  
	    CV.ID_CATALOGO_VALOR AS "@ID_CATALOGO_VALOR"
       ,CV.CL_CATALOGO_VALOR AS "@CL_CATALOGO_VALOR" 
       ,CV.NB_CATALOGO_VALOR AS "@NB_CATALOGO_VALOR"
		FROM ADM.C_CATALOGO_VALOR CV
		WHERE ID_CATALOGO_LISTA =@IdCatalogoGenero
		FOR XML PATH ('CATALOGO_VALOR'), ROOT ('CATALOGO_VALORES')
	)



	SELECT
		  @XML_DEPARTAMENTOS AS XML_DEPARTAMENTOS
		, @XML_C_ESCOLARIDAD AS XML_C_ESCOLARIDAD
		, @XML_C_NIVEL_ESCOLARIDADES AS XML_C_NIVEL_ESCOLARIDADES
		, @XML_CATALOGO_LISTA AS XML_CATALOGO_LISTA
		, @XML_CATALOGO_VALOR AS XML_CATALOGO_VALOR
END

--EXECUTE [ADM].[SPE_OBTIENE_C_NOTIFICAR_REQUISICION]