
-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Juan Perez Pedroza
-- CREATE date: 09/12/2015
-- Description: Obtiene los datos de la tabla  ADM.
-- =============================================
CREATE PROCEDURE [ADM].[SPE_OBTIENE_VW_TIPO_ESCOLARIDAD] 
	  @PIN_ID_NIVEL_ESCOLARIDAD AS int = NULL
	, @PIN_CL_TIPO_ESCOLARIDAD AS nvarchar(20) = NULL
	, @PIN_DS_NIVEL_ESCOLARIDAD AS nvarchar(200) = NULL
	
AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT 
		[ID_NIVEL_ESCOLARIDAD]
		, [CL_TIPO_ESCOLARIDAD]
		, [DS_NIVEL_ESCOLARIDAD]
	
	FROM ADM.VW_TIPO_ESCOLARIDAD
	WHERE (@PIN_ID_NIVEL_ESCOLARIDAD IS NULL OR (@PIN_ID_NIVEL_ESCOLARIDAD IS NOT NULL AND [ID_NIVEL_ESCOLARIDAD] = @PIN_ID_NIVEL_ESCOLARIDAD))
			 AND (@PIN_CL_TIPO_ESCOLARIDAD IS NULL OR (@PIN_CL_TIPO_ESCOLARIDAD IS NOT NULL AND [CL_TIPO_ESCOLARIDAD] = @PIN_CL_TIPO_ESCOLARIDAD))
			 AND (@PIN_DS_NIVEL_ESCOLARIDAD IS NULL OR (@PIN_DS_NIVEL_ESCOLARIDAD IS NOT NULL AND [DS_NIVEL_ESCOLARIDAD] = @PIN_DS_NIVEL_ESCOLARIDAD))
		
			
