-- =============================================
-- Proyecto: Sigein 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Felipe Hernández Palafox
-- CREATE date: 02/12/2015
-- Description: Obtiene los datos de escolaridades 
-- =============================================
CREATE PROCEDURE [ADM].[SPE_OBTIENE_ESCOLARIDADES] 
	    @PIN_ID_ESCOLARIDAD AS int = NULL,
        @PIN_NB_ESCOLARIDAD AS nvarchar(100) = NULL,
        @PIN_DS_ESCOLARIDAD AS nvarchar(200) = NULL,
        @PIN_CL_NIVEL_ESCOLARIDAD AS nvarchar(20) = NULL,
        @PIN_FG_ACTIVO AS bit = NULL,
	    @PIN_ID_NIVEL_ESCOLARIDAD AS int = NULL,
		@PIN_NB_NIVEL_ESCOLARIDAD As nvarchar(100) = NULL

AS   
	SELECT 
			CE.ID_ESCOLARIDAD,
			CE.NB_ESCOLARIDAD,
			CE.DS_ESCOLARIDAD,
			CE.CL_NIVEL_ESCOLARIDAD,
			CE.FG_ACTIVO
			,(CASE WHEN [CE].FG_ACTIVO=1 THEN 'Sí'
			WHEN CE.FG_ACTIVO=0 THEN 'No'
			END)AS NB_ACTIVO
			,'' as DS_FILTRO
			,0 AS ID_NIVEL_ESCOLARIDAD			---ELIMINAR DEL ENTITY FRAMEWORK
			,CE.CL_INSTITUCION
			,CNE.CL_TIPO_ESCOLARIDAD
	FROM ADM.C_ESCOLARIDAD CE
	INNER JOIN ADM.C_NIVEL_ESCOLARIDAD CNE ON CE.CL_NIVEL_ESCOLARIDAD = CNE.CL_NIVEL_ESCOLARIDAD
	WHERE (@PIN_ID_ESCOLARIDAD IS NULL OR (@PIN_ID_ESCOLARIDAD IS NOT NULL AND CE.ID_ESCOLARIDAD = @PIN_ID_ESCOLARIDAD)) AND 
			(@PIN_NB_ESCOLARIDAD IS NULL OR (@PIN_NB_ESCOLARIDAD IS NOT NULL AND CE.NB_ESCOLARIDAD = @PIN_NB_ESCOLARIDAD)) AND 
			(@PIN_DS_ESCOLARIDAD IS NULL OR (@PIN_DS_ESCOLARIDAD IS NOT NULL AND CE.DS_ESCOLARIDAD = @PIN_DS_ESCOLARIDAD)) AND 
			(@PIN_CL_NIVEL_ESCOLARIDAD IS NULL OR (@PIN_CL_NIVEL_ESCOLARIDAD IS NOT NULL AND CE.CL_NIVEL_ESCOLARIDAD = @PIN_CL_NIVEL_ESCOLARIDAD)) AND 
			(@PIN_FG_ACTIVO IS NULL OR (@PIN_FG_ACTIVO IS NOT NULL AND CE.FG_ACTIVO = @PIN_FG_ACTIVO)) AND 
			--(@PIN_ID_NIVEL_ESCOLARIDAD IS NULL OR (@PIN_ID_NIVEL_ESCOLARIDAD IS NOT NULL AND CE.ID_NIVEL_ESCOLARIDAD = @PIN_ID_NIVEL_ESCOLARIDAD)) AND 
			(@PIN_NB_NIVEL_ESCOLARIDAD IS NULL OR (@PIN_NB_NIVEL_ESCOLARIDAD IS NOT NULL AND CNE.CL_NIVEL_ESCOLARIDAD = @PIN_NB_NIVEL_ESCOLARIDAD)) 
	    	

	--EXECUTE [ADM].[SPE_OBTIENE_ESCOLARIDADES] NULL,NULL,NULL,NULL,NULL,NULL,'POSGRADO'