-- =============================================
-- Proyecto: Sistema Nomina
-- Copyright (c) - Acrux - 2015
-- Author: Julio Díaz
-- CREATE date: 26/02/2016
-- Description: Elimina un registro de la tabla C_PLANTILLA_FORMULARIO
-- =============================================
CREATE PROCEDURE [ADM].[SPE_ESTABLECE_PLANTILLA_FORMULARIO_GENERAL]
	@XML_RESULTADO XML OUT,     --APLICA PARA REGRESAR UN NÚMERO 0 PARA ERROR Y 1 PARA CORRECTO
	@PIN_ID_PLANTILLA_FORMULARIO INT, 
	@PIN_CL_FORMULARIO NVARCHAR(20),
	@PIN_CL_USUARIO NVARCHAR(50), --USUARIO QUE MANDA A ELIMINAR EL REGISTRO
	@PIN_NB_PROGRAMA NVARCHAR(50) -- PROGRAMA DONDE EL USUARIO MANDA ELIMINAR EL REGISTRO
AS   
BEGIN
	--SE DECLARA E INICIALIZA LA VARIABLE QUE NOS INDICARA SI GENERAMOS LA TRANSACCION EN ESTE SP
	DECLARE @V_EXIST_TRAN BIT = 0
		, @FE_SISTEMA DATETIME = DBO.F_GETDATE()
	BEGIN TRY		   			
		--SE VERIFICA SI EXISTE UNA TRANSACCION EN EJECUCION
		IF (@@TRANCOUNT = 0) BEGIN
			--EN CASO DE QUE NO SE INICIALIZA LA TRANSACCION
			BEGIN TRANSACTION
			--SE EDITA LA VARIABLE QUE INDICA QUE SE INICIO LA TRANSACCION EN ESTE BLOQUE PARA CANCELARLA SI ES NECESARIO
			SET @V_EXIST_TRAN = 1
		END	
		--SE BORRA EL REGISTRO EN LA TABLA  IDP.C_PLANTILLA_FORMULARIO
		UPDATE ADM.C_PLANTILLA_FORMULARIO 
		SET FG_GENERAL = 0
			, FE_MODIFICACION = @FE_SISTEMA
			, CL_USUARIO_APP_MODIFICA = @PIN_CL_USUARIO
			, NB_PROGRAMA_MODIFICA = @PIN_NB_PROGRAMA
		WHERE CL_FORMULARIO = @PIN_CL_FORMULARIO AND FG_GENERAL = 1
		
		UPDATE ADM.C_PLANTILLA_FORMULARIO 
		SET FG_GENERAL = 1 
			, FE_MODIFICACION = @FE_SISTEMA
			, CL_USUARIO_APP_MODIFICA = @PIN_CL_USUARIO
			, NB_PROGRAMA_MODIFICA = @PIN_NB_PROGRAMA
		WHERE ID_PLANTILLA_SOLICITUD = @PIN_ID_PLANTILLA_FORMULARIO
				

		SET @XML_RESULTADO = DBO.F_ERROR_CREAR_ENCABEZADO( @@ROWCOUNT, ERROR_NUMBER(), 'SUCCESSFUL')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'Proceso exitoso', 'ES')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'Successful Process', 'EN')
		--SI SE GENERO UNA TRANSACCION EN ESTE BLOQUE LA TERMINARA
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			COMMIT
	END TRY
	BEGIN CATCH			
		--SI OCURRIO UN ERROR Y SE INICIO UNA TRANSACCION ENE ESTE BLOQUE SE CANCELARA LA TRANSACCION
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			ROLLBACK
		--SE INDICA EN LA VARIABLE DE RETORNO QUE OCURRIO UN ERROR
		SET @XML_RESULTADO = DBO.F_ERROR_MENSAJES(ERROR_NUMBER(), ERROR_MESSAGE())

	END CATCH	
END 
