-- =============================================
-- Proyecto: Sigein 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Margarita Salcedo
-- CREATE date: 14/09/2015
-- Description: Obtiene los C_PERIODO 
-- =============================================
CREATE PROCEDURE ADM.SPE_OBTIENE_C_PERIODO 
	    @PIN_ID_PERIODO AS int = NULL,
        @PIN_CL_PERIODO AS nvarchar(32) = NULL,
        @PIN_NB_PERIODO AS nvarchar(100) = NULL,
        @PIN_DS_PERIODO AS nvarchar(200) = NULL,
        @PIN_FE_INICIO AS bit = NULL,
        @PIN_FE_TERMINO AS nvarchar(200) = NULL,
        @PIN_CL_ESTADO_PERIODO AS nvarchar(20) = NULL,
        @PIN_XML_CAMPOS_ADICIONALES AS xml = NULL

AS   
	SELECT 
		[ID_PERIODO],
		[CL_PERIODO],
		[NB_PERIODO],
		[DS_PERIODO],
		[FE_INICIO],
		[FE_TERMINO],
		[CL_ESTADO_PERIODO],
		[XML_CAMPOS_ADICIONALES]
		,'' as DS_FILTRO
	FROM ADM.C_PERIODO
	WHERE (@PIN_ID_PERIODO IS NULL OR (@PIN_ID_PERIODO IS NOT NULL AND [ID_PERIODO] = @PIN_ID_PERIODO)) AND 
(@PIN_CL_PERIODO IS NULL OR (@PIN_CL_PERIODO IS NOT NULL AND [CL_PERIODO] = @PIN_CL_PERIODO)) AND 
(@PIN_NB_PERIODO IS NULL OR (@PIN_NB_PERIODO IS NOT NULL AND [NB_PERIODO] = @PIN_NB_PERIODO)) AND 
(@PIN_DS_PERIODO IS NULL OR (@PIN_DS_PERIODO IS NOT NULL AND [DS_PERIODO] = @PIN_DS_PERIODO)) AND 
(@PIN_FE_INICIO IS NULL OR (@PIN_FE_INICIO IS NOT NULL AND [FE_INICIO] = @PIN_FE_INICIO)) AND 
(@PIN_FE_TERMINO IS NULL OR (@PIN_FE_TERMINO IS NOT NULL AND [FE_TERMINO] = @PIN_FE_TERMINO)) AND 
(@PIN_CL_ESTADO_PERIODO IS NULL OR (@PIN_CL_ESTADO_PERIODO IS NOT NULL AND [CL_ESTADO_PERIODO] = @PIN_CL_ESTADO_PERIODO))

