-- =============================================
-- Proyecto: Sigein 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Margarita Salcedo
-- CREATE date: 14/09/2015
-- Description: Elimina un C_ROL_FUNCION
-- =============================================
CREATE PROCEDURE [ADM].[SPE_ELIMINA_C_ROL_FUNCION]
	@POUT_CLAVE_RETORNO  VARCHAR(40) OUT,    --APLICA PARA REGRESAR UN NÚMERO DE (ERROR, ERROR CONTROLADO, O IDENTIFICADOR)
	@PIN_ID_ROL AS int,
    @PIN_ID_FUNCION AS int,
	@PIN_CL_USUARIO_APP_CREA AS nvarchar(50),
	@PIN_NB_PROGRAMA_CREA AS nvarchar(50)
AS   
BEGIN
	DECLARE @V_EXIST_TRAN BIT = 0
	BEGIN TRY		   			
		IF (@@TRANCOUNT = 0) 
		BEGIN
			BEGIN TRANSACTION
			SET @V_EXIST_TRAN = 1
		END	
		DELETE FROM ADM.C_ROL_FUNCION WHERE ID_ROL = @PIN_ID_ROL AND ID_FUNCION = @PIN_ID_FUNCION

		SET @POUT_CLAVE_RETORNO = '-1000' -- Clave: -1000 proceso satisfactorio

		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			COMMIT				
	END TRY
	BEGIN CATCH	
		--SI OCURRIO UN ERROR Y SE INICIO UNA TRANSACCION ENE ESTE BLOQUE SE CANCELARA LA TRANSACCION
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
		ROLLBACK
		--SE INDICA EN LA VARIABLE DE RETORNO QUE OCURRIO UN ERROR
		SET @POUT_CLAVE_RETORNO = 0
		--SE INSERTA EL ERROR EN LA TABLA	
		DECLARE @ERROR_CLAVE INT  = ERROR_NUMBER()
		DECLARE @ERROR_MENSAJE NVARCHAR(250)  = ERROR_MESSAGE()
		EXEC ADM.SPE_INSERTA_S_ERROR
		@PIN_CL_CLAVE = @ERROR_CLAVE,
		@PIN_DS_ERROR = @ERROR_MENSAJE,
		@PIN_CL_USUARIO_APP_CREA =@PIN_CL_USUARIO_APP_CREA,
		@PIN_NB_PROGRAMA_CREA = @PIN_NB_PROGRAMA_CREA

	END CATCH
END 
