-- =============================================
-- Proyecto: Sigein 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Juan Pérez
-- CREATE date: 05/12/2015
-- Description: Obtiene el sueldo del puesto vacante 
-- =============================================

CREATE PROCEDURE [ADM].[SPE_OBTIENE_SUELDO_PROMEDIO_PUESTO]
			@PIN_ID_PUESTO AS INT = NULL
AS   
BEGIN
  DECLARE 
  	 
	--TABLAS
		  @XML_EMPLEADOS XML
	    , @MN_SUELDO_PROMEDIO DECIMAL(13,2)

	SET @MN_SUELDO_PROMEDIO =(
	SELECT ISNULL(AVG(T.MN_SUELDO),0)AS SUELDO_PROMEDIO FROM
	(SELECT ME.ID_EMPLEADO,ME.MN_SUELDO  
	FROM  ADM.M_EMPLEADO ME 
	WHERE ME.FE_BAJA =(SELECT MAX(FE_BAJA) FROM  ADM.M_EMPLEADO WHERE ID_PUESTO= @PIN_ID_PUESTO ) 
	AND ID_PUESTO= @PIN_ID_PUESTO)T
	)
	SET @XML_EMPLEADOS = (
	SELECT  
	    ME.ID_EMPLEADO AS "@ID_EMPLEADO"
      , ME.NB_EMPLEADO + ' ' + ME.NB_APELLIDO_PATERNO + ' ' + ME.NB_APELLIDO_MATERNO AS "@NB_EMPLEADO"
      , ME.CL_EMPLEADO AS "@CL_EMPLEADO" 
      , ME.MN_SUELDO AS "@MN_SUELDO"
	   , ME.MN_SUELDO_VARIABLE AS "@MN_SUELDO_VARIABLE"
		FROM ADM.M_EMPLEADO ME
		WHERE
		 ( ME.FE_BAJA = (SELECT MAX(FE_BAJA) FROM  ADM.M_EMPLEADO WHERE ID_PUESTO= @PIN_ID_PUESTO)) 
		AND ID_PUESTO= @PIN_ID_PUESTO
		FOR XML PATH ('EMPLEADO'), ROOT ('EMPLEADOS')
	)


	SELECT
		  @MN_SUELDO_PROMEDIO AS MN_SUELDO_PROMEDIO
		  ,@XML_EMPLEADOS AS XML_EMPLEADOS
		
END

--EXECUTE [ADM].[SPE_OBTIENE_SUELDO_PROMEDIO_PUESTO] 1