-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Margarita Salcedo
-- CREATE date: 21/09/2015
-- Description: Obtiene los datos de la tabla K_CUESTIONARIO 
-- =============================================
CREATE PROCEDURE ADM.SPE_OBTIENE_K_CUESTIONARIO 
	@PIN_ID_CUESTIONARIO AS int = NULL
	, @PIN_ID_EVALUADO AS int = NULL
	, @PIN_ID_EVALUADO_EVALUADOR AS int = NULL
	
AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT 
		[ID_CUESTIONARIO]
		, [ID_EVALUADO]
		, [ID_EVALUADO_EVALUADOR]
		,'' as DS_FILTRO
	FROM ADM.K_CUESTIONARIO
	WHERE (@PIN_ID_CUESTIONARIO IS NULL OR (@PIN_ID_CUESTIONARIO IS NOT NULL AND [ID_CUESTIONARIO] = @PIN_ID_CUESTIONARIO))
			 AND (@PIN_ID_EVALUADO IS NULL OR (@PIN_ID_EVALUADO IS NOT NULL AND [ID_EVALUADO] = @PIN_ID_EVALUADO))
			 AND (@PIN_ID_EVALUADO_EVALUADOR IS NULL OR (@PIN_ID_EVALUADO_EVALUADOR IS NOT NULL AND [ID_EVALUADO_EVALUADOR] = @PIN_ID_EVALUADO_EVALUADOR))
			
