-- =============================================
-- Proyecto: SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Daniela Sanchez
-- CRETAE date: 22/12/2015
-- Description: Inserta un nuevo registro en la tabla C_CENTRO_ADMVO
-- =============================================
CREATE PROCEDURE [ADM].[SPE_INSERTA_ACTUALIZA_CENTRO_ADMVO] 
	       @XML_RESULTADO XML = '' OUT      --APLICA PARA REGRESAR UN NÚMERO 0 PARA ERROR Y 1 PARA CORRECTO
    	, @PIN_ID_CENTRO_ADMVO AS uniqueidentifier
      ,@PIN_CL_CLIENTE AS nvarchar(10)
      ,@PIN_ID_REGISTRO_PATRONAL AS uniqueidentifier
      ,@PIN_CL_CENTRO_ADMVO AS nvarchar(10)
      ,@PIN_NB_CENTRO_ADMVO AS nvarchar(100)
      ,@PIN_NB_CALLE AS nvarchar(100)
      ,@PIN_NB_NO_EXTERIOR AS nvarchar(10)
      ,@PIN_NB_NO_INTERIOR AS nvarchar(10)
      ,@PIN_NB_COLONIA AS nvarchar(100)
      ,@PIN_CL_MUNICIPIO AS nvarchar(10)
      ,@PIN_NB_MUNICIPIO AS nvarchar(100)
      ,@PIN_CL_ESTADO AS nchar(10)
	  ,@PIN_NB_ESTADO AS nvarchar(100)
      ,@PIN_CL_CODIGO_POSTAL AS nvarchar(10) 
      ,@PIN_CL_ZONA_ECONOMICA AS nchar(1)
      --,@PIN_FE_CREACION AS datetime
      --,@PIN_FE_MODIFICACION AS datetime
      ,@PIN_CL_USUARIO_APP_CREA AS nvarchar (50)
      ,@PIN_CL_USUARIO_APP_MODIFICA AS nvarchar(50)
      ,@PIN_NB_PROGRAMA_CREA AS nvarchar(50)
      ,@PIN_NB_PROGRAMA_MODIFICA AS nvarchar(50)
	  ,@PIN_TIPO_TRANSACCION CHAR(1)
AS 
BEGIN  
	--SE DECLARA E INICIALIZA LA VARIABLE QUE NOS INDICARA SI GENERAMOS LA TRANSACCION EN ESTE SP
	DECLARE @V_EXIST_TRAN BIT = 0
	,@CFE_SISTEMA DATETIME = dbo.F_GETDATE()
    	BEGIN TRY
		--SE VERIFICA SI EXISTE UNA TRANSACCION EN EJECUCION
		IF (@@TRANCOUNT = 0) 
		BEGIN
			--EN CASO DE QUE NO SE INICIALIZA LA TRANSACCION
			BEGIN TRANSACTION
			--SE EDITA LA VARIABLE QUE INDICA QUE SE INICIO LA TRANSACCION EN ESTE BLOQUE PARA CANCELARLA SI ES NECESARIO
			SET @V_EXIST_TRAN = 1
		END	
		--SE VERIFICA SI SE INSERTA EL REGISTRO O SE ACTUALIZARA SEGUN LA VARIABLE DE TIPO DE TRANSACCION  QUE RECIBE EL SP
		IF @PIN_TIPO_TRANSACCION='I'
	    	BEGIN
			
			
			--SE INSERTA EL REGISTRO EN LA TABLA  ADM.C_CENTRO_ADMVO
			INSERT INTO ADM.C_CENTRO_ADMVO
					   (ID_CENTRO_ADMVO
					   ,[CL_CLIENTE]
						,[ID_REGISTRO_PATRONAL]
						,[CL_CENTRO_ADMVO]
						,[NB_CENTRO_ADMVO]
						,[NB_CALLE]
						,[NB_NO_EXTERIOR]
						,[NB_NO_INTERIOR]
						,[NB_COLONIA]
						,[CL_MUNICIPIO]
						,[NB_MUNICIPIO]
						,[CL_ESTADO]
						,[NB_ESTADO]
						,[CL_CODIGO_POSTAL]
						,[FE_CREACION]
						,[CL_USUARIO_APP_CREA]
						,[NB_PROGRAMA_CREA]
					
						)
			VALUES
					   (NEWID() 
					    ,@PIN_CL_CLIENTE
						,@PIN_ID_REGISTRO_PATRONAL
						,@PIN_CL_CENTRO_ADMVO 
						,@PIN_NB_CENTRO_ADMVO 
						,@PIN_NB_CALLE 
						,@PIN_NB_NO_EXTERIOR 
						,@PIN_NB_NO_INTERIOR
						,@PIN_NB_COLONIA 
						,@PIN_CL_MUNICIPIO 
						,@PIN_NB_MUNICIPIO 
						,@PIN_CL_ESTADO
						,@PIN_NB_ESTADO 
						,@PIN_CL_CODIGO_POSTAL 
						,@CFE_SISTEMA
						,@PIN_CL_USUARIO_APP_CREA 			
						,@PIN_NB_PROGRAMA_CREA 
						)
						
			END ELSE BEGIN
			--SE ACTUALIZA EL REGISTRO EN LA TABLA  ADM.C_CENTRO_ADMVO
			UPDATE ADM.C_CENTRO_ADMVO SET
						[CL_CLIENTE] = @PIN_CL_CLIENTE
						,[ID_REGISTRO_PATRONAL] = @PIN_ID_REGISTRO_PATRONAL
						,[CL_CENTRO_ADMVO] = @PIN_CL_CENTRO_ADMVO 
						,[NB_CENTRO_ADMVO] = @PIN_NB_CENTRO_ADMVO
						,[NB_CALLE] = @PIN_NB_CALLE 
						,[NB_NO_EXTERIOR] = @PIN_NB_NO_EXTERIOR 
						,[NB_NO_INTERIOR] = @PIN_NB_NO_INTERIOR
						,[NB_COLONIA] = @PIN_NB_COLONIA 
						,[CL_MUNICIPIO] = @PIN_CL_MUNICIPIO
						,[NB_MUNICIPIO] = @PIN_NB_MUNICIPIO
						,[CL_ESTADO] = @PIN_CL_ESTADO
						,[NB_ESTADO] = @PIN_NB_ESTADO 						 
						,[CL_CODIGO_POSTAL] = @PIN_CL_CODIGO_POSTAL
						,[FE_CREACION] = @CFE_SISTEMA
						,[CL_USUARIO_APP_CREA] = @PIN_CL_USUARIO_APP_CREA
						,[NB_PROGRAMA_CREA] = @PIN_NB_PROGRAMA_CREA 

			WHERE [ID_CENTRO_ADMVO] = @PIN_ID_CENTRO_ADMVO
			END


--SE DEVUELVE LA VARIABLE DE RETORNO INDICANDO QUE TODO SE REALIZO CORRECTAMENTE
		SET @XML_RESULTADO = DBO.F_ERROR_CREAR_ENCABEZADO( @@ROWCOUNT,1, 'SUCCESSFUL')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'Proceso exitoso', 'ES')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'Successful Process', 'EN')
		--SI SE GENERO UNA TRANSACCION EN ESTE BLOQUE LA TERMINARA
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			COMMIT	
	END TRY
	BEGIN CATCH		
		--SI OCURRIO UN ERROR Y SE INICIO UNA TRANSACCION ENE ESTE BLOQUE SE CANCELARA LA TRANSACCION
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			ROLLBACK
		--SE INDICA EN LA VARIABLE DE RETORNO QUE OCURRIO UN ERROR
		--SET @POUT_CLAVE_RETORNO = 0
		--SE INSERTA EL ERROR EN LA TABLA		
		DECLARE @ERROR_CLAVE INT  = 	ERROR_NUMBER()
		DECLARE @ERROR_MENSAJE NVARCHAR(250)  = 	 ERROR_MESSAGE()
		
		SET @XML_RESULTADO = DBO.F_ERROR_CREAR_ENCABEZADO( @@ROWCOUNT, @ERROR_CLAVE, 'ERROR')
		SET @XML_RESULTADO = DBO.F_ERROR_MENSAJES(@ERROR_CLAVE,@ERROR_MENSAJE)
		SET @XML_RESULTADO = DBO.F_ERROR_MENSAJES(@ERROR_CLAVE,@ERROR_MENSAJE)
			
	END CATCH
END