-- =============================================
-- Proyecto: Sigein 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Margarita Salcedo
-- CREATE date: 14/09/2015
-- Description: Obtiene los C_EVALUADOR_EXTERNO 
-- =============================================
CREATE PROCEDURE ADM.SPE_OBTIENE_C_EVALUADOR_EXTERNO 
	    @PIN_ID_EVALUADOR_EXTERNO AS int = NULL,
        @PIN_CL_EVALUADOR_EXTERNO AS nvarchar(32) = NULL,
        @PIN_NB_EVALUADOR_EXTERNO AS nvarchar(100) = NULL,
        @PIN_DS_EVALUARDO_EXTERNO AS nvarchar(200) = NULL,
        @PIN_FG_ACTIVO AS bit = NULL,
        @PIN_XML_CAMPOS_ADICIONALES AS xml = NULL

AS   
	SELECT 
		[ID_EVALUADOR_EXTERNO],
		[CL_EVALUADOR_EXTERNO],
		[NB_EVALUADOR_EXTERNO],
		[DS_EVALUARDO_EXTERNO],
		[FG_ACTIVO],
		[XML_CAMPOS_ADICIONALES]
		,'' as DS_FILTRO
	FROM ADM.C_EVALUADOR_EXTERNO
	WHERE (@PIN_ID_EVALUADOR_EXTERNO IS NULL OR (@PIN_ID_EVALUADOR_EXTERNO IS NOT NULL AND [ID_EVALUADOR_EXTERNO] = @PIN_ID_EVALUADOR_EXTERNO)) AND 
		(@PIN_CL_EVALUADOR_EXTERNO IS NULL OR (@PIN_CL_EVALUADOR_EXTERNO IS NOT NULL AND [CL_EVALUADOR_EXTERNO] = @PIN_CL_EVALUADOR_EXTERNO)) AND 
		(@PIN_NB_EVALUADOR_EXTERNO IS NULL OR (@PIN_NB_EVALUADOR_EXTERNO IS NOT NULL AND [NB_EVALUADOR_EXTERNO] = @PIN_NB_EVALUADOR_EXTERNO)) AND 
		(@PIN_DS_EVALUARDO_EXTERNO IS NULL OR (@PIN_DS_EVALUARDO_EXTERNO IS NOT NULL AND [DS_EVALUARDO_EXTERNO] = @PIN_DS_EVALUARDO_EXTERNO)) AND 
		(@PIN_FG_ACTIVO IS NULL OR (@PIN_FG_ACTIVO IS NOT NULL AND [FG_ACTIVO] = @PIN_FG_ACTIVO))

