CREATE TABLE [IDP].[C_CUESTIONARIO] (
    [ID_CUESTIONARIO]         INT            IDENTITY (1, 1) NOT NULL,
    [CL_CUESTIONARIO]         NVARCHAR (20)  NOT NULL,
    [NB_CUESTIONARIO]         NVARCHAR (100) NOT NULL,
    [FE_CREACION]             DATETIME       NOT NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    CONSTRAINT [PK__C_CUESTI__EE94F5AC34CF3E9E] PRIMARY KEY CLUSTERED ([ID_CUESTIONARIO] ASC)
);

