CREATE TABLE [IDP].[C_FACTOR] (
    [ID_FACTOR]               INT             IDENTITY (1, 1) NOT NULL,
    [CL_FACTOR]               NVARCHAR (20)   NOT NULL,
    [NB_FACTOR]               NVARCHAR (100)  NOT NULL,
    [DS_FACTOR]               NVARCHAR (1000) NULL,
    [ID_VARIABLE]             INT             NULL,
    [NB_ABREVIATURA]          NVARCHAR (50)   NULL,
    [FE_CREACION]             DATETIME        NOT NULL,
    [FE_MODIFICACION]         DATETIME        NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)   NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)   NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)   NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)   NULL,
    CONSTRAINT [PK__C_FACTOR__5B3F73FDA521DE81] PRIMARY KEY CLUSTERED ([ID_FACTOR] ASC),
    CONSTRAINT [FK_C_FACTOR_C_VARIABLE] FOREIGN KEY ([ID_VARIABLE]) REFERENCES [IDP].[C_VARIABLE] ([ID_VARIABLE])
);

