CREATE TABLE [IDP].[C_PRUEBA_NIVEL] (
    [ID_PRUEBA_NIVEL]         INT            IDENTITY (1, 1) NOT NULL,
    [CL_PRUEBA_NIVEL]         NVARCHAR (10)  NOT NULL,
    [NB_PRUEBA_NIVEL]         NVARCHAR (100) NOT NULL,
    [FE_CREACION]             DATETIME       NOT NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([ID_PRUEBA_NIVEL] ASC)
);

