CREATE TABLE [IDP].[C_PRUEBA] (
    [ID_PRUEBA]               INT            IDENTITY (1, 1) NOT NULL,
    [CL_PRUEBA]               NVARCHAR (20)  NOT NULL,
    [NB_PRUEBA]               NVARCHAR (100) NOT NULL,
    [ID_CUESTIONARIO]         INT            NOT NULL,
    [NO_TIEMPO_PRUEBA]        SMALLINT       NOT NULL,
    [NO_ORDEN]                INT            NULL,
    [FE_CREACION]             DATETIME       NOT NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    CONSTRAINT [PK__C_PRUEBA__E845D2CBC57EC781] PRIMARY KEY CLUSTERED ([ID_PRUEBA] ASC),
    CONSTRAINT [FK__C_PRUEBA__ID_CUE__23DE44F1] FOREIGN KEY ([ID_CUESTIONARIO]) REFERENCES [IDP].[C_CUESTIONARIO] ([ID_CUESTIONARIO])
);

