CREATE TABLE [IDP].[C_PRUEBA_SECCION] (
    [ID_PRUEBA_SECCION]       INT            IDENTITY (1, 1) NOT NULL,
    [ID_PRUEBA]               INT            NOT NULL,
    [CL_PRUEBA_SECCION]       NVARCHAR (100) NOT NULL,
    [NB_PRUEBA_SECCION]       NVARCHAR (500) NOT NULL,
    [NO_TIEMPO]               INT            NULL,
    [FE_CREACION]             DATETIME       NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    CONSTRAINT [PK__C_PRUEBA__FB59C81D38A69D74] PRIMARY KEY CLUSTERED ([ID_PRUEBA_SECCION] ASC),
    CONSTRAINT [FK__C_PRUEBA___ID_PR__3F51553C] FOREIGN KEY ([ID_PRUEBA]) REFERENCES [IDP].[C_PRUEBA] ([ID_PRUEBA])
);

