CREATE TABLE [IDP].[C_VARIABLE] (
    [ID_VARIABLE]             INT           NOT NULL,
    [CL_VARIABLE]             NVARCHAR (50) NOT NULL,
    [NB_PRUEBA]               NVARCHAR (50) NOT NULL,
    [CL_TIPO_VARIABLE]        INT           NOT NULL,
    [FE_CREACION]             DATETIME      NOT NULL,
    [FE_MODIFICACION]         DATETIME      NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50) NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50) NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50) NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50) NULL,
    CONSTRAINT [PK_C_VARIABLE] PRIMARY KEY CLUSTERED ([ID_VARIABLE] ASC)
);

