CREATE TABLE [IDP].[K_BATERIA_PRUEBA] (
    [ID_BATERIA]              INT              IDENTITY (1, 1) NOT NULL,
    [FL_BATERIA]              NVARCHAR (30)    NULL,
    [CL_TOKEN]                UNIQUEIDENTIFIER NULL,
    [ID_CANDIDATO]            INT              NOT NULL,
    [FG_ENVIO_CORREO]         BIT              CONSTRAINT [DF_K_BATERIA_PRUEBA_FG_ENVIO_CORREO] DEFAULT ((0)) NOT NULL,
    [ID_CUESTIONARIO_BAREMOS] INT              NULL,
    [FE_CREACION]             DATETIME         NOT NULL,
    [FE_MODIFICACION]         DATETIME         NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)    NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)    NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)    NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)    NULL,
    CONSTRAINT [PK__K_BATERI__7C7B39C7EA099308] PRIMARY KEY CLUSTERED ([ID_BATERIA] ASC),
    CONSTRAINT [FK_K_BATERIA_PRUEBA_C_CANDIDATO] FOREIGN KEY ([ID_CANDIDATO]) REFERENCES [ADM].[C_CANDIDATO] ([ID_CANDIDATO])
);

