CREATE TABLE [IDP].[K_CANDIDATO_COMPETENCIA] (
    [ID_CANDIDATO_COMPETENCIA] INT           IDENTITY (1, 1) NOT NULL,
    [ID_CANDIDATO]             INT           NOT NULL,
    [ID_COMPETENCIA]           INT           NOT NULL,
    [FE_CREACION]              DATETIME      NOT NULL,
    [FE_MODIFICACION]          DATETIME      NULL,
    [CL_USUARIO_APP_CREA]      NVARCHAR (50) NOT NULL,
    [CL_USUARIO_APP_MODIFICA]  NVARCHAR (50) NULL,
    [NB_PROGRAMA_CREA]         NVARCHAR (50) NOT NULL,
    [NB_PROGRAMA_MODIFICA]     NVARCHAR (50) NULL,
    CONSTRAINT [PK_K_CANDIDATO_COMPETENCIA] PRIMARY KEY CLUSTERED ([ID_CANDIDATO_COMPETENCIA] ASC)
);

