CREATE TABLE [IDP].[K_COMPETENCIA_FACTOR] (
    [ID_COMPETENCIA]          INT           NOT NULL,
    [ID_FACTOR]               INT           NOT NULL,
    [FE_CREACION]             DATETIME      NOT NULL,
    [FE_MODIFICACION]         DATETIME      NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50) NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50) NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50) NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([ID_COMPETENCIA] ASC, [ID_FACTOR] ASC),
    CONSTRAINT [FK_COMPETENCIA_COMPETENCIA_FACTOR] FOREIGN KEY ([ID_COMPETENCIA]) REFERENCES [ADM].[C_COMPETENCIA] ([ID_COMPETENCIA]),
    CONSTRAINT [FK_FACTOR_COMPETENCIA_FACTOR] FOREIGN KEY ([ID_FACTOR]) REFERENCES [IDP].[C_FACTOR] ([ID_FACTOR])
);

