CREATE TABLE [IDP].[K_PRUEBA_SECCION] (
    [ID_PRUEBA_SECCION]       INT           IDENTITY (1, 1) NOT NULL,
    [ID_PRUEBA]               INT           NOT NULL,
    [CL_PRUEBA_SECCION]       VARCHAR (20)  NOT NULL,
    [NB_PRUEBA_SECCION]       VARCHAR (200) NOT NULL,
    [NO_TIEMPO]               INT           NULL,
    [CL_ESTADO]               NVARCHAR (20) NULL,
    [FE_INICIO]               DATETIME      NULL,
    [FE_TERMINO]              DATETIME      NULL,
    [FE_CREACION]             DATETIME      NOT NULL,
    [FE_MODIFICACION]         DATETIME      NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50) NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50) NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50) NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([ID_PRUEBA_SECCION] ASC),
    CONSTRAINT [FK__K_PRUEBA___ID_PR__6576FE24] FOREIGN KEY ([ID_PRUEBA]) REFERENCES [IDP].[K_PRUEBA] ([ID_PRUEBA])
);

