CREATE TABLE [IDP].[K_PRUEBA_FACTOR] (
    [ID_PRUEBA]               INT           NOT NULL,
    [ID_FACTOR]               INT           NOT NULL,
    [FE_CREACION]             DATETIME      NOT NULL,
    [FE_MODIFICACION]         DATETIME      NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50) NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50) NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50) NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([ID_PRUEBA] ASC, [ID_FACTOR] ASC),
    CONSTRAINT [FK_FACTOR_PRUEBA_FACTOR] FOREIGN KEY ([ID_FACTOR]) REFERENCES [IDP].[C_FACTOR] ([ID_FACTOR]),
    CONSTRAINT [FK_PRUEBA_PRUEBA_FACTOR] FOREIGN KEY ([ID_PRUEBA]) REFERENCES [IDP].[C_PRUEBA] ([ID_PRUEBA])
);

