CREATE TABLE [IDP].[K_PRUEBA_NIVEL] (
    [ID_PRUEBA_NIVEL]         INT           NOT NULL,
    [ID_PRUEBA]               INT           NOT NULL,
    [FE_CREACION]             DATETIME      NOT NULL,
    [FE_MODIFICACION]         DATETIME      NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50) NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50) NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50) NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50) NULL,
    FOREIGN KEY ([ID_PRUEBA_NIVEL]) REFERENCES [IDP].[C_PRUEBA_NIVEL] ([ID_PRUEBA_NIVEL]),
    CONSTRAINT [FK__K_PRUEBA___ID_PR__30441BD6] FOREIGN KEY ([ID_PRUEBA]) REFERENCES [IDP].[C_PRUEBA] ([ID_PRUEBA])
);

