CREATE TABLE [IDP].[K_RESULTADO] (
    [ID_RESULTADO]            INT             IDENTITY (1, 1) NOT NULL,
    [CL_TIPO_RESULTADO]       INT             NOT NULL,
    [ID_VARIABLE]             INT             NOT NULL,
    [NO_VALOR]                DECIMAL (13, 3) NOT NULL,
    [NO_GRUPO]                INT             NULL,
    [ID_CUESTIONARIO]         INT             NOT NULL,
    [FE_CREACION]             DATETIME        NOT NULL,
    [FE_MODIFICACION]         DATETIME        NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)   NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)   NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)   NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)   NULL,
    CONSTRAINT [PK_K_RESULTADO] PRIMARY KEY CLUSTERED ([ID_RESULTADO] ASC),
    CONSTRAINT [FK_K_RESULTADO_K_CUESTIONARIO] FOREIGN KEY ([ID_CUESTIONARIO]) REFERENCES [ADM].[K_CUESTIONARIO] ([ID_CUESTIONARIO])
);

