-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Margarita Salcedo
-- CREATE date: 21/09/2015
-- Description: Obtiene los datos de la tabla K_EMPLEADO_COMPETENCIA 
-- =============================================
ALTER PROCEDURE ADM.SPE_OBTIENE_K_EMPLEADO_COMPETENCIA 
	@PIN_ID_EMPLEADO_COMPETENCIA AS int = NULL
	, @PIN_ID_EMPLEADO AS int = NULL
	, @PIN_ID_COMPETENCIA AS int = NULL
	, @PIN_NO_CALIFICACION AS decimal(8,3) = NULL
	
AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT 
		[ID_EMPLEADO_COMPETENCIA]
		, [ID_EMPLEADO]
		, [ID_COMPETENCIA]
		, [NO_CALIFICACION]
		,'' as DS_FILTRO
	FROM ADM.K_EMPLEADO_COMPETENCIA
	WHERE (@PIN_ID_EMPLEADO_COMPETENCIA IS NULL OR (@PIN_ID_EMPLEADO_COMPETENCIA IS NOT NULL AND [ID_EMPLEADO_COMPETENCIA] = @PIN_ID_EMPLEADO_COMPETENCIA))
			 AND (@PIN_ID_EMPLEADO IS NULL OR (@PIN_ID_EMPLEADO IS NOT NULL AND [ID_EMPLEADO] = @PIN_ID_EMPLEADO))
			 AND (@PIN_ID_COMPETENCIA IS NULL OR (@PIN_ID_COMPETENCIA IS NOT NULL AND [ID_COMPETENCIA] = @PIN_ID_COMPETENCIA))
			 AND (@PIN_NO_CALIFICACION IS NULL OR (@PIN_NO_CALIFICACION IS NOT NULL AND [NO_CALIFICACION] = @PIN_NO_CALIFICACION))
			
GO
