--=============================================================================================================================
--=============================================================================================================================
SET ANSI_NULLS ON 
GO
SET QUOTED_IDENTIFIER ON 
GO
-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Jesús Vázquez Pereyra
-- CREATE date: 07/10/2015
-- Description: Obtiene los datos de la tabla C_CLASIFICACION_COMPETENCIA 
-- =============================================
alter PROCEDURE ADM.SPE_OBTIENE_C_CLASIFICACION_COMPETENCIA 
	@PIN_ID_CLASIFICACION_COMPETENCIA AS int = NULL
	, @PIN_CL_CLASIFICACION AS nvarchar(20) = NULL
	, @PIN_CL_TIPO_COMPETENCIA AS nvarchar(20) = NULL
	, @PIN_NB_CLASIFICACION_COMPETENCIA AS nvarchar(100) = NULL
	, @PIN_DS_CLASIFICACION_COMPETENCIA AS nvarchar(1000) = NULL
	, @PIN_DS_NOTAS_CLASIFICACION AS nvarchar(1000) = NULL
	, @PIN_FG_ACTIVO AS BIT = NULL
	
AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT 
		CC.[ID_CLASIFICACION_COMPETENCIA]
		, CC.[CL_CLASIFICACION]
		, CC.[CL_TIPO_COMPETENCIA]
		, CC.[NB_CLASIFICACION_COMPETENCIA]
		, CC.[DS_CLASIFICACION_COMPETENCIA]
		, CC.[DS_NOTAS_CLASIFICACION]
		, CC.FG_ACTIVO
		, TP.DS_TIPO_COMPETENCIA
		, TP.NB_TIPO_COMPETENCIA
		,'' as DS_FILTRO
	FROM ADM.C_CLASIFICACION_COMPETENCIA AS CC
	LEFT OUTER JOIN ADM.S_TIPO_COMPETENCIA  AS TP ON TP.CL_TIPO_COMPETENCIA = CC.CL_TIPO_COMPETENCIA
	WHERE (@PIN_ID_CLASIFICACION_COMPETENCIA IS NULL OR (@PIN_ID_CLASIFICACION_COMPETENCIA IS NOT NULL AND CC.[ID_CLASIFICACION_COMPETENCIA] = @PIN_ID_CLASIFICACION_COMPETENCIA))
			 AND (@PIN_CL_CLASIFICACION IS NULL OR (@PIN_CL_CLASIFICACION IS NOT NULL AND CC.[CL_CLASIFICACION] = @PIN_CL_CLASIFICACION))
			 AND (@PIN_CL_TIPO_COMPETENCIA IS NULL OR (@PIN_CL_TIPO_COMPETENCIA IS NOT NULL AND CC.[CL_TIPO_COMPETENCIA] = @PIN_CL_TIPO_COMPETENCIA))
			 AND (@PIN_NB_CLASIFICACION_COMPETENCIA IS NULL OR (@PIN_NB_CLASIFICACION_COMPETENCIA IS NOT NULL AND CC.[NB_CLASIFICACION_COMPETENCIA] = @PIN_NB_CLASIFICACION_COMPETENCIA))
			 AND (@PIN_DS_CLASIFICACION_COMPETENCIA IS NULL OR (@PIN_DS_CLASIFICACION_COMPETENCIA IS NOT NULL AND CC.[DS_CLASIFICACION_COMPETENCIA] = @PIN_DS_CLASIFICACION_COMPETENCIA))
			 AND (@PIN_DS_NOTAS_CLASIFICACION IS NULL OR (@PIN_DS_NOTAS_CLASIFICACION IS NOT NULL AND CC.[DS_NOTAS_CLASIFICACION] = @PIN_DS_NOTAS_CLASIFICACION))
			 AND (@PIN_FG_ACTIVO IS NULL OR (@PIN_FG_ACTIVO IS NOT NULL AND CC.FG_ACTIVO = @PIN_FG_ACTIVO))
			 
			
GO
