-- =============================================
-- Proyecto: Sigein 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Margarita Salcedo
-- CREATE date: 15/09/2015
-- Description: Obtiene los C_EMPLEADO_ESCOLARIDAD 
-- =============================================
ALTER PROCEDURE ADM.SPE_OBTIENE_C_EMPLEADO_ESCOLARIDAD 
	    @PIN_ID_EMPLEADO_ESCOLARIDAD AS int = NULL,
        @PIN_ID_EMPLEADO AS int = NULL,
        @PIN_ID_ESCOLARIDAD AS int = NULL,
        @PIN_FE_PERIODO_INICIO AS date = NULL,
        @PIN_FE_PERIODO_FIN AS date = NULL
AS   
	SELECT 
		[ID_EMPLEADO_ESCOLARIDAD],
		[ID_EMPLEADO],
		[ID_ESCOLARIDAD],
		[FE_PERIODO_INICIO],
		[FE_PERIODO_FIN]
		,'' as DS_FILTRO
	FROM ADM.C_EMPLEADO_ESCOLARIDAD
	WHERE (@PIN_ID_EMPLEADO_ESCOLARIDAD IS NULL OR (@PIN_ID_EMPLEADO_ESCOLARIDAD IS NOT NULL AND [ID_EMPLEADO_ESCOLARIDAD] = @PIN_ID_EMPLEADO_ESCOLARIDAD)) AND 
			(@PIN_ID_EMPLEADO IS NULL OR (@PIN_ID_EMPLEADO IS NOT NULL AND [ID_EMPLEADO] = @PIN_ID_EMPLEADO)) AND 
			(@PIN_ID_ESCOLARIDAD IS NULL OR (@PIN_ID_ESCOLARIDAD IS NOT NULL AND [ID_ESCOLARIDAD] = @PIN_ID_ESCOLARIDAD)) AND 
			(@PIN_FE_PERIODO_INICIO IS NULL OR (@PIN_FE_PERIODO_INICIO IS NOT NULL AND [FE_PERIODO_INICIO] = @PIN_FE_PERIODO_INICIO)) AND 
			(@PIN_FE_PERIODO_FIN IS NULL OR (@PIN_FE_PERIODO_FIN IS NOT NULL AND [FE_PERIODO_FIN] = @PIN_FE_PERIODO_FIN)) 

GO