-- =============================================
-- Proyecto: Sigein 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Margarita Salcedo
-- CREATE date: 14/09/2015
-- Description: Obtiene los S_FUNCION 
-- =============================================
ALTER PROCEDURE ADM.SPE_OBTIENE_S_FUNCION 
	    @PIN_ID_FUNCION AS int = NULL,
        @PIN_CL_FUNCION AS nvarchar(30) = NULL,
        @PIN_CL_TIPO_FUNCION AS nvarchar(100) = NULL,
        @PIN_NB_FUNCION AS nvarchar(100) = NULL,
        @PIN_ID_FUNCION_PADRE AS int = NULL,
        @PIN_NB_URL AS nvarchar(500) = NULL,
        @PIN_XML_CONFIGURACION AS xml = NULL

AS   
	SELECT 
			[ID_FUNCION],
			[CL_FUNCION],
			[CL_TIPO_FUNCION],
			[NB_FUNCION],
			[ID_FUNCION_PADRE],
			[NB_URL],
			[XML_CONFIGURACION]
			,'' as DS_FILTRO
	FROM ADM.S_FUNCION
	WHERE (@PIN_ID_FUNCION IS NULL OR (@PIN_ID_FUNCION IS NOT NULL AND [ID_FUNCION] = @PIN_ID_FUNCION)) AND 
			(@PIN_CL_FUNCION IS NULL OR (@PIN_CL_FUNCION IS NOT NULL AND [CL_FUNCION] = @PIN_CL_FUNCION)) AND 
			(@PIN_CL_TIPO_FUNCION IS NULL OR (@PIN_CL_TIPO_FUNCION IS NOT NULL AND [CL_TIPO_FUNCION] = @PIN_CL_TIPO_FUNCION)) AND 
			(@PIN_NB_FUNCION IS NULL OR (@PIN_NB_FUNCION IS NOT NULL AND [NB_FUNCION] = @PIN_NB_FUNCION)) AND 
			(@PIN_ID_FUNCION_PADRE IS NULL OR (@PIN_ID_FUNCION_PADRE IS NOT NULL AND [ID_FUNCION_PADRE] = @PIN_ID_FUNCION_PADRE)) AND 
			(@PIN_NB_URL IS NULL OR (@PIN_NB_URL IS NOT NULL AND [NB_URL] = @PIN_NB_URL))

GO