-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Margarita Salcedo
-- CREATE date: 02/11/2015
-- Description: Obtiene los datos de la tabla C_EMPRESA 
-- =============================================
ALTER PROCEDURE ADM.SPE_OBTIENE_C_EMPRESA 
	@PIN_ID_EMPRESA AS int = NULL
	, @PIN_CL_EMPRESA AS nvarchar(20) = NULL
	, @PIN_NB_EMPRESA AS nvarchar(100) = NULL
	, @PIN_NB_RAZON_SOCIAL AS nvarchar(200) = NULL
	
AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT 
		[ID_EMPRESA]
		, [CL_EMPRESA]
		, [NB_EMPRESA]
		, [NB_RAZON_SOCIAL]
		
		,'' as DS_FILTRO
	FROM ADM.C_EMPRESA
	WHERE (@PIN_ID_EMPRESA IS NULL OR (@PIN_ID_EMPRESA IS NOT NULL AND [ID_EMPRESA] = @PIN_ID_EMPRESA))
			 AND (@PIN_CL_EMPRESA IS NULL OR (@PIN_CL_EMPRESA IS NOT NULL AND [CL_EMPRESA] = @PIN_CL_EMPRESA))
			 AND (@PIN_NB_EMPRESA IS NULL OR (@PIN_NB_EMPRESA IS NOT NULL AND [NB_EMPRESA] = @PIN_NB_EMPRESA))
			 AND (@PIN_NB_RAZON_SOCIAL IS NULL OR (@PIN_NB_RAZON_SOCIAL IS NOT NULL AND [NB_RAZON_SOCIAL] = @PIN_NB_RAZON_SOCIAL))
			
GO
