-- =============================================
-- Proyecto: Sigein 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Margarita Salcedo
-- CREATE date: 14/09/2015
-- Description: Obtiene los C_MUNICIPIO 
-- =============================================
ALTER PROCEDURE ADM.SPE_OBTIENE_C_MUNICIPIO 
	    @PIN_ID_MUNICIPIO AS int = NULL,
        @PIN_CL_PAIS AS nvarchar(10) = NULL,
        @PIN_CL_ESTADO AS nvarchar(10) = NULL,
        @PIN_CL_MUNICIPIO AS nvarchar(10) = NULL,
        @PIN_NB_MUNICIPIO AS nvarchar(100) = NULL

AS   
	SELECT 
		[ID_MUNICIPIO],
		[CL_PAIS],
		[CL_ESTADO],
		[CL_MUNICIPIO],
		[NB_MUNICIPIO]
		,'' as DS_FILTRO
	FROM ADM.C_MUNICIPIO
	WHERE (@PIN_ID_MUNICIPIO IS NULL OR (@PIN_ID_MUNICIPIO IS NOT NULL AND [ID_MUNICIPIO] = @PIN_ID_MUNICIPIO)) AND 
			(@PIN_CL_PAIS IS NULL OR (@PIN_CL_PAIS IS NOT NULL AND [CL_PAIS] = @PIN_CL_PAIS)) AND 
			(@PIN_CL_ESTADO IS NULL OR (@PIN_CL_ESTADO IS NOT NULL AND [CL_ESTADO] = @PIN_CL_ESTADO)) AND 
			(@PIN_CL_MUNICIPIO IS NULL OR (@PIN_CL_MUNICIPIO IS NOT NULL AND [CL_MUNICIPIO] = @PIN_CL_MUNICIPIO)) AND 
			(@PIN_NB_MUNICIPIO IS NULL OR (@PIN_NB_MUNICIPIO IS NOT NULL AND [NB_MUNICIPIO] = @PIN_NB_MUNICIPIO)) 

GO
