-- =============================================
-- Proyecto: Sigein 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Margarita Salcedo
-- CREATE date: 15/09/2015
-- Description: Obtiene los M_EMPLEADO 
-- =============================================
-- alter: JVP 29/10/2015 se actualiza la tabla y se le agrega el campo de filtrado
-- =============================================

ALTER PROCEDURE ADM.SPE_OBTIENE_M_EMPLEADO 
	@PIN_ID_EMPLEADO AS int = NULL
	, @PIN_CL_EMPLEADO AS nvarchar(20) = NULL
	, @PIN_NB_EMPLEADO AS nvarchar(100) = NULL
	, @PIN_NB_APELLIDO_PATERNO AS nvarchar(100) = NULL
	, @PIN_NB_APELLIDO_MATERNO AS nvarchar(100) = NULL
	, @PIN_CL_ESTADO_EMPLEADO AS nvarchar(20) = NULL
	, @PIN_CL_GENERO AS nvarchar(1) = NULL
	, @PIN_CL_ESTADO_CIVIL AS nvarchar(20) = NULL
	, @PIN_NB_CONYUGUE AS nvarchar(100) = NULL
	, @PIN_CL_RFC AS nvarchar(20) = NULL
	, @PIN_CL_CURP AS nvarchar(20) = NULL
	, @PIN_CL_NSS AS nvarchar(20) = NULL
	, @PIN_CL_TIPO_SANGUINEO AS nvarchar(10) = NULL
	, @PIN_CL_NACIONALIDAD AS nvarchar(30) = NULL
	, @PIN_NB_PAIS AS nvarchar(100) = NULL
	, @PIN_NB_ESTADO AS nvarchar(100) = NULL
	, @PIN_NB_MUNICIPIO AS nvarchar(100) = NULL
	, @PIN_NB_COLONIA AS nvarchar(100) = NULL
	, @PIN_NB_CALLE AS nvarchar(100) = NULL
	, @PIN_NO_INTERIOR AS nvarchar(20) = NULL
	, @PIN_NO_EXTERIOR AS nvarchar(20) = NULL
	, @PIN_CL_CODIGO_POSTAL AS nvarchar(10) = NULL
	, @PIN_XML_TELEFONOS AS xml = NULL
	, @PIN_CL_CORREO_ELECTRONICO AS nvarchar(200) = NULL
	, @PIN_FG_ACTIVO AS bit = NULL
	, @PIN_FE_NACIMIENTO AS date = NULL
	, @PIN_DS_LUGAR_NACIMIENTO AS nvarchar(200) = NULL
	, @PIN_FE_ALTA AS date = NULL
	, @PIN_FE_BAJA AS date = NULL
	, @PIN_ID_PUESTO AS int = NULL
	, @PIN_MN_SUELDO AS decimal(13,2) = NULL
	, @PIN_MN_SUELDO_VARIABLE AS decimal(13,2) = NULL
	, @PIN_DS_SUELDO_COMPOSICION AS nvarchar(512) = NULL
	, @PIN_ID_CANDIDATO AS int = NULL
	, @PIN_ID_EMPRESA AS int = NULL
	, @PIN_XML_CAMPOS_ADICIONALES AS xml = NULL
	
AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT 
		[ID_EMPLEADO]
		, [CL_EMPLEADO]
		, [NB_EMPLEADO]
		, [NB_APELLIDO_PATERNO]
		, [NB_APELLIDO_MATERNO]
		, [CL_ESTADO_EMPLEADO]
		, [CL_GENERO]
		, [CL_ESTADO_CIVIL]
		, [NB_CONYUGUE]
		, [CL_RFC]
		, [CL_CURP]
		, [CL_NSS]
		, [CL_TIPO_SANGUINEO]
		, [CL_NACIONALIDAD]
		, [NB_PAIS]
		, [NB_ESTADO]
		, [NB_MUNICIPIO]
		, [NB_COLONIA]
		, [NB_CALLE]
		, [NO_INTERIOR]
		, [NO_EXTERIOR]
		, [CL_CODIGO_POSTAL]
		, [XML_TELEFONOS]
		, [CL_CORREO_ELECTRONICO]
		, [FG_ACTIVO]
		, [FE_NACIMIENTO]
		, [DS_LUGAR_NACIMIENTO]
		, [FE_ALTA]
		, [FE_BAJA]
		, [ID_PUESTO]
		, [MN_SUELDO]
		, [MN_SUELDO_VARIABLE]
		, [DS_SUELDO_COMPOSICION]
		, [ID_CANDIDATO]
		, [ID_EMPRESA]
		, [XML_CAMPOS_ADICIONALES]
		,'' as DS_FILTRO
	FROM ADM.M_EMPLEADO
	WHERE (@PIN_ID_EMPLEADO IS NULL OR (@PIN_ID_EMPLEADO IS NOT NULL AND [ID_EMPLEADO] = @PIN_ID_EMPLEADO))
			 AND (@PIN_CL_EMPLEADO IS NULL OR (@PIN_CL_EMPLEADO IS NOT NULL AND [CL_EMPLEADO] = @PIN_CL_EMPLEADO))
			 AND (@PIN_NB_EMPLEADO IS NULL OR (@PIN_NB_EMPLEADO IS NOT NULL AND [NB_EMPLEADO] = @PIN_NB_EMPLEADO))
			 AND (@PIN_NB_APELLIDO_PATERNO IS NULL OR (@PIN_NB_APELLIDO_PATERNO IS NOT NULL AND [NB_APELLIDO_PATERNO] = @PIN_NB_APELLIDO_PATERNO))
			 AND (@PIN_NB_APELLIDO_MATERNO IS NULL OR (@PIN_NB_APELLIDO_MATERNO IS NOT NULL AND [NB_APELLIDO_MATERNO] = @PIN_NB_APELLIDO_MATERNO))
			 AND (@PIN_CL_ESTADO_EMPLEADO IS NULL OR (@PIN_CL_ESTADO_EMPLEADO IS NOT NULL AND [CL_ESTADO_EMPLEADO] = @PIN_CL_ESTADO_EMPLEADO))
			 AND (@PIN_CL_GENERO IS NULL OR (@PIN_CL_GENERO IS NOT NULL AND [CL_GENERO] = @PIN_CL_GENERO))
			 AND (@PIN_CL_ESTADO_CIVIL IS NULL OR (@PIN_CL_ESTADO_CIVIL IS NOT NULL AND [CL_ESTADO_CIVIL] = @PIN_CL_ESTADO_CIVIL))
			 AND (@PIN_NB_CONYUGUE IS NULL OR (@PIN_NB_CONYUGUE IS NOT NULL AND [NB_CONYUGUE] = @PIN_NB_CONYUGUE))
			 AND (@PIN_CL_RFC IS NULL OR (@PIN_CL_RFC IS NOT NULL AND [CL_RFC] = @PIN_CL_RFC))
			 AND (@PIN_CL_CURP IS NULL OR (@PIN_CL_CURP IS NOT NULL AND [CL_CURP] = @PIN_CL_CURP))
			 AND (@PIN_CL_NSS IS NULL OR (@PIN_CL_NSS IS NOT NULL AND [CL_NSS] = @PIN_CL_NSS))
			 AND (@PIN_CL_TIPO_SANGUINEO IS NULL OR (@PIN_CL_TIPO_SANGUINEO IS NOT NULL AND [CL_TIPO_SANGUINEO] = @PIN_CL_TIPO_SANGUINEO))
			 AND (@PIN_CL_NACIONALIDAD IS NULL OR (@PIN_CL_NACIONALIDAD IS NOT NULL AND [CL_NACIONALIDAD] = @PIN_CL_NACIONALIDAD))
			 AND (@PIN_NB_PAIS IS NULL OR (@PIN_NB_PAIS IS NOT NULL AND [NB_PAIS] = @PIN_NB_PAIS))
			 AND (@PIN_NB_ESTADO IS NULL OR (@PIN_NB_ESTADO IS NOT NULL AND [NB_ESTADO] = @PIN_NB_ESTADO))
			 AND (@PIN_NB_MUNICIPIO IS NULL OR (@PIN_NB_MUNICIPIO IS NOT NULL AND [NB_MUNICIPIO] = @PIN_NB_MUNICIPIO))
			 AND (@PIN_NB_COLONIA IS NULL OR (@PIN_NB_COLONIA IS NOT NULL AND [NB_COLONIA] = @PIN_NB_COLONIA))
			 AND (@PIN_NB_CALLE IS NULL OR (@PIN_NB_CALLE IS NOT NULL AND [NB_CALLE] = @PIN_NB_CALLE))
			 AND (@PIN_NO_INTERIOR IS NULL OR (@PIN_NO_INTERIOR IS NOT NULL AND [NO_INTERIOR] = @PIN_NO_INTERIOR))
			 AND (@PIN_NO_EXTERIOR IS NULL OR (@PIN_NO_EXTERIOR IS NOT NULL AND [NO_EXTERIOR] = @PIN_NO_EXTERIOR))
			 AND (@PIN_CL_CODIGO_POSTAL IS NULL OR (@PIN_CL_CODIGO_POSTAL IS NOT NULL AND [CL_CODIGO_POSTAL] = @PIN_CL_CODIGO_POSTAL))
		--	 AND (@PIN_XML_TELEFONOS IS NULL OR (@PIN_XML_TELEFONOS IS NOT NULL AND [XML_TELEFONOS] = @PIN_XML_TELEFONOS))
			 AND (@PIN_CL_CORREO_ELECTRONICO IS NULL OR (@PIN_CL_CORREO_ELECTRONICO IS NOT NULL AND [CL_CORREO_ELECTRONICO] = @PIN_CL_CORREO_ELECTRONICO))
			 AND (@PIN_FG_ACTIVO IS NULL OR (@PIN_FG_ACTIVO IS NOT NULL AND [FG_ACTIVO] = @PIN_FG_ACTIVO))
			 AND (@PIN_FE_NACIMIENTO IS NULL OR (@PIN_FE_NACIMIENTO IS NOT NULL AND [FE_NACIMIENTO] = @PIN_FE_NACIMIENTO))
			 AND (@PIN_DS_LUGAR_NACIMIENTO IS NULL OR (@PIN_DS_LUGAR_NACIMIENTO IS NOT NULL AND [DS_LUGAR_NACIMIENTO] = @PIN_DS_LUGAR_NACIMIENTO))
			 AND (@PIN_FE_ALTA IS NULL OR (@PIN_FE_ALTA IS NOT NULL AND [FE_ALTA] = @PIN_FE_ALTA))
			 AND (@PIN_FE_BAJA IS NULL OR (@PIN_FE_BAJA IS NOT NULL AND [FE_BAJA] = @PIN_FE_BAJA))
			 AND (@PIN_ID_PUESTO IS NULL OR (@PIN_ID_PUESTO IS NOT NULL AND [ID_PUESTO] = @PIN_ID_PUESTO))
			 AND (@PIN_MN_SUELDO IS NULL OR (@PIN_MN_SUELDO IS NOT NULL AND [MN_SUELDO] = @PIN_MN_SUELDO))
			 AND (@PIN_MN_SUELDO_VARIABLE IS NULL OR (@PIN_MN_SUELDO_VARIABLE IS NOT NULL AND [MN_SUELDO_VARIABLE] = @PIN_MN_SUELDO_VARIABLE))
			 AND (@PIN_DS_SUELDO_COMPOSICION IS NULL OR (@PIN_DS_SUELDO_COMPOSICION IS NOT NULL AND [DS_SUELDO_COMPOSICION] = @PIN_DS_SUELDO_COMPOSICION))
			 AND (@PIN_ID_CANDIDATO IS NULL OR (@PIN_ID_CANDIDATO IS NOT NULL AND [ID_CANDIDATO] = @PIN_ID_CANDIDATO))
			 AND (@PIN_ID_EMPRESA IS NULL OR (@PIN_ID_EMPRESA IS NOT NULL AND [ID_EMPRESA] = @PIN_ID_EMPRESA))
			-- AND (@PIN_XML_CAMPOS_ADICIONALES IS NULL OR (@PIN_XML_CAMPOS_ADICIONALES IS NOT NULL AND [XML_CAMPOS_ADICIONALES] = @PIN_XML_CAMPOS_ADICIONALES))
