-- =============================================
-- Proyecto: Sigein 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Margarita Salcedo	
-- CREATE date: 15/09/2015
-- Description: Obtiene los C_NIVEL_ESCOLARIDAD 
-- =============================================
ALTER PROCEDURE ADM.SPE_OBTIENE_C_NIVEL_ESCOLARIDAD 
	    @PIN_ID_NIVEL_ESCOLARIDAD AS int = NULL,
        @PIN_CL_NIVEL_ESCOLARIDAD AS nvarchar(100) = NULL,
        @PIN_DS_NIVEL_ESCOLARIDAD AS nvarchar(200) = NULL,
        @PIN_FG_ACTIVO AS bit = NULL

AS   
	SELECT 
			[ID_NIVEL_ESCOLARIDAD],
			[CL_NIVEL_ESCOLARIDAD],
			[DS_NIVEL_ESCOLARIDAD],
			[FG_ACTIVO]
			,'' as DS_FILTRO
	FROM ADM.C_NIVEL_ESCOLARIDAD
	WHERE (@PIN_ID_NIVEL_ESCOLARIDAD IS NULL OR (@PIN_ID_NIVEL_ESCOLARIDAD IS NOT NULL AND [ID_NIVEL_ESCOLARIDAD] = @PIN_ID_NIVEL_ESCOLARIDAD)) AND 
			(@PIN_CL_NIVEL_ESCOLARIDAD IS NULL OR (@PIN_CL_NIVEL_ESCOLARIDAD IS NOT NULL AND [CL_NIVEL_ESCOLARIDAD] = @PIN_CL_NIVEL_ESCOLARIDAD)) AND 
			(@PIN_DS_NIVEL_ESCOLARIDAD IS NULL OR (@PIN_DS_NIVEL_ESCOLARIDAD IS NOT NULL AND [DS_NIVEL_ESCOLARIDAD] = @PIN_DS_NIVEL_ESCOLARIDAD)) AND 
			(@PIN_FG_ACTIVO IS NULL OR (@PIN_FG_ACTIVO IS NOT NULL AND [FG_ACTIVO] = @PIN_FG_ACTIVO)) 

GO