-- =============================================
-- Proyecto: Sigein 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Margarita Salcedo
-- CREATE date: 15/09/2015
-- Description: Obtiene los C_DEPENDIENTE_ECONOMICO 
-- =============================================
alter PROCEDURE ADM.SPE_OBTIENE_C_DEPENDIENTE_ECONOMICO 
	    @PIN_ID_DEPENDIENTE_ECONOMICO AS int = NULL,
        @PIN_NB_DEPENDIENTE_ECONOMICO AS nvarchar(50) = NULL,
        @PIN_CL_PARENTEZCO AS nvarchar(20) = NULL,
        @PIN_CL_GENERO AS nvarchar(1) = NULL,
        @PIN_FE_NACIMIENTO AS date = NULL,
        @PIN_ID_BITACORA AS int = NULL,
        @PIN_CL_OCUPACION AS bit = NULL,
        @PIN_FG_ACTIVO AS bit = NULL

AS   
	SELECT 
		[ID_DEPENDIENTE_ECONOMICO],
		[NB_DEPENDIENTE_ECONOMICO],
		[CL_PARENTEZCO],
		[CL_GENERO],
		[FE_NACIMIENTO],
		[ID_BITACORA],
		[CL_OCUPACION],
		[FG_ACTIVO]
		,'' as DS_FILTRO
	FROM ADM.C_DEPENDIENTE_ECONOMICO
	WHERE (@PIN_ID_DEPENDIENTE_ECONOMICO IS NULL OR (@PIN_ID_DEPENDIENTE_ECONOMICO IS NOT NULL AND [ID_DEPENDIENTE_ECONOMICO] = @PIN_ID_DEPENDIENTE_ECONOMICO)) AND 
	(@PIN_NB_DEPENDIENTE_ECONOMICO IS NULL OR (@PIN_NB_DEPENDIENTE_ECONOMICO IS NOT NULL AND [NB_DEPENDIENTE_ECONOMICO] = @PIN_NB_DEPENDIENTE_ECONOMICO)) AND 
	(@PIN_CL_PARENTEZCO IS NULL OR (@PIN_CL_PARENTEZCO IS NOT NULL AND [CL_PARENTEZCO] = @PIN_CL_PARENTEZCO)) AND 
	(@PIN_CL_GENERO IS NULL OR (@PIN_CL_GENERO IS NOT NULL AND [CL_GENERO] = @PIN_CL_GENERO)) AND 
	(@PIN_FE_NACIMIENTO IS NULL OR (@PIN_FE_NACIMIENTO IS NOT NULL AND [FE_NACIMIENTO] = @PIN_FE_NACIMIENTO)) AND 
	(@PIN_ID_BITACORA IS NULL OR (@PIN_ID_BITACORA IS NOT NULL AND [ID_BITACORA] = @PIN_ID_BITACORA)) AND 
	(@PIN_CL_OCUPACION IS NULL OR (@PIN_CL_OCUPACION IS NOT NULL AND [CL_OCUPACION] = @PIN_CL_OCUPACION)) AND 
	(@PIN_FG_ACTIVO IS NULL OR (@PIN_FG_ACTIVO IS NOT NULL AND [FG_ACTIVO] = @PIN_FG_ACTIVO)) 

GO