-- =============================================
-- Proyecto: Sigein 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Margarita Salcedo
-- CREATE date: 14/09/2015
-- Description: Obtiene los M_PUESTO 
-- =============================================
--jvp 23/10/2015 SE LE AGREGA LOS CAMPOS RELACIONADOS CON LA TABLA DE PUESTOS PENDIENTE PUESTO RELACIONADO
-- =============================================
ALTER  PROCEDURE ADM.SPE_OBTIENE_M_PUESTO 
	@PIN_ID_PUESTO AS int = NULL
	, @PIN_FG_ACTIVO AS bit = NULL
	, @PIN_FE_INACTIVO AS datetime = NULL
	, @PIN_CL_PUESTO AS nvarchar(20) = NULL
	, @PIN_NB_PUESTO AS nvarchar(100) = NULL
	, @PIN_ID_PUESTO_JEFE AS int = NULL
	, @PIN_ID_DEPARTAMENTO AS int = NULL
	, @PIN_XML_CAMPOS_ADICIONALES AS xml = NULL
	, @PIN_ID_BITACORA AS int = NULL
	, @PIN_NB_DEPARTAMENTO AS nvarchar(100) = NULL
	, @PIN_CL_DEPARTAMENTO AS nvarchar(30) = NULL
	, @PIN_XML_CAMPOS_ADICIONALES_DEPARTAMENTO AS xml = NULL
	, @PIN_DS_REPORTA_A  AS nvarchar(300) = NULL
	, @PIN_CL_REPORTA_A  AS nvarchar(100) = NULL
AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT 
		P.ID_PUESTO
		, P.FG_ACTIVO
		, P.FE_INACTIVO
		, P.CL_PUESTO
		, P.NB_PUESTO
		, P.ID_PUESTO_JEFE
		, P.ID_DEPARTAMENTO
		, P.XML_CAMPOS_ADICIONALES
		, P.ID_BITACORA
		, D.NB_DEPARTAMENTO
		, D.CL_DEPARTAMENTO
		, ISNULL(D.XML_CAMPOS_ADICIONALES, '') AS XML_CAMPOS_ADICIONALES_DEPARTAMENTO
		, '' AS DS_REPORTA_A
		, '' AS CL_REPORTA_A
		, P.CL_PUESTO+' '+P.NB_PUESTO  as DS_FILTRO
		
	FROM ADM.M_PUESTO AS P
	LEFT OUTER JOIN ADM.M_DEPARTAMENTO AS D ON D.ID_DEPARTAMENTO = P.ID_DEPARTAMENTO
	WHERE (@PIN_ID_PUESTO IS NULL OR (@PIN_ID_PUESTO IS NOT NULL AND P.ID_PUESTO = @PIN_ID_PUESTO))
			 AND (@PIN_FG_ACTIVO IS NULL OR (@PIN_FG_ACTIVO IS NOT NULL AND P.FG_ACTIVO = @PIN_FG_ACTIVO))
			 AND (@PIN_FE_INACTIVO IS NULL OR (@PIN_FE_INACTIVO IS NOT NULL AND P.FE_INACTIVO = @PIN_FE_INACTIVO))
			 AND (@PIN_CL_PUESTO IS NULL OR (@PIN_CL_PUESTO IS NOT NULL AND P.CL_PUESTO = @PIN_CL_PUESTO))
			 AND (@PIN_NB_PUESTO IS NULL OR (@PIN_NB_PUESTO IS NOT NULL AND P.NB_PUESTO = @PIN_NB_PUESTO))
			 AND (@PIN_ID_PUESTO_JEFE IS NULL OR (@PIN_ID_PUESTO_JEFE IS NOT NULL AND P.ID_PUESTO_JEFE = @PIN_ID_PUESTO_JEFE))
			 AND (@PIN_ID_DEPARTAMENTO IS NULL OR (@PIN_ID_DEPARTAMENTO IS NOT NULL AND P.ID_DEPARTAMENTO = @PIN_ID_DEPARTAMENTO))
			-- AND (@PIN_XML_CAMPOS_ADICIONALES IS NULL OR (@PIN_XML_CAMPOS_ADICIONALES IS NOT NULL AND P.XML_CAMPOS_ADICIONALES = @PIN_XML_CAMPOS_ADICIONALES))
			 AND (@PIN_ID_BITACORA IS NULL OR (@PIN_ID_BITACORA IS NOT NULL AND P.ID_BITACORA = @PIN_ID_BITACORA))
			 
			 AND (@PIN_NB_DEPARTAMENTO IS NULL OR (@PIN_NB_DEPARTAMENTO IS NOT NULL AND D.NB_DEPARTAMENTO = @PIN_NB_DEPARTAMENTO))
			 AND (@PIN_CL_DEPARTAMENTO IS NULL OR (@PIN_CL_DEPARTAMENTO IS NOT NULL AND D.CL_DEPARTAMENTO = @PIN_CL_DEPARTAMENTO))
			-- AND (@PIN_XML_CAMPOS_ADICIONALES_DEPARTAMENTO IS NULL OR (@PIN_XML_CAMPOS_ADICIONALES_DEPARTAMENTO IS NOT NULL AND D.XML_CAMPOS_ADICIONALES = @PIN_XML_CAMPOS_ADICIONALES_DEPARTAMENTO))
			 --AND (@PIN_DS_REPORTA_A IS NULL OR (@PIN_DS_REPORTA_A IS NOT NULL AND x.DS_REPORTA_A = @PIN_DS_REPORTA_A))
			 --AND (@PIN_CL_REPORTA_A IS NULL OR (@PIN_CL_REPORTA_A IS NOT NULL AND x.CL_REPORTA_A = @PIN_CL_REPORTA_A))
			
GO
