-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Margarita Salcedo
-- CREATE date: 27/10/2015
-- Description: Obtiene los datos de la tabla S_CATALOGO_TIPO 
-- =============================================
CREATE PROCEDURE ADM.SPE_OBTIENE_S_CATALOGO_TIPO 
	@PIN_ID_CATALOGO_TIPO AS int = NULL
	, @PIN_NB_CATALOGO_TIPO AS nvarchar(100) = NULL
	, @PIN_DS_CATALOGO_TIPO AS nvarchar(1000) = NULL
	
AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT 
		[ID_CATALOGO_TIPO]
		, [NB_CATALOGO_TIPO]
		, [DS_CATALOGO_TIPO]
		
	FROM ADM.S_CATALOGO_TIPO
	WHERE (@PIN_ID_CATALOGO_TIPO IS NULL OR (@PIN_ID_CATALOGO_TIPO IS NOT NULL AND [ID_CATALOGO_TIPO] = @PIN_ID_CATALOGO_TIPO))
			 AND (@PIN_NB_CATALOGO_TIPO IS NULL OR (@PIN_NB_CATALOGO_TIPO IS NOT NULL AND [NB_CATALOGO_TIPO] = @PIN_NB_CATALOGO_TIPO))
			 AND (@PIN_DS_CATALOGO_TIPO IS NULL OR (@PIN_DS_CATALOGO_TIPO IS NOT NULL AND [DS_CATALOGO_TIPO] = @PIN_DS_CATALOGO_TIPO))
			
GO
