-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Margarita Salcedo
-- CREATE date: 18/09/2015
-- Description: Obtiene los datos de la tabla C_USUARIO 
-- =============================================
ALTER PROCEDURE ADM.SPE_OBTIENE_C_USUARIO 
	@PIN_CL_USUARIO AS nvarchar(50) = NULL
	, @PIN_NB_USUARIO AS nvarchar(300) = NULL
	, @PIN_NB_CORREO_ELECTRONICO AS nvarchar(500) = NULL
	, @PIN_NB_PASSWORD AS nvarchar(100) = NULL
	, @PIN_FG_CAMBIAR_PASSWORD AS bit = NULL
	, @PIN_XML_PERSONALIZACION AS xml = NULL
	, @PIN_ID_ROL AS int = NULL
	, @PIN_ID_EMPLEADO AS int = NULL
	, @PIN_FG_ACTIVO AS bit = NULL
	, @PIN_FE_INACTIVO AS datetime = NULL
	
AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT 
		[CL_USUARIO]
		, [NB_USUARIO]
		, [NB_CORREO_ELECTRONICO]
		, [NB_PASSWORD]
		, [FG_CAMBIAR_PASSWORD]
		, [XML_PERSONALIZACION]
		, [ID_ROL]
		, [ID_EMPLEADO]
		, [FG_ACTIVO]
		, [FE_INACTIVO]
		,'' as DS_FILTRO
	FROM ADM.C_USUARIO
	WHERE (@PIN_CL_USUARIO IS NULL OR (@PIN_CL_USUARIO IS NOT NULL AND [CL_USUARIO] = @PIN_CL_USUARIO))
			 AND (@PIN_NB_USUARIO IS NULL OR (@PIN_NB_USUARIO IS NOT NULL AND [NB_USUARIO] = @PIN_NB_USUARIO))
			 AND (@PIN_NB_CORREO_ELECTRONICO IS NULL OR (@PIN_NB_CORREO_ELECTRONICO IS NOT NULL AND [NB_CORREO_ELECTRONICO] = @PIN_NB_CORREO_ELECTRONICO))
			 AND (@PIN_NB_PASSWORD IS NULL OR (@PIN_NB_PASSWORD IS NOT NULL AND [NB_PASSWORD] = @PIN_NB_PASSWORD))
			 AND (@PIN_FG_CAMBIAR_PASSWORD IS NULL OR (@PIN_FG_CAMBIAR_PASSWORD IS NOT NULL AND [FG_CAMBIAR_PASSWORD] = @PIN_FG_CAMBIAR_PASSWORD))
			 --AND (@PIN_XML_PERSONALIZACION IS NULL OR (@PIN_XML_PERSONALIZACION IS NOT NULL AND [XML_PERSONALIZACION] = @PIN_XML_PERSONALIZACION))
			 AND (@PIN_ID_ROL IS NULL OR (@PIN_ID_ROL IS NOT NULL AND [ID_ROL] = @PIN_ID_ROL))
			 AND (@PIN_ID_EMPLEADO IS NULL OR (@PIN_ID_EMPLEADO IS NOT NULL AND [ID_EMPLEADO] = @PIN_ID_EMPLEADO))
			 AND (@PIN_FG_ACTIVO IS NULL OR (@PIN_FG_ACTIVO IS NOT NULL AND [FG_ACTIVO] = @PIN_FG_ACTIVO))
			 AND (@PIN_FE_INACTIVO IS NULL OR (@PIN_FE_INACTIVO IS NOT NULL AND [FE_INACTIVO] = @PIN_FE_INACTIVO))
			
GO
