-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Margarita Salcedo
-- CREATE date: 04/11/2015
-- Description: Obtiene los datos de la tabla K_SOLICITUD 
-- =============================================
ALTER PROCEDURE ADM.SPE_OBTIENE_K_SOLICITUD 
	@PIN_ID_SOLICITUD AS int = NULL
	, @PIN_ID_CANDIDATO AS int = NULL
	, @PIN_ID_EMPLEADO AS int = NULL
	, @PIN_ID_DESCRIPTIVO AS int = NULL
	, @PIN_ID_REQUISICION AS int = NULL
	, @PIN_CL_SOLICITUD AS nvarchar(20) = NULL
	, @PIN_CL_ACCESO_EVALUACION AS nvarchar(40) = NULL
	, @PIN_ID_PLANTILLA_SOLICITUD AS int = NULL
	, @PIN_DS_COMPETENCIAS_ADICIONALES AS nvarchar(1000) = NULL
	
AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT 
		[ID_SOLICITUD]
		, [ID_CANDIDATO]
		, [ID_EMPLEADO]
		, [ID_DESCRIPTIVO]
		, [ID_REQUISICION]
		, [CL_SOLICITUD]
		, [CL_ACCESO_EVALUACION]
		, [ID_PLANTILLA_SOLICITUD]
		, [DS_COMPETENCIAS_ADICIONALES]
		
		,'' as DS_FILTRO
	FROM ADM.K_SOLICITUD
	WHERE (@PIN_ID_SOLICITUD IS NULL OR (@PIN_ID_SOLICITUD IS NOT NULL AND [ID_SOLICITUD] = @PIN_ID_SOLICITUD))
			 AND (@PIN_ID_CANDIDATO IS NULL OR (@PIN_ID_CANDIDATO IS NOT NULL AND [ID_CANDIDATO] = @PIN_ID_CANDIDATO))
			 AND (@PIN_ID_EMPLEADO IS NULL OR (@PIN_ID_EMPLEADO IS NOT NULL AND [ID_EMPLEADO] = @PIN_ID_EMPLEADO))
			 AND (@PIN_ID_DESCRIPTIVO IS NULL OR (@PIN_ID_DESCRIPTIVO IS NOT NULL AND [ID_DESCRIPTIVO] = @PIN_ID_DESCRIPTIVO))
			 AND (@PIN_ID_REQUISICION IS NULL OR (@PIN_ID_REQUISICION IS NOT NULL AND [ID_REQUISICION] = @PIN_ID_REQUISICION))
			 AND (@PIN_CL_SOLICITUD IS NULL OR (@PIN_CL_SOLICITUD IS NOT NULL AND [CL_SOLICITUD] = @PIN_CL_SOLICITUD))
			 AND (@PIN_CL_ACCESO_EVALUACION IS NULL OR (@PIN_CL_ACCESO_EVALUACION IS NOT NULL AND [CL_ACCESO_EVALUACION] = @PIN_CL_ACCESO_EVALUACION))
			 AND (@PIN_ID_PLANTILLA_SOLICITUD IS NULL OR (@PIN_ID_PLANTILLA_SOLICITUD IS NOT NULL AND [ID_PLANTILLA_SOLICITUD] = @PIN_ID_PLANTILLA_SOLICITUD))
			 AND (@PIN_DS_COMPETENCIAS_ADICIONALES IS NULL OR (@PIN_DS_COMPETENCIAS_ADICIONALES IS NOT NULL AND [DS_COMPETENCIAS_ADICIONALES] = @PIN_DS_COMPETENCIAS_ADICIONALES))
			
GO
