-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Margarita Salcedo
-- CREATE date: 04/11/2015
-- Description: Obtiene los datos de la tabla C_CANDIDATO 
-- =============================================
ALTER PROCEDURE ADM.SPE_OBTIENE_C_CANDIDATO 
	@PIN_ID_CANDIDATO AS int = NULL
	, @PIN_NB_CANDIDATO AS nvarchar(100) = NULL
	, @PIN_NB_APELLIDO_PATERNO AS nvarchar(100) = NULL
	, @PIN_NB_APELLIDO_MATERNO AS nvarchar(100) = NULL
	, @PIN_CL_GENERO AS nvarchar(1) = NULL
	, @PIN_CL_RFC AS nvarchar(20) = NULL
	, @PIN_CL_CURP AS nvarchar(20) = NULL
	, @PIN_CL_ESTADO_CIVIL AS nvarchar(20) = NULL
	, @PIN_NB_CONYUGUE AS nvarchar(100) = NULL
	, @PIN_CL_NSS AS nvarchar(20) = NULL
	, @PIN_CL_TIPO_SANGUINEO AS nvarchar(10) = NULL
	, @PIN_NB_PAIS AS nvarchar(100) = NULL
	, @PIN_NB_ESTADO AS nvarchar(100) = NULL
	, @PIN_NB_MUNICIPIO AS nvarchar(100) = NULL
	, @PIN_NB_COLONIA AS nvarchar(100) = NULL
	, @PIN_NB_CALLE AS nvarchar(100) = NULL
	, @PIN_NO_INTERIOR AS nvarchar(20) = NULL
	, @PIN_NO_EXTERIOR AS nvarchar(20) = NULL
	, @PIN_CL_CODIGO_POSTAL AS nvarchar(10) = NULL
	, @PIN_CL_CORREO_ELECTRONICO AS nvarchar(200) = NULL
	, @PIN_FE_NACIMIENTO AS date = NULL
	, @PIN_DS_LUGAR_NACIMIENTO AS nvarchar(200) = NULL
	, @PIN_MN_SUELDO AS decimal(13,2) = NULL
	, @PIN_CL_NACIONALIDAD AS nvarchar(30) = NULL
	, @PIN_DS_NACIONALIDAD AS nvarchar(30) = NULL
	, @PIN_NB_LICENCIA AS nvarchar(30) = NULL
	, @PIN_DS_VEHICULO AS nvarchar(100) = NULL
	, @PIN_CL_CARTILLA_MILITAR AS nvarchar(30) = NULL
	, @PIN_CL_CEDULA_PROFESIONAL AS nvarchar(30) = NULL
	, @PIN_XML_TELEFONOS AS xml = NULL
	, @PIN_XML_INGRESOS AS xml = NULL
	, @PIN_XML_EGRESOS AS xml = NULL
	, @PIN_XML_PATRIMONIO AS xml = NULL
	, @PIN_DS_DISPONIBILIDAD AS nvarchar(100) = NULL
	, @PIN_CL_DISPONIBILIDAD_VIAJE AS nvarchar(10) = NULL
	, @PIN_XML_PERFIL_RED_SOCIAL AS xml = NULL
	, @PIN_DS_COMENTARIO AS nvarchar(1000) = NULL
	, @PIN_FG_ACTIVO AS bit = NULL
	
AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT 
		[ID_CANDIDATO]
		, [NB_CANDIDATO]
		, [NB_APELLIDO_PATERNO]
		, [NB_APELLIDO_MATERNO]
		, [CL_GENERO]
		, [CL_RFC]
		, [CL_CURP]
		, [CL_ESTADO_CIVIL]
		, [NB_CONYUGUE]
		, [CL_NSS]
		, [CL_TIPO_SANGUINEO]
		, [NB_PAIS]
		, [NB_ESTADO]
		, [NB_MUNICIPIO]
		, [NB_COLONIA]
		, [NB_CALLE]
		, [NO_INTERIOR]
		, [NO_EXTERIOR]
		, [CL_CODIGO_POSTAL]
		, [CL_CORREO_ELECTRONICO]
		, [FE_NACIMIENTO]
		, [DS_LUGAR_NACIMIENTO]
		, [MN_SUELDO]
		, [CL_NACIONALIDAD]
		, [DS_NACIONALIDAD]
		, [NB_LICENCIA]
		, [DS_VEHICULO]
		, [CL_CARTILLA_MILITAR]
		, [CL_CEDULA_PROFESIONAL]
		, [XML_TELEFONOS]
		, [XML_INGRESOS]
		, [XML_EGRESOS]
		, [XML_PATRIMONIO]
		, [DS_DISPONIBILIDAD]
		, [CL_DISPONIBILIDAD_VIAJE]
		, [XML_PERFIL_RED_SOCIAL]
		, [DS_COMENTARIO]
		, [FG_ACTIVO]
		
		,'' as DS_FILTRO
	FROM ADM.C_CANDIDATO
	WHERE (@PIN_ID_CANDIDATO IS NULL OR (@PIN_ID_CANDIDATO IS NOT NULL AND [ID_CANDIDATO] = @PIN_ID_CANDIDATO))
			 AND (@PIN_NB_CANDIDATO IS NULL OR (@PIN_NB_CANDIDATO IS NOT NULL AND [NB_CANDIDATO] = @PIN_NB_CANDIDATO))
			 AND (@PIN_NB_APELLIDO_PATERNO IS NULL OR (@PIN_NB_APELLIDO_PATERNO IS NOT NULL AND [NB_APELLIDO_PATERNO] = @PIN_NB_APELLIDO_PATERNO))
			 AND (@PIN_NB_APELLIDO_MATERNO IS NULL OR (@PIN_NB_APELLIDO_MATERNO IS NOT NULL AND [NB_APELLIDO_MATERNO] = @PIN_NB_APELLIDO_MATERNO))
			 AND (@PIN_CL_GENERO IS NULL OR (@PIN_CL_GENERO IS NOT NULL AND [CL_GENERO] = @PIN_CL_GENERO))
			 AND (@PIN_CL_RFC IS NULL OR (@PIN_CL_RFC IS NOT NULL AND [CL_RFC] = @PIN_CL_RFC))
			 AND (@PIN_CL_CURP IS NULL OR (@PIN_CL_CURP IS NOT NULL AND [CL_CURP] = @PIN_CL_CURP))
			 AND (@PIN_CL_ESTADO_CIVIL IS NULL OR (@PIN_CL_ESTADO_CIVIL IS NOT NULL AND [CL_ESTADO_CIVIL] = @PIN_CL_ESTADO_CIVIL))
			 AND (@PIN_NB_CONYUGUE IS NULL OR (@PIN_NB_CONYUGUE IS NOT NULL AND [NB_CONYUGUE] = @PIN_NB_CONYUGUE))
			 AND (@PIN_CL_NSS IS NULL OR (@PIN_CL_NSS IS NOT NULL AND [CL_NSS] = @PIN_CL_NSS))
			 AND (@PIN_CL_TIPO_SANGUINEO IS NULL OR (@PIN_CL_TIPO_SANGUINEO IS NOT NULL AND [CL_TIPO_SANGUINEO] = @PIN_CL_TIPO_SANGUINEO))
			 AND (@PIN_NB_PAIS IS NULL OR (@PIN_NB_PAIS IS NOT NULL AND [NB_PAIS] = @PIN_NB_PAIS))
			 AND (@PIN_NB_ESTADO IS NULL OR (@PIN_NB_ESTADO IS NOT NULL AND [NB_ESTADO] = @PIN_NB_ESTADO))
			 AND (@PIN_NB_MUNICIPIO IS NULL OR (@PIN_NB_MUNICIPIO IS NOT NULL AND [NB_MUNICIPIO] = @PIN_NB_MUNICIPIO))
			 AND (@PIN_NB_COLONIA IS NULL OR (@PIN_NB_COLONIA IS NOT NULL AND [NB_COLONIA] = @PIN_NB_COLONIA))
			 AND (@PIN_NB_CALLE IS NULL OR (@PIN_NB_CALLE IS NOT NULL AND [NB_CALLE] = @PIN_NB_CALLE))
			 AND (@PIN_NO_INTERIOR IS NULL OR (@PIN_NO_INTERIOR IS NOT NULL AND [NO_INTERIOR] = @PIN_NO_INTERIOR))
			 AND (@PIN_NO_EXTERIOR IS NULL OR (@PIN_NO_EXTERIOR IS NOT NULL AND [NO_EXTERIOR] = @PIN_NO_EXTERIOR))
			 AND (@PIN_CL_CODIGO_POSTAL IS NULL OR (@PIN_CL_CODIGO_POSTAL IS NOT NULL AND [CL_CODIGO_POSTAL] = @PIN_CL_CODIGO_POSTAL))
			 AND (@PIN_CL_CORREO_ELECTRONICO IS NULL OR (@PIN_CL_CORREO_ELECTRONICO IS NOT NULL AND [CL_CORREO_ELECTRONICO] = @PIN_CL_CORREO_ELECTRONICO))
			 AND (@PIN_FE_NACIMIENTO IS NULL OR (@PIN_FE_NACIMIENTO IS NOT NULL AND [FE_NACIMIENTO] = @PIN_FE_NACIMIENTO))
			 AND (@PIN_DS_LUGAR_NACIMIENTO IS NULL OR (@PIN_DS_LUGAR_NACIMIENTO IS NOT NULL AND [DS_LUGAR_NACIMIENTO] = @PIN_DS_LUGAR_NACIMIENTO))
			 AND (@PIN_MN_SUELDO IS NULL OR (@PIN_MN_SUELDO IS NOT NULL AND [MN_SUELDO] = @PIN_MN_SUELDO))
			 AND (@PIN_CL_NACIONALIDAD IS NULL OR (@PIN_CL_NACIONALIDAD IS NOT NULL AND [CL_NACIONALIDAD] = @PIN_CL_NACIONALIDAD))
			 AND (@PIN_DS_NACIONALIDAD IS NULL OR (@PIN_DS_NACIONALIDAD IS NOT NULL AND [DS_NACIONALIDAD] = @PIN_DS_NACIONALIDAD))
			 AND (@PIN_NB_LICENCIA IS NULL OR (@PIN_NB_LICENCIA IS NOT NULL AND [NB_LICENCIA] = @PIN_NB_LICENCIA))
			 AND (@PIN_DS_VEHICULO IS NULL OR (@PIN_DS_VEHICULO IS NOT NULL AND [DS_VEHICULO] = @PIN_DS_VEHICULO))
			 AND (@PIN_CL_CARTILLA_MILITAR IS NULL OR (@PIN_CL_CARTILLA_MILITAR IS NOT NULL AND [CL_CARTILLA_MILITAR] = @PIN_CL_CARTILLA_MILITAR))
			 AND (@PIN_CL_CEDULA_PROFESIONAL IS NULL OR (@PIN_CL_CEDULA_PROFESIONAL IS NOT NULL AND [CL_CEDULA_PROFESIONAL] = @PIN_CL_CEDULA_PROFESIONAL))
			 --AND (@PIN_XML_TELEFONOS IS NULL OR (@PIN_XML_TELEFONOS IS NOT NULL AND [XML_TELEFONOS] = @PIN_XML_TELEFONOS))
			 --AND (@PIN_XML_INGRESOS IS NULL OR (@PIN_XML_INGRESOS IS NOT NULL AND [XML_INGRESOS] = @PIN_XML_INGRESOS))
			 --AND (@PIN_XML_EGRESOS IS NULL OR (@PIN_XML_EGRESOS IS NOT NULL AND [XML_EGRESOS] = @PIN_XML_EGRESOS))
			 --AND (@PIN_XML_PATRIMONIO IS NULL OR (@PIN_XML_PATRIMONIO IS NOT NULL AND [XML_PATRIMONIO] = @PIN_XML_PATRIMONIO))
			 AND (@PIN_DS_DISPONIBILIDAD IS NULL OR (@PIN_DS_DISPONIBILIDAD IS NOT NULL AND [DS_DISPONIBILIDAD] = @PIN_DS_DISPONIBILIDAD))
			 AND (@PIN_CL_DISPONIBILIDAD_VIAJE IS NULL OR (@PIN_CL_DISPONIBILIDAD_VIAJE IS NOT NULL AND [CL_DISPONIBILIDAD_VIAJE] = @PIN_CL_DISPONIBILIDAD_VIAJE))
			 --AND (@PIN_XML_PERFIL_RED_SOCIAL IS NULL OR (@PIN_XML_PERFIL_RED_SOCIAL IS NOT NULL AND [XML_PERFIL_RED_SOCIAL] = @PIN_XML_PERFIL_RED_SOCIAL))
			 AND (@PIN_DS_COMENTARIO IS NULL OR (@PIN_DS_COMENTARIO IS NOT NULL AND [DS_COMENTARIO] = @PIN_DS_COMENTARIO))
			 AND (@PIN_FG_ACTIVO IS NULL OR (@PIN_FG_ACTIVO IS NOT NULL AND [FG_ACTIVO] = @PIN_FG_ACTIVO))
			
GO
