-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Gabriel Vázquez
-- CREATE date: 20/01/2016
-- Description: Insercion de variables de la prueba TIVA
-- =============================================
CREATE PROCEDURE [IDP].[SPE_INSERTA_RESULTADOS_TIVA]
	@XML_RESULTADO XML = '' OUT      --APLICA PARA REGRESAR UN NÚMERO 0 PARA ERROR Y 1 PARA CORRECTO
	,@PIN_XML_RESULTADOS AS XML
	,@PIN_ID_CUESTIONARIO AS INT = NULL
	,@PIN_ID_PRUEBA AS INT
	,@PIN_CL_USUARIO_APP AS NVARCHAR(50)
	,@PIN_NB_PROGRAMA AS NVARCHAR(50)

AS
BEGIN  
	--SE DECLARA E INICIALIZA LA VARIABLE QUE NOS INDICARA SI GENERAMOS LA TRANSACCION EN ESTE SP
	DECLARE @V_EXIST_TRAN BIT = 0,
			@V_FE_SISTEMA AS DATETIME = GETDATE()

    	BEGIN TRY
		--SE VERIFICA SI EXISTE UNA TRANSACCION EN EJECUCION
		IF (@@TRANCOUNT = 0) 
		BEGIN
			--EN CASO DE QUE NO SE INICIALIZA LA TRANSACCION
			BEGIN TRANSACTION
			--SE EDITA LA VARIABLE QUE INDICA QUE SE INICIO LA TRANSACCION EN ESTE BLOQUE PARA CANCELARLA SI ES NECESARIO
			SET @V_EXIST_TRAN = 1
		END	
		--SE VERIFICA SI SE INSERTA EL REGISTRO O SE ACTUALIZARA SEGUN LA VARIABLE DE TIPO DE TRANSACCION  QUE RECIBE EL SP
		IF @PIN_ID_CUESTIONARIO IS NULL BEGIN

			SELECT @PIN_ID_CUESTIONARIO = ID_CUESTIONARIO
			FROM IDP.K_PRUEBA
			WHERE ID_PRUEBA = @PIN_ID_PRUEBA

		END

		DECLARE @T_VARIABLES AS TABLE (CL_VARIABLE_RESPUESTA NVARCHAR(50), CL_VARIABLE_RESULTADO NVARCHAR(50), NO_VALOR1 INT, NO_VALOR2 INT, NO_VALOR3 INT, NO_VALOR4 INT)

		INSERT @T_VARIABLES
		SELECT 'TIVA-A-0001' AS CL_VARIABLE_RESPUESTA, 'TIVA_RES_1' AS CL_VARIABLE_RESULTADO, 2 AS NO_VALOR1, 3 AS NO_VALOR2, 2 AS NO_VALOR3, 1 AS NO_VALOR4 UNION ALL
		SELECT 'TIVA-A-0002' AS CL_VARIABLE_RESPUESTA, 'TIVA_RES_2' AS CL_VARIABLE_RESULTADO, 3 AS NO_VALOR1, 3 AS NO_VALOR2, 1 AS NO_VALOR3, 2 AS NO_VALOR4 UNION ALL
		SELECT 'TIVA-A-0003' AS CL_VARIABLE_RESPUESTA, 'TIVA_RES_3' AS CL_VARIABLE_RESULTADO, 2 AS NO_VALOR1, 3 AS NO_VALOR2, 1 AS NO_VALOR3, 3 AS NO_VALOR4 UNION ALL
		SELECT 'TIVA-A-0004' AS CL_VARIABLE_RESPUESTA, 'TIVA_RES_4' AS CL_VARIABLE_RESULTADO, 3 AS NO_VALOR1, 2 AS NO_VALOR2, 3 AS NO_VALOR3, 1 AS NO_VALOR4 UNION ALL
		SELECT 'TIVA-A-0005' AS CL_VARIABLE_RESPUESTA, 'TIVA_RES_5' AS CL_VARIABLE_RESULTADO, 1 AS NO_VALOR1, 2 AS NO_VALOR2, 3 AS NO_VALOR3, 3 AS NO_VALOR4 UNION ALL
		SELECT 'TIVA-A-0006' AS CL_VARIABLE_RESPUESTA, 'TIVA_RES_6' AS CL_VARIABLE_RESULTADO, 3 AS NO_VALOR1, 1 AS NO_VALOR2, 2 AS NO_VALOR3, 1 AS NO_VALOR4 UNION ALL
		SELECT 'TIVA-A-0007' AS CL_VARIABLE_RESPUESTA, 'TIVA_RES_7' AS CL_VARIABLE_RESULTADO, 3 AS NO_VALOR1, 2 AS NO_VALOR2, 1 AS NO_VALOR3, 2 AS NO_VALOR4 UNION ALL
		SELECT 'TIVA-A-0008' AS CL_VARIABLE_RESPUESTA, 'TIVA_RES_8' AS CL_VARIABLE_RESULTADO, 1 AS NO_VALOR1, 1 AS NO_VALOR2, 3 AS NO_VALOR3, 2 AS NO_VALOR4 UNION ALL
		SELECT 'TIVA-A-0009' AS CL_VARIABLE_RESPUESTA, 'TIVA_RES_9' AS CL_VARIABLE_RESULTADO, 1 AS NO_VALOR1, 3 AS NO_VALOR2, 2 AS NO_VALOR3, 1 AS NO_VALOR4 UNION ALL
		SELECT 'TIVA-A-0010' AS CL_VARIABLE_RESPUESTA, 'TIVA_RES_10' AS CL_VARIABLE_RESULTADO, 1 AS NO_VALOR1, 3 AS NO_VALOR2, 1 AS NO_VALOR3, 2 AS NO_VALOR4 UNION ALL
		SELECT 'TIVA-A-0011' AS CL_VARIABLE_RESPUESTA, 'TIVA_RES_11' AS CL_VARIABLE_RESULTADO, 3 AS NO_VALOR1, 1 AS NO_VALOR2, 2 AS NO_VALOR3, 1 AS NO_VALOR4 UNION ALL
		SELECT 'TIVA-A-0012' AS CL_VARIABLE_RESPUESTA, 'TIVA_RES_12' AS CL_VARIABLE_RESULTADO, 3 AS NO_VALOR1, 2 AS NO_VALOR2, 1 AS NO_VALOR3, 2 AS NO_VALOR4 UNION ALL
		SELECT 'TIVA-A-0013' AS CL_VARIABLE_RESPUESTA, 'TIVA_RES_13' AS CL_VARIABLE_RESULTADO, 3 AS NO_VALOR1, 2 AS NO_VALOR2, 3 AS NO_VALOR3, 1 AS NO_VALOR4 UNION ALL
		SELECT 'TIVA-A-0014' AS CL_VARIABLE_RESPUESTA, 'TIVA_RES_14' AS CL_VARIABLE_RESULTADO, 3 AS NO_VALOR1, 2 AS NO_VALOR2, 3 AS NO_VALOR3, 1 AS NO_VALOR4 UNION ALL
		SELECT 'TIVA-A-0015' AS CL_VARIABLE_RESPUESTA, 'TIVA_RES_15' AS CL_VARIABLE_RESULTADO, 2 AS NO_VALOR1, 1 AS NO_VALOR2, 3 AS NO_VALOR3, 1 AS NO_VALOR4 UNION ALL
		SELECT 'TIVA-A-0016' AS CL_VARIABLE_RESPUESTA, 'TIVA_RES_16' AS CL_VARIABLE_RESULTADO, 1 AS NO_VALOR1, 2 AS NO_VALOR2, 2 AS NO_VALOR3, 3 AS NO_VALOR4 UNION ALL
		SELECT 'TIVA-A-0017' AS CL_VARIABLE_RESPUESTA, 'TIVA_RES_17' AS CL_VARIABLE_RESULTADO, 2 AS NO_VALOR1, 3 AS NO_VALOR2, 1 AS NO_VALOR3, 2 AS NO_VALOR4 UNION ALL
		SELECT 'TIVA-A-0018' AS CL_VARIABLE_RESPUESTA, 'TIVA_RES_18' AS CL_VARIABLE_RESULTADO, 1 AS NO_VALOR1, 3 AS NO_VALOR2, 1 AS NO_VALOR3, 2 AS NO_VALOR4 UNION ALL
		SELECT 'TIVA-A-0019' AS CL_VARIABLE_RESPUESTA, 'TIVA_RES_19' AS CL_VARIABLE_RESULTADO, 3 AS NO_VALOR1, 1 AS NO_VALOR2, 2 AS NO_VALOR3, 2 AS NO_VALOR4 UNION ALL
		SELECT 'TIVA-A-0020' AS CL_VARIABLE_RESPUESTA, 'TIVA_RES_20' AS CL_VARIABLE_RESULTADO, 3 AS NO_VALOR1, 2 AS NO_VALOR2, 3 AS NO_VALOR3, 1 AS NO_VALOR4 

		IF @PIN_XML_RESULTADOS IS NULL 
		BEGIN
			
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA])
			SELECT 2 AS CL_TIPO_RESULTADO, CV2.ID_VARIABLE, CASE KR.NO_VALOR WHEN 1 THEN TV.NO_VALOR1 WHEN 2 THEN TV.NO_VALOR2 WHEN 3 THEN TV.NO_VALOR3 WHEN 4 THEN TV.NO_VALOR4 ELSE 0 END , @PIN_ID_CUESTIONARIO, @V_FE_SISTEMA, @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA
			FROM @T_VARIABLES TV
				INNER JOIN IDP.C_VARIABLE CV1 ON TV.CL_VARIABLE_RESPUESTA = CV1.CL_VARIABLE
				INNER JOIN IDP.K_RESULTADO KR ON CV1.ID_VARIABLE = KR.ID_VARIABLE
				INNER JOIN IDP.C_VARIABLE CV2 ON TV.CL_VARIABLE_RESULTADO = CV2.CL_VARIABLE
			WHERE KR.ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			/*
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 570 AS ID_VARIABLE,/*1*/ CASE NO_VALOR WHEN 1 THEN 2 WHEN 2 THEN 3 WHEN 3 THEN 2 WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 550 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 571 AS ID_VARIABLE,/*2*/ CASE NO_VALOR WHEN 1 THEN 3 WHEN 2 THEN 3 WHEN 3 THEN 1 WHEN 4 THEN 2 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 551 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 572 AS ID_VARIABLE,/*3*/ CASE NO_VALOR WHEN 1 THEN 2 WHEN 2 THEN 3 WHEN 3 THEN 1 WHEN 4 THEN 3 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 552 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 573 AS ID_VARIABLE,/*4*/ CASE NO_VALOR WHEN 1 THEN 3 WHEN 2 THEN 2 WHEN 3 THEN 3 WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 553 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 574 AS ID_VARIABLE,/*5*/ CASE NO_VALOR WHEN 1 THEN 1 WHEN 2 THEN 2 WHEN 3 THEN 3 WHEN 4 THEN 3 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 554 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 575 AS ID_VARIABLE,/*6*/ CASE NO_VALOR WHEN 1 THEN 3 WHEN 2 THEN 1 WHEN 3 THEN 2 WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 555 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 576 AS ID_VARIABLE,/*7*/ CASE NO_VALOR WHEN 1 THEN 3 WHEN 2 THEN 2 WHEN 3 THEN 1 WHEN 4 THEN 2 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 556 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 577 AS ID_VARIABLE,/*8*/ CASE NO_VALOR WHEN 1 THEN 1 WHEN 2 THEN 1 WHEN 3 THEN 3 WHEN 4 THEN 2 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 557 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 578 AS ID_VARIABLE,/*9*/ CASE NO_VALOR WHEN 1 THEN 1 WHEN 2 THEN 3 WHEN 3 THEN 2 WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 558 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 579 AS ID_VARIABLE,/*10*/ CASE NO_VALOR WHEN 1 THEN 1 WHEN 2 THEN 3 WHEN 3 THEN 1 WHEN 4 THEN 2 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 559 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 580 AS ID_VARIABLE,/*11*/ CASE NO_VALOR WHEN 1 THEN 3 WHEN 2 THEN 1 WHEN 3 THEN 2 WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 560 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 581 AS ID_VARIABLE,/*12*/ CASE NO_VALOR WHEN 1 THEN 3 WHEN 2 THEN 2 WHEN 3 THEN 1 WHEN 4 THEN 2 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 561 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 582 AS ID_VARIABLE,/*13*/ CASE NO_VALOR WHEN 1 THEN 3 WHEN 2 THEN 2 WHEN 3 THEN 3 WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 562 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 583 AS ID_VARIABLE,/*14*/ CASE NO_VALOR WHEN 1 THEN 3 WHEN 2 THEN 2 WHEN 3 THEN 3 WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 563 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 584 AS ID_VARIABLE,/*15*/ CASE NO_VALOR WHEN 1 THEN 2 WHEN 2 THEN 1 WHEN 3 THEN 3 WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 564 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 585 AS ID_VARIABLE,/*16*/ CASE NO_VALOR WHEN 1 THEN 1 WHEN 2 THEN 2 WHEN 3 THEN 2 WHEN 4 THEN 3 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 565 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 586 AS ID_VARIABLE,/*17*/ CASE NO_VALOR WHEN 1 THEN 2 WHEN 2 THEN 3 WHEN 3 THEN 1 WHEN 4 THEN 2 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 566 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 587 AS ID_VARIABLE,/*18*/ CASE NO_VALOR WHEN 1 THEN 1 WHEN 2 THEN 3 WHEN 3 THEN 1 WHEN 4 THEN 2 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 567 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 588 AS ID_VARIABLE,/*19*/ CASE NO_VALOR WHEN 1 THEN 3 WHEN 2 THEN 1 WHEN 3 THEN 2 WHEN 4 THEN 2 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 568 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 589 AS ID_VARIABLE,/*20*/ CASE NO_VALOR WHEN 1 THEN 3 WHEN 2 THEN 2 WHEN 3 THEN 3 WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 569 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			*/
		END 
		
		IF @PIN_XML_RESULTADOS IS NOT NULL BEGIN
			
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA])
			SELECT 2 AS CL_TIPO_RESULTADO, CV2.ID_VARIABLE, CASE d.value('@NO_VALOR', 'INT') WHEN 1 THEN TV.NO_VALOR1 WHEN 2 THEN TV.NO_VALOR2 WHEN 3 THEN TV.NO_VALOR3 WHEN 4 THEN TV.NO_VALOR4 ELSE 0 END , @PIN_ID_CUESTIONARIO, @V_FE_SISTEMA, @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA
			FROM @T_VARIABLES TV
				INNER JOIN IDP.C_VARIABLE CV2 ON TV.CL_VARIABLE_RESULTADO = CV2.CL_VARIABLE
				INNER JOIN @PIN_XML_RESULTADOS.nodes('RESULTADOS/RESULTADO') AS T(d) ON CV2.ID_VARIABLE = d.value('@ID_VARIABLE', 'INT')
			--WHERE KR.ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO

			/*
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 570 AS ID_VARIABLE,/*1*/ CASE d.value('@NO_VALOR', 'INT') WHEN 1 THEN 2 WHEN 2 THEN 3 WHEN 3 THEN 2 WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, @PIN_ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM @PIN_XML_RESULTADOS.nodes('RESULTADOS/RESULTADO') AS T(d) WHERE d.value('@ID_VARIABLE', 'INT') = 570
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 571 AS ID_VARIABLE,/*2*/ CASE d.value('@NO_VALOR', 'INT') WHEN 1 THEN 3 WHEN 2 THEN 3 WHEN 3 THEN 1 WHEN 4 THEN 2 ELSE 0 END AS NO_VALOR, @PIN_ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM @PIN_XML_RESULTADOS.nodes('RESULTADOS/RESULTADO') AS T(d) WHERE d.value('@ID_VARIABLE', 'INT') = 571
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 572 AS ID_VARIABLE,/*3*/ CASE d.value('@NO_VALOR', 'INT') WHEN 1 THEN 2 WHEN 2 THEN 3 WHEN 3 THEN 1 WHEN 4 THEN 3 ELSE 0 END AS NO_VALOR, @PIN_ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM @PIN_XML_RESULTADOS.nodes('RESULTADOS/RESULTADO') AS T(d) WHERE d.value('@ID_VARIABLE', 'INT') = 572
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 573 AS ID_VARIABLE,/*4*/ CASE d.value('@NO_VALOR', 'INT') WHEN 1 THEN 3 WHEN 2 THEN 2 WHEN 3 THEN 3 WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, @PIN_ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM @PIN_XML_RESULTADOS.nodes('RESULTADOS/RESULTADO') AS T(d) WHERE d.value('@ID_VARIABLE', 'INT') = 573
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 574 AS ID_VARIABLE,/*5*/ CASE d.value('@NO_VALOR', 'INT') WHEN 1 THEN 1 WHEN 2 THEN 2 WHEN 3 THEN 3 WHEN 4 THEN 3 ELSE 0 END AS NO_VALOR, @PIN_ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM @PIN_XML_RESULTADOS.nodes('RESULTADOS/RESULTADO') AS T(d) WHERE d.value('@ID_VARIABLE', 'INT') = 574
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 575 AS ID_VARIABLE,/*6*/ CASE d.value('@NO_VALOR', 'INT') WHEN 1 THEN 3 WHEN 2 THEN 1 WHEN 3 THEN 2 WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, @PIN_ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM @PIN_XML_RESULTADOS.nodes('RESULTADOS/RESULTADO') AS T(d) WHERE d.value('@ID_VARIABLE', 'INT') = 575
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 576 AS ID_VARIABLE,/*7*/ CASE d.value('@NO_VALOR', 'INT') WHEN 1 THEN 3 WHEN 2 THEN 2 WHEN 3 THEN 1 WHEN 4 THEN 2 ELSE 0 END AS NO_VALOR, @PIN_ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM @PIN_XML_RESULTADOS.nodes('RESULTADOS/RESULTADO') AS T(d) WHERE d.value('@ID_VARIABLE', 'INT') = 576
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 577 AS ID_VARIABLE,/*8*/ CASE d.value('@NO_VALOR', 'INT') WHEN 1 THEN 1 WHEN 2 THEN 1 WHEN 3 THEN 3 WHEN 4 THEN 2 ELSE 0 END AS NO_VALOR, @PIN_ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM @PIN_XML_RESULTADOS.nodes('RESULTADOS/RESULTADO') AS T(d) WHERE d.value('@ID_VARIABLE', 'INT') = 577
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 578 AS ID_VARIABLE,/*9*/ CASE d.value('@NO_VALOR', 'INT') WHEN 1 THEN 1 WHEN 2 THEN 3 WHEN 3 THEN 2 WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, @PIN_ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM @PIN_XML_RESULTADOS.nodes('RESULTADOS/RESULTADO') AS T(d) WHERE d.value('@ID_VARIABLE', 'INT') = 578
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 579 AS ID_VARIABLE,/*10*/ CASE d.value('@NO_VALOR', 'INT') WHEN 1 THEN 1 WHEN 2 THEN 3 WHEN 3 THEN 1 WHEN 4 THEN 2 ELSE 0 END AS NO_VALOR, @PIN_ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM @PIN_XML_RESULTADOS.nodes('RESULTADOS/RESULTADO') AS T(d) WHERE d.value('@ID_VARIABLE', 'INT') = 579
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 580 AS ID_VARIABLE,/*11*/ CASE d.value('@NO_VALOR', 'INT') WHEN 1 THEN 3 WHEN 2 THEN 1 WHEN 3 THEN 2 WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, @PIN_ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM @PIN_XML_RESULTADOS.nodes('RESULTADOS/RESULTADO') AS T(d) WHERE d.value('@ID_VARIABLE', 'INT') = 580
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 581 AS ID_VARIABLE,/*12*/ CASE d.value('@NO_VALOR', 'INT') WHEN 1 THEN 3 WHEN 2 THEN 2 WHEN 3 THEN 1 WHEN 4 THEN 2 ELSE 0 END AS NO_VALOR, @PIN_ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM @PIN_XML_RESULTADOS.nodes('RESULTADOS/RESULTADO') AS T(d) WHERE d.value('@ID_VARIABLE', 'INT') = 581
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 582 AS ID_VARIABLE,/*13*/ CASE d.value('@NO_VALOR', 'INT') WHEN 1 THEN 3 WHEN 2 THEN 2 WHEN 3 THEN 3 WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, @PIN_ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM @PIN_XML_RESULTADOS.nodes('RESULTADOS/RESULTADO') AS T(d) WHERE d.value('@ID_VARIABLE', 'INT') = 582
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 583 AS ID_VARIABLE,/*14*/ CASE d.value('@NO_VALOR', 'INT') WHEN 1 THEN 3 WHEN 2 THEN 2 WHEN 3 THEN 3 WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, @PIN_ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM @PIN_XML_RESULTADOS.nodes('RESULTADOS/RESULTADO') AS T(d) WHERE d.value('@ID_VARIABLE', 'INT') = 583
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 584 AS ID_VARIABLE,/*15*/ CASE d.value('@NO_VALOR', 'INT') WHEN 1 THEN 2 WHEN 2 THEN 1 WHEN 3 THEN 3 WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, @PIN_ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM @PIN_XML_RESULTADOS.nodes('RESULTADOS/RESULTADO') AS T(d) WHERE d.value('@ID_VARIABLE', 'INT') = 584
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 585 AS ID_VARIABLE,/*16*/ CASE d.value('@NO_VALOR', 'INT') WHEN 1 THEN 1 WHEN 2 THEN 2 WHEN 3 THEN 2 WHEN 4 THEN 3 ELSE 0 END AS NO_VALOR, @PIN_ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM @PIN_XML_RESULTADOS.nodes('RESULTADOS/RESULTADO') AS T(d) WHERE d.value('@ID_VARIABLE', 'INT') = 585
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 586 AS ID_VARIABLE,/*17*/ CASE d.value('@NO_VALOR', 'INT') WHEN 1 THEN 2 WHEN 2 THEN 3 WHEN 3 THEN 1 WHEN 4 THEN 2 ELSE 0 END AS NO_VALOR, @PIN_ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM @PIN_XML_RESULTADOS.nodes('RESULTADOS/RESULTADO') AS T(d) WHERE d.value('@ID_VARIABLE', 'INT') = 586
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 587 AS ID_VARIABLE,/*18*/ CASE d.value('@NO_VALOR', 'INT') WHEN 1 THEN 1 WHEN 2 THEN 3 WHEN 3 THEN 1 WHEN 4 THEN 2 ELSE 0 END AS NO_VALOR, @PIN_ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM @PIN_XML_RESULTADOS.nodes('RESULTADOS/RESULTADO') AS T(d) WHERE d.value('@ID_VARIABLE', 'INT') = 587
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 588 AS ID_VARIABLE,/*19*/ CASE d.value('@NO_VALOR', 'INT') WHEN 1 THEN 3 WHEN 2 THEN 1 WHEN 3 THEN 2 WHEN 4 THEN 2 ELSE 0 END AS NO_VALOR, @PIN_ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM @PIN_XML_RESULTADOS.nodes('RESULTADOS/RESULTADO') AS T(d) WHERE d.value('@ID_VARIABLE', 'INT') = 588
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 589 AS ID_VARIABLE,/*20*/ CASE d.value('@NO_VALOR', 'INT') WHEN 1 THEN 3 WHEN 2 THEN 2 WHEN 3 THEN 3 WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, @PIN_ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM @PIN_XML_RESULTADOS.nodes('RESULTADOS/RESULTADO') AS T(d) WHERE d.value('@ID_VARIABLE', 'INT') = 589
			*/
				--EXEC [IDP].[SPE_INSERTA_REPORTE_TIVA] @XML_RESULTADO ,@PIN_ID_CUESTIONARIO ,@PIN_CL_USUARIO_APP,@PIN_NB_PROGRAMA
		END

		EXEC [IDP].[SPE_INSERTA_REPORTE_TIVA] @XML_RESULTADO ,@PIN_ID_CUESTIONARIO ,@PIN_CL_USUARIO_APP,@PIN_NB_PROGRAMA

		--SE DEVUELVE LA VARIABLE DE RETORNO INDICANDO QUE TODO SE REALIZO CORRECTAMENTE
		SET @XML_RESULTADO = DBO.F_ERROR_CREAR_ENCABEZADO( @@ROWCOUNT, 1, 'SUCCESSFUL')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'Proceso exitoso', 'ES')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'Successful Process', 'EN')
		--SI SE GENERO UNA TRANSACCION EN ESTE BLOQUE LA TERMINARA
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			COMMIT
	END TRY
	BEGIN CATCH
		--SI OCURRIO UN ERROR Y SE INICIO UNA TRANSACCION ENE ESTE BLOQUE SE CANCELARA LA TRANSACCION
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			ROLLBACK
		--SE INDICA EN LA VARIABLE DE RETORNO QUE OCURRIO UN ERROR
		--SET @POUT_CLAVE_RETORNO = 0
		--SE INSERTA EL ERROR EN LA TABLA
		DECLARE @ERROR_CLAVE INT  = ERROR_NUMBER()
		DECLARE @ERROR_MENSAJE NVARCHAR(250)  = ERROR_MESSAGE()
		
		SET @XML_RESULTADO = DBO.F_ERROR_CREAR_ENCABEZADO( @@ROWCOUNT, @ERROR_CLAVE, 'ERROR')
		SET @XML_RESULTADO = DBO.F_ERROR_MENSAJES(@ERROR_CLAVE,@ERROR_MENSAJE)
		SET @XML_RESULTADO = DBO.F_ERROR_MENSAJES(@ERROR_CLAVE,@ERROR_MENSAJE)
	END CATCH
END


