-- =============================================
-- Proyecto: Sigein 5.0
-- Copyright (c) - Acrux - 2016
-- Author: Daniela Sanchez
-- CREATE date: 03/02/2016
-- Description: Inserta variables tipo 3 de prueba TECNICAPC
-- =============================================
CREATE PROCEDURE [IDP].[SPE_INSERTA_REPORTE_TECNICAPC]
	@XML_RESULTADO XML = '' OUT 
	,@PIN_ID_CUESTIONARIO AS INT = NULL
	,@PIN_CL_USUARIO_APP_CREA AS nvarchar(50)
    ,@PIN_NB_PROGRAMA_CREA AS nvarchar(50)
AS
BEGIN
DECLARE @V_EXIST_TRAN BIT = 0
			
    	BEGIN TRY
		--SE VERIFICA SI EXISTE UNA TRANSACCION EN EJECUCION
		IF (@@TRANCOUNT = 0) 
		BEGIN
			--EN CASO DE QUE NO SE INICIALIZA LA TRANSACCION
			BEGIN TRANSACTION
			--SE EDITA LA VARIABLE QUE INDICA QUE SE INICIO LA TRANSACCION EN ESTE BLOQUE PARA CANCELARLA SI ES NECESARIO
			SET @V_EXIST_TRAN = 1
		END	
		--SE VERIFICA SI SE INSERTA EL REGISTRO O SE ACTUALIZARA SEGUN LA VARIABLE DE TIPO DE TRANSACCION  QUE RECIBE EL SP
		IF @PIN_ID_CUESTIONARIO IS NOT NULL
			BEGIN

DECLARE @PIN_TECNICAPC_REP_T DECIMAL(5,2) =0
DECLARE @PIN_TECNICAPC_REP_C DECIMAL(5,2) =0
DECLARE @PIN_TECNICAPC_REP_S DECIMAL(5,2) =0
DECLARE @PIN_TECNICAPC_REP_I DECIMAL(5,2) =0
DECLARE @PIN_TECNICAPC_REP_H DECIMAL(5,2) =0
DECLARE @PIN_TECNICAPC_REP_P_T DECIMAL(5,2) =0

DECLARE @PIN_NIVEL_C DECIMAL(5,2) =0
DECLARE @PIN_NIVEL_S DECIMAL(5,2) =0
DECLARE @PIN_NIVEL_I DECIMAL(5,2) =0
DECLARE @PIN_NIVEL_H DECIMAL(5,2) =0


SELECT @PIN_TECNICAPC_REP_T = (SELECT SUM(NO_VALOR) FROM SIGEIN.IDP.K_RESULTADO kr
									INNER JOIN SIGEIN.IDP.C_VARIABLE cv ON cv.ID_VARIABLE = kr.ID_VARIABLE
									where (
									cv.CL_VARIABLE ='TECNICAPC_RES_C' OR
									cv.CL_VARIABLE ='TECNICAPC_RES_S' OR 
									cv.CL_VARIABLE ='TECNICAPC_RES_I' OR 
									cv.CL_VARIABLE ='TECNICAPC_RES_H'  ) AND KR.ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO)

SELECT @PIN_TECNICAPC_REP_C = (SELECT NO_VALOR FROM SIGEIN.IDP.K_RESULTADO kr
									INNER JOIN SIGEIN.IDP.C_VARIABLE cv ON cv.ID_VARIABLE = kr.ID_VARIABLE
									where (
									cv.CL_VARIABLE ='TECNICAPC_RES_C' ) AND KR.ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO)

SELECT @PIN_TECNICAPC_REP_S = (SELECT NO_VALOR FROM SIGEIN.IDP.K_RESULTADO kr
									INNER JOIN SIGEIN.IDP.C_VARIABLE cv ON cv.ID_VARIABLE = kr.ID_VARIABLE
									where (
									cv.CL_VARIABLE ='TECNICAPC_RES_S' ) AND KR.ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO)
									
SELECT @PIN_TECNICAPC_REP_I = (SELECT NO_VALOR FROM SIGEIN.IDP.K_RESULTADO kr
									INNER JOIN SIGEIN.IDP.C_VARIABLE cv ON cv.ID_VARIABLE = kr.ID_VARIABLE
									where (
									cv.CL_VARIABLE ='TECNICAPC_RES_I' ) AND KR.ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO)
									
SELECT @PIN_TECNICAPC_REP_H = (SELECT NO_VALOR FROM SIGEIN.IDP.K_RESULTADO kr
									INNER JOIN SIGEIN.IDP.C_VARIABLE cv ON cv.ID_VARIABLE = kr.ID_VARIABLE
									where (
									cv.CL_VARIABLE ='TECNICAPC_RES_H' ) AND KR.ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO)																		

SELECT @PIN_TECNICAPC_REP_P_T= ((@PIN_TECNICAPC_REP_T/84)*100)

SET @PIN_NIVEL_C = CASE 
												WHEN @PIN_TECNICAPC_REP_C BETWEEN 19 AND 20 THEN 1
												WHEN @PIN_TECNICAPC_REP_C BETWEEN 17 AND 18 THEN 2
												WHEN @PIN_TECNICAPC_REP_C BETWEEN 16 AND 16 THEN 3
												WHEN @PIN_TECNICAPC_REP_C BETWEEN 13 AND 15 THEN 4
												WHEN @PIN_TECNICAPC_REP_C BETWEEN 12 AND 12 THEN 5
												ELSE 0 END

SET @PIN_NIVEL_S = CASE 
												WHEN @PIN_TECNICAPC_REP_S BETWEEN 23 AND 24 THEN 1
												WHEN @PIN_TECNICAPC_REP_S BETWEEN 20 AND 22 THEN 2
												WHEN @PIN_TECNICAPC_REP_S BETWEEN 19 AND 19 THEN 3
												WHEN @PIN_TECNICAPC_REP_S BETWEEN 15 AND 18 THEN 4
												WHEN @PIN_TECNICAPC_REP_S BETWEEN 14 AND 14 THEN 5
												ELSE 0 END

SET @PIN_NIVEL_I = CASE 
												WHEN @PIN_TECNICAPC_REP_I BETWEEN 15 AND 16 THEN 1
												WHEN @PIN_TECNICAPC_REP_I BETWEEN 13 AND 14 THEN 2
												WHEN @PIN_TECNICAPC_REP_I BETWEEN 11 AND 12 THEN 3
												WHEN @PIN_TECNICAPC_REP_I BETWEEN 10 AND 10 THEN 4
												WHEN @PIN_TECNICAPC_REP_I BETWEEN 9 AND 9 THEN 5
												ELSE 0 END


SET @PIN_NIVEL_H = CASE 
												WHEN @PIN_TECNICAPC_REP_H BETWEEN 23 AND 24 THEN 1
												WHEN @PIN_TECNICAPC_REP_H BETWEEN 20 AND 22 THEN 2
												WHEN @PIN_TECNICAPC_REP_H BETWEEN 19 AND 19 THEN 3
												WHEN @PIN_TECNICAPC_REP_H BETWEEN 15 AND 18 THEN 4
												WHEN @PIN_TECNICAPC_REP_H BETWEEN 14 AND 14 THEN 5
												ELSE 0 END


	DELETE SIGEIN.IDP.K_RESULTADO WHERE ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO AND CL_TIPO_RESULTADO = 3

	INSERT INTO SIGEIN.[IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 3 AS CL_TIPO_RESULTADO,1221 AS ID_VARIABLE, @PIN_TECNICAPC_REP_C , @PIN_ID_CUESTIONARIO , GETDATE() ,@PIN_CL_USUARIO_APP_CREA,@PIN_NB_PROGRAMA_CREA
	INSERT INTO SIGEIN.[IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 3 AS CL_TIPO_RESULTADO,1222 AS ID_VARIABLE, @PIN_TECNICAPC_REP_S , @PIN_ID_CUESTIONARIO , GETDATE() ,@PIN_CL_USUARIO_APP_CREA,@PIN_NB_PROGRAMA_CREA
	INSERT INTO SIGEIN.[IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 3 AS CL_TIPO_RESULTADO,1223 AS ID_VARIABLE, @PIN_TECNICAPC_REP_I , @PIN_ID_CUESTIONARIO , GETDATE() ,@PIN_CL_USUARIO_APP_CREA,@PIN_NB_PROGRAMA_CREA
	INSERT INTO SIGEIN.[IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 3 AS CL_TIPO_RESULTADO,1224 AS ID_VARIABLE, @PIN_TECNICAPC_REP_H , @PIN_ID_CUESTIONARIO , GETDATE() ,@PIN_CL_USUARIO_APP_CREA,@PIN_NB_PROGRAMA_CREA
	INSERT INTO SIGEIN.[IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 3 AS CL_TIPO_RESULTADO,1225 AS ID_VARIABLE, @PIN_TECNICAPC_REP_T , @PIN_ID_CUESTIONARIO , GETDATE() ,@PIN_CL_USUARIO_APP_CREA,@PIN_NB_PROGRAMA_CREA
	INSERT INTO SIGEIN.[IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 3 AS CL_TIPO_RESULTADO,1226 AS ID_VARIABLE, ((@PIN_TECNICAPC_REP_C/20)*100) , @PIN_ID_CUESTIONARIO , GETDATE() ,@PIN_CL_USUARIO_APP_CREA,@PIN_NB_PROGRAMA_CREA
	INSERT INTO SIGEIN.[IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 3 AS CL_TIPO_RESULTADO,1227 AS ID_VARIABLE, ((@PIN_TECNICAPC_REP_S/16)*100) , @PIN_ID_CUESTIONARIO , GETDATE() ,@PIN_CL_USUARIO_APP_CREA,@PIN_NB_PROGRAMA_CREA
	INSERT INTO SIGEIN.[IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 3 AS CL_TIPO_RESULTADO,1228 AS ID_VARIABLE, ((@PIN_TECNICAPC_REP_I/24)*100) , @PIN_ID_CUESTIONARIO , GETDATE() ,@PIN_CL_USUARIO_APP_CREA,@PIN_NB_PROGRAMA_CREA
	INSERT INTO SIGEIN.[IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 3 AS CL_TIPO_RESULTADO,1229 AS ID_VARIABLE, ((@PIN_TECNICAPC_REP_H/24)*100) , @PIN_ID_CUESTIONARIO , GETDATE() ,@PIN_CL_USUARIO_APP_CREA,@PIN_NB_PROGRAMA_CREA
	INSERT INTO SIGEIN.[IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 3 AS CL_TIPO_RESULTADO,1230 AS ID_VARIABLE, @PIN_TECNICAPC_REP_P_T , @PIN_ID_CUESTIONARIO , GETDATE() ,@PIN_CL_USUARIO_APP_CREA,@PIN_NB_PROGRAMA_CREA
	INSERT INTO SIGEIN.[IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 3 AS CL_TIPO_RESULTADO,1231 AS ID_VARIABLE, @PIN_NIVEL_C , @PIN_ID_CUESTIONARIO , GETDATE() ,@PIN_CL_USUARIO_APP_CREA,@PIN_NB_PROGRAMA_CREA
	INSERT INTO SIGEIN.[IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 3 AS CL_TIPO_RESULTADO,1232 AS ID_VARIABLE, @PIN_NIVEL_S , @PIN_ID_CUESTIONARIO , GETDATE() ,@PIN_CL_USUARIO_APP_CREA,@PIN_NB_PROGRAMA_CREA
	INSERT INTO SIGEIN.[IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 3 AS CL_TIPO_RESULTADO,1233 AS ID_VARIABLE, @PIN_NIVEL_I , @PIN_ID_CUESTIONARIO , GETDATE() ,@PIN_CL_USUARIO_APP_CREA,@PIN_NB_PROGRAMA_CREA   
	INSERT INTO SIGEIN.[IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 3 AS CL_TIPO_RESULTADO,1234 AS ID_VARIABLE, @PIN_NIVEL_H , @PIN_ID_CUESTIONARIO , GETDATE() ,@PIN_CL_USUARIO_APP_CREA,@PIN_NB_PROGRAMA_CREA
	

END
--SE DEVUELVE LA VARIABLE DE RETORNO INDICANDO QUE TODO SE REALIZO CORRECTAMENTE
		SET @XML_RESULTADO = DBO.F_ERROR_CREAR_ENCABEZADO( @@ROWCOUNT, 1, 'SUCCESSFUL')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'Proceso exitoso', 'ES')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'Successful Process', 'EN')
		--SI SE GENERO UNA TRANSACCION EN ESTE BLOQUE LA TERMINARA
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			COMMIT
	END TRY
	BEGIN CATCH
		--SI OCURRIO UN ERROR Y SE INICIO UNA TRANSACCION ENE ESTE BLOQUE SE CANCELARA LA TRANSACCION
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			ROLLBACK
		--SE INDICA EN LA VARIABLE DE RETORNO QUE OCURRIO UN ERROR
		--SET @POUT_CLAVE_RETORNO = 0
		--SE INSERTA EL ERROR EN LA TABLA
		DECLARE @ERROR_CLAVE INT  = ERROR_NUMBER()
		DECLARE @ERROR_MENSAJE NVARCHAR(250)  = ERROR_MESSAGE()
		
		SET @XML_RESULTADO = DBO.F_ERROR_CREAR_ENCABEZADO( @@ROWCOUNT, @ERROR_CLAVE, 'ERROR')
		SET @XML_RESULTADO = DBO.F_ERROR_MENSAJES(@ERROR_CLAVE,@ERROR_MENSAJE)
		SET @XML_RESULTADO = DBO.F_ERROR_MENSAJES(@ERROR_CLAVE,@ERROR_MENSAJE)			
	END CATCH
END
