-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Juan De Dios Pérez Pedroza
-- CREATE date: 13/11/2015
-- Description: Obtiene los datos de las solicitudes
-- =============================================
CREATE PROCEDURE [IDP].[SPE_OBTIENE_SOLICITUDES] 
	
AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT  
	      KS.[ID_SOLICITUD]
		, KS.[ID_CANDIDATO]
		, KS.[ID_EMPLEADO]
		--, KS.[ID_DESCRIPTIVO]
		, KS.[ID_REQUISICION]
		, KS.[CL_SOLICITUD] AS K_SOLICITUD_CL_SOLICITUD
		, KS.[CL_ACCESO_EVALUACION] AS K_SOLICITUD_CL_ACCESO_EVALUACION
		--, KS.[ID_PLANTILLA_SOLICITUD] 
		, CC.[DS_COMPETENCIAS_ADICIONALES] AS K_SOLICITUD_DS_COMPETENCIAS_ADICIONALES
		, KS.FE_SOLICITUD AS K_SOLICITUD_FE_SOLICITUD
		, KS.CL_SOLICITUD_ESTATUS AS K_SOLICITUD_CL_SOLICITUD_ESTATUS
		

		-----------C_CANDIDATO----------------

		,CC.[NB_CANDIDATO] AS C_CANDIDATO_NB_CANDIDATO
		,CC.[NB_APELLIDO_PATERNO] AS C_CANDIDATO_NB_APELLIDO_PATERNO
		,CC.[NB_APELLIDO_MATERNO] AS C_CANDIDATO_NB_APELLIDO_MATERNO
		, CONCAT ( CC.[NB_CANDIDATO], ' ',CC.[NB_APELLIDO_PATERNO],' ' , CC.[NB_APELLIDO_MATERNO] )AS C_CANDIDATO_NB_EMPLEADO_COMPLETO
		,CC.[CL_GENERO] AS C_CANDIDATO_CL_GENERO
		,CC.[CL_RFC] AS C_CANDIDATO_CL_RFC
		,CC.[CL_CURP] AS C_CANDIDATO_CL_CURP
		,CC.[CL_ESTADO_CIVIL] AS C_CANDIDATO_CL_ESTADO_CIVIL
		,CC.[NB_CONYUGUE] AS C_CANDIDATO_NB_CONYUGUE
		,CC.[CL_NSS] AS C_CANDIDATO_CL_NSS
		,CC.[CL_TIPO_SANGUINEO] AS C_CANDIDATO_CL_TIPO_SANGUINEO
		,CC.[NB_PAIS] AS C_CANDIDATO_NB_PAIS
		,CC.[NB_ESTADO] AS C_CANDIDATO_NB_ESTADO
		,CC.[NB_MUNICIPIO] AS C_CANDIDATO_NB_MUNICIPIO
		,CC.[NB_COLONIA] AS C_CANDIDATO_NB_COLONIA
		,CC.[NB_CALLE] AS C_CANDIDATO_NB_CALLE
		,CC.[NO_INTERIOR] AS C_CANDIDATO_NO_INTERIOR
		,CC.[NO_EXTERIOR] AS C_CANDIDATO_NO_EXTERIOR
		,CC.[CL_CODIGO_POSTAL] AS C_CANDIDATO_CL_CODIGO_POSTAL
		,CC.[CL_CORREO_ELECTRONICO] AS C_CANDIDATO_CL_CORREO_ELECTRONICO
		,CC.[FE_NACIMIENTO] AS C_CANDIDATO_FE_NACIMIENTO
		,CC.[DS_LUGAR_NACIMIENTO] AS C_CANDIDATO_DS_LUGAR_NACIMIENTO
		,CC.[MN_SUELDO] AS C_CANDIDATO_MN_SUELDO
		,CC.[CL_NACIONALIDAD] AS C_CANDIDATO_CL_NACIONALIDAD
		,CC.[DS_NACIONALIDAD] AS C_CANDIDATO_DS_NACIONALIDAD
		,CC.[NB_LICENCIA] AS C_CANDIDATO_NB_LICENCIA
		,CC.[DS_VEHICULO] AS C_CANDIDATO_DS_VEHICULO
		,CC.[CL_CARTILLA_MILITAR] AS C_CANDIDATO_CL_CARTILLA_MILITAR
		,CC.[CL_CEDULA_PROFESIONAL] AS C_CANDIDATO_CL_CEDULA_PROFESIONAL
		,CC.[XML_TELEFONOS] AS C_CANDIDATO_XML_TELEFONOS
		,CC.[XML_INGRESOS] AS C_CANDIDATO_XML_INGRESOS
		,CC.[XML_EGRESOS] AS C_CANDIDATO_XML_EGRESOS
		,CC.[XML_PATRIMONIO] AS C_CANDIDATO_XML_PATRIMONIO
		,CC.[DS_DISPONIBILIDAD] AS C_CANDIDATO_DS_DISPONIBILIDAD
		,CC.[CL_DISPONIBILIDAD_VIAJE] AS C_CANDIDATO_CL_DISPONIBILIDAD_VIAJE
		,CC.[XML_PERFIL_RED_SOCIAL] AS C_CANDIDATO_XML_PERFIL_RED_SOCIAL
		,CC.[DS_COMENTARIO] AS C_CANDIDATO_DS_COMENTARIO
		,CC.[FG_ACTIVO] AS C_CANDIDATO_FG_ACTIVO
		,(CASE WHEN CC.[FG_ACTIVO]  =1 THEN 'Sí'WHEN CC.[FG_ACTIVO]=0 THEN 'No' END) AS C_CANDIDATO_NB_ACTIVO
		
		------------------------M_EMPLEADO-------------------------------------
		-----------------------------------------------------------------------
		, ME.[CL_EMPLEADO]  AS M_EMPLEADO_CL_EMPLEADO
		,CONCAT ( ME.[NB_EMPLEADO], ' ',ME.[NB_APELLIDO_PATERNO],' ' , ME.[NB_APELLIDO_MATERNO] ) AS M_EMPLEADO_NB_EMPLEADO_COMPLETO
		,ME.[NB_EMPLEADO]  AS M_EMPLEADO_NB_EMPLEADO
		, ME.[NB_APELLIDO_PATERNO]  AS M_EMPLEADO_NB_APELLIDO_PATERNO
		, ME.[NB_APELLIDO_MATERNO]  AS M_EMPLEADO_NB_APELLIDO_MATERNO
		, ME.[CL_ESTADO_EMPLEADO]  AS M_EMPLEADO_CL_ESTADO_EMPLEADO
		, ME.[CL_GENERO]  AS M_EMPLEADO_CL_GENERO
		, ME.[CL_ESTADO_CIVIL]  AS M_EMPLEADO_CL_ESTADO_CIVIL
		, ME.[NB_CONYUGUE]  AS M_EMPLEADO_NB_CONYUGUE
		, ME.[CL_RFC]  AS M_EMPLEADO_CL_RFC
		, ME.[CL_CURP]  AS M_EMPLEADO_CL_CURP
		, ME.[CL_NSS]  AS M_EMPLEADO_CL_NSS
		, ME.[CL_TIPO_SANGUINEO]  AS M_EMPLEADO_CL_TIPO_SANGUINEO
		, ME.[CL_NACIONALIDAD]  AS M_EMPLEADO_CL_NACIONALIDAD
		, ME.[NB_PAIS]  AS M_EMPLEADO_NB_PAIS
		, ME.[NB_ESTADO]  AS M_EMPLEADO_NB_ESTADO
		, ME.[NB_MUNICIPIO]  AS M_EMPLEADO_NB_MUNICIPIO
		, ME.[NB_COLONIA]  AS M_EMPLEADO_NB_COLONIA
		, ME.[NB_CALLE]  AS M_EMPLEADO_NB_CALLE
		, ME.[NO_INTERIOR]  AS M_EMPLEADO_NO_INTERIOR
		, ME.[NO_EXTERIOR]  AS M_EMPLEADO_NO_EXTERIOR
		, ME.[CL_CODIGO_POSTAL]  AS M_EMPLEADO_CL_CODIGO_POSTAL
		, ME.[XML_TELEFONOS]  AS M_EMPLEADO_XML_TELEFONOS
		, ME.[CL_CORREO_ELECTRONICO]  AS M_EMPLEADO_CL_CORREO_ELECTRONICO
		, ME.[FG_ACTIVO]  AS M_EMPLEADO_FG_ACTIVO
		,(CASE WHEN ME.[FG_ACTIVO]  =1 THEN 'Sí' WHEN ME.[FG_ACTIVO]=0 THEN 'No' END) AS M_EMPLEADO_NB_ACTIVO
		, ME.[FE_NACIMIENTO] AS M_EMPLEADO_FE_NACIMIENTO
		, ME.[DS_LUGAR_NACIMIENTO]  AS M_EMPLEADO_DS_LUGAR_NACIMIENTO
		, ME.[FE_ALTA] AS M_EMPLEADO_FE_ALTA
		, ME.[FE_BAJA]  AS M_EMPLEADO_FE_BAJA
		--, ME.[ID_PUESTO]  AS M_EMPLEADO_ID_PUESTO
		, ME.[MN_SUELDO]  AS M_EMPLEADO_MN_SUELDO
		, ME.[MN_SUELDO_VARIABLE]  AS M_EMPLEADO_MN_SUELDO_VARIABLE
		, ME.[DS_SUELDO_COMPOSICION]  AS M_EMPLEADO_DS_SUELDO_COMPOSICION
		--, ME.[ID_CANDIDATO]  AS M_EMPLEADO_ID_CANDIDATO
		, ME.[XML_CAMPOS_ADICIONALES]  AS M_EMPLEADO_XML_CAMPOS_ADICIONALES
		--, ME.[ID_EMPRESA]  AS M_EMPLEADO_ID_EMPRESA

		--------------------M_PUESTO-----------------------------------
		---------------------------------------------------------------

		, MP.[FG_ACTIVO]  AS M_PUESTO_FG_ACTIVO
		,(CASE WHEN MP.[FG_ACTIVO] =1 THEN 'Sí' WHEN MP.[FG_ACTIVO] =0 THEN 'No' END) AS NB_ACTIVO
		, MP.[FE_INACTIVO] AS M_PUESTO_FE_INACTIVO
		, MP.[CL_PUESTO] AS M_PUESTO_CL_PUESTO
		, MP.[NB_PUESTO] AS M_PUESTO_NB_PUESTO
		, MP.[ID_DEPARTAMENTO] --AS M_PUESTO_ID_DEPARTAMENTO
		, MP.[XML_CAMPOS_ADICIONALES] AS M_PUESTO_XML_CAMPOS_ADICIONALES
		, MP.[ID_BITACORA] --AS M_PUESTO_ID_BITACORA
		, MP.[NO_EDAD_MINIMA] AS M_PUESTO_NO_EDAD_MINIMA
		, MP.[NO_EDAD_MAXIMA] AS M_PUESTO_NO_EDAD_MAXIMA
		, MP.[CL_GENERO] AS M_PUESTO_CL_GENERO
		, MP.[CL_ESTADO_CIVIL] AS M_PUESTO_CL_ESTADO_CIVIL
		, MP.[XML_REQUERIMIENTOS] AS M_PUESTO_XML_REQUERIMIENTOS
		, MP.[XML_OBSERVACIONES] AS M_PUESTO_XML_OBSERVACIONES
		, MP.[XML_RESPONSABILIDAD] AS M_PUESTO_XML_RESPONSABILIDAD
		, MP.[XML_AUTORIDAD] AS M_PUESTO_XML_AUTORIDAD
		, MP.[XML_CURSOS_ADICIONALES] AS M_PUESTO_XML_CURSOS_ADICIONALES
		, MP.[XML_MENTOR] AS M_PUESTO_XML_MENTOR
		, MP.[CL_TIPO_PUESTO] AS M_PUESTO_CL_TIPO_PUESTO
		, MP.[ID_CENTRO_ADMINISTRATIVO] --AS M_PUESTO_ID_CENTRO_ADMINISTRATIVO
		, MP.[ID_CENTRO_OPERATIVO] --AS M_PUESTO_ID_CENTRO_OPERATIVO
		, MP.[ID_PAQUETE_PRESTACIONES] --AS M_PUESTO_ID_PAQUETE_PRESTACIONES 

		-------------------------------------------
		---------------K_REQUISICION
		, KR.NO_REQUISICION AS M_DEPARTAMENTO_NO_REQUISICION
		, KR.FE_SOLICITUD AS M_DEPARTAMENTO_FE_SOLICITUD
		--, KR.ID_PUESTO AS M_DEPARTAMENTO_ID_PUESTO
		, KR.CL_ESTADO AS M_DEPARTAMENTO_CL_ESTADO
		, KR.CL_CAUSA AS M_DEPARTAMENTO_CL_CAUSA 
		, KR.DS_CAUSA AS M_DEPARTAMENTO_DS_CAUSA
		, KR.ID_NOTIFICACION --AS M_DEPARTAMENTO_ID_NOTIFICACION
		, KR.ID_SOLICITANTE --AS M_DEPARTAMENTO_ID_SOLICITANTE
		, KR.ID_AUTORIZA --AS M_DEPARTAMENTO_ID_AUTORIZA
		, KR.ID_VISTO_BUENO --AS M_DEPARTAMENTO_ID_VISTO_BUENO
		, KR.ID_EMPRESA -- AS M_DEPARTAMENTO_ID_EMPRESA
		
		----------------------------------------------
		--------------------C_EMPRESA------------------------
		, CE.[CL_EMPRESA] AS C_EMPRESA_CL_EMPRESA
		, CE.[NB_EMPRESA] AS C_EMPRESA_NB_EMPRESA
		, CE.[NB_RAZON_SOCIAL] AS C_EMPRESA_NB_RAZON_SOCIAL

		-------------------M_DEPARTAMENTO-------------------------------------
		---------------------------------------------------------

		,MD.[FG_ACTIVO] AS M_DEPARTAMENTO_FG_ACTIVO
		,(CASE WHEN MD.FG_ACTIVO=1 THEN 'Sí' WHEN MD.FG_ACTIVO=0 THEN 'No' END)AS M_DEPARTAMENTO_NB_ACTIVO
		,MD.[FE_INACTIVO]  AS M_DEPARTAMENTO_FE_INACTIVO
		,MD.[CL_DEPARTAMENTO]  AS M_DEPARTAMENTO_CL_DEPARTAMENTO
		,MD.[NB_DEPARTAMENTO] AS M_DEPARTAMENTO_NB_DEPARTAMENTO
		,MD.[XML_CAMPOS_ADICIONALES] AS M_DEPARTAMENTO_XML_CAMPOS_ADICIONALES

		--------------------ULTIMO REGISTRO DE K_BATERIA_PRUEBA----------------
		,KBP.ID_BATERIA

	    FROM ADM.K_SOLICITUD KS
		LEFT OUTER JOIN ADM.C_CANDIDATO CC ON CC.ID_CANDIDATO = KS.ID_CANDIDATO
		LEFT OUTER JOIN ADM.M_EMPLEADO ME ON ME.ID_EMPLEADO = KS.ID_EMPLEADO
		LEFT OUTER JOIN ADM.K_REQUISICION KR ON KR.ID_REQUISICION = KS.ID_REQUISICION
		LEFT OUTER JOIN ADM.C_EMPRESA CE ON CE.ID_EMPRESA = KR.ID_EMPRESA
		LEFT OUTER JOIN ADM.M_PUESTO MP ON MP.ID_PUESTO = KS.ID_DESCRIPTIVO
		LEFT OUTER JOIN ADM.M_DEPARTAMENTO MD ON MD.ID_DEPARTAMENTO = MP.ID_DEPARTAMENTO
		LEFT OUTER JOIN (
							SELECT ROW_NUMBER() OVER(PARTITION BY ID_CANDIDATO ORDER BY ID_BATERIA DESC) AS NO_FILA, ID_CANDIDATO, ID_BATERIA, FL_BATERIA, CL_TOKEN
							FROM IDP.K_BATERIA_PRUEBA 
						) AS KBP ON KS.ID_CANDIDATO = KBP.ID_CANDIDATO AND NO_FILA = 1

		-- EXECUTE [IDP].[SPE_OBTIENE_SOLICITUDES] 