-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Juan Castillo
-- CREATE date: 21/01/2015
-- Description: Obtiene los datos de las baterias de pruebas
-- =============================================
CREATE PROCEDURE [IDP].[SPE_OBTIENE_BATERIA_PRUEBAS] 
	@PIN_ID_BATERIA AS int = NULL
	, @PIN_FL_BATERIA AS int = NULL
	, @PIN_ID_CANDIDATO AS nvarchar(100) = NULL		
	, @PIN_CL_CORREO_ELECTRONICO AS nvarchar(100) = NULL		
AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	with pruebas_terminadas (ID_BATERIA,CL_ESTADO,CANTIDAD)
as (
	SELECT ID_BATERIA,CL_ESTADO,COUNT(ID_BATERIA) CANTIDAD
	FROM IDP.K_PRUEBA KPR WHERE CL_ESTADO='TERMINADA'
	GROUP BY CL_ESTADO,ID_BATERIA 
),
pruebas_creadas (ID_BATERIA,CL_ESTADO,CANTIDAD)
as (
	SELECT ID_BATERIA,CL_ESTADO,COUNT(ID_BATERIA) CANTIDAD
	FROM IDP.K_PRUEBA KPR WHERE CL_ESTADO='CREADA'
	GROUP BY CL_ESTADO,ID_BATERIA 
)
select KBP.ID_BATERIA
		,FL_BATERIA 
		,NB_CANDIDATO +' '+NB_APELLIDO_PATERNO +' '+NB_APELLIDO_MATERNO NB_CANDIDATO
		,CL_CORREO_ELECTRONICO
		,CL_TOKEN	/*,PCR.CANTIDAD	,PTE.CANTIDAD*/
		,CASE WHEN ISNULL(PCR.CANTIDAD,0)>0 AND ISNULL(PTE.CANTIDAD,0)> 0 THEN 'INICIADA'
			  WHEN ISNULL(PCR.CANTIDAD,0)=0 AND ISNULL(PTE.CANTIDAD,0)> 0 THEN 'TERMINADA' 
			  ELSE 'CREADA'
		END AS ESTATUS,
		(
			SELECT MAX(FE_TERMINO)  
			FROM IDP.K_PRUEBA KPR 
			WHERE ID_BATERIA =KBP.ID_BATERIA
		 ) FE_TERMINO,
		 CASE WHEN FG_ENVIO_CORREO = '0' THEN 'No' ELSE 'Sí' END AS FG_ENVIO_CORREO
	from IDP.K_BATERIA_PRUEBA KBP 
	JOIN ADM.C_CANDIDATO CCA ON KBP.ID_CANDIDATO = CCA.ID_CANDIDATO	
	LEFT OUTER JOIN pruebas_terminadas PTE ON PTE.ID_BATERIA = KBP.ID_BATERIA AND PTE.CL_ESTADO='TERMINADA'
	LEFT OUTER JOIN pruebas_creadas PCR ON PCR.ID_BATERIA = KBP.ID_BATERIA AND PCR.CL_ESTADO='CREADA'
	WHERE (@PIN_ID_CANDIDATO IS NULL OR (@PIN_ID_CANDIDATO IS NOT NULL AND KBP.[ID_CANDIDATO] = @PIN_ID_CANDIDATO))
	AND (@PIN_ID_BATERIA IS NULL OR (@PIN_ID_BATERIA IS NOT NULL AND KBP.ID_BATERIA = @PIN_ID_BATERIA))
	AND (@PIN_FL_BATERIA IS NULL OR (@PIN_FL_BATERIA IS NOT NULL AND KBP.FL_BATERIA = @PIN_FL_BATERIA))
	AND (@PIN_CL_CORREO_ELECTRONICO IS NULL OR (@PIN_CL_CORREO_ELECTRONICO IS NOT NULL AND CL_CORREO_ELECTRONICO = @PIN_CL_CORREO_ELECTRONICO))
	ORDER BY FL_BATERIA	desc
			
