-- =============================================
-- Proyecto: SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Daniela Sanchez
-- CRETAE date: 20/01/2016
-- Description: Inserta variables de respuesta de la prueba Aptitud metal 1
-- =============================================
CREATE PROCEDURE [IDP].[SPE_INSERTA_REPORTE_APTITUD2]
	 @XML_RESULTADO XML = '' OUT 
	,@PIN_ID_CUESTIONARIO AS INT = NULL
	,@PIN_CL_USUARIO_APP AS nvarchar(50)
    ,@PIN_NB_PROGRAMA AS nvarchar(50)
	AS
BEGIN  
	--SE DECLARA E INICIALIZA LA VARIABLE QUE NOS INDICARA SI GENERAMOS LA TRANSACCION EN ESTE SP
	DECLARE @V_EXIST_TRAN BIT = 0,
			@V_FE_SISTEMA AS DATETIME = GETDATE()

    	BEGIN TRY
		--SE VERIFICA SI EXISTE UNA TRANSACCION EN EJECUCION
		IF (@@TRANCOUNT = 0) 
		BEGIN
			--EN CASO DE QUE NO SE INICIALIZA LA TRANSACCION
			BEGIN TRANSACTION
			--SE EDITA LA VARIABLE QUE INDICA QUE SE INICIO LA TRANSACCION EN ESTE BLOQUE PARA CANCELARLA SI ES NECESARIO
			SET @V_EXIST_TRAN = 1
		END	
		--SE VERIFICA SI SE INSERTA EL REGISTRO O SE ACTUALIZARA SEGUN LA VARIABLE DE TIPO DE TRANSACCION  QUE RECIBE EL SP
			

		DELETE FROM IDP.K_RESULTADO WHERE ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO AND CL_TIPO_RESULTADO = 3

		DECLARE @V_NO_CI AS INT,
				@V_NO_TOTAL_ACIERTOS AS INT,
				@V_NO_MAGNITUD_PROBLEMAS AS INT,
				@V_NO_COMPARATIVO_INTELIGENCIA AS INT,
				@V_NO_PREGUNTA_SIN_RESPUESTA AS INT = 0,
				@V_NO_RESOLVER_PROBLEMAS AS INT,
				@V_NO_TIEMPO_TERMINO AS INT,
				@V_NO_VELOCIDAD AS INT,
				@V_ID_DESCRIPCION_CI AS INT

		SELECT @V_NO_TIEMPO_TERMINO = DATEDIFF(MINUTE,FE_INICIO,FE_TERMINO) FROM IDP.K_PRUEBA WHERE ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
		SELECT @V_NO_TOTAL_ACIERTOS = SUM(NO_VALOR) FROM IDP.K_RESULTADO WHERE ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO AND CL_TIPO_RESULTADO = 2 AND NO_VALOR = 1 GROUP BY ID_CUESTIONARIO
		SELECT @V_NO_PREGUNTA_SIN_RESPUESTA = SUM(NO_VALOR) * -1 FROM IDP.K_RESULTADO WHERE ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO AND CL_TIPO_RESULTADO = 2 AND NO_VALOR = -1 GROUP BY ID_CUESTIONARIO


		SET @V_NO_CI = IDP.F_OBTIENE_CI(@PIN_ID_CUESTIONARIO, 2)

		SET @V_ID_DESCRIPCION_CI = CASE
										WHEN @V_NO_CI BETWEEN 0 AND 49 THEN 1
										WHEN @V_NO_CI BETWEEN 50 AND 69 THEN 2
										WHEN @V_NO_CI BETWEEN 70 AND 79 THEN 3
										WHEN @V_NO_CI BETWEEN 80 AND 89 THEN 4
										WHEN @V_NO_CI BETWEEN 90 AND 110 THEN 5
										WHEN @V_NO_CI BETWEEN 111 AND 120 THEN 6
										WHEN @V_NO_CI >= 121 THEN 7
										ELSE 0 END
		
		
		INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) 
		SELECT 3 AS CL_TIPO_RESULTADO, ID_VARIABLE, @V_ID_DESCRIPCION_CI, @PIN_ID_CUESTIONARIO, @V_FE_SISTEMA, @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.C_VARIABLE CV WHERE CL_VARIABLE = 'APTITUD2_REP_DESC_CI'


		-- CASE CORRESPONDIENTE A LA LA PREGUNTA "MAGNITUD DE PROBLEMAS QUE PUEDE RESOLVER DE FORMA SATISFACTORIA"
		SET @V_NO_MAGNITUD_PROBLEMAS = CASE
											WHEN @V_NO_CI <= 79 THEN 1 -- Simples
											WHEN @V_NO_CI BETWEEN 80 AND 89 THEN 2 -- Comunes
											WHEN @V_NO_CI BETWEEN 90 AND 109 THEN 3 -- términos medios
											WHEN @V_NO_CI BETWEEN 110 AND 119 THEN 4 -- Dificiles
											WHEN @V_NO_CI >= 120 THEN 5 -- De lo mas complejo
											ELSE 0 END

		-- CASE CORRESPONDIENTE A COMPARATIVAMENTE ES MÁS INTELIGENTE QUE ESTE PORCENTAJE DE LAS PERSONAS
		SET @V_NO_COMPARATIVO_INTELIGENCIA = CASE 
													WHEN @V_NO_CI <= 69 THEN 1 -- PRIMER 10
													WHEN @V_NO_CI BETWEEN 70 AND 79 THEN 2 -- SEGUNDO 10
													WHEN @V_NO_CI BETWEEN 80 AND 84 THEN 3 -- 20
													WHEN @V_NO_CI BETWEEN 85 AND 90 THEN 4 -- 30
													WHEN @V_NO_CI BETWEEN 90 AND 99 THEN 5 -- 40
													WHEN @V_NO_CI BETWEEN 100 AND 109 THEN 6 -- 50
													WHEN @V_NO_CI BETWEEN 110 AND 114 THEN 7 -- 60
													WHEN @V_NO_CI BETWEEN 115 AND 119 THEN 8 -- 70
													WHEN @V_NO_CI BETWEEN 120 AND 124 THEN 9 -- 80
													WHEN @V_NO_CI >= 125 THEN 10 -- 90
													ELSE 0 END

		-- CASE CORRESPONDIENTE A SU FORMA DE RESOLVER LOS PROBLEMAS
		SET @V_NO_RESOLVER_PROBLEMAS = CASE 
											WHEN @V_NO_PREGUNTA_SIN_RESPUESTA >= 9 THEN 1 -- SIN ORDEN DISPERSO
											WHEN @V_NO_PREGUNTA_SIN_RESPUESTA BETWEEN 6 AND 8 THEN 2 -- TIENDE A SER DISPERSO
											WHEN @V_NO_PREGUNTA_SIN_RESPUESTA BETWEEN 3 AND 5 THEN 3 -- NINGÚN EXTREMO
											WHEN @V_NO_PREGUNTA_SIN_RESPUESTA BETWEEN 1 AND 2 THEN 4 -- TIENDE A SER METODICO
											WHEN @V_NO_PREGUNTA_SIN_RESPUESTA = 0 THEN 5 -- METÓDICO ORGANIZADO
											END

		-- CASE CORRESPONDIENTE A SU VELODICDAD EN TAREAS MENTALES
		SET @V_NO_VELOCIDAD = CASE 
									WHEN @V_NO_TIEMPO_TERMINO <= 25 AND @V_NO_TOTAL_ACIERTOS = 75 THEN  5 -- MUY RAPIDO
									WHEN @V_NO_TIEMPO_TERMINO >= 30 AND @V_NO_TOTAL_ACIERTOS = 75 THEN  4 -- RAPIDO
									WHEN @V_NO_TIEMPO_TERMINO >= 30 AND @V_NO_TOTAL_ACIERTOS BETWEEN 60 AND 74 THEN  3 -- NINGÚN EXTREMO
									WHEN @V_NO_TIEMPO_TERMINO >= 30 AND @V_NO_TOTAL_ACIERTOS BETWEEN 40 AND 59 THEN  2 -- LENTO
									WHEN @V_NO_TIEMPO_TERMINO >= 30 AND @V_NO_TOTAL_ACIERTOS <= 39 THEN  1 -- MUY LENTO
									ELSE 0 END

		-- INSERCION DE COEFICIENTE INTELECTUAL
		INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA])
		SELECT 3 AS CL_TIPO_RESULTADO, ID_VARIABLE, @V_NO_CI, @PIN_ID_CUESTIONARIO, @V_FE_SISTEMA, @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.C_VARIABLE CV WHERE CL_VARIABLE = 'APTITUD2_REP_CI'

		-- INSERCION DE TOTAL DE ACIERTOS
		INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA])
		SELECT 3 AS CL_TIPO_RESULTADO, ID_VARIABLE, @V_NO_TOTAL_ACIERTOS, @PIN_ID_CUESTIONARIO, @V_FE_SISTEMA, @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.C_VARIABLE CV WHERE CL_VARIABLE = 'APTITUD2_REP_ACIERTOS'

		-- INSERCION DE LA COMPARACION 1
		INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA])
		SELECT 3 AS CL_TIPO_RESULTADO, ID_VARIABLE, @V_NO_MAGNITUD_PROBLEMAS, @PIN_ID_CUESTIONARIO, @V_FE_SISTEMA, @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.C_VARIABLE CV WHERE CL_VARIABLE = 'APTITUD2_REP_C1'

		-- INSERCION DE LA COMPARACION 2
		INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA])
		SELECT 3 AS CL_TIPO_RESULTADO, ID_VARIABLE, @V_NO_COMPARATIVO_INTELIGENCIA, @PIN_ID_CUESTIONARIO, @V_FE_SISTEMA, @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.C_VARIABLE CV WHERE CL_VARIABLE = 'APTITUD2_REP_C2'

		-- INSERCION DE LA COMPARACION 3
		INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA])
		SELECT 3 AS CL_TIPO_RESULTADO, ID_VARIABLE, @V_NO_RESOLVER_PROBLEMAS, @PIN_ID_CUESTIONARIO, @V_FE_SISTEMA, @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.C_VARIABLE CV WHERE CL_VARIABLE = 'APTITUD2_REP_C3'

		--INSERCION DE LA COMPARACION 4
		INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA])
		SELECT 3 AS CL_TIPO_RESULTADO, ID_VARIABLE, @V_NO_VELOCIDAD, @PIN_ID_CUESTIONARIO, @V_FE_SISTEMA, @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.C_VARIABLE CV WHERE CL_VARIABLE = 'APTITUD2_REP_C4'


		--INSERTAR ESTAS VARIABLES DE TIPO 3
		--SELECT @V_NO_CI, @V_NO_TOTAL_ACIERTOS, @V_NO_MAGNITUD_PROBLEMAS, @V_NO_COMPARATIVO_INTELIGENCIA, @V_NO_RESOLVER_PROBLEMAS, @V_NO_VELOCIDAD


		;WITH T_VARIABLE AS (
			SELECT 'APTITUD2-RES-0001' AS CL_VARIABLE, 4 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0002' AS CL_VARIABLE, 3 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0003' AS CL_VARIABLE, 7 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0004' AS CL_VARIABLE, 7 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0005' AS CL_VARIABLE, 10 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0006' AS CL_VARIABLE, 7 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0007' AS CL_VARIABLE, 4 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0008' AS CL_VARIABLE, 4 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0009' AS CL_VARIABLE, 7 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0010' AS CL_VARIABLE, 4 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0011' AS CL_VARIABLE, 8 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0012' AS CL_VARIABLE, 4 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0013' AS CL_VARIABLE, 3 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0014' AS CL_VARIABLE, 3 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0015' AS CL_VARIABLE, 9 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0016' AS CL_VARIABLE, 2 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0017' AS CL_VARIABLE, 5 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0018' AS CL_VARIABLE, 7 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0019' AS CL_VARIABLE, 6 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0020' AS CL_VARIABLE, 9 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0021' AS CL_VARIABLE, 1 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0022' AS CL_VARIABLE, 7 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0023' AS CL_VARIABLE, 7 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0024' AS CL_VARIABLE, 2 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0025' AS CL_VARIABLE, 7 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0026' AS CL_VARIABLE, 7 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0027' AS CL_VARIABLE, 9 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0028' AS CL_VARIABLE, 6 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0029' AS CL_VARIABLE, 4 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0030' AS CL_VARIABLE, 7 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0031' AS CL_VARIABLE, 10 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0032' AS CL_VARIABLE, 6 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0033' AS CL_VARIABLE, 7 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0034' AS CL_VARIABLE, 7 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0035' AS CL_VARIABLE, 8 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0036' AS CL_VARIABLE, 5 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0037' AS CL_VARIABLE, 4 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0038' AS CL_VARIABLE, 2 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0039' AS CL_VARIABLE, 8 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0040' AS CL_VARIABLE, 2 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0041' AS CL_VARIABLE, 8 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0042' AS CL_VARIABLE, 8 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0043' AS CL_VARIABLE, 8 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0044' AS CL_VARIABLE, 1 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0045' AS CL_VARIABLE, 8 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0046' AS CL_VARIABLE, 2 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0047' AS CL_VARIABLE, 8 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0048' AS CL_VARIABLE, 8 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0049' AS CL_VARIABLE, 5 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0050' AS CL_VARIABLE, 2 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0051' AS CL_VARIABLE, 8 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0052' AS CL_VARIABLE, 4 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0053' AS CL_VARIABLE, 8 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0054' AS CL_VARIABLE, 9 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0055' AS CL_VARIABLE, 2 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0056' AS CL_VARIABLE, 8 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0057' AS CL_VARIABLE, 7 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0058' AS CL_VARIABLE, 10 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0059' AS CL_VARIABLE, 4 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0060' AS CL_VARIABLE, 8 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0061' AS CL_VARIABLE, 10 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0062' AS CL_VARIABLE, 2 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0063' AS CL_VARIABLE, 1 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0064' AS CL_VARIABLE, 10 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0065' AS CL_VARIABLE, 3 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0066' AS CL_VARIABLE, 9 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0067' AS CL_VARIABLE, 8 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0068' AS CL_VARIABLE, 2 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0069' AS CL_VARIABLE, 8 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0070' AS CL_VARIABLE, 8 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0071' AS CL_VARIABLE, 1 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0072' AS CL_VARIABLE, 8 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0073' AS CL_VARIABLE, 10 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0074' AS CL_VARIABLE, 5 AS CL_GRUPO UNION ALL
			SELECT 'APTITUD2-RES-0075' AS CL_VARIABLE, 8 AS CL_GRUPO )
		, T_GRUPO AS (
			SELECT 1 AS CL_GRUPO, CAST(4 AS decimal(13,3)) AS NO_ACIERTOS, 'APTITUD2_REP_CONOCIMIENTO' AS CL_VARIABLE UNION ALL
			SELECT 2 AS CL_GRUPO, CAST(9 AS decimal(13,3)) AS NO_ACIERTOS, 'APTITUD2_REP_COMPRENSION' AS CL_VARIABLE UNION ALL
			SELECT 3 AS CL_GRUPO, CAST(4 AS decimal(13,3)) AS NO_ACIERTOS, 'APTITUD2_REP_SIGNIFICADO' AS CL_VARIABLE UNION ALL
			SELECT 4 AS CL_GRUPO, CAST(9 AS decimal(13,3)) AS NO_ACIERTOS, 'APTITUD2_REP_LOGICA' AS CL_VARIABLE UNION ALL
			SELECT 5 AS CL_GRUPO, CAST(4 AS decimal(13,3)) AS NO_ACIERTOS, 'APTITUD2_REP_ARITMETICA' AS CL_VARIABLE UNION ALL
			SELECT 6 AS CL_GRUPO, CAST(3 AS decimal(13,3)) AS NO_ACIERTOS, 'APTITUD2_REP_JUICIO' AS CL_VARIABLE UNION ALL
			SELECT 7 AS CL_GRUPO, CAST(13 AS decimal(13,3)) AS NO_ACIERTOS, 'APTITUD2_REP_ANALOGIAS' AS CL_VARIABLE UNION ALL
			SELECT 8 AS CL_GRUPO, CAST(18 AS decimal(13,3)) AS NO_ACIERTOS, 'APTITUD2_REP_ORDENAMIENTO' AS CL_VARIABLE UNION ALL
			SELECT 9 AS CL_GRUPO, CAST(5 AS decimal(13,3)) AS NO_ACIERTOS, 'APTITUD2_REP_CLASIFICACION' AS CL_VARIABLE UNION ALL
			SELECT 10 AS CL_GRUPO, CAST(6 AS decimal(13,3)) AS NO_ACIERTOS, 'APTITUD2_REP_SERIACION' AS CL_VARIABLE)
		, T_RESULTADO AS (
			SELECT tg.CL_GRUPO, tg.NO_ACIERTOS, tv.CL_VARIABLE AS CL_VARIABLE_RESULTADO, tg.CL_VARIABLE AS CL_VARIABLE_REPORTE
			FROM T_VARIABLE tv
				INNER JOIN T_GRUPO tg ON tv.CL_GRUPO = tg.CL_GRUPO)


			-- INSERCION DE VARIABLES DE TIPO 3
		INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA])
		SELECT 3 AS CL_TIPO_RESULTADO, V2.ID_VARIABLE, (SUM(KR.NO_VALOR) / TR.NO_ACIERTOS) * 100 AS NO_PORCENTAJE, @PIN_ID_CUESTIONARIO, @V_FE_SISTEMA, @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA
		FROM T_RESULTADO TR
			INNER JOIN IDP.C_VARIABLE V1 ON TR.CL_VARIABLE_RESULTADO = V1.CL_VARIABLE
			INNER JOIN IDP.C_VARIABLE V2 ON TR.CL_VARIABLE_REPORTE = V2.CL_VARIABLE
			INNER JOIN IDP.K_RESULTADO KR  ON V1.ID_VARIABLE = KR.ID_VARIABLE
		WHERE KR.ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO AND KR.NO_VALOR = 1
		GROUP BY TR.CL_GRUPO, V2.ID_VARIABLE, TR.NO_ACIERTOS
		ORDER BY TR.CL_GRUPO


		--SE DEVUELVE LA VARIABLE DE RETORNO INDICANDO QUE TODO SE REALIZO CORRECTAMENTE
		SET @XML_RESULTADO = DBO.F_ERROR_CREAR_ENCABEZADO( @@ROWCOUNT, 1, 'SUCCESSFUL')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'Proceso exitoso', 'ES')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'Successful Process', 'EN')
		--SI SE GENERO UNA TRANSACCION EN ESTE BLOQUE LA TERMINARA
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			COMMIT
	END TRY
	BEGIN CATCH
		--SI OCURRIO UN ERROR Y SE INICIO UNA TRANSACCION ENE ESTE BLOQUE SE CANCELARA LA TRANSACCION
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			ROLLBACK
		--SE INDICA EN LA VARIABLE DE RETORNO QUE OCURRIO UN ERROR
		--SET @POUT_CLAVE_RETORNO = 0
		--SE INSERTA EL ERROR EN LA TABLA
		DECLARE @ERROR_CLAVE INT  = ERROR_NUMBER()
		DECLARE @ERROR_MENSAJE NVARCHAR(250)  = ERROR_MESSAGE()
		
		SET @XML_RESULTADO = DBO.F_ERROR_CREAR_ENCABEZADO( @@ROWCOUNT, @ERROR_CLAVE, 'ERROR')
		SET @XML_RESULTADO = DBO.F_ERROR_MENSAJES(@ERROR_CLAVE,@ERROR_MENSAJE)
		SET @XML_RESULTADO = DBO.F_ERROR_MENSAJES(@ERROR_CLAVE,@ERROR_MENSAJE)			
	END CATCH
END


