CREATE PROCEDURE [IDP].[SPE_OBTIENE_CONSULTA_PERSONAL_DETALLADA]

	@PIN_ID_BATERIA AS INT

AS
BEGIN

	DECLARE @V_ID_CUESTIONARIO_BAREMOS AS INT

	SELECT @V_ID_CUESTIONARIO_BAREMOS = ID_CUESTIONARIO_BAREMOS
	FROM IDP.K_BATERIA_PRUEBA
	WHERE ID_BATERIA = @PIN_ID_BATERIA


		SELECT
			NO_VALOR,
			ID_VARIABLE,
			CL_VARIABLE,
			CL_FACTOR,
			NB_FACTOR,
			DS_FACTOR,
			ID_FACTOR,
			ID_COMPETENCIA,
			NB_COMPETENCIA,
			DS_COMPETENCIA,
			CL_TIPO_COMPETENCIA,
			CL_CLASIFICACION,
			CL_COLOR,
			--NB_PRUEBA,
			CASE
				WHEN NB_PRUEBA IN ('ORTOGRAFIA', 'REDACCION', 'COMUNICACION') THEN 'COMUNICACION' ELSE NB_PRUEBA END AS NB_PRUEBA,
			NB_ABREVIATURA
		FROM IDP.F_OBTIENE_DATOS_CONSULTA_PERSONAL(@V_ID_CUESTIONARIO_BAREMOS)


END