-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: juan De Dios Pérez Pedroza
-- CRETAE date: 21/09/2015
-- Description: Inserta un nuevo registro en la tabla K_CUESTIONARIO_PREGUNTA
-- =============================================
CREATE PROCEDURE [IDP].[SPE_INSERTA_ACTUALIZA_K_CUESTIONARIO_PREGUNTA] 
	      @XML_RESULTADO XML = '' OUT      --APLICA PARA REGRESAR UN NÚMERO 0 PARA ERROR Y 1 PARA CORRECTO
    	, @PIN_ID_EVALUADO AS int
		, @PIN_ID_EVALUADOR AS int
		, @PIN_ID_CUESTIONARIO_PREGUNTA AS int
		, @PIN_ID_CUESTIONARIO AS int
		, @XML_CUESTIONARIO AS xml
		, @PIN_NB_PRUEBA AS NVARCHAR(50)
		, @PIN_CL_USUARIO_APP_CREA AS nvarchar(50)
		, @PIN_CL_USUARIO_APP_MODIFICA AS nvarchar(50)
		, @PIN_NB_PROGRAMA_CREA AS nvarchar(50)
		, @PIN_NB_PROGRAMA_MODIFICA AS nvarchar(50)
		, @PIN_TIPO_TRANSACCION CHAR(1)             --I=INSERCIÓN   A=ACTUALIZACIÓN
AS 
BEGIN  
	--SE DECLARA E INICIALIZA LA VARIABLE QUE NOS INDICARA SI GENERAMOS LA TRANSACCION EN ESTE SP
	DECLARE @V_EXIST_TRAN BIT = 0
    	BEGIN TRY
		--SE VERIFICA SI EXISTE UNA TRANSACCION EN EJECUCION
		IF (@@TRANCOUNT = 0) 
		BEGIN
			--EN CASO DE QUE NO SE INICIALIZA LA TRANSACCION
			BEGIN TRANSACTION
			--SE EDITA LA VARIABLE QUE INDICA QUE SE INICIO LA TRANSACCION EN ESTE BLOQUE PARA CANCELARLA SI ES NECESARIO
			SET @V_EXIST_TRAN = 1
		END	
		--SE VERIFICA SI SE INSERTA EL REGISTRO O SE ACTUALIZARA SEGUN LA VARIABLE DE TIPO DE TRANSACCION  QUE RECIBE EL SP
		IF @PIN_TIPO_TRANSACCION='I'
	    	BEGIN
			--SE INSERTA EL REGISTRO EN LA TABLA  ADM.K_CUESTIONARIO_PREGUNTA

-----------------------------------inserta en k_cuestionario--------------------------------------------------------------
				INSERT INTO ADM.K_CUESTIONARIO
					   (  [ID_EVALUADO]
						, [ID_EVALUADO_EVALUADOR]
						, [FE_CREACION]
						, [CL_USUARIO_APP_CREA]
						, [NB_PROGRAMA_CREA]
					    )
			VALUES
					   (  @PIN_ID_EVALUADO
						, @PIN_ID_EVALUADOR
						, GETDATE()
						, @PIN_CL_USUARIO_APP_CREA
						, @PIN_NB_PROGRAMA_CREA
					)	
-----------------------------OBTENEMOS EL ID DEL CUESTIONARIO DEL QUE VAMOS A INSERTAR LAS RESPUESTAS-------------------
		SET @PIN_ID_CUESTIONARIO = SCOPE_IDENTITY();
------------------------------------------------------------------------------------------------------------------------

			INSERT INTO ADM.K_CUESTIONARIO_PREGUNTA
					   ([ID_CUESTIONARIO]
						, [ID_PREGUNTA]
						, [NB_PREGUNTA]
						, [NB_RESPUESTA]
						, [NO_VALOR_RESPUESTA]
						, [FE_CREACION]
						, [CL_USUARIO_APP_CREA]
						, [NB_PROGRAMA_CREA]
					)
					SELECT
				   @PIN_ID_CUESTIONARIO,
				   COLUMNA.value('@ID_PREGUNTA', 'INT'),
				   COLUMNA.value('@NB_PREGUNTA', 'NVARCHAR(200)'),
				   COLUMNA.value('@NB_RESPUESTA', 'NVARCHAR(200)'),
				   COLUMNA.value('@NO_VALOR_RESPUESTA', 'DECIMAL(3,2)'),
				   GETDATE(),
				   @PIN_CL_USUARIO_APP_CREA,
				   @PIN_NB_PROGRAMA_CREA
					FROM @XML_CUESTIONARIO.nodes('/RESPUESTAS/RESPUESTA') tbl(COLUMNA)
			
		END ELSE BEGIN
			--SE ACTUALIZA EL REGISTRO EN LA TABLA  ADM.K_CUESTIONARIO_PREGUNTA
			UPDATE KCP SET
				  [NB_PREGUNTA] =COLUMNA.value('@NB_PREGUNTA', 'NVARCHAR(200)')
				, [NB_RESPUESTA] =COLUMNA.value('@NB_RESPUESTA', 'NVARCHAR(200)')  
				, [NO_VALOR_RESPUESTA] = COLUMNA.value('@NO_VALOR_RESPUESTA', 'DECIMAL(3,2)')
				, [FE_MODIFICACION] = GETDATE()
				, [CL_USUARIO_APP_MODIFICA] = @PIN_CL_USUARIO_APP_MODIFICA
				, [NB_PROGRAMA_MODIFICA] = @PIN_NB_PROGRAMA_MODIFICA
			     FROM ADM.K_CUESTIONARIO_PREGUNTA KCP
				 INNER JOIN @XML_CUESTIONARIO.nodes('/RESPUESTAS/RESPUESTA') tbl(COLUMNA) ON
				  COLUMNA.value('@ID_CUESTIONARIO_PREGUNTA', 'INT') = KCP.ID_CUESTIONARIO_PREGUNTA;


			SELECT
					@PIN_ID_CUESTIONARIO = cp.ID_CUESTIONARIO
			FROM @XML_CUESTIONARIO.nodes('/RESPUESTAS/RESPUESTA[1]') tbl(COLUMNA)
			INNER JOIN ADM.K_CUESTIONARIO_PREGUNTA cp ON COLUMNA.value('@ID_CUESTIONARIO_PREGUNTA', 'INT') = cp.ID_CUESTIONARIO_PREGUNTA

			--SE ACTUALIZA EL ESTATUS DE LA PRUEBA A TERMINADA
			UPDATE IDP.K_PRUEBA 
			SET CL_ESTADO= 'TERMINADA' 
			WHERE ID_CUESTIONARIO=@PIN_ID_CUESTIONARIO;

		END

		
------------------------------------------------------------------------------------------------
		IF @PIN_NB_PRUEBA = 'LABORAL2' BEGIN

			DELETE IDP.K_RESULTADO WHERE ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO

			INSERT INTO [IDP].[K_RESULTADO]
					   ([CL_TIPO_RESULTADO]
					   ,[ID_VARIABLE]
					   ,[NO_VALOR]
					   ,[ID_CUESTIONARIO]
					   ,[FE_CREACION]
					   ,[CL_USUARIO_APP_CREA]
					   ,[NB_PROGRAMA_CREA])
			SELECT
						v.CL_TIPO_VARIABLE,
						v.ID_VARIABLE,
						COLUMNA.value('@NB_RESPUESTA', 'DECIMAL(3,2)'),
						@PIN_ID_CUESTIONARIO,
						GETDATE(),
						@PIN_CL_USUARIO_APP_CREA,
						@PIN_NB_PROGRAMA_CREA
			FROM @XML_CUESTIONARIO.nodes('/RESPUESTAS/RESPUESTA') tbl(COLUMNA)
				INNER JOIN ADM.C_PREGUNTA p ON COLUMNA.value('@ID_PREGUNTA', 'INT') = p.ID_PREGUNTA
				INNER JOIN IDP.C_VARIABLE v ON V.CL_VARIABLE = p.CL_PREGUNTA AND v.CL_TIPO_VARIABLE = 1
			
			EXEC IDP.SPE_INSERTA_RESULTADOS_LABORAL2 @XML_RESULTADO OUT, NULL, @PIN_ID_CUESTIONARIO, NULL, @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA
		END

------------------------------------------------------------------------------------------------------------
		IF @PIN_NB_PRUEBA = 'PENSAMIENTO' BEGIN
			
			DELETE IDP.K_RESULTADO WHERE ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO

			INSERT INTO [IDP].[K_RESULTADO]
					   ([CL_TIPO_RESULTADO]
					   ,[ID_VARIABLE]
					   ,[NO_VALOR]
					   ,[ID_CUESTIONARIO]
					   ,[FE_CREACION]
					   ,[CL_USUARIO_APP_CREA]
					   ,[NB_PROGRAMA_CREA])
			SELECT
						v.CL_TIPO_VARIABLE,
						v.ID_VARIABLE,
						COLUMNA.value('@NB_RESPUESTA', 'DECIMAL(3,2)'),
						@PIN_ID_CUESTIONARIO,
						GETDATE(),
						@PIN_CL_USUARIO_APP_CREA,
						@PIN_NB_PROGRAMA_CREA
			FROM @XML_CUESTIONARIO.nodes('/RESPUESTAS/RESPUESTA') tbl(COLUMNA)
				INNER JOIN ADM.C_PREGUNTA p ON COLUMNA.value('@ID_PREGUNTA', 'INT') = p.ID_PREGUNTA
				INNER JOIN IDP.C_VARIABLE v ON V.CL_VARIABLE = p.CL_PREGUNTA AND v.CL_TIPO_VARIABLE = 1
			
			EXEC IDP.SPE_INSERTA_RESULTADOS_PENSAMIENTO @XML_RESULTADO OUT, NULL, @PIN_ID_CUESTIONARIO, NULL, @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA

		END
--------------------------------------------------------------------------------------------------------------
		IF @PIN_NB_PRUEBA = 'TIVA' BEGIN
			
			
			DELETE IDP.K_RESULTADO WHERE ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO

			INSERT INTO [IDP].[K_RESULTADO]
					   ([CL_TIPO_RESULTADO]
					   ,[ID_VARIABLE]
					   ,[NO_VALOR]
					   ,[ID_CUESTIONARIO]
					   ,[FE_CREACION]
					   ,[CL_USUARIO_APP_CREA]
					   ,[NB_PROGRAMA_CREA])
			SELECT
						v.CL_TIPO_VARIABLE,
						v.ID_VARIABLE,
						CASE COLUMNA.value('@NB_RESPUESTA', 'NVARCHAR(1)')
							WHEN 'a' THEN 1.0
							WHEN 'b' THEN 2.0
							WHEN 'c' THEN 3.0
							WHEN 'd' THEN 4.0
							ELSE 0
						END AS NO_VALOR,
						@PIN_ID_CUESTIONARIO,
						GETDATE(),
						@PIN_CL_USUARIO_APP_CREA,
						@PIN_NB_PROGRAMA_CREA
			FROM @XML_CUESTIONARIO.nodes('/RESPUESTAS/RESPUESTA') tbl(COLUMNA)
				INNER JOIN ADM.C_PREGUNTA p ON COLUMNA.value('@ID_PREGUNTA', 'INT') = p.ID_PREGUNTA
				INNER JOIN IDP.C_VARIABLE v ON V.CL_VARIABLE = p.CL_PREGUNTA AND v.CL_TIPO_VARIABLE = 1

			EXEC IDP.SPE_INSERTA_RESULTADOS_TIVA @XML_RESULTADO OUT, NULL, @PIN_ID_CUESTIONARIO, NULL, @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA
		END
-------------------------------------------------------------------------------------------------------------------
		IF @PIN_NB_PRUEBA = 'INTERES' BEGIN
			
			DELETE IDP.K_RESULTADO WHERE ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO

			INSERT INTO [IDP].[K_RESULTADO]
					   ([CL_TIPO_RESULTADO]
					   ,[ID_VARIABLE]
					   ,[NO_VALOR]
					   ,[ID_CUESTIONARIO]
					   ,[FE_CREACION]
					   ,[CL_USUARIO_APP_CREA]
					   ,[NB_PROGRAMA_CREA])
			SELECT
						v.CL_TIPO_VARIABLE,
						v.ID_VARIABLE,
						COLUMNA.value('@NB_RESPUESTA', 'INT'),
						@PIN_ID_CUESTIONARIO,
						GETDATE(),
						@PIN_CL_USUARIO_APP_CREA,
						@PIN_NB_PROGRAMA_CREA
			FROM @XML_CUESTIONARIO.nodes('/RESPUESTAS/RESPUESTA') tbl(COLUMNA)
				INNER JOIN ADM.C_PREGUNTA p ON COLUMNA.value('@ID_PREGUNTA', 'INT') = p.ID_PREGUNTA
				INNER JOIN IDP.C_VARIABLE v ON V.CL_VARIABLE = p.CL_PREGUNTA AND v.CL_TIPO_VARIABLE = 1

			EXEC IDP.SPE_INSERTA_RESULTADOS_INTERES_PERSONAL @XML_RESULTADO OUT,@XML_CUESTIONARIO , @PIN_ID_CUESTIONARIO, NULL, @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA
		END
-------------------------------------------------------------------------------------------------------------------------
		IF @PIN_NB_PRUEBA = 'TECNICAPC' BEGIN
			
			DELETE IDP.K_RESULTADO WHERE ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO

			INSERT INTO [IDP].[K_RESULTADO]
					   ([CL_TIPO_RESULTADO]
					   ,[ID_VARIABLE]
					   ,[NO_VALOR]
					   ,[ID_CUESTIONARIO]
					   ,[FE_CREACION]
					   ,[CL_USUARIO_APP_CREA]
					   ,[NB_PROGRAMA_CREA])
			SELECT
						v.CL_TIPO_VARIABLE,
						v.ID_VARIABLE,
						COLUMNA.value('@NB_RESPUESTA', 'INT'),
						@PIN_ID_CUESTIONARIO,
						GETDATE(),
						@PIN_CL_USUARIO_APP_CREA,
						@PIN_NB_PROGRAMA_CREA
			FROM @XML_CUESTIONARIO.nodes('/RESPUESTAS/RESPUESTA') tbl(COLUMNA)
				INNER JOIN ADM.C_PREGUNTA p ON COLUMNA.value('@ID_PREGUNTA', 'INT') = p.ID_PREGUNTA
				INNER JOIN IDP.C_VARIABLE v ON V.CL_VARIABLE = p.CL_PREGUNTA AND v.CL_TIPO_VARIABLE = 1
			EXEC IDP.SPE_INSERTA_RESULTADOS_TECNICAPC @XML_RESULTADO OUT, NULL, @PIN_ID_CUESTIONARIO, NULL, @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA
		END

---------------------------------------------------------------------------------------------------------------------
IF @PIN_NB_PRUEBA = 'REDACCION' BEGIN
			
			DELETE IDP.K_RESULTADO WHERE ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO

			INSERT INTO [IDP].[K_RESULTADO]
					   ([CL_TIPO_RESULTADO]
					   ,[ID_VARIABLE]
					   ,[NO_VALOR]
					   ,[ID_CUESTIONARIO]
					   ,[FE_CREACION]
					   ,[CL_USUARIO_APP_CREA]
					   ,[NB_PROGRAMA_CREA])
			SELECT
						v.CL_TIPO_VARIABLE,
						v.ID_VARIABLE,
						COLUMNA.value('@NO_VALOR_RESPUESTA', 'INT'),
						@PIN_ID_CUESTIONARIO,
						GETDATE(),
						@PIN_CL_USUARIO_APP_CREA,
						@PIN_NB_PROGRAMA_CREA
			FROM @XML_CUESTIONARIO.nodes('/RESPUESTAS/RESPUESTA') tbl(COLUMNA)
				INNER JOIN ADM.C_PREGUNTA p ON COLUMNA.value('@ID_PREGUNTA', 'INT') = p.ID_PREGUNTA
				INNER JOIN IDP.C_VARIABLE v ON V.CL_VARIABLE = p.CL_PREGUNTA AND v.CL_TIPO_VARIABLE = 1
			EXEC IDP.SPE_INSERTA_RESULTADOS_REDACCION @XML_RESULTADO OUT,@XML_CUESTIONARIO, @PIN_ID_CUESTIONARIO, NULL,@PIN_CL_USUARIO_APP_MODIFICA, @PIN_NB_PROGRAMA_MODIFICA
		END
--------------------------------------------------------------------------------------------------------------------

IF @PIN_NB_PRUEBA = 'APTITUD_MENTAL2' BEGIN
			
			DELETE IDP.K_RESULTADO WHERE ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO

			INSERT INTO [IDP].[K_RESULTADO]
					   ([CL_TIPO_RESULTADO]
					   ,[ID_VARIABLE]
					   ,[NO_VALOR]
					   ,[ID_CUESTIONARIO]
					   ,[FE_CREACION]
					   ,[CL_USUARIO_APP_CREA]
					   ,[NB_PROGRAMA_CREA])
			SELECT
						v.CL_TIPO_VARIABLE,
						v.ID_VARIABLE,
						COLUMNA.value('@NO_VALOR_RESPUESTA', 'INT'),
						@PIN_ID_CUESTIONARIO,
						GETDATE(),
						@PIN_CL_USUARIO_APP_CREA,
						@PIN_NB_PROGRAMA_CREA
			FROM @XML_CUESTIONARIO.nodes('/RESPUESTAS/RESPUESTA') tbl(COLUMNA)
				INNER JOIN ADM.C_PREGUNTA p ON COLUMNA.value('@ID_PREGUNTA', 'INT') = p.ID_PREGUNTA
				INNER JOIN IDP.C_VARIABLE v ON V.CL_VARIABLE = p.CL_PREGUNTA AND v.CL_TIPO_VARIABLE = 1
			EXEC IDP.SPE_INSERTA_RESULTADOS_APTITUD2 @XML_RESULTADO OUT,@XML_CUESTIONARIO, @PIN_ID_CUESTIONARIO, NULL,@PIN_CL_USUARIO_APP_MODIFICA, @PIN_NB_PROGRAMA_MODIFICA
		END
--------------------------------------------------------------------------------------------------------------------


IF @PIN_NB_PRUEBA = 'ORTOGRAFIA-1' BEGIN
			
			DELETE IDP.K_RESULTADO WHERE ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO

			INSERT INTO [IDP].[K_RESULTADO]
					   ([CL_TIPO_RESULTADO]
					   ,[ID_VARIABLE]
					   ,[NO_VALOR]
					   ,[ID_CUESTIONARIO]
					   ,[FE_CREACION]
					   ,[CL_USUARIO_APP_CREA]
					   ,[NB_PROGRAMA_CREA])
			SELECT
						v.CL_TIPO_VARIABLE,
						v.ID_VARIABLE,
						COLUMNA.value('@NO_VALOR_RESPUESTA', 'INT'),
						@PIN_ID_CUESTIONARIO,
						GETDATE(),
						@PIN_CL_USUARIO_APP_CREA,
						@PIN_NB_PROGRAMA_CREA
			FROM @XML_CUESTIONARIO.nodes('/RESPUESTAS/RESPUESTA') tbl(COLUMNA)
				INNER JOIN ADM.C_PREGUNTA p ON COLUMNA.value('@ID_PREGUNTA', 'INT') = p.ID_PREGUNTA
				INNER JOIN IDP.C_VARIABLE v ON V.CL_VARIABLE = p.CL_PREGUNTA AND v.CL_TIPO_VARIABLE = 1
			EXEC IDP.SPE_INSERTA_RESULTADOS_ORTOGRAFIAS @XML_RESULTADO OUT,@XML_CUESTIONARIO, @PIN_ID_CUESTIONARIO, NULL,@PIN_NB_PRUEBA,@PIN_CL_USUARIO_APP_MODIFICA, @PIN_NB_PROGRAMA_MODIFICA
		END
--------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
			IF @PIN_NB_PRUEBA = 'ORTOGRAFIA-2' BEGIN
			DELETE IDP.K_RESULTADO WHERE ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO

						INSERT INTO [IDP].[K_RESULTADO]
					   ([CL_TIPO_RESULTADO]
					   ,[ID_VARIABLE]
					   ,[NO_VALOR]
					   ,[ID_CUESTIONARIO]
					   ,[FE_CREACION]
					   ,[CL_USUARIO_APP_CREA]
					   ,[NB_PROGRAMA_CREA])
			SELECT
						v.CL_TIPO_VARIABLE,
						v.ID_VARIABLE,
						COLUMNA.value('@NO_VALOR_RESPUESTA', 'INT'),
						@PIN_ID_CUESTIONARIO,
						GETDATE(),
						@PIN_CL_USUARIO_APP_CREA,
						@PIN_NB_PROGRAMA_CREA
			FROM @XML_CUESTIONARIO.nodes('/RESPUESTAS/RESPUESTA') tbl(COLUMNA)
				INNER JOIN ADM.C_PREGUNTA p ON COLUMNA.value('@ID_PREGUNTA', 'INT') = p.ID_PREGUNTA
				INNER JOIN IDP.C_VARIABLE v ON V.CL_VARIABLE = p.CL_PREGUNTA AND v.CL_TIPO_VARIABLE = 1
			EXEC IDP.SPE_INSERTA_RESULTADOS_ORTOGRAFIAS @XML_RESULTADO OUT,@XML_CUESTIONARIO, @PIN_ID_CUESTIONARIO, NULL,@PIN_NB_PRUEBA,@PIN_CL_USUARIO_APP_MODIFICA, @PIN_NB_PROGRAMA_MODIFICA
		END
--------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
		 
		  IF @PIN_NB_PRUEBA = 'ORTOGRAFIA-3' BEGIN
		  DELETE IDP.K_RESULTADO WHERE ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
						INSERT INTO [IDP].[K_RESULTADO]
					   ([CL_TIPO_RESULTADO]
					   ,[ID_VARIABLE]
					   ,[NO_VALOR]
					   ,[ID_CUESTIONARIO]
					   ,[FE_CREACION]
					   ,[CL_USUARIO_APP_CREA]
					   ,[NB_PROGRAMA_CREA])
			SELECT
						v.CL_TIPO_VARIABLE,
						v.ID_VARIABLE,
						COLUMNA.value('@NO_VALOR_RESPUESTA', 'INT'),
						@PIN_ID_CUESTIONARIO,
						GETDATE(),
						@PIN_CL_USUARIO_APP_CREA,
						@PIN_NB_PROGRAMA_CREA
			FROM @XML_CUESTIONARIO.nodes('/RESPUESTAS/RESPUESTA') tbl(COLUMNA)
				INNER JOIN ADM.C_PREGUNTA p ON COLUMNA.value('@ID_PREGUNTA', 'INT') = p.ID_PREGUNTA
				INNER JOIN IDP.C_VARIABLE v ON V.CL_VARIABLE = p.CL_PREGUNTA AND v.CL_TIPO_VARIABLE = 1

			
			EXEC IDP.SPE_INSERTA_RESULTADOS_ORTOGRAFIAS @XML_RESULTADO OUT,@XML_CUESTIONARIO, @PIN_ID_CUESTIONARIO, NULL,@PIN_NB_PRUEBA,@PIN_CL_USUARIO_APP_MODIFICA, @PIN_NB_PROGRAMA_MODIFICA
		END
--------------------------------------------------------------------------------------------------------------------


IF @PIN_NB_PRUEBA = 'PERSONALIDAD_LABORAL' BEGIN
			
			DELETE IDP.K_RESULTADO WHERE ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO

			INSERT INTO [IDP].[K_RESULTADO]
					   ([CL_TIPO_RESULTADO]
					   ,[ID_VARIABLE]
					   ,[NO_VALOR]
					   ,[ID_CUESTIONARIO]
					   ,[FE_CREACION]
					   ,[CL_USUARIO_APP_CREA]
					   ,[NB_PROGRAMA_CREA])
			SELECT
						v.CL_TIPO_VARIABLE,
						v.ID_VARIABLE,
						COLUMNA.value('@NO_VALOR_RESPUESTA', 'INT'),
						@PIN_ID_CUESTIONARIO,
						GETDATE(),
						@PIN_CL_USUARIO_APP_CREA,
						@PIN_NB_PROGRAMA_CREA
			FROM @XML_CUESTIONARIO.nodes('/RESPUESTAS/RESPUESTA') tbl(COLUMNA)
				INNER JOIN ADM.C_PREGUNTA p ON COLUMNA.value('@ID_PREGUNTA', 'INT') = p.ID_PREGUNTA
				INNER JOIN IDP.C_VARIABLE v ON V.CL_VARIABLE = p.CL_PREGUNTA AND v.CL_TIPO_VARIABLE = 1
			EXEC IDP.SPE_INSERTA_RESULTADOS_LABORAL1 @XML_RESULTADO OUT,@XML_CUESTIONARIO, @PIN_ID_CUESTIONARIO, NULL,@PIN_CL_USUARIO_APP_MODIFICA, @PIN_NB_PROGRAMA_MODIFICA
		END
--------------------------------------------------------------------------------------------------------------------

IF @PIN_NB_PRUEBA = 'INGLES-1' BEGIN
			
			DELETE IDP.K_RESULTADO
			WHERE ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO AND ID_VARIABLE IN (SELECT ID_VARIABLE FROM IDP.C_VARIABLE WHERE CL_VARIABLE LIKE '%INGLES-A-%')

			INSERT INTO [IDP].[K_RESULTADO]
					   ([CL_TIPO_RESULTADO]
					   ,[ID_VARIABLE]
					   ,[NO_VALOR]
					   ,[ID_CUESTIONARIO]
					   ,[FE_CREACION]
					   ,[CL_USUARIO_APP_CREA]
					   ,[NB_PROGRAMA_CREA])
			SELECT
						v.CL_TIPO_VARIABLE,
						v.ID_VARIABLE,
						COLUMNA.value('@NO_VALOR_RESPUESTA', 'INT'),
						@PIN_ID_CUESTIONARIO,
						GETDATE(),
						@PIN_CL_USUARIO_APP_CREA,
						@PIN_NB_PROGRAMA_CREA
			FROM @XML_CUESTIONARIO.nodes('/RESPUESTAS/RESPUESTA') tbl(COLUMNA)
				INNER JOIN ADM.C_PREGUNTA p ON COLUMNA.value('@ID_PREGUNTA', 'INT') = p.ID_PREGUNTA
				INNER JOIN IDP.C_VARIABLE v ON V.CL_VARIABLE = p.CL_PREGUNTA AND v.CL_TIPO_VARIABLE = 1
			EXEC IDP.SPE_INSERTA_RESULTADOS_INGLES @XML_RESULTADO OUT,@XML_CUESTIONARIO, @PIN_ID_CUESTIONARIO, NULL,@PIN_NB_PRUEBA,@PIN_CL_USUARIO_APP_MODIFICA, @PIN_NB_PROGRAMA_MODIFICA
		END
--------------------------------------------------------------------------------------------------------------------

IF @PIN_NB_PRUEBA = 'INGLES-2' BEGIN
			
			DELETE IDP.K_RESULTADO
			WHERE ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO AND ID_VARIABLE IN (SELECT ID_VARIABLE FROM IDP.C_VARIABLE WHERE CL_VARIABLE LIKE '%INGLES-B-%')

			INSERT INTO [IDP].[K_RESULTADO]
					   ([CL_TIPO_RESULTADO]
					   ,[ID_VARIABLE]
					   ,[NO_VALOR]
					   ,[ID_CUESTIONARIO]
					   ,[FE_CREACION]
					   ,[CL_USUARIO_APP_CREA]
					   ,[NB_PROGRAMA_CREA])
			SELECT
						v.CL_TIPO_VARIABLE,
						v.ID_VARIABLE,
						COLUMNA.value('@NO_VALOR_RESPUESTA', 'INT'),
						@PIN_ID_CUESTIONARIO,
						GETDATE(),
						@PIN_CL_USUARIO_APP_CREA,
						@PIN_NB_PROGRAMA_CREA
			FROM @XML_CUESTIONARIO.nodes('/RESPUESTAS/RESPUESTA') tbl(COLUMNA)
				INNER JOIN ADM.C_PREGUNTA p ON COLUMNA.value('@ID_PREGUNTA', 'INT') = p.ID_PREGUNTA
				INNER JOIN IDP.C_VARIABLE v ON V.CL_VARIABLE = p.CL_PREGUNTA AND v.CL_TIPO_VARIABLE = 1
			EXEC IDP.SPE_INSERTA_RESULTADOS_INGLES @XML_RESULTADO OUT,@XML_CUESTIONARIO, @PIN_ID_CUESTIONARIO, NULL,@PIN_NB_PRUEBA,@PIN_CL_USUARIO_APP_MODIFICA, @PIN_NB_PROGRAMA_MODIFICA
		END
--------------------------------------------------------------------------------------------------------------------

IF @PIN_NB_PRUEBA = 'INGLES-3' BEGIN
			
			DELETE IDP.K_RESULTADO
			WHERE ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO AND ID_VARIABLE IN (SELECT ID_VARIABLE FROM IDP.C_VARIABLE WHERE CL_VARIABLE LIKE '%INGLES-C-%')
			INSERT INTO [IDP].[K_RESULTADO]
					   ([CL_TIPO_RESULTADO]
					   ,[ID_VARIABLE]
					   ,[NO_VALOR]
					   ,[ID_CUESTIONARIO]
					   ,[FE_CREACION]
					   ,[CL_USUARIO_APP_CREA]
					   ,[NB_PROGRAMA_CREA])
			SELECT
						v.CL_TIPO_VARIABLE,
						v.ID_VARIABLE,
						COLUMNA.value('@NO_VALOR_RESPUESTA', 'INT'),
						@PIN_ID_CUESTIONARIO,
						GETDATE(),
						@PIN_CL_USUARIO_APP_CREA,
						@PIN_NB_PROGRAMA_CREA
			FROM @XML_CUESTIONARIO.nodes('/RESPUESTAS/RESPUESTA') tbl(COLUMNA)
				INNER JOIN ADM.C_PREGUNTA p ON COLUMNA.value('@ID_PREGUNTA', 'INT') = p.ID_PREGUNTA
				INNER JOIN IDP.C_VARIABLE v ON V.CL_VARIABLE = p.CL_PREGUNTA AND v.CL_TIPO_VARIABLE = 1
			EXEC IDP.SPE_INSERTA_RESULTADOS_INGLES @XML_RESULTADO OUT,@XML_CUESTIONARIO, @PIN_ID_CUESTIONARIO, NULL,@PIN_NB_PRUEBA,@PIN_CL_USUARIO_APP_MODIFICA, @PIN_NB_PROGRAMA_MODIFICA
		END
--------------------------------------------------------------------------------------------------------------------

IF @PIN_NB_PRUEBA = 'INGLES-4' BEGIN
			DELETE IDP.K_RESULTADO
			WHERE ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO AND ID_VARIABLE IN (SELECT ID_VARIABLE FROM IDP.C_VARIABLE WHERE CL_VARIABLE LIKE '%INGLES-D-%')
			INSERT INTO [IDP].[K_RESULTADO]
					   ([CL_TIPO_RESULTADO]
					   ,[ID_VARIABLE]
					   ,[NO_VALOR]
					   ,[ID_CUESTIONARIO]
					   ,[FE_CREACION]
					   ,[CL_USUARIO_APP_CREA]
					   ,[NB_PROGRAMA_CREA])
			SELECT
						v.CL_TIPO_VARIABLE,
						v.ID_VARIABLE,
						COLUMNA.value('@NO_VALOR_RESPUESTA', 'INT'),
						@PIN_ID_CUESTIONARIO,
						GETDATE(),
						@PIN_CL_USUARIO_APP_CREA,
						@PIN_NB_PROGRAMA_CREA
			FROM @XML_CUESTIONARIO.nodes('/RESPUESTAS/RESPUESTA') tbl(COLUMNA)
				INNER JOIN ADM.C_PREGUNTA p ON COLUMNA.value('@ID_PREGUNTA', 'INT') = p.ID_PREGUNTA
				INNER JOIN IDP.C_VARIABLE v ON V.CL_VARIABLE = p.CL_PREGUNTA AND v.CL_TIPO_VARIABLE = 1
			EXEC IDP.SPE_INSERTA_RESULTADOS_INGLES @XML_RESULTADO OUT,@XML_CUESTIONARIO, @PIN_ID_CUESTIONARIO, NULL,@PIN_NB_PRUEBA,@PIN_CL_USUARIO_APP_MODIFICA, @PIN_NB_PROGRAMA_MODIFICA
		END
--------------------------------------------------------------------------------------------------------------------
		IF @PIN_NB_PRUEBA LIKE 'APTITUD1%' BEGIN

			EXEC IDP.SPE_INSERTA_RESPUESTAS_APTITUD1 @XML_RESULTADO OUT,  @XML_CUESTIONARIO, @PIN_ID_CUESTIONARIO, @PIN_NB_PRUEBA, NULL, @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA

			IF @PIN_NB_PRUEBA = 'APTITUD110' BEGIN
				
				DELETE IDP.K_RESULTADO WHERE ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO AND CL_TIPO_RESULTADO = 2

				EXEC [IDP].[SPE_INSERTA_RESULTADOS_APTITUD_1] @XML_RESULTADO  OUT , NULL, @PIN_ID_CUESTIONARIO, NULL, @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA

			END
		END

		--SE DEVUELVE LA VARIABLE DE RETORNO INDICANDO QUE TODO SE REALIZO CORRECTAMENTE
		SET @XML_RESULTADO = DBO.F_ERROR_CREAR_ENCABEZADO( @@ROWCOUNT, 1, 'SUCCESSFUL')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'Proceso exitoso', 'ES')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'Successful Process', 'EN')
		--SI SE GENERO UNA TRANSACCION EN ESTE BLOQUE LA TERMINARA
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			COMMIT
	END TRY
	BEGIN CATCH
		--SI OCURRIO UN ERROR Y SE INICIO UNA TRANSACCION ENE ESTE BLOQUE SE CANCELARA LA TRANSACCION
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			ROLLBACK
		--SE INDICA EN LA VARIABLE DE RETORNO QUE OCURRIO UN ERROR
		--SET @POUT_CLAVE_RETORNO = 0
		--SE INSERTA EL ERROR EN LA TABLA		
		DECLARE @ERROR_CLAVE INT  = 	ERROR_NUMBER()
		DECLARE @ERROR_MENSAJE NVARCHAR(250)  = 	 ERROR_MESSAGE() + ' cuestionario_pregunta'
		
		SET @XML_RESULTADO = DBO.F_ERROR_CREAR_ENCABEZADO( @@ROWCOUNT, @ERROR_CLAVE, 'ERROR')
		SET @XML_RESULTADO = DBO.F_ERROR_MENSAJES(@ERROR_CLAVE,@ERROR_MENSAJE)
		SET @XML_RESULTADO = DBO.F_ERROR_MENSAJES(@ERROR_CLAVE,@ERROR_MENSAJE)			
	END CATCH
END
