-- =============================================
-- Proyecto: SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Daniela Sanchez
-- CRETAE date: 20/01/2016
-- Description: Inserta variables de respuesta de la prueba Aptitud metal 1
-- =============================================
CREATE PROCEDURE [IDP].[SPE_INSERTA_RESULTADOS_APTITUD_1]
@XML_RESULTADO XML = '' OUT 
,@PIN_XML_RESULTADOS AS XML
	,@PIN_ID_CUESTIONARIO AS INT = NULL
	,@PIN_ID_PRUEBA AS INT
	,@PIN_CL_USUARIO_APP_CREA AS nvarchar(50)
    ,@PIN_NB_PROGRAMA_CREA AS nvarchar(50)
	AS
BEGIN  
	--SE DECLARA E INICIALIZA LA VARIABLE QUE NOS INDICARA SI GENERAMOS LA TRANSACCION EN ESTE SP
	DECLARE @V_EXIST_TRAN BIT = 0,
			@V_FE_ACTUAL AS DATE = GETDATE()
    	BEGIN TRY
		--SE VERIFICA SI EXISTE UNA TRANSACCION EN EJECUCION
		IF (@@TRANCOUNT = 0) 
		BEGIN
			--EN CASO DE QUE NO SE INICIALIZA LA TRANSACCION
			BEGIN TRANSACTION
			--SE EDITA LA VARIABLE QUE INDICA QUE SE INICIO LA TRANSACCION EN ESTE BLOQUE PARA CANCELARLA SI ES NECESARIO
			SET @V_EXIST_TRAN = 1
		END	
		--SE VERIFICA SI SE INSERTA EL REGISTRO O SE ACTUALIZARA SEGUN LA VARIABLE DE TIPO DE TRANSACCION  QUE RECIBE EL SP
		IF @PIN_ID_CUESTIONARIO IS NULL BEGIN

			SELECT @PIN_ID_CUESTIONARIO = ID_CUESTIONARIO
			FROM IDP.K_PRUEBA
			WHERE ID_PRUEBA = @PIN_ID_PRUEBA

		END

		IF @PIN_XML_RESULTADOS IS NOT NULL 
		BEGIN

			INSERT INTO [IDP].[K_RESULTADO] ([CL_TIPO_RESULTADO] ,[ID_VARIABLE] ,[NO_VALOR], [ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA])
					SELECT 2, res.ID_VARIABLE, res.NO_VALOR, @PIN_ID_CUESTIONARIO, GETDATE(),@PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA
					FROM (
							SELECT
								d.value('@ID_VARIABLE', 'INT') AS ID_VARIABLE,
								d.value('@NO_VALOR', 'INT') AS NO_VALOR
							FROM @PIN_XML_RESULTADOS.nodes('RESULTADOS/RESULTADO') AS T(d)
					) AS res

					UPDATE IDP.K_PRUEBA 
					SET CL_ESTADO='TERMINADA'
					WHERE  ID_PRUEBA=@PIN_ID_PRUEBA

		END 

		IF @PIN_XML_RESULTADOS IS NULL
		BEGIN
			

			;WITH T_VARIABLES AS (
				--SECCION 1
				SELECT 1 AS CL_SECCION, 'APTITUD1-A-0001' AS CL_VARIABLE UNION ALL
				SELECT 1 AS CL_SECCION, 'APTITUD1-A-0002' AS CL_VARIABLE UNION ALL
				SELECT 1 AS CL_SECCION, 'APTITUD1-A-0003' AS CL_VARIABLE UNION ALL
				SELECT 1 AS CL_SECCION, 'APTITUD1-A-0004' AS CL_VARIABLE UNION ALL
				SELECT 1 AS CL_SECCION, 'APTITUD1-A-0005' AS CL_VARIABLE UNION ALL
				SELECT 1 AS CL_SECCION, 'APTITUD1-A-0006' AS CL_VARIABLE UNION ALL
				SELECT 1 AS CL_SECCION, 'APTITUD1-A-0007' AS CL_VARIABLE UNION ALL
				SELECT 1 AS CL_SECCION, 'APTITUD1-A-0008' AS CL_VARIABLE UNION ALL
				SELECT 1 AS CL_SECCION, 'APTITUD1-A-0009' AS CL_VARIABLE UNION ALL
				SELECT 1 AS CL_SECCION, 'APTITUD1-A-0010' AS CL_VARIABLE UNION ALL
				SELECT 1 AS CL_SECCION, 'APTITUD1-A-0011' AS CL_VARIABLE UNION ALL
				SELECT 1 AS CL_SECCION, 'APTITUD1-A-0012' AS CL_VARIABLE UNION ALL
				SELECT 1 AS CL_SECCION, 'APTITUD1-A-0013' AS CL_VARIABLE UNION ALL
				SELECT 1 AS CL_SECCION, 'APTITUD1-A-0014' AS CL_VARIABLE UNION ALL
				SELECT 1 AS CL_SECCION, 'APTITUD1-A-0015' AS CL_VARIABLE UNION ALL
				SELECT 1 AS CL_SECCION, 'APTITUD1-A-0016' AS CL_VARIABLE UNION ALL
				-- SECCION 2
				SELECT 2 AS CL_SECCION, 'APTITUD1-B-0001' AS CL_VARIABLE UNION ALL
				SELECT 2 AS CL_SECCION, 'APTITUD1-B-0002' AS CL_VARIABLE UNION ALL
				SELECT 2 AS CL_SECCION, 'APTITUD1-B-0003' AS CL_VARIABLE UNION ALL
				SELECT 2 AS CL_SECCION, 'APTITUD1-B-0004' AS CL_VARIABLE UNION ALL
				SELECT 2 AS CL_SECCION, 'APTITUD1-B-0005' AS CL_VARIABLE UNION ALL
				SELECT 2 AS CL_SECCION, 'APTITUD1-B-0006' AS CL_VARIABLE UNION ALL
				SELECT 2 AS CL_SECCION, 'APTITUD1-B-0007' AS CL_VARIABLE UNION ALL
				SELECT 2 AS CL_SECCION, 'APTITUD1-B-0008' AS CL_VARIABLE UNION ALL
				SELECT 2 AS CL_SECCION, 'APTITUD1-B-0009' AS CL_VARIABLE UNION ALL
				SELECT 2 AS CL_SECCION, 'APTITUD1-B-0010' AS CL_VARIABLE UNION ALL
				SELECT 2 AS CL_SECCION, 'APTITUD1-B-0011' AS CL_VARIABLE UNION ALL
				-- SECCION 3
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0001' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0002' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0003' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0004' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0005' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0006' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0007' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0008' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0009' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0010' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0011' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0012' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0013' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0014' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0015' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0016' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0017' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0018' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0019' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0020' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0021' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0022' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0023' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0024' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0025' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0026' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0027' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0028' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0029' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 'APTITUD1-C-0030' AS CL_VARIABLE UNION ALL
				-- SECCION 4
				SELECT 4 AS CL_SECCION, 'APTITUD1-D-0001' AS CL_VARIABLE UNION ALL
				SELECT 4 AS CL_SECCION, 'APTITUD1-D-0002' AS CL_VARIABLE UNION ALL
				SELECT 4 AS CL_SECCION, 'APTITUD1-D-0003' AS CL_VARIABLE UNION ALL
				SELECT 4 AS CL_SECCION, 'APTITUD1-D-0004' AS CL_VARIABLE UNION ALL
				SELECT 4 AS CL_SECCION, 'APTITUD1-D-0005' AS CL_VARIABLE UNION ALL
				SELECT 4 AS CL_SECCION, 'APTITUD1-D-0006' AS CL_VARIABLE UNION ALL
				SELECT 4 AS CL_SECCION, 'APTITUD1-D-0007' AS CL_VARIABLE UNION ALL
				SELECT 4 AS CL_SECCION, 'APTITUD1-D-0008' AS CL_VARIABLE UNION ALL
				SELECT 4 AS CL_SECCION, 'APTITUD1-D-0009' AS CL_VARIABLE UNION ALL
				SELECT 4 AS CL_SECCION, 'APTITUD1-D-0010' AS CL_VARIABLE UNION ALL
				SELECT 4 AS CL_SECCION, 'APTITUD1-D-0011' AS CL_VARIABLE UNION ALL
				SELECT 4 AS CL_SECCION, 'APTITUD1-D-0012' AS CL_VARIABLE UNION ALL
				SELECT 4 AS CL_SECCION, 'APTITUD1-D-0013' AS CL_VARIABLE UNION ALL
				SELECT 4 AS CL_SECCION, 'APTITUD1-D-0014' AS CL_VARIABLE UNION ALL
				SELECT 4 AS CL_SECCION, 'APTITUD1-D-0015' AS CL_VARIABLE UNION ALL
				SELECT 4 AS CL_SECCION, 'APTITUD1-D-0016' AS CL_VARIABLE UNION ALL
				SELECT 4 AS CL_SECCION, 'APTITUD1-D-0017' AS CL_VARIABLE UNION ALL
				SELECT 4 AS CL_SECCION, 'APTITUD1-D-0018' AS CL_VARIABLE UNION ALL
				-- SECCION 5
				SELECT 5 AS CL_SECCION, 'APTITUD1-E-0001' AS CL_VARIABLE UNION ALL
				SELECT 5 AS CL_SECCION, 'APTITUD1-E-0002' AS CL_VARIABLE UNION ALL
				SELECT 5 AS CL_SECCION, 'APTITUD1-E-0003' AS CL_VARIABLE UNION ALL
				SELECT 5 AS CL_SECCION, 'APTITUD1-E-0004' AS CL_VARIABLE UNION ALL
				SELECT 5 AS CL_SECCION, 'APTITUD1-E-0005' AS CL_VARIABLE UNION ALL
				SELECT 5 AS CL_SECCION, 'APTITUD1-E-0006' AS CL_VARIABLE UNION ALL
				SELECT 5 AS CL_SECCION, 'APTITUD1-E-0007' AS CL_VARIABLE UNION ALL
				SELECT 5 AS CL_SECCION, 'APTITUD1-E-0008' AS CL_VARIABLE UNION ALL
				SELECT 5 AS CL_SECCION, 'APTITUD1-E-0009' AS CL_VARIABLE UNION ALL
				SELECT 5 AS CL_SECCION, 'APTITUD1-E-0010' AS CL_VARIABLE UNION ALL
				SELECT 5 AS CL_SECCION, 'APTITUD1-E-0011' AS CL_VARIABLE UNION ALL
				SELECT 5 AS CL_SECCION, 'APTITUD1-E-0012' AS CL_VARIABLE UNION ALL
				-- SECCION 6
				SELECT 6 AS CL_SECCION, 'APTITUD1-F-0001' AS CL_VARIABLE UNION ALL
				SELECT 6 AS CL_SECCION, 'APTITUD1-F-0002' AS CL_VARIABLE UNION ALL
				SELECT 6 AS CL_SECCION, 'APTITUD1-F-0003' AS CL_VARIABLE UNION ALL
				SELECT 6 AS CL_SECCION, 'APTITUD1-F-0004' AS CL_VARIABLE UNION ALL
				SELECT 6 AS CL_SECCION, 'APTITUD1-F-0005' AS CL_VARIABLE UNION ALL
				SELECT 6 AS CL_SECCION, 'APTITUD1-F-0006' AS CL_VARIABLE UNION ALL
				SELECT 6 AS CL_SECCION, 'APTITUD1-F-0007' AS CL_VARIABLE UNION ALL
				SELECT 6 AS CL_SECCION, 'APTITUD1-F-0008' AS CL_VARIABLE UNION ALL
				SELECT 6 AS CL_SECCION, 'APTITUD1-F-0009' AS CL_VARIABLE UNION ALL
				SELECT 6 AS CL_SECCION, 'APTITUD1-F-0010' AS CL_VARIABLE UNION ALL
				SELECT 6 AS CL_SECCION, 'APTITUD1-F-0011' AS CL_VARIABLE UNION ALL
				SELECT 6 AS CL_SECCION, 'APTITUD1-F-0012' AS CL_VARIABLE UNION ALL
				SELECT 6 AS CL_SECCION, 'APTITUD1-F-0013' AS CL_VARIABLE UNION ALL
				SELECT 6 AS CL_SECCION, 'APTITUD1-F-0014' AS CL_VARIABLE UNION ALL
				SELECT 6 AS CL_SECCION, 'APTITUD1-F-0015' AS CL_VARIABLE UNION ALL
				SELECT 6 AS CL_SECCION, 'APTITUD1-F-0016' AS CL_VARIABLE UNION ALL
				SELECT 6 AS CL_SECCION, 'APTITUD1-F-0017' AS CL_VARIABLE UNION ALL
				SELECT 6 AS CL_SECCION, 'APTITUD1-F-0018' AS CL_VARIABLE UNION ALL
				SELECT 6 AS CL_SECCION, 'APTITUD1-F-0019' AS CL_VARIABLE UNION ALL
				SELECT 6 AS CL_SECCION, 'APTITUD1-F-0020' AS CL_VARIABLE UNION ALL
				-- SECCION 7
				SELECT 7 AS CL_SECCION, 'APTITUD1-G-0001' AS CL_VARIABLE UNION ALL
				SELECT 7 AS CL_SECCION, 'APTITUD1-G-0002' AS CL_VARIABLE UNION ALL
				SELECT 7 AS CL_SECCION, 'APTITUD1-G-0003' AS CL_VARIABLE UNION ALL
				SELECT 7 AS CL_SECCION, 'APTITUD1-G-0004' AS CL_VARIABLE UNION ALL
				SELECT 7 AS CL_SECCION, 'APTITUD1-G-0005' AS CL_VARIABLE UNION ALL
				SELECT 7 AS CL_SECCION, 'APTITUD1-G-0006' AS CL_VARIABLE UNION ALL
				SELECT 7 AS CL_SECCION, 'APTITUD1-G-0007' AS CL_VARIABLE UNION ALL
				SELECT 7 AS CL_SECCION, 'APTITUD1-G-0008' AS CL_VARIABLE UNION ALL
				SELECT 7 AS CL_SECCION, 'APTITUD1-G-0009' AS CL_VARIABLE UNION ALL
				SELECT 7 AS CL_SECCION, 'APTITUD1-G-0010' AS CL_VARIABLE UNION ALL
				SELECT 7 AS CL_SECCION, 'APTITUD1-G-0011' AS CL_VARIABLE UNION ALL
				SELECT 7 AS CL_SECCION, 'APTITUD1-G-0012' AS CL_VARIABLE UNION ALL
				SELECT 7 AS CL_SECCION, 'APTITUD1-G-0013' AS CL_VARIABLE UNION ALL
				SELECT 7 AS CL_SECCION, 'APTITUD1-G-0014' AS CL_VARIABLE UNION ALL
				SELECT 7 AS CL_SECCION, 'APTITUD1-G-0015' AS CL_VARIABLE UNION ALL
				SELECT 7 AS CL_SECCION, 'APTITUD1-G-0016' AS CL_VARIABLE UNION ALL
				SELECT 7 AS CL_SECCION, 'APTITUD1-G-0017' AS CL_VARIABLE UNION ALL
				SELECT 7 AS CL_SECCION, 'APTITUD1-G-0018' AS CL_VARIABLE UNION ALL
				SELECT 7 AS CL_SECCION, 'APTITUD1-G-0019' AS CL_VARIABLE UNION ALL
				SELECT 7 AS CL_SECCION, 'APTITUD1-G-0020' AS CL_VARIABLE UNION ALL
				-- SECCION 8
				SELECT 8 AS CL_SECCION, 'APTITUD1-H-0001' AS CL_VARIABLE UNION ALL
				SELECT 8 AS CL_SECCION, 'APTITUD1-H-0002' AS CL_VARIABLE UNION ALL
				SELECT 8 AS CL_SECCION, 'APTITUD1-H-0003' AS CL_VARIABLE UNION ALL
				SELECT 8 AS CL_SECCION, 'APTITUD1-H-0004' AS CL_VARIABLE UNION ALL
				SELECT 8 AS CL_SECCION, 'APTITUD1-H-0005' AS CL_VARIABLE UNION ALL
				SELECT 8 AS CL_SECCION, 'APTITUD1-H-0006' AS CL_VARIABLE UNION ALL
				SELECT 8 AS CL_SECCION, 'APTITUD1-H-0007' AS CL_VARIABLE UNION ALL
				SELECT 8 AS CL_SECCION, 'APTITUD1-H-0008' AS CL_VARIABLE UNION ALL
				SELECT 8 AS CL_SECCION, 'APTITUD1-H-0009' AS CL_VARIABLE UNION ALL
				SELECT 8 AS CL_SECCION, 'APTITUD1-H-0010' AS CL_VARIABLE UNION ALL
				SELECT 8 AS CL_SECCION, 'APTITUD1-H-0011' AS CL_VARIABLE UNION ALL
				SELECT 8 AS CL_SECCION, 'APTITUD1-H-0012' AS CL_VARIABLE UNION ALL
				SELECT 8 AS CL_SECCION, 'APTITUD1-H-0013' AS CL_VARIABLE UNION ALL
				SELECT 8 AS CL_SECCION, 'APTITUD1-H-0014' AS CL_VARIABLE UNION ALL
				SELECT 8 AS CL_SECCION, 'APTITUD1-H-0015' AS CL_VARIABLE UNION ALL
				SELECT 8 AS CL_SECCION, 'APTITUD1-H-0016' AS CL_VARIABLE UNION ALL
				SELECT 8 AS CL_SECCION, 'APTITUD1-H-0017' AS CL_VARIABLE UNION ALL
				-- SECCION 9
				SELECT 9 AS CL_SECCION, 'APTITUD1-I-0001' AS CL_VARIABLE UNION ALL
				SELECT 9 AS CL_SECCION, 'APTITUD1-I-0002' AS CL_VARIABLE UNION ALL
				SELECT 9 AS CL_SECCION, 'APTITUD1-I-0003' AS CL_VARIABLE UNION ALL
				SELECT 9 AS CL_SECCION, 'APTITUD1-I-0004' AS CL_VARIABLE UNION ALL
				SELECT 9 AS CL_SECCION, 'APTITUD1-I-0005' AS CL_VARIABLE UNION ALL
				SELECT 9 AS CL_SECCION, 'APTITUD1-I-0006' AS CL_VARIABLE UNION ALL
				SELECT 9 AS CL_SECCION, 'APTITUD1-I-0007' AS CL_VARIABLE UNION ALL
				SELECT 9 AS CL_SECCION, 'APTITUD1-I-0008' AS CL_VARIABLE UNION ALL
				SELECT 9 AS CL_SECCION, 'APTITUD1-I-0009' AS CL_VARIABLE UNION ALL
				SELECT 9 AS CL_SECCION, 'APTITUD1-I-0010' AS CL_VARIABLE UNION ALL
				SELECT 9 AS CL_SECCION, 'APTITUD1-I-0011' AS CL_VARIABLE UNION ALL
				SELECT 9 AS CL_SECCION, 'APTITUD1-I-0012' AS CL_VARIABLE UNION ALL
				SELECT 9 AS CL_SECCION, 'APTITUD1-I-0013' AS CL_VARIABLE UNION ALL
				SELECT 9 AS CL_SECCION, 'APTITUD1-I-0014' AS CL_VARIABLE UNION ALL
				SELECT 9 AS CL_SECCION, 'APTITUD1-I-0015' AS CL_VARIABLE UNION ALL
				SELECT 9 AS CL_SECCION, 'APTITUD1-I-0016' AS CL_VARIABLE UNION ALL
				SELECT 9 AS CL_SECCION, 'APTITUD1-I-0017' AS CL_VARIABLE UNION ALL
				SELECT 9 AS CL_SECCION, 'APTITUD1-I-0018' AS CL_VARIABLE UNION ALL
				-- SECCION 10
				SELECT 10, 'APTITUD1-J-0001' AS CL_VARIABLE UNION ALL
				SELECT 10, 'APTITUD1-J-0002' AS CL_VARIABLE UNION ALL
				SELECT 10, 'APTITUD1-J-0003' AS CL_VARIABLE UNION ALL
				SELECT 10, 'APTITUD1-J-0004' AS CL_VARIABLE UNION ALL
				SELECT 10, 'APTITUD1-J-0005' AS CL_VARIABLE UNION ALL
				SELECT 10, 'APTITUD1-J-0006' AS CL_VARIABLE UNION ALL
				SELECT 10, 'APTITUD1-J-0007' AS CL_VARIABLE UNION ALL
				SELECT 10, 'APTITUD1-J-0008' AS CL_VARIABLE UNION ALL
				SELECT 10, 'APTITUD1-J-0009' AS CL_VARIABLE UNION ALL
				SELECT 10, 'APTITUD1-J-0010' AS CL_VARIABLE UNION ALL
				SELECT 10, 'APTITUD1-J-0011' AS CL_VARIABLE
			), T_SECCION AS (
				SELECT 1 AS CL_SECCION, 1 AS NO_FACTOR, 'APTITUD1-RES-0001' AS CL_VARIABLE UNION ALL
				SELECT 2 AS CL_SECCION, 2 AS NO_FACTOR, 'APTITUD1-RES-0002' AS CL_VARIABLE UNION ALL
				SELECT 3 AS CL_SECCION, 1 AS NO_FACTOR, 'APTITUD1-RES-0003' AS CL_VARIABLE UNION ALL
				SELECT 4 AS CL_SECCION, 1 AS NO_FACTOR, 'APTITUD1-RES-0004' AS CL_VARIABLE UNION ALL
				SELECT 5 AS CL_SECCION, 2 AS NO_FACTOR, 'APTITUD1-RES-0005' AS CL_VARIABLE UNION ALL
				SELECT 6 AS CL_SECCION, 1 AS NO_FACTOR, 'APTITUD1-RES-0006' AS CL_VARIABLE UNION ALL
				SELECT 7 AS CL_SECCION, 1 AS NO_FACTOR, 'APTITUD1-RES-0007' AS CL_VARIABLE UNION ALL
				SELECT 8 AS CL_SECCION, 1 AS NO_FACTOR, 'APTITUD1-RES-0008' AS CL_VARIABLE UNION ALL
				SELECT 9 AS CL_SECCION, 1 AS NO_FACTOR, 'APTITUD1-RES-0009' AS CL_VARIABLE UNION ALL
				SELECT 10 AS CL_SECCION, 2 AS NO_FACTOR, 'APTITUD1-RES-0010' AS CL_VARIABLE
			), T_SUMA_RESPUESTAS AS (
				SELECT TV.CL_SECCION,  SUM(KR.NO_VALOR) AS NO_SUMA_RESPUESTA
				FROM IDP.C_VARIABLE CV
					INNER JOIN T_VARIABLES TV
						ON TV.CL_VARIABLE = CV.CL_VARIABLE
					INNER JOIN IDP.K_RESULTADO KR
						ON KR.ID_VARIABLE = CV.ID_VARIABLE
						AND KR.ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
				GROUP BY TV.CL_SECCION
			), T_RESPUESTAS_FACTOR AS (
				SELECT TS.CL_SECCION, TSR.NO_SUMA_RESPUESTA * TS.NO_FACTOR AS NO_RESULTADO, CV.ID_VARIABLE
				FROM T_SUMA_RESPUESTAS TSR
					INNER JOIN T_SECCION TS
						ON TSR.CL_SECCION = TS.CL_SECCION
					INNER JOIN IDP.C_VARIABLE CV
						ON CV.CL_VARIABLE = TS.CL_VARIABLE
			)
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) --SELECT 2 AS CL_TIPO_RESULTADO, 97 AS ID_VARIABLE, SUM(NO_VALOR), ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE BETWEEN 107 AND 122 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO GROUP BY ID_CUESTIONARIO
			SELECT 2 AS CL_TIPO_RESULTADO, ID_VARIABLE, NO_RESULTADO, @PIN_ID_CUESTIONARIO, @V_FE_ACTUAL, @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM T_RESPUESTAS_FACTOR




			/*
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 97 AS ID_VARIABLE, SUM(NO_VALOR), ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE BETWEEN 107 AND 122 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO GROUP BY ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 98 AS ID_VARIABLE, SUM(NO_VALOR) * 2, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE BETWEEN 123 AND 133 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO GROUP BY ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 99 AS ID_VARIABLE, SUM(NO_VALOR), ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE BETWEEN 134 AND 163 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO GROUP BY ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 100 AS ID_VARIABLE, SUM(NO_VALOR), ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE BETWEEN 164 AND 181 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO GROUP BY ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 101 AS ID_VARIABLE, SUM(NO_VALOR) * 2, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE BETWEEN 182 AND 193 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO GROUP BY ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 102 AS ID_VARIABLE, SUM(NO_VALOR), ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE BETWEEN 194 AND 213 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO GROUP BY ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 103 AS ID_VARIABLE, SUM(NO_VALOR), ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE BETWEEN 214 AND 233 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO GROUP BY ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 104 AS ID_VARIABLE, SUM(NO_VALOR), ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE BETWEEN 234 AND 250 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO GROUP BY ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 105 AS ID_VARIABLE, SUM(NO_VALOR), ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE BETWEEN 251 AND 268 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO GROUP BY ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 106 AS ID_VARIABLE, SUM(NO_VALOR) * 2, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE IN (269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279) AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO GROUP BY ID_CUESTIONARIO
			*/
		END

		EXEC [IDP].[SPE_INSERTA_REPORTE_APTITUD1] @PIN_XML_RESULTADOS OUT, @PIN_ID_CUESTIONARIO, @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA


		--SE DEVUELVE LA VARIABLE DE RETORNO INDICANDO QUE TODO SE REALIZO CORRECTAMENTE
		SET @XML_RESULTADO = DBO.F_ERROR_CREAR_ENCABEZADO( @@ROWCOUNT, 1, 'SUCCESSFUL')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'Proceso exitoso', 'ES')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'Successful Process', 'EN')
		--SI SE GENERO UNA TRANSACCION EN ESTE BLOQUE LA TERMINARA
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			COMMIT
	END TRY
	BEGIN CATCH
		--SI OCURRIO UN ERROR Y SE INICIO UNA TRANSACCION ENE ESTE BLOQUE SE CANCELARA LA TRANSACCION
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			ROLLBACK
		--SE INDICA EN LA VARIABLE DE RETORNO QUE OCURRIO UN ERROR
		--SET @POUT_CLAVE_RETORNO = 0
		--SE INSERTA EL ERROR EN LA TABLA
		DECLARE @ERROR_CLAVE INT  = ERROR_NUMBER()
		DECLARE @ERROR_MENSAJE NVARCHAR(250)  = ERROR_MESSAGE()
		
		SET @XML_RESULTADO = DBO.F_ERROR_CREAR_ENCABEZADO( @@ROWCOUNT, @ERROR_CLAVE, 'ERROR')
		SET @XML_RESULTADO = DBO.F_ERROR_MENSAJES(@ERROR_CLAVE,@ERROR_MENSAJE)
		SET @XML_RESULTADO = DBO.F_ERROR_MENSAJES(@ERROR_CLAVE,@ERROR_MENSAJE)			
	END CATCH
END


