
-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2016
-- Author: Gabriel Vázquez Torres
-- CREATE date: 17/02/2016
-- Description: Obtiene los datos de la tabla IDP.C_FACTOR
-- =============================================
CREATE PROCEDURE [IDP].[SPE_OBTIENE_C_FACTOR]
	 @PIN_ID_FACTOR AS int
	,@PIN_CL_FACTOR as nvarchar(40)
	,@PIN_NB_FACTOR as nvarchar(200)
	,@PIN_DS_FACTOR as nvarchar(2000)
	,@PIN_ID_VARIABLE as int
	,@PIN_NB_ABREVIATURA nvarchar(100)

AS

	SELECT [ID_FACTOR]
		  ,[CL_FACTOR]
		  ,[NB_FACTOR]
		  ,[DS_FACTOR]
		  ,[ID_VARIABLE]
		  ,[NB_ABREVIATURA]
	  FROM [IDP].[C_FACTOR]
	  WHERE
			((@PIN_ID_FACTOR IS NULL OR (@PIN_ID_FACTOR IS NOT NULL AND ID_FACTOR = @PIN_ID_FACTOR)) AND
			(@PIN_CL_FACTOR IS NULL OR (@PIN_CL_FACTOR IS NOT NULL AND CL_FACTOR = @PIN_CL_FACTOR)) AND
			(@PIN_NB_FACTOR IS NULL OR (@PIN_NB_FACTOR IS NOT NULL AND NB_FACTOR = @PIN_NB_FACTOR)) AND
			(@PIN_DS_FACTOR IS NULL OR (@PIN_DS_FACTOR IS NOT NULL AND DS_FACTOR = @PIN_DS_FACTOR)) AND
			(@PIN_ID_VARIABLE IS NULL OR (@PIN_ID_VARIABLE IS NOT NULL AND ID_VARIABLE = @PIN_ID_VARIABLE)) AND
			(@PIN_NB_ABREVIATURA IS NULL OR (@PIN_NB_ABREVIATURA IS NOT NULL AND NB_ABREVIATURA = @PIN_NB_ABREVIATURA)))




