-- =============================================
-- Proyecto: Sigein 5.0
-- Copyright (c) - Acrux - 2016
-- Author: Daniela Sanchez
-- CREATE date: 28/01/2016
-- Description: Inserta variables tipo 3 de prueba LABORAL1
-- =============================================
CREATE PROCEDURE [IDP].[SPE_INSERTA_REPORTE_LABORAL1]
	@XML_RESULTADO XML = '' OUT 
	,@PIN_ID_CUESTIONARIO AS INT = NULL
	,@PIN_CL_USUARIO_APP_CREA AS nvarchar(50)
    ,@PIN_NB_PROGRAMA_CREA AS nvarchar(50)
AS
BEGIN
DECLARE @V_EXIST_TRAN BIT = 0
			
    	BEGIN TRY
		--SE VERIFICA SI EXISTE UNA TRANSACCION EN EJECUCION
		IF (@@TRANCOUNT = 0) 
		BEGIN
			--EN CASO DE QUE NO SE INICIALIZA LA TRANSACCION
			BEGIN TRANSACTION
			--SE EDITA LA VARIABLE QUE INDICA QUE SE INICIO LA TRANSACCION EN ESTE BLOQUE PARA CANCELARLA SI ES NECESARIO
			SET @V_EXIST_TRAN = 1
		END	
		--SE VERIFICA SI SE INSERTA EL REGISTRO O SE ACTUALIZARA SEGUN LA VARIABLE DE TIPO DE TRANSACCION  QUE RECIBE EL SP
		IF @PIN_ID_CUESTIONARIO IS NOT NULL
			BEGIN 

	DECLARE @T_VALORES_DISC TABLE (
	CL_VARIABLE NVARCHAR(50)
	, NO_VALOR_PARAMETRO INT
	, CL_TIPO_DISC NVARCHAR(1)
	, CL_TIPO_ML NVARCHAR(1)
)

DECLARE @T_LIMITES TABLE (
	NO_LIMITE_INFERIOR INT
	, NO_LIMITE_SUPERIOR INT
	, NO_VALOR_1 DECIMAL(13,3)
	, NO_VALOR_2 DECIMAL(13,3)
	, CL_TIPO_DISC NVARCHAR(1)
	, CL_SITUACION NVARCHAR(20)
)

DECLARE @T_RESULTADO_DISC TABLE (
	CL_TIPO_DISC NVARCHAR(1)
	, CL_TIPO_ML NVARCHAR(1)
	, NO_VALOR_RESULTADO INT
)

DECLARE @T_RESULTADO TABLE (
 CL_VARIABLE_REPORTE NVARCHAR(30)
	,CL_VARIABLE_GRAFICO NVARCHAR(30)
	,CL_TIPO_DISC NVARCHAR (1)
	,CL_SITUACION NVARCHAR(20)
	,NO_VALOR_2 DECIMAL(13,3) 
	, NO_VALOR_RESULTADO INT
	
)

INSERT INTO @T_VALORES_DISC
SELECT 'LABORAL1-RES-A01' AS CL_VARIABLE, 0 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-A02' AS CL_VARIABLE, 4 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-B01' AS CL_VARIABLE, 1 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-B02' AS CL_VARIABLE, 0 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-C01' AS CL_VARIABLE, 3 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-C02' AS CL_VARIABLE, 3 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-D01' AS CL_VARIABLE, 2 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-D02' AS CL_VARIABLE, 0 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-E01' AS CL_VARIABLE, 2 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-E02' AS CL_VARIABLE, 2 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-F01' AS CL_VARIABLE, 0 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-F02' AS CL_VARIABLE, 4 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-G01' AS CL_VARIABLE, 0 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-G02' AS CL_VARIABLE, 1 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-H01' AS CL_VARIABLE, 4 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-H02' AS CL_VARIABLE, 4 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-I01' AS CL_VARIABLE, 0 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-I02' AS CL_VARIABLE, 3 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-J01' AS CL_VARIABLE, 4 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-J02' AS CL_VARIABLE, 4 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-K01' AS CL_VARIABLE, 1 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-K02' AS CL_VARIABLE, 1 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-L01' AS CL_VARIABLE, 4 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-L02' AS CL_VARIABLE, 4 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-M01' AS CL_VARIABLE, 3 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-M02' AS CL_VARIABLE, 3 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-N01' AS CL_VARIABLE, 2 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-N02' AS CL_VARIABLE, 2 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-O01' AS CL_VARIABLE, 1 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-O02' AS CL_VARIABLE, 0 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-P01' AS CL_VARIABLE, 2 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-P02' AS CL_VARIABLE, 2 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-Q01' AS CL_VARIABLE, 3 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-Q02' AS CL_VARIABLE, 3 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-R01' AS CL_VARIABLE, 4 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-R02' AS CL_VARIABLE, 4 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-S01' AS CL_VARIABLE, 1 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-S02' AS CL_VARIABLE, 1 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-T01' AS CL_VARIABLE, 3 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-T02' AS CL_VARIABLE, 3 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-U01' AS CL_VARIABLE, 4 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-U02' AS CL_VARIABLE, 4 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-V01' AS CL_VARIABLE, 3 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-V02' AS CL_VARIABLE, 3 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-W01' AS CL_VARIABLE, 2 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-W02' AS CL_VARIABLE, 2 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-X01' AS CL_VARIABLE, 1 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-X02' AS CL_VARIABLE, 1 AS NO_VALOR, 'D' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-A01' AS CL_VARIABLE, 1 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-A02' AS CL_VARIABLE, 0 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-B01' AS CL_VARIABLE, 2 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-B02' AS CL_VARIABLE, 2 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-C01' AS CL_VARIABLE, 4 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-C02' AS CL_VARIABLE, 4 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-D01' AS CL_VARIABLE, 3 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-D02' AS CL_VARIABLE, 3 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-E01' AS CL_VARIABLE, 4 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-E02' AS CL_VARIABLE, 4 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-F01' AS CL_VARIABLE, 0 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-F02' AS CL_VARIABLE, 0 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-G01' AS CL_VARIABLE, 4 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-G02' AS CL_VARIABLE, 4 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-H01' AS CL_VARIABLE, 1 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-H02' AS CL_VARIABLE, 0 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-I01' AS CL_VARIABLE, 0 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-I02' AS CL_VARIABLE, 4 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-J01' AS CL_VARIABLE, 0 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-J02' AS CL_VARIABLE, 3 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-K01' AS CL_VARIABLE, 0 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-K02' AS CL_VARIABLE, 2 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-L01' AS CL_VARIABLE, 1 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-L02' AS CL_VARIABLE, 0 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-M01' AS CL_VARIABLE, 4 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-M02' AS CL_VARIABLE, 4 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-N01' AS CL_VARIABLE, 3 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-N02' AS CL_VARIABLE, 3 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-O01' AS CL_VARIABLE, 2 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-O02' AS CL_VARIABLE, 0 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-P01' AS CL_VARIABLE, 4 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-P02' AS CL_VARIABLE, 4 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-Q01' AS CL_VARIABLE, 1 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-Q02' AS CL_VARIABLE, 1 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-R01' AS CL_VARIABLE, 0 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-R02' AS CL_VARIABLE, 2 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-S01' AS CL_VARIABLE, 0 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-S02' AS CL_VARIABLE, 3 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-T01' AS CL_VARIABLE, 4 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-T02' AS CL_VARIABLE, 4 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-U01' AS CL_VARIABLE, 1 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-U02' AS CL_VARIABLE, 1 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-V01' AS CL_VARIABLE, 4 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-V02' AS CL_VARIABLE, 4 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-W01' AS CL_VARIABLE, 0 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-W02' AS CL_VARIABLE, 3 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-X01' AS CL_VARIABLE, 0 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-X02' AS CL_VARIABLE, 2 AS NO_VALOR, 'I' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-A01' AS CL_VARIABLE, 2 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-A02' AS CL_VARIABLE, 2 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-B01' AS CL_VARIABLE, 3 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-B02' AS CL_VARIABLE, 3 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-C01' AS CL_VARIABLE, 0 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-C02' AS CL_VARIABLE, 1 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-D01' AS CL_VARIABLE, 4 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-D02' AS CL_VARIABLE, 0 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-E01' AS CL_VARIABLE, 3 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-E02' AS CL_VARIABLE, 0 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-F01' AS CL_VARIABLE, 1 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-F02' AS CL_VARIABLE, 0 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-G01' AS CL_VARIABLE, 3 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-G02' AS CL_VARIABLE, 3 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-H01' AS CL_VARIABLE, 0 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-H02' AS CL_VARIABLE, 2 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-I01' AS CL_VARIABLE, 1 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-I02' AS CL_VARIABLE, 1 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-J01' AS CL_VARIABLE, 2 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-J02' AS CL_VARIABLE, 2 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-K01' AS CL_VARIABLE, 3 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-K02' AS CL_VARIABLE, 3 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-L01' AS CL_VARIABLE, 2 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-L02' AS CL_VARIABLE, 0 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-M01' AS CL_VARIABLE, 1 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-M02' AS CL_VARIABLE, 0 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-N01' AS CL_VARIABLE, 4 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-N02' AS CL_VARIABLE, 4 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-O01' AS CL_VARIABLE, 0 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-O02' AS CL_VARIABLE, 3 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-P01' AS CL_VARIABLE, 0 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-P02' AS CL_VARIABLE, 3 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-Q01' AS CL_VARIABLE, 2 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-Q02' AS CL_VARIABLE, 2 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-R01' AS CL_VARIABLE, 2 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-R02' AS CL_VARIABLE, 1 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-S01' AS CL_VARIABLE, 4 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-S02' AS CL_VARIABLE, 4 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-T01' AS CL_VARIABLE, 1 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-T02' AS CL_VARIABLE, 1 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-U01' AS CL_VARIABLE, 2 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-U02' AS CL_VARIABLE, 2 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-V01' AS CL_VARIABLE, 0 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-V02' AS CL_VARIABLE, 1 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-W01' AS CL_VARIABLE, 4 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-W02' AS CL_VARIABLE, 4 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-X01' AS CL_VARIABLE, 3 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-X02' AS CL_VARIABLE, 3 AS NO_VALOR, 'S' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-A01' AS CL_VARIABLE, 3 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-A02' AS CL_VARIABLE, 3 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-B01' AS CL_VARIABLE, 0 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-B02' AS CL_VARIABLE, 4 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-C01' AS CL_VARIABLE, 2 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-C02' AS CL_VARIABLE, 2 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-D01' AS CL_VARIABLE, 1 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-D02' AS CL_VARIABLE, 1 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-E01' AS CL_VARIABLE, 0 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-E02' AS CL_VARIABLE, 1 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-F01' AS CL_VARIABLE, 3 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-F02' AS CL_VARIABLE, 3 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-G01' AS CL_VARIABLE, 2 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-G02' AS CL_VARIABLE, 0 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-H01' AS CL_VARIABLE, 0 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-H02' AS CL_VARIABLE, 3 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-I01' AS CL_VARIABLE, 2 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-I02' AS CL_VARIABLE, 2 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-J01' AS CL_VARIABLE, 1 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-J02' AS CL_VARIABLE, 0 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-K01' AS CL_VARIABLE, 0 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-K02' AS CL_VARIABLE, 4 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-L01' AS CL_VARIABLE, 0 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-L02' AS CL_VARIABLE, 3 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-M01' AS CL_VARIABLE, 0 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-M02' AS CL_VARIABLE, 2 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-N01' AS CL_VARIABLE, 1 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-N02' AS CL_VARIABLE, 0 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-O01' AS CL_VARIABLE, 0 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-O02' AS CL_VARIABLE, 4 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-P01' AS CL_VARIABLE, 1 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-P02' AS CL_VARIABLE, 0 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-Q01' AS CL_VARIABLE, 4 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-Q02' AS CL_VARIABLE, 0 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-R01' AS CL_VARIABLE, 3 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-R02' AS CL_VARIABLE, 3 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-S01' AS CL_VARIABLE, 2 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-S02' AS CL_VARIABLE, 0 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-T01' AS CL_VARIABLE, 0 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-T02' AS CL_VARIABLE, 2 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-U01' AS CL_VARIABLE, 0 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-U02' AS CL_VARIABLE, 3 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-V01' AS CL_VARIABLE, 2 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-V02' AS CL_VARIABLE, 0 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-W01' AS CL_VARIABLE, 1 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-W02' AS CL_VARIABLE, 0 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-X01' AS CL_VARIABLE, 4 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'M' AS CL_TIPO_ML UNION ALL 
SELECT 'LABORAL1-RES-X02' AS CL_VARIABLE, 4 AS NO_VALOR, 'C' AS CL_TIPO_DISC, 'L' AS CL_TIPO_ML

INSERT INTO @T_LIMITES
SELECT -18 AS NO_LIMITE_INFERIOR, -16 AS NO_LIMITE_SUPERIOR, -21 AS NO_VALOR_1, 2.5 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -15 AS NO_LIMITE_INFERIOR, -15 AS NO_LIMITE_SUPERIOR, -17.9 AS NO_VALOR_1, 5 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -14 AS NO_LIMITE_INFERIOR, -14 AS NO_LIMITE_SUPERIOR, -14.9 AS NO_VALOR_1, 7.5 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -13 AS NO_LIMITE_INFERIOR, -13 AS NO_LIMITE_SUPERIOR, -13.9 AS NO_VALOR_1, 12 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -12 AS NO_LIMITE_INFERIOR, -12 AS NO_LIMITE_SUPERIOR, -12.9 AS NO_VALOR_1, 15 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -11 AS NO_LIMITE_INFERIOR, -11 AS NO_LIMITE_SUPERIOR, -11.9 AS NO_VALOR_1, 17 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -10 AS NO_LIMITE_INFERIOR, -10 AS NO_LIMITE_SUPERIOR, -10.9 AS NO_VALOR_1, 22 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -9 AS NO_LIMITE_INFERIOR, -9 AS NO_LIMITE_SUPERIOR, -9.9 AS NO_VALOR_1, 24 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -8 AS NO_LIMITE_INFERIOR, -8 AS NO_LIMITE_SUPERIOR, -8.9 AS NO_VALOR_1, 26 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -7 AS NO_LIMITE_INFERIOR, -7 AS NO_LIMITE_SUPERIOR, -7.9 AS NO_VALOR_1, 28 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -6 AS NO_LIMITE_INFERIOR, -6 AS NO_LIMITE_SUPERIOR, -6.9 AS NO_VALOR_1, 33 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -5 AS NO_LIMITE_INFERIOR, -5 AS NO_LIMITE_SUPERIOR, -5.9 AS NO_VALOR_1, 35 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -4 AS NO_LIMITE_INFERIOR, -4 AS NO_LIMITE_SUPERIOR, -4.9 AS NO_VALOR_1, 37 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -3 AS NO_LIMITE_INFERIOR, -3 AS NO_LIMITE_SUPERIOR, -3.9 AS NO_VALOR_1, 41 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -2 AS NO_LIMITE_INFERIOR, -2 AS NO_LIMITE_SUPERIOR, -2.9 AS NO_VALOR_1, 45 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -1 AS NO_LIMITE_INFERIOR, -1 AS NO_LIMITE_SUPERIOR, 1.9 AS NO_VALOR_1, 47 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 0 AS NO_LIMITE_INFERIOR, 0 AS NO_LIMITE_SUPERIOR, 0.9 AS NO_VALOR_1, 48 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 1 AS NO_LIMITE_INFERIOR, 1 AS NO_LIMITE_SUPERIOR, 1.9 AS NO_VALOR_1, 52 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 2 AS NO_LIMITE_INFERIOR, 2 AS NO_LIMITE_SUPERIOR, 2.9 AS NO_VALOR_1, 56 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 3 AS NO_LIMITE_INFERIOR, 3 AS NO_LIMITE_SUPERIOR, 3.9 AS NO_VALOR_1, 58 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 4 AS NO_LIMITE_INFERIOR, 4 AS NO_LIMITE_SUPERIOR, 4.9 AS NO_VALOR_1, 60 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 5 AS NO_LIMITE_INFERIOR, 5 AS NO_LIMITE_SUPERIOR, 5.9 AS NO_VALOR_1, 62 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 6 AS NO_LIMITE_INFERIOR, 6 AS NO_LIMITE_SUPERIOR, 6.9 AS NO_VALOR_1, 65 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 7 AS NO_LIMITE_INFERIOR, 7 AS NO_LIMITE_SUPERIOR, 7.9 AS NO_VALOR_1, 68.5 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 8 AS NO_LIMITE_INFERIOR, 8 AS NO_LIMITE_SUPERIOR, 8.9 AS NO_VALOR_1, 72 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 9 AS NO_LIMITE_INFERIOR, 9 AS NO_LIMITE_SUPERIOR, 9.9 AS NO_VALOR_1, 75 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 10 AS NO_LIMITE_INFERIOR, 10 AS NO_LIMITE_SUPERIOR, 10.9 AS NO_VALOR_1, 78 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 11 AS NO_LIMITE_INFERIOR, 11 AS NO_LIMITE_SUPERIOR, 11.9 AS NO_VALOR_1, 80 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 12 AS NO_LIMITE_INFERIOR, 12 AS NO_LIMITE_SUPERIOR, 12.9 AS NO_VALOR_1, 82 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 13 AS NO_LIMITE_INFERIOR, 13 AS NO_LIMITE_SUPERIOR, 13.9 AS NO_VALOR_1, 85 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 14 AS NO_LIMITE_INFERIOR, 14 AS NO_LIMITE_SUPERIOR, 14.9 AS NO_VALOR_1, 87.5 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 15 AS NO_LIMITE_INFERIOR, 15 AS NO_LIMITE_SUPERIOR, 15.9 AS NO_VALOR_1, 92 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 16 AS NO_LIMITE_INFERIOR, 16 AS NO_LIMITE_SUPERIOR, 16.9 AS NO_VALOR_1, 95 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 17 AS NO_LIMITE_INFERIOR, 19 AS NO_LIMITE_SUPERIOR, 18.9 AS NO_VALOR_1, 96 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 20 AS NO_LIMITE_INFERIOR, 20 AS NO_LIMITE_SUPERIOR, 21.9 AS NO_VALOR_1, 98 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -11 AS NO_LIMITE_INFERIOR, -11 AS NO_LIMITE_SUPERIOR, -19 AS NO_VALOR_1, 3 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -10 AS NO_LIMITE_INFERIOR, -10 AS NO_LIMITE_SUPERIOR, -10.9 AS NO_VALOR_1, 6 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -9 AS NO_LIMITE_INFERIOR, -9 AS NO_LIMITE_SUPERIOR, -9.9 AS NO_VALOR_1, 10 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -8 AS NO_LIMITE_INFERIOR, -8 AS NO_LIMITE_SUPERIOR, -8.9 AS NO_VALOR_1, 13 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -7 AS NO_LIMITE_INFERIOR, -7 AS NO_LIMITE_SUPERIOR, -7.9 AS NO_VALOR_1, 17.5 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -6 AS NO_LIMITE_INFERIOR, -6 AS NO_LIMITE_SUPERIOR, -6.9 AS NO_VALOR_1, 23 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -5 AS NO_LIMITE_INFERIOR, -5 AS NO_LIMITE_SUPERIOR, -5.9 AS NO_VALOR_1, 27 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -4 AS NO_LIMITE_INFERIOR, -4 AS NO_LIMITE_SUPERIOR, -4.9 AS NO_VALOR_1, 32.5 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -3 AS NO_LIMITE_INFERIOR, -3 AS NO_LIMITE_SUPERIOR, -3.9 AS NO_VALOR_1, 37 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -2 AS NO_LIMITE_INFERIOR, -2 AS NO_LIMITE_SUPERIOR, -2.9 AS NO_VALOR_1, 41 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -1 AS NO_LIMITE_INFERIOR, -1 AS NO_LIMITE_SUPERIOR, -1.9 AS NO_VALOR_1, 47 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 0 AS NO_LIMITE_INFERIOR, 0 AS NO_LIMITE_SUPERIOR, 0.9 AS NO_VALOR_1, 52.5 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 1 AS NO_LIMITE_INFERIOR, 1 AS NO_LIMITE_SUPERIOR, 1.9 AS NO_VALOR_1, 57.5 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 2 AS NO_LIMITE_INFERIOR, 2 AS NO_LIMITE_SUPERIOR, 2.9 AS NO_VALOR_1, 62.5 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 3 AS NO_LIMITE_INFERIOR, 3 AS NO_LIMITE_SUPERIOR, 3.9 AS NO_VALOR_1, 67.5 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 4 AS NO_LIMITE_INFERIOR, 4 AS NO_LIMITE_SUPERIOR, 4.9 AS NO_VALOR_1, 74 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 5 AS NO_LIMITE_INFERIOR, 5 AS NO_LIMITE_SUPERIOR, 5.9 AS NO_VALOR_1, 78 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 6 AS NO_LIMITE_INFERIOR, 6 AS NO_LIMITE_SUPERIOR, 6.9 AS NO_VALOR_1, 85 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 7 AS NO_LIMITE_INFERIOR, 7 AS NO_LIMITE_SUPERIOR, 7.9 AS NO_VALOR_1, 88 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 8 AS NO_LIMITE_INFERIOR, 8 AS NO_LIMITE_SUPERIOR, 8.9 AS NO_VALOR_1, 92 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 9 AS NO_LIMITE_INFERIOR, 12 AS NO_LIMITE_SUPERIOR, 12.9 AS NO_VALOR_1, 96 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 13 AS NO_LIMITE_INFERIOR, 13 AS NO_LIMITE_SUPERIOR, 17 AS NO_VALOR_1, 98 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -15 AS NO_LIMITE_INFERIOR, -14 AS NO_LIMITE_SUPERIOR, -19 AS NO_VALOR_1, 2 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -13 AS NO_LIMITE_INFERIOR, -13 AS NO_LIMITE_SUPERIOR, -14.9 AS NO_VALOR_1, 4 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -12 AS NO_LIMITE_INFERIOR, -12 AS NO_LIMITE_SUPERIOR, -12.9 AS NO_VALOR_1, 6 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -11 AS NO_LIMITE_INFERIOR, -11 AS NO_LIMITE_SUPERIOR, -11.9 AS NO_VALOR_1, 9.5 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -10 AS NO_LIMITE_INFERIOR, -10 AS NO_LIMITE_SUPERIOR, -10.9 AS NO_VALOR_1, 13 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -9 AS NO_LIMITE_INFERIOR, -9 AS NO_LIMITE_SUPERIOR, -9.9 AS NO_VALOR_1, 18 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -8 AS NO_LIMITE_INFERIOR, -8 AS NO_LIMITE_SUPERIOR, -8.9 AS NO_VALOR_1, 23 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -7 AS NO_LIMITE_INFERIOR, -7 AS NO_LIMITE_SUPERIOR, -7.9 AS NO_VALOR_1, 27 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -6 AS NO_LIMITE_INFERIOR, -6 AS NO_LIMITE_SUPERIOR, -6.9 AS NO_VALOR_1, 32 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -5 AS NO_LIMITE_INFERIOR, -5 AS NO_LIMITE_SUPERIOR, -5.9 AS NO_VALOR_1, 35 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -4 AS NO_LIMITE_INFERIOR, -4 AS NO_LIMITE_SUPERIOR, -4.9 AS NO_VALOR_1, 37.5 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -3 AS NO_LIMITE_INFERIOR, -3 AS NO_LIMITE_SUPERIOR, -3.9 AS NO_VALOR_1, 41 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -2 AS NO_LIMITE_INFERIOR, -2 AS NO_LIMITE_SUPERIOR, -2.9 AS NO_VALOR_1, 44.5 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -1 AS NO_LIMITE_INFERIOR, -1 AS NO_LIMITE_SUPERIOR, -1.9 AS NO_VALOR_1, 48.5 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 0 AS NO_LIMITE_INFERIOR, 0 AS NO_LIMITE_SUPERIOR, 0.9 AS NO_VALOR_1, 53.5 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 1 AS NO_LIMITE_INFERIOR, 1 AS NO_LIMITE_SUPERIOR, 1.9 AS NO_VALOR_1, 57 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 2 AS NO_LIMITE_INFERIOR, 2 AS NO_LIMITE_SUPERIOR, 2.9 AS NO_VALOR_1, 62.5 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 3 AS NO_LIMITE_INFERIOR, 3 AS NO_LIMITE_SUPERIOR, 3.9 AS NO_VALOR_1, 66 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 4 AS NO_LIMITE_INFERIOR, 4 AS NO_LIMITE_SUPERIOR, 4.9 AS NO_VALOR_1, 70 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 5 AS NO_LIMITE_INFERIOR, 5 AS NO_LIMITE_SUPERIOR, 5.9 AS NO_VALOR_1, 73 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 6 AS NO_LIMITE_INFERIOR, 6 AS NO_LIMITE_SUPERIOR, 6.9 AS NO_VALOR_1, 77 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 7 AS NO_LIMITE_INFERIOR, 7 AS NO_LIMITE_SUPERIOR, 7.9 AS NO_VALOR_1, 80 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 8 AS NO_LIMITE_INFERIOR, 8 AS NO_LIMITE_SUPERIOR, 8.9 AS NO_VALOR_1, 83 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 9 AS NO_LIMITE_INFERIOR, 9 AS NO_LIMITE_SUPERIOR, 9.9 AS NO_VALOR_1, 77.5 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 10 AS NO_LIMITE_INFERIOR, 12 AS NO_LIMITE_SUPERIOR, 12.9 AS NO_VALOR_1, 92 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 13 AS NO_LIMITE_INFERIOR, 16 AS NO_LIMITE_SUPERIOR, 16.9 AS NO_VALOR_1, 95 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 17 AS NO_LIMITE_INFERIOR, 17 AS NO_LIMITE_SUPERIOR, 19 AS NO_VALOR_1, 98 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -16 AS NO_LIMITE_INFERIOR, -15 AS NO_LIMITE_SUPERIOR, -17.9 AS NO_VALOR_1, 2 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -14 AS NO_LIMITE_INFERIOR, -13 AS NO_LIMITE_SUPERIOR, -15.9 AS NO_VALOR_1, 4 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -12 AS NO_LIMITE_INFERIOR, -12 AS NO_LIMITE_SUPERIOR, -13.9 AS NO_VALOR_1, 6 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -11 AS NO_LIMITE_INFERIOR, -11 AS NO_LIMITE_SUPERIOR, -11.9 AS NO_VALOR_1, 10 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -10 AS NO_LIMITE_INFERIOR, -10 AS NO_LIMITE_SUPERIOR, -10.9 AS NO_VALOR_1, 13.5 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -9 AS NO_LIMITE_INFERIOR, -9 AS NO_LIMITE_SUPERIOR, -9.9 AS NO_VALOR_1, 17 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -8 AS NO_LIMITE_INFERIOR, -8 AS NO_LIMITE_SUPERIOR, -8.9 AS NO_VALOR_1, 21.5 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -7 AS NO_LIMITE_INFERIOR, -7 AS NO_LIMITE_SUPERIOR, -7.9 AS NO_VALOR_1, 26 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -6 AS NO_LIMITE_INFERIOR, -6 AS NO_LIMITE_SUPERIOR, -6.9 AS NO_VALOR_1, 32.5 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -5 AS NO_LIMITE_INFERIOR, -5 AS NO_LIMITE_SUPERIOR, -5.9 AS NO_VALOR_1, 35 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -4 AS NO_LIMITE_INFERIOR, -4 AS NO_LIMITE_SUPERIOR, -4.9 AS NO_VALOR_1, 42 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -3 AS NO_LIMITE_INFERIOR, -3 AS NO_LIMITE_SUPERIOR, -3.9 AS NO_VALOR_1, 46 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -2 AS NO_LIMITE_INFERIOR, -2 AS NO_LIMITE_SUPERIOR, -2.9 AS NO_VALOR_1, 52.5 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT -1 AS NO_LIMITE_INFERIOR, -1 AS NO_LIMITE_SUPERIOR, -1.9 AS NO_VALOR_1, 55.5 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 0 AS NO_LIMITE_INFERIOR, 0 AS NO_LIMITE_SUPERIOR, 0.9 AS NO_VALOR_1, 60 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 1 AS NO_LIMITE_INFERIOR, 1 AS NO_LIMITE_SUPERIOR, 1.9 AS NO_VALOR_1, 67 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 2 AS NO_LIMITE_INFERIOR, 2 AS NO_LIMITE_SUPERIOR, 2.9 AS NO_VALOR_1, 73.5 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 3 AS NO_LIMITE_INFERIOR, 3 AS NO_LIMITE_SUPERIOR, 3.9 AS NO_VALOR_1, 78 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 4 AS NO_LIMITE_INFERIOR, 4 AS NO_LIMITE_SUPERIOR, 4.9 AS NO_VALOR_1, 83 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 5 AS NO_LIMITE_INFERIOR, 5 AS NO_LIMITE_SUPERIOR, 5.9 AS NO_VALOR_1, 88 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 6 AS NO_LIMITE_INFERIOR, 6 AS NO_LIMITE_SUPERIOR, 6.9 AS NO_VALOR_1, 91 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 7 AS NO_LIMITE_INFERIOR, 7 AS NO_LIMITE_SUPERIOR, 7.9 AS NO_VALOR_1, 95 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 8 AS NO_LIMITE_INFERIOR, 10 AS NO_LIMITE_SUPERIOR, 10.9 AS NO_VALOR_1, 96 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 11 AS NO_LIMITE_INFERIOR, 12 AS NO_LIMITE_SUPERIOR, 12.9 AS NO_VALOR_1, 97 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 13 AS NO_LIMITE_INFERIOR, 13 AS NO_LIMITE_SUPERIOR, 15 AS NO_VALOR_1, 98 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION UNION ALL
SELECT 0 AS NO_LIMITE_INFERIOR, 0 AS NO_LIMITE_SUPERIOR, 0.9 AS NO_VALOR_1, 5 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 1 AS NO_LIMITE_INFERIOR, 1 AS NO_LIMITE_SUPERIOR, 1.9 AS NO_VALOR_1, 15 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 2 AS NO_LIMITE_INFERIOR, 2 AS NO_LIMITE_SUPERIOR, 2.9 AS NO_VALOR_1, 23 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 3 AS NO_LIMITE_INFERIOR, 3 AS NO_LIMITE_SUPERIOR, 3.9 AS NO_VALOR_1, 32 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 4 AS NO_LIMITE_INFERIOR, 4 AS NO_LIMITE_SUPERIOR, 4.9 AS NO_VALOR_1, 38.5 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 5 AS NO_LIMITE_INFERIOR, 5 AS NO_LIMITE_SUPERIOR, 5.9 AS NO_VALOR_1, 44.5 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 6 AS NO_LIMITE_INFERIOR, 6 AS NO_LIMITE_SUPERIOR, 6.9 AS NO_VALOR_1, 47.5 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 7 AS NO_LIMITE_INFERIOR, 7 AS NO_LIMITE_SUPERIOR, 7.9 AS NO_VALOR_1, 53 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 8 AS NO_LIMITE_INFERIOR, 8 AS NO_LIMITE_SUPERIOR, 8.9 AS NO_VALOR_1, 60 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 9 AS NO_LIMITE_INFERIOR, 9 AS NO_LIMITE_SUPERIOR, 9.9 AS NO_VALOR_1, 64 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 10 AS NO_LIMITE_INFERIOR, 10 AS NO_LIMITE_SUPERIOR, 10.9 AS NO_VALOR_1, 73 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 11 AS NO_LIMITE_INFERIOR, 11 AS NO_LIMITE_SUPERIOR, 11.9 AS NO_VALOR_1, 75 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 12 AS NO_LIMITE_INFERIOR, 12 AS NO_LIMITE_SUPERIOR, 12.9 AS NO_VALOR_1, 77.5 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 13 AS NO_LIMITE_INFERIOR, 13 AS NO_LIMITE_SUPERIOR, 13.9 AS NO_VALOR_1, 82 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 14 AS NO_LIMITE_INFERIOR, 14 AS NO_LIMITE_SUPERIOR, 14.9 AS NO_VALOR_1, 85 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 15 AS NO_LIMITE_INFERIOR, 15 AS NO_LIMITE_SUPERIOR, 15.9 AS NO_VALOR_1, 90 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 16 AS NO_LIMITE_INFERIOR, 17 AS NO_LIMITE_SUPERIOR, 17.9 AS NO_VALOR_1, 95 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 18 AS NO_LIMITE_INFERIOR, 18 AS NO_LIMITE_SUPERIOR, 20 AS NO_VALOR_1, 98 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 0 AS NO_LIMITE_INFERIOR, 0 AS NO_LIMITE_SUPERIOR, 0.9 AS NO_VALOR_1, 8 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 1 AS NO_LIMITE_INFERIOR, 1 AS NO_LIMITE_SUPERIOR, 1.9 AS NO_VALOR_1, 23 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 2 AS NO_LIMITE_INFERIOR, 2 AS NO_LIMITE_SUPERIOR, 2.9 AS NO_VALOR_1, 36 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 3 AS NO_LIMITE_INFERIOR, 3 AS NO_LIMITE_SUPERIOR, 3.9 AS NO_VALOR_1, 43.5 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 4 AS NO_LIMITE_INFERIOR, 4 AS NO_LIMITE_SUPERIOR, 4.9 AS NO_VALOR_1, 53 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 5 AS NO_LIMITE_INFERIOR, 5 AS NO_LIMITE_SUPERIOR, 5.9 AS NO_VALOR_1, 62.5 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 6 AS NO_LIMITE_INFERIOR, 6 AS NO_LIMITE_SUPERIOR, 6.9 AS NO_VALOR_1, 69 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 7 AS NO_LIMITE_INFERIOR, 7 AS NO_LIMITE_SUPERIOR, 7.9 AS NO_VALOR_1, 77 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 8 AS NO_LIMITE_INFERIOR, 8 AS NO_LIMITE_SUPERIOR, 8.9 AS NO_VALOR_1, 85 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 9 AS NO_LIMITE_INFERIOR, 9 AS NO_LIMITE_SUPERIOR, 9.9 AS NO_VALOR_1, 88 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 10 AS NO_LIMITE_INFERIOR, 10 AS NO_LIMITE_SUPERIOR, 10.9 AS NO_VALOR_1, 94 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 11 AS NO_LIMITE_INFERIOR, 13 AS NO_LIMITE_SUPERIOR, 13.9 AS NO_VALOR_1, 96 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 14 AS NO_LIMITE_INFERIOR, 14 AS NO_LIMITE_SUPERIOR, 17 AS NO_VALOR_1, 98 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 0 AS NO_LIMITE_INFERIOR, 0 AS NO_LIMITE_SUPERIOR, 0.9 AS NO_VALOR_1, 13 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 1 AS NO_LIMITE_INFERIOR, 1 AS NO_LIMITE_SUPERIOR, 1.9 AS NO_VALOR_1, 24 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 2 AS NO_LIMITE_INFERIOR, 2 AS NO_LIMITE_SUPERIOR, 2.9 AS NO_VALOR_1, 31 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 3 AS NO_LIMITE_INFERIOR, 3 AS NO_LIMITE_SUPERIOR, 3.9 AS NO_VALOR_1, 37.5 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 4 AS NO_LIMITE_INFERIOR, 4 AS NO_LIMITE_SUPERIOR, 4.9 AS NO_VALOR_1, 44.5 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 5 AS NO_LIMITE_INFERIOR, 5 AS NO_LIMITE_SUPERIOR, 5.9 AS NO_VALOR_1, 53 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 6 AS NO_LIMITE_INFERIOR, 6 AS NO_LIMITE_SUPERIOR, 6.9 AS NO_VALOR_1, 58 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 7 AS NO_LIMITE_INFERIOR, 7 AS NO_LIMITE_SUPERIOR, 7.9 AS NO_VALOR_1, 64 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 8 AS NO_LIMITE_INFERIOR, 8 AS NO_LIMITE_SUPERIOR, 8.9 AS NO_VALOR_1, 71 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 9 AS NO_LIMITE_INFERIOR, 9 AS NO_LIMITE_SUPERIOR, 9.9 AS NO_VALOR_1, 75.5 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 10 AS NO_LIMITE_INFERIOR, 10 AS NO_LIMITE_SUPERIOR, 10.9 AS NO_VALOR_1, 83 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 11 AS NO_LIMITE_INFERIOR, 11 AS NO_LIMITE_SUPERIOR, 11.9 AS NO_VALOR_1, 87 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 12 AS NO_LIMITE_INFERIOR, 12 AS NO_LIMITE_SUPERIOR, 12.9 AS NO_VALOR_1, 94 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 13 AS NO_LIMITE_INFERIOR, 15 AS NO_LIMITE_SUPERIOR, 15.9 AS NO_VALOR_1, 96 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 16 AS NO_LIMITE_INFERIOR, 16 AS NO_LIMITE_SUPERIOR, 19 AS NO_VALOR_1, 98 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 0 AS NO_LIMITE_INFERIOR, 0 AS NO_LIMITE_SUPERIOR, 0.9 AS NO_VALOR_1, 3 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 1 AS NO_LIMITE_INFERIOR, 1 AS NO_LIMITE_SUPERIOR, 1.9 AS NO_VALOR_1, 17.5 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 2 AS NO_LIMITE_INFERIOR, 2 AS NO_LIMITE_SUPERIOR, 2.9 AS NO_VALOR_1, 31 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 3 AS NO_LIMITE_INFERIOR, 3 AS NO_LIMITE_SUPERIOR, 3.9 AS NO_VALOR_1, 40 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 4 AS NO_LIMITE_INFERIOR, 4 AS NO_LIMITE_SUPERIOR, 4.9 AS NO_VALOR_1, 52.5 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 5 AS NO_LIMITE_INFERIOR, 5 AS NO_LIMITE_SUPERIOR, 5.9 AS NO_VALOR_1, 62.5 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 6 AS NO_LIMITE_INFERIOR, 6 AS NO_LIMITE_SUPERIOR, 6.9 AS NO_VALOR_1, 71 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 7 AS NO_LIMITE_INFERIOR, 7 AS NO_LIMITE_SUPERIOR, 7.9 AS NO_VALOR_1, 81 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 8 AS NO_LIMITE_INFERIOR, 8 AS NO_LIMITE_SUPERIOR, 8.9 AS NO_VALOR_1, 86 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 9 AS NO_LIMITE_INFERIOR, 9 AS NO_LIMITE_SUPERIOR, 9.9 AS NO_VALOR_1, 95 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 10 AS NO_LIMITE_INFERIOR, 10 AS NO_LIMITE_SUPERIOR, 10.9 AS NO_VALOR_1, 96 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 11 AS NO_LIMITE_INFERIOR, 13 AS NO_LIMITE_SUPERIOR, 13.9 AS NO_VALOR_1, 97 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 14 AS NO_LIMITE_INFERIOR, 14 AS NO_LIMITE_SUPERIOR, 17 AS NO_VALOR_1, 98 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION UNION ALL
SELECT 0 AS NO_LIMITE_INFERIOR, 0 AS NO_LIMITE_SUPERIOR, 0.9 AS NO_VALOR_1, 98 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 1 AS NO_LIMITE_INFERIOR, 1 AS NO_LIMITE_SUPERIOR, 1.9 AS NO_VALOR_1, 85 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 2 AS NO_LIMITE_INFERIOR, 2 AS NO_LIMITE_SUPERIOR, 2.9 AS NO_VALOR_1, 74 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 3 AS NO_LIMITE_INFERIOR, 3 AS NO_LIMITE_SUPERIOR, 3.9 AS NO_VALOR_1, 66 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 4 AS NO_LIMITE_INFERIOR, 4 AS NO_LIMITE_SUPERIOR, 4.9 AS NO_VALOR_1, 59 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 5 AS NO_LIMITE_INFERIOR, 5 AS NO_LIMITE_SUPERIOR, 5.9 AS NO_VALOR_1, 53.5 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 6 AS NO_LIMITE_INFERIOR, 6 AS NO_LIMITE_SUPERIOR, 6.9 AS NO_VALOR_1, 48 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 7 AS NO_LIMITE_INFERIOR, 7 AS NO_LIMITE_SUPERIOR, 7.9 AS NO_VALOR_1, 44 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 8 AS NO_LIMITE_INFERIOR, 8 AS NO_LIMITE_SUPERIOR, 8.9 AS NO_VALOR_1, 40 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 9 AS NO_LIMITE_INFERIOR, 9 AS NO_LIMITE_SUPERIOR, 9.9 AS NO_VALOR_1, 35 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 10 AS NO_LIMITE_INFERIOR, 10 AS NO_LIMITE_SUPERIOR, 10.9 AS NO_VALOR_1, 30 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 11 AS NO_LIMITE_INFERIOR, 11 AS NO_LIMITE_SUPERIOR, 11.9 AS NO_VALOR_1, 27 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 12 AS NO_LIMITE_INFERIOR, 12 AS NO_LIMITE_SUPERIOR, 12.9 AS NO_VALOR_1, 22 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 13 AS NO_LIMITE_INFERIOR, 13 AS NO_LIMITE_SUPERIOR, 13.9 AS NO_VALOR_1, 17.5 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 14 AS NO_LIMITE_INFERIOR, 14 AS NO_LIMITE_SUPERIOR, 14.9 AS NO_VALOR_1, 13.5 AS NO_VALOR_2, 'D' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 0 AS NO_LIMITE_INFERIOR, 0 AS NO_LIMITE_SUPERIOR, 0.9 AS NO_VALOR_1, 98 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 1 AS NO_LIMITE_INFERIOR, 1 AS NO_LIMITE_SUPERIOR, 1.9 AS NO_VALOR_1, 85 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 2 AS NO_LIMITE_INFERIOR, 2 AS NO_LIMITE_SUPERIOR, 2.9 AS NO_VALOR_1, 73 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 3 AS NO_LIMITE_INFERIOR, 3 AS NO_LIMITE_SUPERIOR, 3.9 AS NO_VALOR_1, 64 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 4 AS NO_LIMITE_INFERIOR, 4 AS NO_LIMITE_SUPERIOR, 4.9 AS NO_VALOR_1, 54 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 5 AS NO_LIMITE_INFERIOR, 5 AS NO_LIMITE_SUPERIOR, 5.9 AS NO_VALOR_1, 47 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 6 AS NO_LIMITE_INFERIOR, 6 AS NO_LIMITE_SUPERIOR, 6.9 AS NO_VALOR_1, 37 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 7 AS NO_LIMITE_INFERIOR, 7 AS NO_LIMITE_SUPERIOR, 7.9 AS NO_VALOR_1, 30 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 8 AS NO_LIMITE_INFERIOR, 8 AS NO_LIMITE_SUPERIOR, 8.9 AS NO_VALOR_1, 22.5 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 9 AS NO_LIMITE_INFERIOR, 9 AS NO_LIMITE_SUPERIOR, 9.9 AS NO_VALOR_1, 17 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 10 AS NO_LIMITE_INFERIOR, 10 AS NO_LIMITE_SUPERIOR, 10.9 AS NO_VALOR_1, 11 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 11 AS NO_LIMITE_INFERIOR, 11 AS NO_LIMITE_SUPERIOR, 11.9 AS NO_VALOR_1, 7.5 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 12 AS NO_LIMITE_INFERIOR, 12 AS NO_LIMITE_SUPERIOR, 12.9 AS NO_VALOR_1, 5 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 13 AS NO_LIMITE_INFERIOR, 15 AS NO_LIMITE_SUPERIOR, 15.9 AS NO_VALOR_1, 4 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 16 AS NO_LIMITE_INFERIOR, 16 AS NO_LIMITE_SUPERIOR, 19 AS NO_VALOR_1, 2 AS NO_VALOR_2, 'I' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 0 AS NO_LIMITE_INFERIOR, 0 AS NO_LIMITE_SUPERIOR, 0.9 AS NO_VALOR_1, 98 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 1 AS NO_LIMITE_INFERIOR, 1 AS NO_LIMITE_SUPERIOR, 1.9 AS NO_VALOR_1, 94 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 2 AS NO_LIMITE_INFERIOR, 2 AS NO_LIMITE_SUPERIOR, 2.9 AS NO_VALOR_1, 83.5 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 3 AS NO_LIMITE_INFERIOR, 3 AS NO_LIMITE_SUPERIOR, 3.9 AS NO_VALOR_1, 74.5 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 4 AS NO_LIMITE_INFERIOR, 4 AS NO_LIMITE_SUPERIOR, 4.9 AS NO_VALOR_1, 66 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 5 AS NO_LIMITE_INFERIOR, 5 AS NO_LIMITE_SUPERIOR, 5.9 AS NO_VALOR_1, 58.5 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 6 AS NO_LIMITE_INFERIOR, 6 AS NO_LIMITE_SUPERIOR, 6.9 AS NO_VALOR_1, 54 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 7 AS NO_LIMITE_INFERIOR, 7 AS NO_LIMITE_SUPERIOR, 7.9 AS NO_VALOR_1, 43.5 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 8 AS NO_LIMITE_INFERIOR, 8 AS NO_LIMITE_SUPERIOR, 8.9 AS NO_VALOR_1, 37.5 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 9 AS NO_LIMITE_INFERIOR, 9 AS NO_LIMITE_SUPERIOR, 9.9 AS NO_VALOR_1, 30 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 10 AS NO_LIMITE_INFERIOR, 10 AS NO_LIMITE_SUPERIOR, 10.9 AS NO_VALOR_1, 23.5 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 11 AS NO_LIMITE_INFERIOR, 11 AS NO_LIMITE_SUPERIOR, 11.9 AS NO_VALOR_1, 16 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 12 AS NO_LIMITE_INFERIOR, 12 AS NO_LIMITE_SUPERIOR, 12.9 AS NO_VALOR_1, 10 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 13 AS NO_LIMITE_INFERIOR, 15 AS NO_LIMITE_SUPERIOR, 15.9 AS NO_VALOR_1, 5 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 16 AS NO_LIMITE_INFERIOR, 16 AS NO_LIMITE_SUPERIOR, 19 AS NO_VALOR_1, 2 AS NO_VALOR_2, 'S' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 0 AS NO_LIMITE_INFERIOR, 0 AS NO_LIMITE_SUPERIOR, 0.9 AS NO_VALOR_1, 98 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 1 AS NO_LIMITE_INFERIOR, 1 AS NO_LIMITE_SUPERIOR, 1.9 AS NO_VALOR_1, 94 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 2 AS NO_LIMITE_INFERIOR, 2 AS NO_LIMITE_SUPERIOR, 2.9 AS NO_VALOR_1, 87 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 3 AS NO_LIMITE_INFERIOR, 3 AS NO_LIMITE_SUPERIOR, 3.9 AS NO_VALOR_1, 79 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 4 AS NO_LIMITE_INFERIOR, 4 AS NO_LIMITE_SUPERIOR, 4.9 AS NO_VALOR_1, 72 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 5 AS NO_LIMITE_INFERIOR, 5 AS NO_LIMITE_SUPERIOR, 5.9 AS NO_VALOR_1, 63 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 6 AS NO_LIMITE_INFERIOR, 6 AS NO_LIMITE_SUPERIOR, 6.9 AS NO_VALOR_1, 54 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 7 AS NO_LIMITE_INFERIOR, 7 AS NO_LIMITE_SUPERIOR, 7.9 AS NO_VALOR_1, 48 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 8 AS NO_LIMITE_INFERIOR, 8 AS NO_LIMITE_SUPERIOR, 8.9 AS NO_VALOR_1, 39.5 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 9 AS NO_LIMITE_INFERIOR, 9 AS NO_LIMITE_SUPERIOR, 9.9 AS NO_VALOR_1, 33.5 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 10 AS NO_LIMITE_INFERIOR, 10 AS NO_LIMITE_SUPERIOR, 10.9 AS NO_VALOR_1, 26 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 11 AS NO_LIMITE_INFERIOR, 11 AS NO_LIMITE_SUPERIOR, 11.9 AS NO_VALOR_1, 16 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 12 AS NO_LIMITE_INFERIOR, 12 AS NO_LIMITE_SUPERIOR, 12.9 AS NO_VALOR_1, 10 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 13 AS NO_LIMITE_INFERIOR, 14 AS NO_LIMITE_SUPERIOR, 14.9 AS NO_VALOR_1, 6 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION UNION ALL
SELECT 15 AS NO_LIMITE_INFERIOR, 15 AS NO_LIMITE_SUPERIOR, 16 AS NO_VALOR_1, 3 AS NO_VALOR_2, 'C' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION


INSERT INTO  @T_RESULTADO
SELECT 'LABORAL1-REP-DT' AS CL_VARIABLE_REPORTE, 'LABORAL1-REP-COTIDIANO-D' AS CL_VARIABLE_GRAFICO, 'D' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION ,0, 0 UNION ALL
SELECT 'LABORAL1-REP-IT' AS CL_VARIABLE_REPORTE, 'LABORAL1-REP-COTIDIANO-I' AS CL_VARIABLE_GRAFICO, 'I' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION ,0, 0 UNION ALL
SELECT 'LABORAL1-REP-ST' AS CL_VARIABLE_REPORTE, 'LABORAL1-REP-COTIDIANO-S' AS CL_VARIABLE_GRAFICO, 'S' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION ,0, 0 UNION ALL
SELECT 'LABORAL1-REP-CT' AS CL_VARIABLE_REPORTE, 'LABORAL1-REP-COTIDIANO-C' AS CL_VARIABLE_GRAFICO, 'C' AS CL_TIPO_DISC, 'COTIDIANO' AS CL_SITUACION ,0, 0 UNION ALL
SELECT 'LABORAL1-REP-DM' AS CL_VARIABLE_REPORTE, 'LABORAL1-REP-MOTIVANTE-D' AS CL_VARIABLE_GRAFICO, 'D' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION ,0, 0 UNION ALL
SELECT 'LABORAL1-REP-IM' AS CL_VARIABLE_REPORTE, 'LABORAL1-REP-MOTIVANTE-I' AS CL_VARIABLE_GRAFICO, 'I' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION ,0, 0 UNION ALL
SELECT 'LABORAL1-REP-SM' AS CL_VARIABLE_REPORTE, 'LABORAL1-REP-MOTIVANTE-S' AS CL_VARIABLE_GRAFICO, 'S' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION ,0, 0 UNION ALL
SELECT 'LABORAL1-REP-CM' AS CL_VARIABLE_REPORTE, 'LABORAL1-REP-MOTIVANTE-C' AS CL_VARIABLE_GRAFICO, 'C' AS CL_TIPO_DISC, 'MOTIVANTE' AS CL_SITUACION ,0, 0 UNION ALL
SELECT 'LABORAL1-REP-DL' AS CL_VARIABLE_REPORTE, 'LABORAL1-REP-PRESION-D' AS CL_VARIABLE_GRAFICO, 'D' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION ,0, 0 UNION ALL
SELECT 'LABORAL1-REP-IL' AS CL_VARIABLE_REPORTE, 'LABORAL1-REP-PRESION-I' AS CL_VARIABLE_GRAFICO, 'I' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION ,0, 0 UNION ALL
SELECT 'LABORAL1-REP-SL' AS CL_VARIABLE_REPORTE, 'LABORAL1-REP-PRESION-S' AS CL_VARIABLE_GRAFICO, 'S' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION ,0, 0 UNION ALL
SELECT 'LABORAL1-REP-CL' AS CL_VARIABLE_REPORTE, 'LABORAL1-REP-PRESION-C' AS CL_VARIABLE_GRAFICO, 'C' AS CL_TIPO_DISC, 'PRESION' AS CL_SITUACION ,0, 0  


; WITH T_VARIABLES AS (
	SELECT CV.ID_VARIABLE, TVD.* 
	FROM @T_VALORES_DISC TVD
		INNER JOIN IDP.C_VARIABLE CV
			ON TVD.CL_VARIABLE = CV.CL_VARIABLE
), T_VALORES_VARIABLES AS (
	SELECT TV.*, CAST(KR.NO_VALOR AS INT) AS NO_RESPUESTA
		, CASE WHEN NO_VALOR = NO_VALOR_PARAMETRO THEN 1 ELSE 0 END AS NO_VALOR
	FROM T_VARIABLES TV
		INNER JOIN IDP.K_RESULTADO KR
			ON KR.ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			AND KR.ID_VARIABLE = TV.ID_VARIABLE
), T_VALORES_RESPUESTA AS (
	SELECT TVV.CL_TIPO_DISC, TVV.CL_TIPO_ML, SUM(TVV.NO_VALOR) AS NO_SUMA_VALOR
	FROM T_VALORES_VARIABLES TVV
	GROUP BY TVV.CL_TIPO_DISC, TVV.CL_TIPO_ML
)
INSERT INTO @T_RESULTADO_DISC

SELECT * FROM T_VALORES_RESPUESTA


INSERT INTO @T_RESULTADO_DISC
SELECT CL_TIPO_DISC
	, 'T' AS CL_TIPO_ML
	, SUM(
		CASE CL_TIPO_ML 
			WHEN 'M' THEN NO_VALOR_RESULTADO
			WHEN 'L' THEN NO_VALOR_RESULTADO * -1
		END
	)
FROM @T_RESULTADO_DISC
GROUP BY CL_TIPO_DISC

; WITH T_SITUACIONES AS (
	SELECT 'COTIDIANO' AS CL_SITUACION, 'T' AS CL_TIPO_ML UNION ALL
	SELECT 'MOTIVANTE' AS CL_SITUACION, 'M' AS CL_TIPO_ML UNION ALL
	SELECT 'PRESION' AS CL_SITUACION, 'L' AS CL_TIPO_ML
	 
) 

UPDATE TR SET
  [NO_VALOR_2] =TRF.NO_VALOR_2
, [NO_VALOR_RESULTADO] =TRF.NO_VALOR_RESULTADO
			
 FROM @T_RESULTADO TR
 INNER JOIN
 (SELECT NO_VALOR_2, NO_VALOR_RESULTADO, TL.CL_TIPO_DISC,TS.CL_SITUACION
 FROM @T_RESULTADO_DISC AS TRD
	INNER JOIN T_SITUACIONES TS
		ON TRD.CL_TIPO_ML = TS.CL_TIPO_ML
	LEFT JOIN @T_LIMITES TL
		ON TS.CL_SITUACION = TL.CL_SITUACION
		AND TRD.CL_TIPO_DISC = TL.CL_TIPO_DISC
		AND TRD.NO_VALOR_RESULTADO BETWEEN TL.NO_LIMITE_INFERIOR AND TL.NO_LIMITE_SUPERIOR) TRF
		  ON  TRF.CL_SITUACION= TR.CL_SITUACION AND TRF.CL_TIPO_DISC=TR.CL_TIPO_DISC

		  --SELECT * FROM @T_RESULTADO

		DELETE IDP.K_RESULTADO WHERE ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO AND CL_TIPO_RESULTADO = 3

		
		INSERT INTO [IDP].[K_RESULTADO] ([CL_TIPO_RESULTADO] ,[ID_VARIABLE] ,[NO_VALOR], [ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA])
		SELECT  3 AS CL_VARIABLE_GRAFICO, cv.ID_VARIABLE,NO_VALOR_2, @PIN_ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA , @PIN_NB_PROGRAMA_CREA
		from @T_RESULTADO tr
		INNER JOIN IDP.C_VARIABLE cv ON tr.CL_VARIABLE_GRAFICO = cv.CL_VARIABLE 

		INSERT INTO [IDP].[K_RESULTADO] ([CL_TIPO_RESULTADO] ,[ID_VARIABLE] ,[NO_VALOR], [ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA])
		SELECT  3 AS CL_VARIABLE_REPORTE, cv.ID_VARIABLE,NO_VALOR_RESULTADO, @PIN_ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA , @PIN_NB_PROGRAMA_CREA
		from @T_RESULTADO tr
		INNER JOIN IDP.C_VARIABLE cv ON tr.CL_VARIABLE_REPORTE = cv.CL_VARIABLE 


END
--SE DEVUELVE LA VARIABLE DE RETORNO INDICANDO QUE TODO SE REALIZO CORRECTAMENTE
		SET @XML_RESULTADO = DBO.F_ERROR_CREAR_ENCABEZADO( @@ROWCOUNT, 1, 'SUCCESSFUL')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'Proceso exitoso', 'ES')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'Successful Process', 'EN')
		--SI SE GENERO UNA TRANSACCION EN ESTE BLOQUE LA TERMINARA
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			COMMIT
	END TRY
	BEGIN CATCH
		--SI OCURRIO UN ERROR Y SE INICIO UNA TRANSACCION ENE ESTE BLOQUE SE CANCELARA LA TRANSACCION
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			ROLLBACK
		--SE INDICA EN LA VARIABLE DE RETORNO QUE OCURRIO UN ERROR
		--SET @POUT_CLAVE_RETORNO = 0
		--SE INSERTA EL ERROR EN LA TABLA
		DECLARE @ERROR_CLAVE INT  = ERROR_NUMBER()
		DECLARE @ERROR_MENSAJE NVARCHAR(250)  = ERROR_MESSAGE()
		
		SET @XML_RESULTADO = DBO.F_ERROR_CREAR_ENCABEZADO( @@ROWCOUNT, @ERROR_CLAVE, 'ERROR')
		SET @XML_RESULTADO = DBO.F_ERROR_MENSAJES(@ERROR_CLAVE,@ERROR_MENSAJE)
		SET @XML_RESULTADO = DBO.F_ERROR_MENSAJES(@ERROR_CLAVE,@ERROR_MENSAJE)			
	END CATCH
END