
-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Juan De Dios Pérez Pedroza
-- CREATE date: 21/09/2015
-- Description: Obtiene los datos de la tabla K_PRUEBA_SECCION
-- =============================================
CREATE PROCEDURE [IDP].[SPE_OBTIENE_K_PRUEBA_SECCION] 
      @PIN_ID_PRUEBA_SECCION AS int = NULL
	, @PIN_ID_PRUEBA AS int = NULL
	, @PIN_CL_PRUEBA_SECCION AS NVARCHAR(20) = NULL
	, @PIN_NB_PRUEBA_SECCION AS NVARCHAR(200) = NULL
	, @PIN_NO_TIEMPO AS int = NULL	
	, @PIN_CL_ESTADO AS nvarchar(10) = NULL
	, @PIN_FE_INICIO AS datetime = NULL
	, @PIN_FE_TERMINO AS datetime = NULL
AS   
		

		--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
		SELECT 
	     [ID_PRUEBA_SECCION]
		,[ID_PRUEBA]
		,[CL_PRUEBA_SECCION]
		,[NB_PRUEBA_SECCION]
		,[NO_TIEMPO]
		,[CL_ESTADO]
		,[FE_INICIO]
		,[FE_TERMINO]
		FROM IDP.K_PRUEBA_SECCION 


		WHERE			 (@PIN_ID_PRUEBA_SECCION IS NULL OR (@PIN_ID_PRUEBA_SECCION IS NOT NULL AND [ID_PRUEBA_SECCION] = @PIN_ID_PRUEBA_SECCION  /*AND KP.CL_TOKEN_EXTERNO = @PIN_CL_TOKEN_EXTERNO*/))
				 AND     (@PIN_ID_PRUEBA IS NULL OR (@PIN_ID_PRUEBA IS NOT NULL AND [ID_PRUEBA] = @PIN_ID_PRUEBA))
				 AND (@PIN_CL_PRUEBA_SECCION IS NULL OR (@PIN_CL_PRUEBA_SECCION IS NOT NULL AND [CL_PRUEBA_SECCION] = @PIN_CL_PRUEBA_SECCION))
				 AND (@PIN_NB_PRUEBA_SECCION IS NULL OR (@PIN_NB_PRUEBA_SECCION IS NOT NULL AND [NB_PRUEBA_SECCION] = @PIN_NB_PRUEBA_SECCION))
				 AND (@PIN_NO_TIEMPO IS NULL OR (@PIN_NO_TIEMPO IS NOT NULL AND [NO_TIEMPO] = @PIN_NO_TIEMPO))				 
				 AND (@PIN_CL_ESTADO IS NULL OR (@PIN_CL_ESTADO IS NOT NULL AND [CL_ESTADO] = @PIN_CL_ESTADO))
ORDER BY FE_CREACION DESC

