
-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Juan Castillo
-- CREATE date: 27/01/2016
-- Description: Obtiene los Resultados de la prueba
-- =============================================
CREATE PROCEDURE [IDP].[SPE_OBTIENE_RESULTADO_PRUEBA] 
	  @PIN_ID_PRUEBA int = NULL
	, @PIN_CL_TOKEN_EXTERNO AS UNIQUEIDENTIFIER = NULL	

AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT  KPR.ID_PRUEBA,
		CPR.ID_PREGUNTA,
		CVA.ID_VARIABLE,
		CPR.CL_PREGUNTA,
		CVA.CL_TIPO_VARIABLE,
		CPR.NB_PREGUNTA,
		NB_RESPUESTA,
		NO_VALOR_RESPUESTA 
	FROM IDP.K_PRUEBA KPR JOIN
	ADM.K_CUESTIONARIO_PREGUNTA KCP ON KPR.ID_CUESTIONARIO = KCP.ID_CUESTIONARIO
	JOIN ADM.C_PREGUNTA CPR ON KCP.ID_PREGUNTA = CPR.ID_PREGUNTA
	JOIN IDP.C_VARIABLE CVA ON CVA.CL_VARIABLE = CPR.CL_PREGUNTA
	LEFT OUTER JOIN IDP.K_RESULTADO KRE ON KRE.ID_VARIABLE =CVA.ID_VARIABLE AND KRE.ID_CUESTIONARIO=KCP.ID_CUESTIONARIO
	WHERE KPR.ID_PRUEBA=@PIN_ID_PRUEBA 
	AND KPR.CL_TOKEN_EXTERNO = @PIN_CL_TOKEN_EXTERNO
	AND CVA.CL_TIPO_VARIABLE=1
	UNION ALL
	SELECT KPR.ID_PRUEBA,NULL,CVA.ID_VARIABLE,CL_VARIABLE,CL_TIPO_VARIABLE,NULL,NULL,NO_VALOR 
	FROM IDP.C_VARIABLE CVA 
	JOIN IDP.K_RESULTADO KRE ON KRE.ID_VARIABLE =CVA.ID_VARIABLE --AND KRE.ID_CUESTIONARIO=KCP.ID_CUESTIONARIO
	JOIN IDP.K_PRUEBA KPR ON KPR.ID_CUESTIONARIO = KRE.ID_CUESTIONARIO
	WHERE KPR.ID_PRUEBA = @PIN_ID_PRUEBA 
	AND KPR.CL_TOKEN_EXTERNO = @PIN_CL_TOKEN_EXTERNO
	AND CVA.CL_TIPO_VARIABLE=2
		
