-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Juan Castillo
-- CREATE date: 13/01/2016
-- Description: Obtiene las pruebas que corresponden al puesto 
-- =============================================
CREATE PROCEDURE [IDP].[SPE_OBTIENE_PRUEBA_POR_PUESTO] 
	@PIN_ID_PUESTO AS int = NULL	
AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT DISTINCT CPR.ID_PRUEBA,
			CL_PRUEBA,
			NB_PRUEBA 
	FROM ADM.C_PUESTO_COMPETENCIA CPC
	JOIN IDP.K_COMPETENCIA_FACTOR KCF ON CPC.ID_COMPETENCIA = KCF.ID_COMPETENCIA
	JOIN IDP.K_PRUEBA_FACTOR KPF ON KCF.ID_FACTOR = KPF.ID_FACTOR
	JOIN IDP.C_PRUEBA CPR ON KPF.ID_PRUEBA = CPR.ID_PRUEBA
	WHERE CPC.ID_PUESTO = @PIN_ID_PUESTO;