-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Gabriel Vázquez
-- CREATE date: 10/02/2016
-- Description: inserción de variables de baremos de prueba APTITUD MENTAL 2
-- =============================================
CREATE PROCEDURE [IDP].[SPE_INSERTA_BAREMOS_APTITUD2]
	 @PIN_ID_BATERIA AS INT
	,@PIN_CL_USUARIO_APP AS NVARCHAR(50)
	,@PIN_NB_PROGRAMA AS NVARCHAR(50)

AS
BEGIN  
	--SE DECLARA E INICIALIZA LA VARIABLE QUE NOS INDICARA SI GENERAMOS LA TRANSACCION EN ESTE SP
	DECLARE @V_EXIST_TRAN BIT = 0,
			@V_FE_SISTEMA AS DATETIME = GETDATE()

	DECLARE @V_ID_CUESTIONARIO AS INT,
			@V_NO_BAREMOS_CI AS INT,
			@V_NO_BAREMOS_VELOCIDAD AS INT,
			@V_NO_BAREMOS_APRENDIZAJE AS INT

	--SE VERIFICA SI SE INSERTA EL REGISTRO O SE ACTUALIZARA SEGUN LA VARIABLE DE TIPO DE TRANSACCION  QUE RECIBE EL SP
		
	SELECT @V_ID_CUESTIONARIO = ID_CUESTIONARIO_BAREMOS
	FROM IDP.K_BATERIA_PRUEBA
	WHERE ID_BATERIA = @PIN_ID_BATERIA

	;WITH T_VARIABLES AS (
		SELECT 'APTITUD2_REP_CONOCIMIENTO'	 AS CL_VARIABLE_REPORTE, 1 AS NO_FILA UNION ALL
		SELECT 'APTITUD2_REP_COMPRENSION'	 AS CL_VARIABLE_REPORTE, 2 AS NO_FILA UNION ALL
		SELECT 'APTITUD2_REP_LOGICA'		 AS CL_VARIABLE_REPORTE, 3 AS NO_FILA UNION ALL
		SELECT 'APTITUD2_REP_ARITMETICA'	 AS CL_VARIABLE_REPORTE, 4 AS NO_FILA UNION ALL
		SELECT 'APTITUD2_REP_JUICIO'		 AS CL_VARIABLE_REPORTE, 5 AS NO_FILA UNION ALL
		SELECT 'APTITUD2_REP_ANALOGIAS'		 AS CL_VARIABLE_REPORTE, 6 AS NO_FILA UNION ALL
		SELECT 'APTITUD2_REP_ORDENAMIENTO'	 AS CL_VARIABLE_REPORTE, 7 AS NO_FILA UNION ALL
		SELECT 'APTITUD2_REP_CLASIFICACION'	 AS CL_VARIABLE_REPORTE, 8 AS NO_FILA UNION ALL
		SELECT 'APTITUD2_REP_SERIACION'		 AS CL_VARIABLE_REPORTE, 9 AS NO_FILA UNION ALL
		SELECT 'APTITUD2_REP_ACIERTOS'		 AS CL_VARIABLE_REPORTE, 10 AS NO_FILA
	), T_RESULTADOS AS (

		SELECT TV.CL_VARIABLE_REPORTE, TV.NO_FILA, KR.NO_VALOR
		FROM T_VARIABLES TV
			INNER JOIN IDP.C_VARIABLE CV ON TV.CL_VARIABLE_REPORTE = CV.CL_VARIABLE
			INNER JOIN IDP.K_RESULTADO KR ON CV.ID_VARIABLE = KR.ID_VARIABLE
			INNER JOIN ADM.K_CUESTIONARIO KC ON KR.ID_CUESTIONARIO = KC.ID_CUESTIONARIO
			INNER JOIN IDP.K_PRUEBA KP ON KC.ID_CUESTIONARIO = KP.ID_CUESTIONARIO
		WHERE KP.ID_BATERIA = @PIN_ID_BATERIA

	), T_BAREMOS AS (
		SELECT 'AT-CULTURA GENERAL'					 AS CL_VARIABLE_BAREMOS, 1 AS NO_FILA UNION ALL
		SELECT 'AT-CAPACIDAD DE JUICIO'				 AS CL_VARIABLE_BAREMOS, 2 AS NO_FILA UNION ALL
		SELECT 'AT-CAPACIDAD DE ANÁLISIS Y SÍNTESIS' AS CL_VARIABLE_BAREMOS, 3 AS NO_FILA UNION ALL
		SELECT 'AT-CAPACIDAD DE ABSTRACCIÓN'		 AS CL_VARIABLE_BAREMOS, 4 AS NO_FILA UNION ALL
		SELECT 'AT-CAPACIDAD DE RAZONAMIENTO'		 AS CL_VARIABLE_BAREMOS, 5 AS NO_FILA UNION ALL
		SELECT 'AT-SENTIDO COMÚN'					 AS CL_VARIABLE_BAREMOS, 6 AS NO_FILA UNION ALL
		SELECT 'AT-PENSAMIENTO ORGANIZADO'			 AS CL_VARIABLE_BAREMOS, 7 AS NO_FILA UNION ALL
		SELECT 'AT-CAPACIDAD DE PLANEACIÓN'			 AS CL_VARIABLE_BAREMOS, 8 AS NO_FILA UNION ALL
		SELECT 'AT-CAPACIDAD DE DISCRIMINACIÓN'		 AS CL_VARIABLE_BAREMOS, 9 AS NO_FILA UNION ALL
		SELECT 'AT-CAPACIDAD DE DEDUCCIÓN'			 AS CL_VARIABLE_BAREMOS, 10 AS NO_FILA 
	)

	INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA])
	SELECT 4 AS CL_TIPO_RESULTADO, CV.ID_VARIABLE,[IDP].[F_OBTIENE_VALORES_BAREMOS](7, TR.NO_VALOR, 'PORCENTAJE'), @V_ID_CUESTIONARIO, @V_FE_SISTEMA, @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA  --*, [IDP].[F_OBTIENE_VALORES_BAREMOS](7, TR.NO_VALOR, 'PORCENTAJE')
	FROM T_RESULTADOS TR
		INNER JOIN T_BAREMOS TB ON TR.NO_FILA  = TB.NO_FILA
		INNER JOIN IDP.C_VARIABLE CV ON TB.CL_VARIABLE_BAREMOS = CV.CL_VARIABLE

	-- OBTENEMOS LE VALOR DE BAREMOS DEL COEFICIENTE INTELECTUAL
	SELECT @V_NO_BAREMOS_CI = [IDP].[F_OBTIENE_VALORES_BAREMOS](7, KR.NO_VALOR, 'APTITUD2_REP_CI')
	FROM IDP.C_VARIABLE CV 
		INNER JOIN IDP.K_RESULTADO KR ON CV.ID_VARIABLE = KR.ID_VARIABLE
		INNER JOIN ADM.K_CUESTIONARIO KC ON KR.ID_CUESTIONARIO = KC.ID_CUESTIONARIO
		INNER JOIN IDP.K_PRUEBA KP ON KC.ID_CUESTIONARIO = KP.ID_CUESTIONARIO
	WHERE KP.ID_BATERIA = @PIN_ID_BATERIA AND CV.CL_VARIABLE = 'APTITUD2_REP_CI'

	-- OBTENEMOS EL VALOR DE BAREMOS DE LA VELOCIDAD DE RESPUESTA DE LA PRUEBA
	SELECT @V_NO_BAREMOS_VELOCIDAD = [IDP].[F_OBTIENE_VALORES_BAREMOS](7, KR.NO_VALOR, 'APTITUD2_REP_C4')
	FROM IDP.C_VARIABLE CV 
		INNER JOIN IDP.K_RESULTADO KR ON CV.ID_VARIABLE = KR.ID_VARIABLE
		INNER JOIN ADM.K_CUESTIONARIO KC ON KR.ID_CUESTIONARIO = KC.ID_CUESTIONARIO
		INNER JOIN IDP.K_PRUEBA KP ON KC.ID_CUESTIONARIO = KP.ID_CUESTIONARIO
	WHERE KP.ID_BATERIA = @PIN_ID_BATERIA AND CV.CL_VARIABLE = 'APTITUD2_REP_C4'


	-- EL CALCULO DEL ULTIMO BAREMOS SE HARA DIRECTAMENTE EN EL PROCEDIMIENTO, PARA NO METER OTRA VARIABLE EN LA FUNCION
	IF @V_NO_BAREMOS_CI IS NOT NULL AND @V_NO_BAREMOS_VELOCIDAD IS NOT NULL BEGIN
		SET @V_NO_BAREMOS_APRENDIZAJE = CASE 
											WHEN (@V_NO_BAREMOS_CI = 3 AND @V_NO_BAREMOS_VELOCIDAD = 3) OR (@V_NO_BAREMOS_CI = 2 AND @V_NO_BAREMOS_VELOCIDAD = 3) THEN 3
											WHEN (@V_NO_BAREMOS_CI = 2 AND @V_NO_BAREMOS_VELOCIDAD = 2) OR (@V_NO_BAREMOS_CI = 3 AND @V_NO_BAREMOS_VELOCIDAD = 1) THEN 2
											WHEN (@V_NO_BAREMOS_CI = 2 AND @V_NO_BAREMOS_VELOCIDAD = 1) OR (@V_NO_BAREMOS_CI = 1 AND @V_NO_BAREMOS_VELOCIDAD = 2) THEN 1
											ELSE 0 END
	END

	IF @V_NO_BAREMOS_CI IS NOT NULL BEGIN
		INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA])
		SELECT CL_TIPO_VARIABLE, ID_VARIABLE, @V_NO_BAREMOS_CI, @V_ID_CUESTIONARIO, @V_FE_SISTEMA, @PIN_CL_USUARIO_APP,  @PIN_NB_PROGRAMA
		FROM IDP.C_VARIABLE
		WHERE CL_VARIABLE = 'AT-INTELIGENCIA'
	END

	IF @V_NO_BAREMOS_APRENDIZAJE IS NOT NULL BEGIN
		INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA])
		SELECT CL_TIPO_VARIABLE, ID_VARIABLE, @V_NO_BAREMOS_APRENDIZAJE, @V_ID_CUESTIONARIO, @V_FE_SISTEMA, @PIN_CL_USUARIO_APP,  @PIN_NB_PROGRAMA
		FROM IDP.C_VARIABLE
		WHERE CL_VARIABLE = 'AT-APRENDIZAJE'
	END
END


