
-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Juan De Dios Pérez Pedroza
-- CREATE date: 21/09/2015
-- Description: Obtiene los datos de la tabla C_PRUEBA_NIVEL 
-- =============================================
CREATE PROCEDURE [IDP].[SPE_OBTIENE_C_PRUEBA_NIVEL] 

	  @PIN_ID_PRUEBA_NIVEL AS int = NULL
	, @PIN_CL_PRUEBA_NIVEL AS nvarchar(20) = NULL
	, @PIN_NB_PRUEBA_NIVEL AS nvarchar(200) = NULL
AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT 
		  [ID_PRUEBA_NIVEL]
		, [CL_PRUEBA_NIVEL]
		, [NB_PRUEBA_NIVEL]

	FROM IDP.C_PRUEBA_NIVEL
	WHERE        (@PIN_ID_PRUEBA_NIVEL IS NULL OR (@PIN_ID_PRUEBA_NIVEL IS NOT NULL AND [ID_PRUEBA_NIVEL] = @PIN_ID_PRUEBA_NIVEL))
			 AND (@PIN_CL_PRUEBA_NIVEL IS NULL OR (@PIN_CL_PRUEBA_NIVEL IS NOT NULL AND [CL_PRUEBA_NIVEL] = @PIN_CL_PRUEBA_NIVEL))
			 AND (@PIN_NB_PRUEBA_NIVEL IS NULL OR (@PIN_NB_PRUEBA_NIVEL IS NOT NULL AND [NB_PRUEBA_NIVEL] = @PIN_NB_PRUEBA_NIVEL))
			
