
-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Juan De Dios Pérez Pedroza
-- CREATE date: 21/09/2015
-- Description: Obtiene los datos de la tabla K_PRUEBA
-- =============================================
CREATE PROCEDURE [IDP].[SPE_OBTIENE_K_PRUEBA] 
      @PIN_ID_PRUEBA AS int = NULL
	, @PIN_ID_PRUEBA_PLANTILLA AS int = NULL
	, @PIN_ID_CANDIDATO AS int = NULL
	, @PIN_ID_EMPLEADO AS int = NULL
	, @PIN_CL_EMPLEADO AS nvarchar(20) = NULL
	, @PIN_CL_ESTADO AS nvarchar(10) = NULL
	, @PIN_FE_INICIO AS datetime = NULL
	, @PIN_FE_TERMINO AS datetime = NULL
	, @PIN_NO_TIEMPO AS int = NULL	
	,@PIN_CL_TOKEN_EXTERNO AS UNIQUEIDENTIFIER = NULL
	,@PIN_CL_TOKEN_BATERIA AS UNIQUEIDENTIFIER = NULL
	, @PIN_ID_BATERIA AS int = NULL	
AS   
		--ACTUALIZAR VALOR DE INICIO SI SE ESTA CONSULTANDO UNA PRUEBA EN ESPECIFICO
	/*	DECLARE @V_EXIST_TRAN BIT = 0,
			@V_ID_CUESTIONARIO INT,
			@V_CL_ESTADO NVARCHAR(20),
			@V_NO_TIEMPO INT;

		SELECT @V_CL_ESTADO = CL_ESTADO,
			   @V_NO_TIEMPO = NO_TIEMPO
		FROM IDP.K_PRUEBA
		WHERE ID_PRUEBA_PLANTILLA = @PIN_ID_PRUEBA_PLANTILLA
		AND ID_PRUEBA = @PIN_ID_PRUEBA
		--AND CL_ESTADO = 'CREADA'
		AND CL_TOKEN_EXTERNO = @PIN_CL_TOKEN_EXTERNO;

		IF(ISNULL(@V_CL_ESTADO,'') = 'CREADA' )BEGIN
			--ACTUALIZAR A 'INICIADA'
			UPDATE IDP.K_PRUEBA
				SET FE_INICIO = ISNULL(@PIN_FE_INICIO,GETDATE())
				--,CL_ESTADO = 'INICIADA'
			WHERE ID_PRUEBA = @PIN_ID_PRUEBA;
		END;
	*/

		--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
		SELECT 
	      KP.[ID_PRUEBA]
		, KP.[ID_PRUEBA_PLANTILLA]
		, KP.[ID_CANDIDATO]
		, KP.[ID_EMPLEADO]
		, KP.[CL_EMPLEADO]
		, KP.[CL_ESTADO]
		, KP.[FE_INICIO]
		, KP.[FE_TERMINO]
		, KP.[NO_TIEMPO]
		, KP.[CL_TOKEN_EXTERNO]
		, CP.CL_PRUEBA
		, CP.NB_PRUEBA
		, CP.NO_TIEMPO_PRUEBA

	   ,CONCAT ( CC.[NB_CANDIDATO], ' ',CC.[NB_APELLIDO_PATERNO],' ' , CC.[NB_APELLIDO_MATERNO] ) AS NB_CANDIDATO_COMPLETO
	   ,CONCAT ( ME.[NB_EMPLEADO], ' ',ME.[NB_APELLIDO_PATERNO],' ' , ME.[NB_APELLIDO_MATERNO] ) AS NB_EMPLEADO_COMPLETO

	   ,KR.NO_REQUISICION
	   ,KR.ID_REQUISICION
	   ,CC.CL_CORREO_ELECTRONICO
	   ,KP.ID_BATERIA
		FROM IDP.K_BATERIA_PRUEBA KBP 
		JOIN IDP.K_PRUEBA AS KP ON KBP.ID_BATERIA = KP.ID_BATERIA
		LEFT OUTER JOIN IDP.C_PRUEBA CP ON KP.ID_PRUEBA_PLANTILLA = CP.ID_PRUEBA
		LEFT OUTER JOIN ADM.C_CANDIDATO CC ON KP.ID_CANDIDATO = CC.ID_CANDIDATO
		LEFT OUTER JOIN ADM.M_EMPLEADO ME ON KP.ID_EMPLEADO = ME.ID_EMPLEADO
		LEFT OUTER JOIN ADM.K_SOLICITUD KS ON KP.ID_CANDIDATO = KS.ID_CANDIDATO
		LEFT OUTER JOIN ADM.K_REQUISICION KR ON KS.ID_REQUISICION = KR.ID_REQUISICION
		WHERE			 (@PIN_ID_PRUEBA IS NULL OR (@PIN_ID_PRUEBA IS NOT NULL AND KP.[ID_PRUEBA] = @PIN_ID_PRUEBA  /*AND KP.CL_TOKEN_EXTERNO = @PIN_CL_TOKEN_EXTERNO*/))
				 AND (@PIN_CL_TOKEN_BATERIA IS NULL OR (@PIN_CL_TOKEN_BATERIA IS NOT NULL AND KBP.CL_TOKEN = @PIN_CL_TOKEN_BATERIA))
				 AND (@PIN_ID_PRUEBA_PLANTILLA IS NULL OR (@PIN_ID_PRUEBA_PLANTILLA IS NOT NULL AND KP.[ID_PRUEBA_PLANTILLA] = @PIN_ID_PRUEBA_PLANTILLA))
				 AND (@PIN_ID_CANDIDATO IS NULL OR (@PIN_ID_CANDIDATO IS NOT NULL AND KP.[ID_CANDIDATO] = @PIN_ID_CANDIDATO))
				 AND (@PIN_ID_EMPLEADO IS NULL OR (@PIN_ID_EMPLEADO IS NOT NULL AND KP.[ID_EMPLEADO] = @PIN_ID_EMPLEADO))
				 AND (@PIN_CL_EMPLEADO IS NULL OR (@PIN_CL_EMPLEADO IS NOT NULL AND KP.[CL_EMPLEADO] = @PIN_CL_EMPLEADO))
				 AND (@PIN_CL_ESTADO IS NULL OR (@PIN_CL_ESTADO IS NOT NULL AND KP.[CL_ESTADO] = @PIN_CL_ESTADO))
				 AND (@PIN_ID_BATERIA IS NULL OR (@PIN_ID_BATERIA IS NOT NULL AND KP.[ID_BATERIA] = @PIN_ID_BATERIA))
				 --AND (@PIN_FE_INICIO IS NULL OR (@PIN_FE_INICIO IS NOT NULL AND KP.[FE_INICIO] = @PIN_FE_INICIO))
				 --AND (@PIN_FE_TERMINO IS NULL OR (@PIN_FE_TERMINO IS NOT NULL AND KP.[FE_TERMINO] = @PIN_FE_TERMINO))
				 AND (@PIN_NO_TIEMPO IS NULL OR (@PIN_NO_TIEMPO IS NOT NULL AND KP.[NO_TIEMPO] = @PIN_NO_TIEMPO))
				 --AND (@PIN_CL_TOKEN_EXTERNO IS NULL OR (@PIN_CL_TOKEN_EXTERNO IS NOT NULL AND KP.CL_TOKEN_EXTERNO = @PIN_CL_TOKEN_EXTERNO))
ORDER BY CP.NO_ORDEN ASC
			--EXECUTE [IDP].[SPE_OBTIENE_K_PRUEBA] 

