-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: JUAN CASTILLO
-- CREATE date: 07/01/2016
-- Description: Obtiene los datos de la tabla C_PREGUNTA 
-- =============================================
CREATE PROCEDURE [IDP].[SPE_OBTIENE_K_PREGUNTA] 
	@PIN_ID_PREGUNTA AS int = NULL
	, @PIN_CL_PREGUNTA AS nvarchar(32) = NULL
	, @PIN_NB_PREGUNTA AS nvarchar(100) = NULL
	, @PIN_DS_PREGUNTA AS nvarchar(200) = NULL
	, @PIN_CL_TIPO_PREGUNTA AS nvarchar(10) = NULL
	, @PIN_NO_VALOR AS decimal(8,3) = NULL
	, @PIN_FG_REQUERIDO AS bit = NULL
	, @PIN_FG_ACTIVO AS bit = NULL
	, @PIN_ID_COMPETENCIA AS int = NULL
	, @PIN_ID_BITACORA AS int = NULL
	, @PIN_ID_PRUEBA AS INT = NULL
	, @PIN_ID_CUESTIONARIO AS INT = NULL
	, @PIN_CL_TOKEN_EXTERNO AS UNIQUEIDENTIFIER = NULL
	
AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT 
		ID_PRUEBA
		,[ID_CUESTIONARIO_PREGUNTA]
		,KCP.[ID_CUESTIONARIO]
		,KCP.[ID_PREGUNTA]
		, [CL_PREGUNTA]
		,KCP.[NB_PREGUNTA]
		, [DS_PREGUNTA]
		, [CL_TIPO_PREGUNTA]
		, [NO_VALOR]
		, [NO_VALOR_RESPUESTA]
		, [NB_RESPUESTA]
		, [FG_REQUERIDO]
		, [FG_ACTIVO]
		, [ID_COMPETENCIA]
		, [ID_BITACORA]
		,'' as DS_FILTRO
	FROM ADM.K_CUESTIONARIO_PREGUNTA KCP
	JOIN IDP.K_PRUEBA KPR ON KPR.ID_CUESTIONARIO= KCP.ID_CUESTIONARIO
	JOIN ADM.C_PREGUNTA CPR ON KCP.ID_PREGUNTA = CPR.ID_PREGUNTA
	WHERE ID_PRUEBA= @PIN_ID_PRUEBA
		AND CL_TOKEN_EXTERNO = @PIN_CL_TOKEN_EXTERNO
		AND (@PIN_ID_PREGUNTA IS NULL OR (@PIN_ID_PREGUNTA IS NOT NULL AND KCP.[ID_PREGUNTA] = @PIN_ID_PREGUNTA))
		AND (@PIN_CL_PREGUNTA IS NULL OR (@PIN_CL_PREGUNTA IS NOT NULL AND [CL_PREGUNTA] = @PIN_CL_PREGUNTA))
		AND (@PIN_NB_PREGUNTA IS NULL OR (@PIN_NB_PREGUNTA IS NOT NULL AND KCP.[NB_PREGUNTA] = @PIN_NB_PREGUNTA))
		AND (@PIN_DS_PREGUNTA IS NULL OR (@PIN_DS_PREGUNTA IS NOT NULL AND [DS_PREGUNTA] = @PIN_DS_PREGUNTA))
		AND (@PIN_CL_TIPO_PREGUNTA IS NULL OR (@PIN_CL_TIPO_PREGUNTA IS NOT NULL AND [CL_TIPO_PREGUNTA] = @PIN_CL_TIPO_PREGUNTA))
		AND (@PIN_NO_VALOR IS NULL OR (@PIN_NO_VALOR IS NOT NULL AND [NO_VALOR] = @PIN_NO_VALOR))
		AND (@PIN_FG_REQUERIDO IS NULL OR (@PIN_FG_REQUERIDO IS NOT NULL AND [FG_REQUERIDO] = @PIN_FG_REQUERIDO))
		AND (@PIN_FG_ACTIVO IS NULL OR (@PIN_FG_ACTIVO IS NOT NULL AND [FG_ACTIVO] = @PIN_FG_ACTIVO))
		AND (@PIN_ID_COMPETENCIA IS NULL OR (@PIN_ID_COMPETENCIA IS NOT NULL AND [ID_COMPETENCIA] = @PIN_ID_COMPETENCIA))
		AND (@PIN_ID_BITACORA IS NULL OR (@PIN_ID_BITACORA IS NOT NULL AND [ID_BITACORA] = @PIN_ID_BITACORA));
			
