-- =============================================
-- Proyecto: SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Daniela Sanchez
-- CRETAE date: 20/01/2016
-- Description: Inserta variables de respuesta de la prueba Aptitud metal 2
-- =============================================
CREATE PROCEDURE [IDP].[SPE_INSERTA_RESULTADOS_APTITUD2]
@XML_RESULTADO XML = '' OUT 
,@PIN_XML_RESULTADOS AS XML
	,@PIN_ID_CUESTIONARIO AS INT = NULL
	,@PIN_ID_PRUEBA AS INT
	,@PIN_CL_USUARIO_APP_CREA AS nvarchar(50)
    ,@PIN_NB_PROGRAMA_CREA AS nvarchar(50)
	AS 
BEGIN  
	--SE DECLARA E INICIALIZA LA VARIABLE QUE NOS INDICARA SI GENERAMOS LA TRANSACCION EN ESTE SP
	DECLARE @V_EXIST_TRAN BIT = 0,
			@V_FE_SISTEMA AS DATETIME = GETDATE()
    	BEGIN TRY
		--SE VERIFICA SI EXISTE UNA TRANSACCION EN EJECUCION
		IF (@@TRANCOUNT = 0) 
		BEGIN
			--EN CASO DE QUE NO SE INICIALIZA LA TRANSACCION
			BEGIN TRANSACTION
			--SE EDITA LA VARIABLE QUE INDICA QUE SE INICIO LA TRANSACCION EN ESTE BLOQUE PARA CANCELARLA SI ES NECESARIO
			SET @V_EXIST_TRAN = 1
		END	
		
			IF @PIN_ID_CUESTIONARIO IS NULL BEGIN

			SELECT @PIN_ID_CUESTIONARIO = ID_CUESTIONARIO
			FROM IDP.K_PRUEBA
			WHERE ID_PRUEBA = @PIN_ID_PRUEBA
	End


	--------------------------------------------------------


	-------------------------------------------------------
		
	IF @PIN_ID_CUESTIONARIO IS NULL
	
	 BEGIN
		
        
			INSERT INTO [IDP].[K_RESULTADO] ([CL_TIPO_RESULTADO] ,[ID_VARIABLE] ,[NO_VALOR], [ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA])
					SELECT 2, res.ID_VARIABLE, res.NO_VALOR, @PIN_ID_CUESTIONARIO, GETDATE(),@PIN_CL_USUARIO_APP_CREA,@PIN_NB_PROGRAMA_CREA
					FROM (
							SELECT
								d.value('@ID_VARIABLE', 'INT') AS ID_VARIABLE,
								d.value('@NO_VALOR', 'INT') AS NO_VALOR
							FROM @PIN_XML_RESULTADOS.nodes('RESULTADOS/RESULTADO') AS T(d)
					) AS res

					UPDATE IDP.K_PRUEBA 
					SET CL_ESTADO='TERMINADA'
					WHERE  ID_PRUEBA=@PIN_ID_PRUEBA

		END

		--------------------------------------------------------------------

		IF @PIN_ID_CUESTIONARIO IS NOT NULL
		BEGIN



		;WITH T_VARIABLES AS (
			SELECT 'APTITUD2-A-0001' AS CL_VARIABLE_RESP,'APTITUD2-RES-0001' AS CL_VARIABLE_RES, 4 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0002' AS CL_VARIABLE_RESP,'APTITUD2-RES-0002' AS CL_VARIABLE_RES, 3 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0003' AS CL_VARIABLE_RESP,'APTITUD2-RES-0003' AS CL_VARIABLE_RES, 4 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0004' AS CL_VARIABLE_RESP,'APTITUD2-RES-0004' AS CL_VARIABLE_RES, 4 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0005' AS CL_VARIABLE_RESP,'APTITUD2-RES-0005' AS CL_VARIABLE_RES, 2 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0006' AS CL_VARIABLE_RESP,'APTITUD2-RES-0006' AS CL_VARIABLE_RES, 1 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0007' AS CL_VARIABLE_RESP,'APTITUD2-RES-0007' AS CL_VARIABLE_RES, 5 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0008' AS CL_VARIABLE_RESP,'APTITUD2-RES-0008' AS CL_VARIABLE_RES, 5 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0009' AS CL_VARIABLE_RESP,'APTITUD2-RES-0009' AS CL_VARIABLE_RES, 1 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0010' AS CL_VARIABLE_RESP,'APTITUD2-RES-0010' AS CL_VARIABLE_RES, 3 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0011' AS CL_VARIABLE_RESP,'APTITUD2-RES-0011' AS CL_VARIABLE_RES, 2 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0012' AS CL_VARIABLE_RESP,'APTITUD2-RES-0012' AS CL_VARIABLE_RES, 2 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0013' AS CL_VARIABLE_RESP,'APTITUD2-RES-0013' AS CL_VARIABLE_RES, 5 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0014' AS CL_VARIABLE_RESP,'APTITUD2-RES-0014' AS CL_VARIABLE_RES, 2 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0015' AS CL_VARIABLE_RESP,'APTITUD2-RES-0015' AS CL_VARIABLE_RES, 4 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0016' AS CL_VARIABLE_RESP,'APTITUD2-RES-0016' AS CL_VARIABLE_RES, 4 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0017' AS CL_VARIABLE_RESP,'APTITUD2-RES-0017' AS CL_VARIABLE_RES, 4 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0018' AS CL_VARIABLE_RESP,'APTITUD2-RES-0018' AS CL_VARIABLE_RES, 5 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0019' AS CL_VARIABLE_RESP,'APTITUD2-RES-0019' AS CL_VARIABLE_RES, 2 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0020' AS CL_VARIABLE_RESP,'APTITUD2-RES-0020' AS CL_VARIABLE_RES, 3 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0021' AS CL_VARIABLE_RESP,'APTITUD2-RES-0021' AS CL_VARIABLE_RES, 4 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0022' AS CL_VARIABLE_RESP,'APTITUD2-RES-0022' AS CL_VARIABLE_RES, 3 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0023' AS CL_VARIABLE_RESP,'APTITUD2-RES-0023' AS CL_VARIABLE_RES, 3 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0024' AS CL_VARIABLE_RESP,'APTITUD2-RES-0024' AS CL_VARIABLE_RES, 4 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0025' AS CL_VARIABLE_RESP,'APTITUD2-RES-0025' AS CL_VARIABLE_RES, 5 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0026' AS CL_VARIABLE_RESP,'APTITUD2-RES-0026' AS CL_VARIABLE_RES, 3 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0027' AS CL_VARIABLE_RESP,'APTITUD2-RES-0027' AS CL_VARIABLE_RES, 5 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0028' AS CL_VARIABLE_RESP,'APTITUD2-RES-0028' AS CL_VARIABLE_RES, 2 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0029' AS CL_VARIABLE_RESP,'APTITUD2-RES-0029' AS CL_VARIABLE_RES, 5 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0030' AS CL_VARIABLE_RESP,'APTITUD2-RES-0030' AS CL_VARIABLE_RES, 5 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0031' AS CL_VARIABLE_RESP,'APTITUD2-RES-0031' AS CL_VARIABLE_RES, 1 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0032' AS CL_VARIABLE_RESP,'APTITUD2-RES-0032' AS CL_VARIABLE_RES, 3 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0033' AS CL_VARIABLE_RESP,'APTITUD2-RES-0033' AS CL_VARIABLE_RES, 2 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0034' AS CL_VARIABLE_RESP,'APTITUD2-RES-0034' AS CL_VARIABLE_RES, 4 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0035' AS CL_VARIABLE_RESP,'APTITUD2-RES-0035' AS CL_VARIABLE_RES, 3 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0036' AS CL_VARIABLE_RESP,'APTITUD2-RES-0036' AS CL_VARIABLE_RES, 1 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0037' AS CL_VARIABLE_RESP,'APTITUD2-RES-0037' AS CL_VARIABLE_RES, 2 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0038' AS CL_VARIABLE_RESP,'APTITUD2-RES-0038' AS CL_VARIABLE_RES, 2 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0039' AS CL_VARIABLE_RESP,'APTITUD2-RES-0039' AS CL_VARIABLE_RES, 1 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0040' AS CL_VARIABLE_RESP,'APTITUD2-RES-0040' AS CL_VARIABLE_RES, 1 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0041' AS CL_VARIABLE_RESP,'APTITUD2-RES-0041' AS CL_VARIABLE_RES, 3 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0042' AS CL_VARIABLE_RESP,'APTITUD2-RES-0042' AS CL_VARIABLE_RES, 2 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0043' AS CL_VARIABLE_RESP,'APTITUD2-RES-0043' AS CL_VARIABLE_RES, 1 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0044' AS CL_VARIABLE_RESP,'APTITUD2-RES-0044' AS CL_VARIABLE_RES, 3 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0045' AS CL_VARIABLE_RESP,'APTITUD2-RES-0045' AS CL_VARIABLE_RES, 2 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0046' AS CL_VARIABLE_RESP,'APTITUD2-RES-0046' AS CL_VARIABLE_RES, 3 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0047' AS CL_VARIABLE_RESP,'APTITUD2-RES-0047' AS CL_VARIABLE_RES, 3 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0048' AS CL_VARIABLE_RESP,'APTITUD2-RES-0048' AS CL_VARIABLE_RES, 1 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0049' AS CL_VARIABLE_RESP,'APTITUD2-RES-0049' AS CL_VARIABLE_RES, 3 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0050' AS CL_VARIABLE_RESP,'APTITUD2-RES-0050' AS CL_VARIABLE_RES, 2 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0051' AS CL_VARIABLE_RESP,'APTITUD2-RES-0051' AS CL_VARIABLE_RES, 4 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0052' AS CL_VARIABLE_RESP,'APTITUD2-RES-0052' AS CL_VARIABLE_RES, 1 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0053' AS CL_VARIABLE_RESP,'APTITUD2-RES-0053' AS CL_VARIABLE_RES, 1 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0054' AS CL_VARIABLE_RESP,'APTITUD2-RES-0054' AS CL_VARIABLE_RES, 3 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0055' AS CL_VARIABLE_RESP,'APTITUD2-RES-0055' AS CL_VARIABLE_RES, 3 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0056' AS CL_VARIABLE_RESP,'APTITUD2-RES-0056' AS CL_VARIABLE_RES, 4 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0057' AS CL_VARIABLE_RESP,'APTITUD2-RES-0057' AS CL_VARIABLE_RES, 3 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0058' AS CL_VARIABLE_RESP,'APTITUD2-RES-0058' AS CL_VARIABLE_RES, 3 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0059' AS CL_VARIABLE_RESP,'APTITUD2-RES-0059' AS CL_VARIABLE_RES, 5 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0060' AS CL_VARIABLE_RESP,'APTITUD2-RES-0060' AS CL_VARIABLE_RES, 4 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0061' AS CL_VARIABLE_RESP,'APTITUD2-RES-0061' AS CL_VARIABLE_RES, 3 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0062' AS CL_VARIABLE_RESP,'APTITUD2-RES-0062' AS CL_VARIABLE_RES, 4 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0063' AS CL_VARIABLE_RESP,'APTITUD2-RES-0063' AS CL_VARIABLE_RES, 1 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0064' AS CL_VARIABLE_RESP,'APTITUD2-RES-0064' AS CL_VARIABLE_RES, 3 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0065' AS CL_VARIABLE_RESP,'APTITUD2-RES-0065' AS CL_VARIABLE_RES, 4 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0066' AS CL_VARIABLE_RESP,'APTITUD2-RES-0066' AS CL_VARIABLE_RES, 3 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0067' AS CL_VARIABLE_RESP,'APTITUD2-RES-0067' AS CL_VARIABLE_RES, 1 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0068' AS CL_VARIABLE_RESP,'APTITUD2-RES-0068' AS CL_VARIABLE_RES, 4 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0069' AS CL_VARIABLE_RESP,'APTITUD2-RES-0069' AS CL_VARIABLE_RES, 4 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0070' AS CL_VARIABLE_RESP,'APTITUD2-RES-0070' AS CL_VARIABLE_RES, 2 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0071' AS CL_VARIABLE_RESP,'APTITUD2-RES-0071' AS CL_VARIABLE_RES, 4 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0072' AS CL_VARIABLE_RESP,'APTITUD2-RES-0072' AS CL_VARIABLE_RES, 1 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0073' AS CL_VARIABLE_RESP,'APTITUD2-RES-0073' AS CL_VARIABLE_RES, 2 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0074' AS CL_VARIABLE_RESP,'APTITUD2-RES-0074' AS CL_VARIABLE_RES, 3 AS NO_RESPUESTA UNION ALL
			SELECT 'APTITUD2-A-0075' AS CL_VARIABLE_RESP,'APTITUD2-RES-0075' AS CL_VARIABLE_RES, 5 AS NO_RESPUESTA )

			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA])
			SELECT 2 AS CL_TIPO_RESULTADO,V2.ID_VARIABLE, CASE WHEN R.NO_VALOR = 0 THEN -1  WHEN R.NO_VALOR = V.NO_RESPUESTA THEN 1 ELSE 0 END AS FG_CORRECTO, @PIN_ID_CUESTIONARIO, @V_FE_SISTEMA, @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA
			FROM T_VARIABLES V
				INNER JOIN IDP.C_VARIABLE V1 ON V.CL_VARIABLE_RESP = V1.CL_VARIABLE
				INNER JOIN IDP.C_VARIABLE V2 ON V.CL_VARIABLE_RES = V2.CL_VARIABLE
				INNER JOIN IDP.K_RESULTADO R ON V1.ID_VARIABLE = R.ID_VARIABLE
			WHERE R.ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO

			/*
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 280 AS ID_VARIABLE, CASE NO_VALOR WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 280 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 281 AS ID_VARIABLE, CASE NO_VALOR WHEN 3 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 281 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 282 AS ID_VARIABLE, CASE NO_VALOR WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 282 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 283 AS ID_VARIABLE, CASE NO_VALOR WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 283 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 284 AS ID_VARIABLE, CASE NO_VALOR WHEN 2 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 284 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 285 AS ID_VARIABLE, CASE NO_VALOR WHEN 1 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 285 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 286 AS ID_VARIABLE, CASE NO_VALOR WHEN 5 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 286 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 287 AS ID_VARIABLE, CASE NO_VALOR WHEN 5 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 287 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 288 AS ID_VARIABLE, CASE NO_VALOR WHEN 1 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 288 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 289 AS ID_VARIABLE, CASE NO_VALOR WHEN 3 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 289 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 290 AS ID_VARIABLE, CASE NO_VALOR WHEN 2 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 290 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 291 AS ID_VARIABLE, CASE NO_VALOR WHEN 2 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 291 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 292 AS ID_VARIABLE, CASE NO_VALOR WHEN 5 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 292 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 293 AS ID_VARIABLE, CASE NO_VALOR WHEN 2 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 293 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 294 AS ID_VARIABLE, CASE NO_VALOR WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 294 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 295 AS ID_VARIABLE, CASE NO_VALOR WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 295 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 296 AS ID_VARIABLE, CASE NO_VALOR WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 296 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 297 AS ID_VARIABLE, CASE NO_VALOR WHEN 5 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 297 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 298 AS ID_VARIABLE, CASE NO_VALOR WHEN 2 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 298 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 299 AS ID_VARIABLE, CASE NO_VALOR WHEN 3 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 299 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 300 AS ID_VARIABLE, CASE NO_VALOR WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 300 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 301 AS ID_VARIABLE, CASE NO_VALOR WHEN 3 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 301 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 302 AS ID_VARIABLE, CASE NO_VALOR WHEN 3 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 302 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 303 AS ID_VARIABLE, CASE NO_VALOR WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 303 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 304 AS ID_VARIABLE, CASE NO_VALOR WHEN 5 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 304 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 305 AS ID_VARIABLE, CASE NO_VALOR WHEN 3 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 305 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 306 AS ID_VARIABLE, CASE NO_VALOR WHEN 5 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 306 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 307 AS ID_VARIABLE, CASE NO_VALOR WHEN 2 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 307 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 308 AS ID_VARIABLE, CASE NO_VALOR WHEN 5 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 308 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 309 AS ID_VARIABLE, CASE NO_VALOR WHEN 5 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 309 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 310 AS ID_VARIABLE, CASE NO_VALOR WHEN 1 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 310 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 311 AS ID_VARIABLE, CASE NO_VALOR WHEN 3 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 311 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 312 AS ID_VARIABLE, CASE NO_VALOR WHEN 2 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 312 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 313 AS ID_VARIABLE, CASE NO_VALOR WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 313 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 314 AS ID_VARIABLE, CASE NO_VALOR WHEN 3 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 314 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 315 AS ID_VARIABLE, CASE NO_VALOR WHEN 1 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 315 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 316 AS ID_VARIABLE, CASE NO_VALOR WHEN 2 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 316 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 317 AS ID_VARIABLE, CASE NO_VALOR WHEN 2 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 317 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 318 AS ID_VARIABLE, CASE NO_VALOR WHEN 1 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 318 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 319 AS ID_VARIABLE, CASE NO_VALOR WHEN 1 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 319 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 320 AS ID_VARIABLE, CASE NO_VALOR WHEN 3 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 320 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 321 AS ID_VARIABLE, CASE NO_VALOR WHEN 2 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 321 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 322 AS ID_VARIABLE, CASE NO_VALOR WHEN 1 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 322 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 323 AS ID_VARIABLE, CASE NO_VALOR WHEN 3 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 323 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 324 AS ID_VARIABLE, CASE NO_VALOR WHEN 2 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 324 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 325 AS ID_VARIABLE, CASE NO_VALOR WHEN 3 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 325 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 326 AS ID_VARIABLE, CASE NO_VALOR WHEN 3 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 326 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 327 AS ID_VARIABLE, CASE NO_VALOR WHEN 1 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 327 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 328 AS ID_VARIABLE, CASE NO_VALOR WHEN 3 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 328 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 329 AS ID_VARIABLE, CASE NO_VALOR WHEN 2 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 329 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 330 AS ID_VARIABLE, CASE NO_VALOR WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 330 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 331 AS ID_VARIABLE, CASE NO_VALOR WHEN 1 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 331 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 332 AS ID_VARIABLE, CASE NO_VALOR WHEN 1 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 332 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 333 AS ID_VARIABLE, CASE NO_VALOR WHEN 3 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 333 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 334 AS ID_VARIABLE, CASE NO_VALOR WHEN 3 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 334 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 335 AS ID_VARIABLE, CASE NO_VALOR WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 335 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 336 AS ID_VARIABLE, CASE NO_VALOR WHEN 3 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 336 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 337 AS ID_VARIABLE, CASE NO_VALOR WHEN 3 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 337 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 338 AS ID_VARIABLE, CASE NO_VALOR WHEN 5 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 338 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 339 AS ID_VARIABLE, CASE NO_VALOR WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 339 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 340 AS ID_VARIABLE, CASE NO_VALOR WHEN 3 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 340 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 341 AS ID_VARIABLE, CASE NO_VALOR WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 341 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 342 AS ID_VARIABLE, CASE NO_VALOR WHEN 1 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 342 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 343 AS ID_VARIABLE, CASE NO_VALOR WHEN 3 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 343 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 344 AS ID_VARIABLE, CASE NO_VALOR WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 344 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 345 AS ID_VARIABLE, CASE NO_VALOR WHEN 3 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 345 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 346 AS ID_VARIABLE, CASE NO_VALOR WHEN 1 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 346 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 347 AS ID_VARIABLE, CASE NO_VALOR WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 347 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 348 AS ID_VARIABLE, CASE NO_VALOR WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 348 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 349 AS ID_VARIABLE, CASE NO_VALOR WHEN 2 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 349 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 350 AS ID_VARIABLE, CASE NO_VALOR WHEN 4 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 350 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 351 AS ID_VARIABLE, CASE NO_VALOR WHEN 1 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 351 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 352 AS ID_VARIABLE, CASE NO_VALOR WHEN 2 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 352 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 353 AS ID_VARIABLE, CASE NO_VALOR WHEN 3 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 353 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 354 AS ID_VARIABLE, CASE NO_VALOR WHEN 5 THEN 1 ELSE 0 END AS NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 354 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			*/

		END 

		EXEC [IDP].[SPE_INSERTA_REPORTE_APTITUD2] @XML_RESULTADO OUT, @PIN_ID_CUESTIONARIO, @PIN_CL_USUARIO_APP_CREA, @PIN_NB_PROGRAMA_CREA

		--SE DEVUELVE LA VARIABLE DE RETORNO INDICANDO QUE TODO SE REALIZO CORRECTAMENTE
		SET @XML_RESULTADO = DBO.F_ERROR_CREAR_ENCABEZADO( @@ROWCOUNT, 1, 'SUCCESSFUL')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'Proceso exitoso', 'ES')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'Successful Process', 'EN')
		--SI SE GENERO UNA TRANSACCION EN ESTE BLOQUE LA TERMINARA
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			COMMIT
	END TRY
	BEGIN CATCH
		--SI OCURRIO UN ERROR Y SE INICIO UNA TRANSACCION ENE ESTE BLOQUE SE CANCELARA LA TRANSACCION
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			ROLLBACK
		--SE INDICA EN LA VARIABLE DE RETORNO QUE OCURRIO UN ERROR
		--SET @POUT_CLAVE_RETORNO = 0
		--SE INSERTA EL ERROR EN LA TABLA
		DECLARE @ERROR_CLAVE INT  = ERROR_NUMBER()
		DECLARE @ERROR_MENSAJE NVARCHAR(250)  = ERROR_MESSAGE()
		
		SET @XML_RESULTADO = DBO.F_ERROR_CREAR_ENCABEZADO( @@ROWCOUNT, @ERROR_CLAVE, 'ERROR')
		SET @XML_RESULTADO = DBO.F_ERROR_MENSAJES(@ERROR_CLAVE,@ERROR_MENSAJE)
		SET @XML_RESULTADO = DBO.F_ERROR_MENSAJES(@ERROR_CLAVE,@ERROR_MENSAJE)			
	END CATCH
END


