-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Gabriel Vázquez
-- CREATE date: 20/01/2016
-- Description: Insercion de variables de la prueba de Pensamiento
-- =============================================
CREATE PROCEDURE [IDP].[SPE_INSERTA_RESULTADOS_PENSAMIENTO]
	@XML_RESULTADO XML = '' OUT      --APLICA PARA REGRESAR UN NÚMERO 0 PARA ERROR Y 1 PARA CORRECTO
	,@PIN_XML_RESULTADOS AS XML
	,@PIN_ID_CUESTIONARIO AS INT = NULL
	,@PIN_ID_PRUEBA AS INT
	,@PIN_CL_USUARIO_APP AS NVARCHAR(50)
	,@PIN_NB_PROGRAMA AS NVARCHAR(50)

AS
BEGIN  
	--SE DECLARA E INICIALIZA LA VARIABLE QUE NOS INDICARA SI GENERAMOS LA TRANSACCION EN ESTE SP
	DECLARE @V_EXIST_TRAN BIT = 0
			,@V_FE_SISTEMA AS DATETIME = GETDATE()
    	BEGIN TRY
		--SE VERIFICA SI EXISTE UNA TRANSACCION EN EJECUCION
		IF (@@TRANCOUNT = 0) 
		BEGIN
			--EN CASO DE QUE NO SE INICIALIZA LA TRANSACCION
			BEGIN TRANSACTION
			--SE EDITA LA VARIABLE QUE INDICA QUE SE INICIO LA TRANSACCION EN ESTE BLOQUE PARA CANCELARLA SI ES NECESARIO
			SET @V_EXIST_TRAN = 1
		END	
		--SE VERIFICA SI SE INSERTA EL REGISTRO O SE ACTUALIZARA SEGUN LA VARIABLE DE TIPO DE TRANSACCION  QUE RECIBE EL SP
		IF @PIN_ID_CUESTIONARIO IS NULL BEGIN

			SELECT @PIN_ID_CUESTIONARIO = ID_CUESTIONARIO
			FROM IDP.K_PRUEBA
			WHERE ID_PRUEBA = @PIN_ID_PRUEBA

		END

		IF @PIN_XML_RESULTADOS IS NULL 
		BEGIN
			
			;WITH T_VARIABLE AS (
				SELECT 'PENSAMIENTO-A-0001' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_A1' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-A-0002' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_A2' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-A-0003' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_A3' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-A-0004' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_A4' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-A-0005' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_A5' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-A-0006' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_A6' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-A-0007' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_A7' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-A-0008' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_A8' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-A-0009' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_A9' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-A-0010' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_A10' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-A-0011' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_A11' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-A-0012' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_A12' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-A-0013' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_A13' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-A-0014' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_A14' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-A-0015' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_A15' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-A-0016' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_A16' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-A-0017' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_A17' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-A-0018' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_A18' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-A-0019' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_A19' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-A-0020' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_A20' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-B-0001' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_B1' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-B-0002' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_B2' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-B-0003' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_B3' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-B-0004' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_B4' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-B-0005' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_B5' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-B-0006' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_B6' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-B-0007' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_B7' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-B-0008' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_B8' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-B-0009' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_B9' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-B-0010' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_B10' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-B-0011' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_B11' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-B-0012' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_B12' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-B-0013' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_B13' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-B-0014' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_B14' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-B-0015' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_B15' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-B-0016' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_B16' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-B-0017' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_B17' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-B-0018' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_B18' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-B-0019' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_B19' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-B-0020' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_B20' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-C-0001' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_C1' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-C-0002' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_C2' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-C-0003' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_C3' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-C-0004' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_C4' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-C-0005' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_C5' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-C-0006' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_C6' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-C-0007' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_C7' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-C-0008' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_C8' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-C-0009' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_C9' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-C-0010' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_C10' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-C-0011' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_C11' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-C-0012' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_C12' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-C-0013' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_C13' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-C-0014' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_C14' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-C-0015' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_C15' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-C-0016' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_C16' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-C-0017' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_C17' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-C-0018' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_C18' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-C-0019' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_C19' AS CL_VARIABLE_RESULTADO UNION ALL
				SELECT 'PENSAMIENTO-C-0020' AS CL_VARIABLE_RESPUESTA, 'PENSAMIENTO_RES_C20' AS CL_VARIABLE_RESULTADO
			)

			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA])
			SELECT 2 AS CL_TIPO_RESULTADO, v2.ID_VARIABLE, r.NO_VALOR, @PIN_ID_CUESTIONARIO, @V_FE_SISTEMA, @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA
			 FROM T_VARIABLE v
				INNER JOIN IDP.C_VARIABLE v1 ON V.CL_VARIABLE_RESPUESTA = v1.CL_VARIABLE
				INNER JOIN IDP.C_VARIABLE v2 ON v.CL_VARIABLE_RESULTADO = v2.CL_VARIABLE
				INNER JOIN IDP.K_RESULTADO r ON v1.ID_VARIABLE = R.ID_VARIABLE
			WHERE r.ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO

			/*
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 490 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 430 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 491 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 431 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 492 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 432 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 493 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 433 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 494 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 434 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 495 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 435 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 496 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 436 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 497 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 437 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 498 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 438 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 499 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 439 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 500 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 440 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 501 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 441 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 502 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 442 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 503 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 443 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 504 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 444 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 505 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 445 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 506 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 446 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 507 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 447 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 508 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 448 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 509 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 449 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 510 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 450 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 511 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 451 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 512 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 452 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 513 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 453 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 514 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 454 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 515 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 455 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 516 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 456 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 517 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 457 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 518 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 458 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 519 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 459 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 520 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 460 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 521 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 461 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 522 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 462 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 523 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 463 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 524 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 464 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 525 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 465 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 526 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 466 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 527 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 467 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 528 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 468 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 529 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 469 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 530 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 470 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 531 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 471 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 532 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 472 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 533 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 473 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 534 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 474 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 535 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 475 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 536 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 476 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 537 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 477 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 538 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 478 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 539 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 479 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 540 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 480 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 541 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 481 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 542 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 482 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 543 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 483 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 544 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 484 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 545 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 485 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 546 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 486 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 547 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 487 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 548 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 488 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA]) SELECT 2 AS CL_TIPO_RESULTADO, 549 AS ID_VARIABLE, NO_VALOR, ID_CUESTIONARIO, GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA FROM IDP.K_RESULTADO WHERE ID_VARIABLE = 489 AND ID_CUESTIONARIO = @PIN_ID_CUESTIONARIO
			*/
		END 
		
		IF @PIN_XML_RESULTADOS IS NOT NULL 
		BEGIN

			INSERT INTO [IDP].[K_RESULTADO] ([CL_TIPO_RESULTADO] ,[ID_VARIABLE] ,[NO_VALOR], [ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA])
					SELECT 2, res.ID_VARIABLE, res.NO_VALOR_RESPUESTA, @PIN_ID_CUESTIONARIO, @V_FE_SISTEMA,@PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA
					FROM (
							SELECT
								d.value('@ID_VARIABLE', 'INT') AS ID_VARIABLE,
								d.value('@NO_VALOR', 'INT') AS NO_VALOR_RESPUESTA
							FROM @PIN_XML_RESULTADOS.nodes('RESULTADOS/RESULTADO') AS T(d)
					) AS res
		END

		EXEC [IDP].[SPE_INSERTA_REPORTE_PENSAMIENTO] @XML_RESULTADO OUT, @PIN_ID_CUESTIONARIO, @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA

		--SE DEVUELVE LA VARIABLE DE RETORNO INDICANDO QUE TODO SE REALIZO CORRECTAMENTE
		SET @XML_RESULTADO = DBO.F_ERROR_CREAR_ENCABEZADO( @@ROWCOUNT, 1, 'SUCCESSFUL')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'Proceso exitoso', 'ES')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'Successful Process', 'EN')
		--SI SE GENERO UNA TRANSACCION EN ESTE BLOQUE LA TERMINARA
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			COMMIT
	END TRY
	BEGIN CATCH
		--SI OCURRIO UN ERROR Y SE INICIO UNA TRANSACCION ENE ESTE BLOQUE SE CANCELARA LA TRANSACCION
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			ROLLBACK
		--SE INDICA EN LA VARIABLE DE RETORNO QUE OCURRIO UN ERROR
		--SET @POUT_CLAVE_RETORNO = 0
		--SE INSERTA EL ERROR EN LA TABLA
		DECLARE @ERROR_CLAVE INT  = ERROR_NUMBER()
		DECLARE @ERROR_MENSAJE NVARCHAR(250)  = ERROR_MESSAGE()
		
		SET @XML_RESULTADO = DBO.F_ERROR_CREAR_ENCABEZADO( @@ROWCOUNT, @ERROR_CLAVE, 'ERROR')
		SET @XML_RESULTADO = DBO.F_ERROR_MENSAJES(@ERROR_CLAVE,@ERROR_MENSAJE)
		SET @XML_RESULTADO = DBO.F_ERROR_MENSAJES(@ERROR_CLAVE,@ERROR_MENSAJE)			
	END CATCH
END


