
-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Juan De Dios Pérez Pedroza
-- CREATE date: 02/01/2016
-- Description: Obtiene los datos de la tabla C_AREA_INTERES 
-- =============================================
CREATE PROCEDURE [IDP].[SPE_OBTIENE_C_PRUEBA] 
	  @PIN_ID_PRUEBA int = NULL
	, @PIN_CL_PRUEBA AS nvarchar(10) = NULL
	, @PIN_NB_PRUEBA AS nvarchar(200) = NULL
	, @PIN_ID_CUESTIONARIO AS INT = NULL
	, @PIN_NO_TIEMPO_PRUEBA AS smallint = NULL

AS   
	--SE DEVUELVE LOS REGISTROS EN BASE A LOS PARAMETROS INSERTADOS
	SELECT 
		[ID_PRUEBA]
		,[CL_PRUEBA]
		,[NB_PRUEBA]
		,[ID_CUESTIONARIO]
	    ,[NO_TIEMPO_PRUEBA]

	FROM [SIGEIN].[IDP].[C_PRUEBA]
	WHERE	     (@PIN_ID_PRUEBA IS NULL OR (@PIN_ID_PRUEBA IS NOT NULL AND [ID_PRUEBA] = @PIN_ID_PRUEBA))
			 AND (@PIN_CL_PRUEBA IS NULL OR (@PIN_CL_PRUEBA IS NOT NULL AND [CL_PRUEBA] = @PIN_CL_PRUEBA))
			 AND (@PIN_NB_PRUEBA IS NULL OR (@PIN_NB_PRUEBA IS NOT NULL AND [NB_PRUEBA] = @PIN_NB_PRUEBA))
			 AND (@PIN_ID_CUESTIONARIO IS NULL OR (@PIN_ID_CUESTIONARIO IS NOT NULL AND [ID_CUESTIONARIO] = @PIN_ID_CUESTIONARIO))
			 AND (@PIN_NO_TIEMPO_PRUEBA IS NULL OR (@PIN_NO_TIEMPO_PRUEBA IS NOT NULL AND [NO_TIEMPO_PRUEBA] = @PIN_NO_TIEMPO_PRUEBA))
			
