-- =============================================
-- Proyecto: Sistema SIGEIN  5.0
-- Copyright (c) - Acrux - 2015
-- Author: Juan Castillo
-- CRETAE date: 29/01/2015
-- Description: Actualiza estatus de baterias a enviadas
-- =============================================
-- =============================================
CREATE PROCEDURE [IDP].[SPE_ACTUALIZA_BATERIAS_ENVIADAS] 
		  @XML_RESULTADO XML = '' OUT      --APLICA PARA REGRESAR UN NÚMERO 0 PARA ERROR Y 1 PARA CORRECTO    	
		, @PIN_XML_BATERIAS AS xml
		, @PIN_CL_USUARIO AS nvarchar(50)
		, @PIN_NB_PROGRAMA_CREA AS nvarchar(50)	

AS 
BEGIN  
	--SE DECLARA E INICIALIZA LA VARIABLE QUE NOS INDICARA SI GENERAMOS LA TRANSACCION EN ESTE SP
	DECLARE @V_EXIST_TRAN BIT = 0;

    	BEGIN TRY
		--SE VERIFICA SI EXISTE UNA TRANSACCION EN EJECUCION
		IF (@@TRANCOUNT = 0) 
		BEGIN
			--EN CASO DE QUE NO SE INICIALIZA LA TRANSACCION
			BEGIN TRANSACTION
			--SE EDITA LA VARIABLE QUE INDICA QUE SE INICIO LA TRANSACCION EN ESTE BLOQUE PARA CANCELARLA SI ES NECESARIO
			SET @V_EXIST_TRAN = 1
		END
			UPDATE KBP
			SET FG_ENVIO_CORREO = '1'
			FROM IDP.K_BATERIA_PRUEBA KBP
			JOIN @PIN_XML_BATERIAS.nodes('/BATERIAS/BATERIA') tbl(COLUMNA)
			ON COLUMNA.value('@ID_BATERIA', 'int') = KBP.ID_BATERIA;
			

			--SE DEVUELVE LA VARIABLE DE RETORNO INDICANDO QUE TODO SE REALIZO CORRECTAMENTE		

			SET @XML_RESULTADO = DBO.F_ERROR_CREAR_ENCABEZADO( @@ROWCOUNT, 1, 'SUCCESSFUL')
			SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'ENVIO CORRECTO', 'ES')
			SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'ENVIO CORRECTO', 'EN')
			--SI SE GENERO UNA TRANSACCION EN ESTE BLOQUE LA TERMINARA
			IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
				COMMIT	
	END TRY
	BEGIN CATCH		
		--SI OCURRIO UN ERROR Y SE INICIO UNA TRANSACCION ENE ESTE BLOQUE SE CANCELARA LA TRANSACCION
		IF (@@TRANCOUNT > 0 AND @V_EXIST_TRAN = 1)
			ROLLBACK
		--SE INDICA EN LA VARIABLE DE RETORNO QUE OCURRIO UN ERROR
		
		--SE INSERTA EL ERROR EN LA TABLA		
		DECLARE @ERROR_CLAVE INT  = 	ERROR_NUMBER()
		DECLARE @ERROR_MENSAJE NVARCHAR(250)  = 	 ERROR_MESSAGE()

		SET @XML_RESULTADO = DBO.F_ERROR_CREAR_ENCABEZADO( @@ROWCOUNT, @ERROR_CLAVE, 'ERROR')
		SET @XML_RESULTADO = DBO.F_ERROR_MENSAJES(@ERROR_CLAVE,@ERROR_MENSAJE)
		SET @XML_RESULTADO = DBO.F_ERROR_MENSAJES(@ERROR_CLAVE,@ERROR_MENSAJE)
			
	END CATCH
END
