-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Gabriel Vázquez
-- CREATE date: 10/02/2016
-- Description: inserción de variables de baremos de prueba APTITUD MENTAL 1
-- =============================================
CREATE PROCEDURE [IDP].[SPE_INSERTA_BAREMOS_TIVA]
	 @PIN_ID_BATERIA AS INT
	,@PIN_CL_USUARIO_APP AS NVARCHAR(50)
	,@PIN_NB_PROGRAMA AS NVARCHAR(50)

AS
BEGIN  
	--SE DECLARA E INICIALIZA LA VARIABLE QUE NOS INDICARA SI GENERAMOS LA TRANSACCION EN ESTE SP
	DECLARE @V_EXIST_TRAN BIT = 0,
			@V_FE_SISTEMA AS DATETIME = GETDATE()

	DECLARE @V_ID_CUESTIONARIO AS INT

	SELECT @V_ID_CUESTIONARIO = ID_CUESTIONARIO_BAREMOS
	FROM IDP.K_BATERIA_PRUEBA
	WHERE ID_BATERIA = @PIN_ID_BATERIA

	;WITH T_VARIABLE AS (
		SELECT 'TV-PERSONAL'					AS CL_VARIABLE_BAREMOS, 'TIVA-REP_INDICE_IP' AS CL_VARIABLE_REPORTE UNION ALL
		SELECT 'TV-LEYES Y REGLAMENTOS'			AS CL_VARIABLE_BAREMOS, 'TIVA-REP_INDICE_ALR' AS CL_VARIABLE_REPORTE UNION ALL
		SELECT 'TV-INTEGRIDAD Y ÉTICA LABORAL'	AS CL_VARIABLE_BAREMOS, 'TIVA-REP_INDICE_IEL' AS CL_VARIABLE_REPORTE UNION ALL
		SELECT 'TV-CÍVICA'						AS CL_VARIABLE_BAREMOS, 'TIVA-REP_INDICE_IC' AS CL_VARIABLE_REPORTE UNION ALL
		SELECT 'TV-TOTAL'						AS CL_VARIABLE_BAREMOS, 'TIVA-REP_INDICE_GI' AS CL_VARIABLE_REPORTE
	)

	INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA])
	SELECT CV2.CL_TIPO_VARIABLE, CV2.ID_VARIABLE, [IDP].[F_OBTIENE_VALORES_BAREMOS](9, KR.NO_VALOR, NULL), @V_ID_CUESTIONARIO, @V_FE_SISTEMA, @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA 
	FROM T_VARIABLE TV
		INNER JOIN IDP.C_VARIABLE CV1 ON TV.CL_VARIABLE_REPORTE = CV1.CL_VARIABLE
		INNER JOIN IDP.K_RESULTADO KR ON CV1.ID_VARIABLE = KR.ID_VARIABLE
		INNER JOIN ADM.K_CUESTIONARIO KC ON KR.ID_CUESTIONARIO = KC.ID_CUESTIONARIO
		INNER JOIN IDP.K_PRUEBA KP ON KC.ID_CUESTIONARIO = KP.ID_CUESTIONARIO
		INNER JOIN IDP.C_VARIABLE CV2 ON TV.CL_VARIABLE_BAREMOS = CV2.CL_VARIABLE
	WHERE KP.ID_BATERIA = @PIN_ID_BATERIA

END


