-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Gabriel Vázquez
-- CREATE date: 10/02/2016
-- Description: inserción de variables de baremos de prueba APTITUD MENTAL 1
-- =============================================
CREATE PROCEDURE [IDP].[SPE_INSERTA_BAREMOS_ORTOGRAFIAS]
	 @PIN_ID_BATERIA AS INT
	,@PIN_CL_USUARIO_APP AS NVARCHAR(50)
	,@PIN_NB_PROGRAMA AS NVARCHAR(50)

AS
BEGIN  
	--SE DECLARA E INICIALIZA LA VARIABLE QUE NOS INDICARA SI GENERAMOS LA TRANSACCION EN ESTE SP
	DECLARE @V_EXIST_TRAN BIT = 0,
			@V_FE_SISTEMA AS DATETIME = GETDATE()

	DECLARE @V_ID_CUESTIONARIO AS INT,
			@V_NO_VALOR AS INT

		
	SELECT @V_ID_CUESTIONARIO = ID_CUESTIONARIO_BAREMOS
	FROM IDP.K_BATERIA_PRUEBA
	WHERE ID_BATERIA = @PIN_ID_BATERIA

	SELECT @V_NO_VALOR = SUM(KR.NO_VALOR)
	FROM IDP.C_VARIABLE CV
		INNER JOIN IDP.K_RESULTADO KR ON CV.ID_VARIABLE = KR.ID_VARIABLE
		INNER JOIN ADM.K_CUESTIONARIO KC ON KR.ID_CUESTIONARIO = KC.ID_CUESTIONARIO
		INNER JOIN IDP.K_PRUEBA KP ON KC.ID_CUESTIONARIO = KP.ID_CUESTIONARIO
	WHERE KP.ID_BATERIA = @PIN_ID_BATERIA AND CV.CL_VARIABLE IN ('ORTOGRAFIA1-RES-01', 'ORTOGRAFIA2-RES-01', 'ORTOGRAFIA3-RES-01')


	IF @V_NO_VALOR IS NOT NULL BEGIN
		INSERT INTO [IDP].[K_RESULTADO]([CL_TIPO_RESULTADO],[ID_VARIABLE],[NO_VALOR],[ID_CUESTIONARIO],[FE_CREACION],[CL_USUARIO_APP_CREA],[NB_PROGRAMA_CREA])
		VALUES(4, 1289, IDP.F_OBTIENE_VALORES_BAREMOS(10, @V_NO_VALOR, NULL), @V_ID_CUESTIONARIO,dbo.F_GETDATE(), @PIN_CL_USUARIO_APP, @PIN_NB_PROGRAMA)
	END

END


