-- =============================================
-- Proyecto: Sistema SIGEIN 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Julio Díaz
-- CREATE date: 19/01/2016
-- Description: Vista del porcentaje del nivel de dominio del idioma
-- =============================================

CREATE VIEW [ADM].[VW_IDIOMA_CERTIFICADO]
AS
SELECT CAST(0 AS INT) AS CL_IDIOMA_CERTIFICADO, 'N/A' AS NB_IDIOMA_CERTIFICADO UNION 
SELECT CAST(1 AS INT) AS CL_IDIOMA_CERTIFICADO, 'TOEFL' AS NB_IDIOMA_CERTIFICADO UNION 
SELECT CAST(2 AS INT) AS CL_IDIOMA_CERTIFICADO, 'TOEIC' AS NB_IDIOMA_CERTIFICADO UNION 
SELECT CAST(3 AS INT) AS CL_IDIOMA_CERTIFICADO, 'IELTS' AS NB_IDIOMA_CERTIFICADO UNION 
SELECT CAST(4 AS INT) AS CL_IDIOMA_CERTIFICADO, 'EXCI' AS NB_IDIOMA_CERTIFICADO

