-- =============================================
-- Proyecto: Sigein 5.0
-- Copyright (c) - Acrux - 2015
-- Author: Margarita Salcedo
-- CRETAE date: 14/09/2015
-- Description: Inserta un nuevo C_SECUENCIA
-- =============================================

CREATE VIEW ADM.VW_OBTIENE_MESES
AS

	SELECT 1 AS NUMERO, 'ENERO' AS MES
	UNION
	SELECT 2 AS NUMERO, 'FEBRERO' AS MES
	UNION
	SELECT 3 AS NUMERO, 'MARZO' AS MES
	UNION
	SELECT 4 AS NUMERO, 'ABRIL' AS MES
	UNION
	SELECT 5 AS NUMERO, 'MAYO' AS MES
	UNION
	SELECT 6 AS NUMERO, 'JUNIO' AS MES
	UNION
	SELECT 7 AS NUMERO, 'JULIO' AS MES
	UNION
	SELECT 8 AS NUMERO, 'AGOSTO' AS MES
	UNION
	SELECT 9 AS NUMERO, 'SEPTIEMBRE' AS MES
	UNION
	SELECT 10 AS NUMERO, 'OCTUBRE' AS MES
	UNION
	SELECT 11 AS NUMERO, 'NOVIEMBRE' AS MES
	UNION
	SELECT 12 AS NUMERO, 'DICIEMBRE' AS MES