
 CREATE VIEW [ADM].[VW_TIPO_ESCOLARIDAD] AS
  SELECT 1 AS ID_NIVEL_ESCOLARIDAD, 'Primaria' AS DS_NIVEL_ESCOLARIDAD, 'PRIMARIA' AS CL_TIPO_ESCOLARIDAD UNION ALL
  SELECT 2 AS ID_NIVEL_ESCOLARIDAD, 'Secundaria' AS DS_NIVEL_ESCOLARIDAD, 'SECUNDARIA' AS CL_TIPO_ESCOLARIDAD UNION ALL
  SELECT 3 AS ID_NIVEL_ESCOLARIDAD, 'Preparatoria' AS DS_NIVEL_ESCOLARIDAD, 'PREPARATORIA' AS CL_TIPO_ESCOLARIDAD UNION ALL
  SELECT 4 AS ID_NIVEL_ESCOLARIDAD, 'Técnica' AS DS_NIVEL_ESCOLARIDAD, 'TECNICA' AS CL_TIPO_ESCOLARIDAD UNION ALL
  SELECT 5 AS ID_NIVEL_ESCOLARIDAD, 'Profesional' AS DS_NIVEL_ESCOLARIDAD, 'PROFESIONAL' AS CL_TIPO_ESCOLARIDAD UNION ALL
  SELECT 6 AS ID_NIVEL_ESCOLARIDAD, 'Postgrado' AS DS_NIVEL_ESCOLARIDAD, 'POSTGRADO' AS CL_TIPO_ESCOLARIDAD
  --FROM ADM.C_NIVEL_ESCOLARIDAD

