
CREATE VIEW [ADM].[VW_ZONA_LOCALIDAD]
AS
SELECT 'Rural' AS CL_ZONA_LOCALIDAD, 'Aeropuerto' AS NB_ZONA_LOCALIDAD UNION ALL
SELECT 'Semiurbano' AS CL_ZONA_LOCALIDAD, 'Aeropuerto' AS NB_ZONA_LOCALIDAD UNION ALL
SELECT 'Urbano' AS CL_ZONA_LOCALIDAD, 'Aeropuerto' AS NB_ZONA_LOCALIDAD
