CREATE TABLE [ADM].[C_CAMPO_ADICIONAL] (
    [ID_CAMPO]                INT            IDENTITY (1, 1) NOT NULL,
    [CL_CAMPO]                NVARCHAR (32)  NOT NULL,
    [NB_CAMPO]                NVARCHAR (100) NOT NULL,
    [DS_CAMPO]                NVARCHAR (200) NULL,
    [FG_REQUERIDO]            BIT            DEFAULT ((0)) NOT NULL,
    [NO_VALOR_DEFECTO]        NVARCHAR (200) NULL,
    [CL_TIPO_DATO]            NVARCHAR (20)  NOT NULL,
    [CL_DIMENSION]            NVARCHAR (20)  NOT NULL,
    [CL_TABLA_REFERENCIA]     NVARCHAR (50)  NOT NULL,
    [CL_ESQUEMA_REFERENCIA]   NVARCHAR (10)  NOT NULL,
    [FG_MOSTRAR]              BIT            NULL,
    [ID_CATALOGO_LIST]        INT            NULL,
    [FG_ADICIONAL]            BIT            NULL,
    [FE_CREACION]             DATETIME       NOT NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([ID_CAMPO] ASC)
);

