CREATE TABLE [ADM].[C_CATALOGO_VALOR] (
    [ID_CATALOGO_VALOR]       INT             IDENTITY (1, 1) NOT NULL,
    [CL_CATALOGO_VALOR]       NVARCHAR (20)   NOT NULL,
    [NB_CATALOGO_VALOR]       NVARCHAR (100)  NOT NULL,
    [DS_CATALOGO_VALOR]       NVARCHAR (1000) NULL,
    [ID_CATALOGO_LISTA]       INT             NOT NULL,
    [FE_CREACION]             DATETIME        NOT NULL,
    [FE_MODIFICACION]         DATETIME        NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)   NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)   NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)   NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)   NULL,
    CONSTRAINT [PK_C_CATALOGO_VALOR] PRIMARY KEY CLUSTERED ([ID_CATALOGO_VALOR] ASC),
    CONSTRAINT [FK_C_CATALOGO_VALOR_C_CATALOGO_LISTA] FOREIGN KEY ([ID_CATALOGO_LISTA]) REFERENCES [ADM].[C_CATALOGO_LISTA] ([ID_CATALOGO_LISTA]),
    CONSTRAINT [UC_CL_CATALOGO_VALOR] UNIQUE NONCLUSTERED ([CL_CATALOGO_VALOR] ASC),
    CONSTRAINT [UC_NB_CATALOGO_VALOR] UNIQUE NONCLUSTERED ([NB_CATALOGO_VALOR] ASC)
);

