CREATE TABLE [ADM].[C_CLASIFICACION_COMPETENCIA] (
    [ID_CLASIFICACION_COMPETENCIA] INT             IDENTITY (1, 1) NOT NULL,
    [CL_CLASIFICACION]             NVARCHAR (20)   NOT NULL,
    [CL_TIPO_COMPETENCIA]          NVARCHAR (20)   NOT NULL,
    [NB_CLASIFICACION_COMPETENCIA] NVARCHAR (200)  NOT NULL,
    [DS_CLASIFICACION_COMPETENCIA] NVARCHAR (1000) NOT NULL,
    [DS_NOTAS_CLASIFICACION]       NVARCHAR (1000) NULL,
    [CL_COLOR]                     NVARCHAR (20)   NULL,
    [FE_CREACION]                  DATETIME        NOT NULL,
    [FE_MODIFICACION]              DATETIME        NULL,
    [CL_USUARIO_APP_CREA]          NVARCHAR (50)   NOT NULL,
    [CL_USUARIO_APP_MODIFICA]      NVARCHAR (50)   NULL,
    [NB_PROGRAMA_CREA]             NVARCHAR (50)   NOT NULL,
    [NB_PROGRAMA_MODIFICA]         NVARCHAR (50)   NULL,
    [FG_ACTIVO]                    BIT             CONSTRAINT [DF_C_CLASIFICACION_COMPETENCIA_FG_ACTIVO] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_C_CLASIFICACION_COMPETENCIA] PRIMARY KEY CLUSTERED ([ID_CLASIFICACION_COMPETENCIA] ASC),
    CONSTRAINT [FK_C_CLASIFICACION_COMPETENCIA_S_TIPO_COMPETENCIA] FOREIGN KEY ([CL_TIPO_COMPETENCIA]) REFERENCES [ADM].[S_TIPO_COMPETENCIA] ([CL_TIPO_COMPETENCIA]),
    CONSTRAINT [CU_CL_CLASIFICACION] UNIQUE NONCLUSTERED ([CL_CLASIFICACION] ASC),
    CONSTRAINT [CU_NB_CLASIFICACION_COMPETENCIA] UNIQUE NONCLUSTERED ([NB_CLASIFICACION_COMPETENCIA] ASC)
);

