CREATE TABLE [ADM].[C_COMPETENCIA_NIVEL] (
    [ID_NIVEL_COMPETENCIA]         INT             IDENTITY (1, 1) NOT NULL,
    [CL_NIVEL_COMPETENCIA]         NVARCHAR (20)   NOT NULL,
    [NB_NIVEL_COMPETENCIA]         NVARCHAR (100)  NOT NULL,
    [DS_NIVEL_COMPETENCIA_PUESTO]  NVARCHAR (200)  NULL,
    [DS_NIVEL_COMPETENCIA_PERSONA] NVARCHAR (200)  NULL,
    [NO_VALOR_NIVEL]               DECIMAL (10, 2) NULL,
    [ID_COMPETENCIA]               INT             NULL,
    [FE_CREACION]                  DATETIME        NOT NULL,
    [FE_MODIFICACION]              DATETIME        NULL,
    [CL_USUARIO_APP_CREA]          NVARCHAR (50)   NOT NULL,
    [CL_USUARIO_APP_MODIFICA]      NVARCHAR (50)   NULL,
    [NB_PROGRAMA_CREA]             NVARCHAR (50)   NOT NULL,
    [NB_PROGRAMA_MODIFICA]         NVARCHAR (50)   NULL,
    CONSTRAINT [PK_C_COMPETENCIA_NIVEL] PRIMARY KEY CLUSTERED ([ID_NIVEL_COMPETENCIA] ASC)
);

