CREATE TABLE [ADM].[C_COMPETENCIA] (
    [ID_COMPETENCIA]          INT             IDENTITY (1, 1) NOT NULL,
    [CL_COMPETENCIA]          NVARCHAR (32)   NOT NULL,
    [NB_COMPETENCIA]          NVARCHAR (200)  NOT NULL,
    [DS_COMPETENCIA]          NVARCHAR (1000) NULL,
    [CL_TIPO_COMPETENCIA]     NVARCHAR (20)   NOT NULL,
    [CL_CLASIFICACION]        NVARCHAR (200)  NULL,
    [FG_ACTIVO]               BIT             CONSTRAINT [DF_C_COMPETENCIA_FG_ACTIVO] DEFAULT ((1)) NOT NULL,
    [XML_CAMPOS_ADICIONALES]  XML             NULL,
    [FE_CREACION]             DATETIME        NOT NULL,
    [FE_MODIFICACION]         DATETIME        NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)   NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)   NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)   NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)   NULL,
    CONSTRAINT [PK_C_COMPETENCIA] PRIMARY KEY CLUSTERED ([ID_COMPETENCIA] ASC)
);

