CREATE TABLE [ADM].[C_COLONIA] (
    [ID_COLONIA]              INT            IDENTITY (1, 1) NOT NULL,
    [CL_PAIS]                 NVARCHAR (10)  CONSTRAINT [DF_C_COLONIA_CL_PAIS] DEFAULT ('MEX') NOT NULL,
    [CL_ESTADO]               NVARCHAR (10)  NOT NULL,
    [CL_MUNICIPIO]            NVARCHAR (10)  NOT NULL,
    [CL_COLONIA]              NVARCHAR (30)  NOT NULL,
    [NB_COLONIA]              NVARCHAR (100) NOT NULL,
    [CL_TIPO_ASENTAMIENTO]    NVARCHAR (30)  CONSTRAINT [DF_C_COLONIA_CL_TIPO_ASENTAMIENTO] DEFAULT ('COLONIA') NOT NULL,
    [CL_CODIGO_POSTAL]        NVARCHAR (10)  NULL,
    [FE_CREACION]             DATETIME       NOT NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    CONSTRAINT [PK_C_COLONIA] PRIMARY KEY CLUSTERED ([ID_COLONIA] ASC)
);

