CREATE TABLE [ADM].[C_DEPENDIENTE_ECONOMICO] (
    [ID_DEPENDIENTE_ECONOMICO] INT           NOT NULL,
    [NB_DEPENDIENTE_ECONOMICO] NVARCHAR (50) NOT NULL,
    [CL_PARENTEZCO]            NVARCHAR (20) NOT NULL,
    [CL_GENERO]                NVARCHAR (1)  NULL,
    [FE_NACIMIENTO]            DATE          NULL,
    [ID_BITACORA]              INT           NULL,
    [CL_OCUPACION]             BIT           NULL,
    [FG_ACTIVO]                BIT           CONSTRAINT [DF_C_DEPENDIENTE_ECONOMICO_FG_ACTIVO] DEFAULT ((1)) NOT NULL,
    [FE_CREACION]              DATETIME      NOT NULL,
    [FE_MODIFICACION]          DATETIME      NULL,
    [CL_USUARIO_APP_CREA]      NVARCHAR (50) NOT NULL,
    [CL_USUARIO_APP_MODIFICA]  NVARCHAR (50) NULL,
    [NB_PROGRAMA_CREA]         NVARCHAR (50) NOT NULL,
    [NB_PROGRAMA_MODIFICA]     NVARCHAR (50) NULL,
    CONSTRAINT [PK_C_DEPENDIENTE_ECONOMICO] PRIMARY KEY CLUSTERED ([ID_DEPENDIENTE_ECONOMICO] ASC)
);

