CREATE TABLE [ADM].[C_EMPRESA] (
    [ID_EMPRESA]              INT            IDENTITY (1, 1) NOT NULL,
    [CL_EMPRESA]              NVARCHAR (20)  NOT NULL,
    [NB_EMPRESA]              NVARCHAR (100) NOT NULL,
    [NB_RAZON_SOCIAL]         NVARCHAR (200) NOT NULL,
    [FE_CREACION]             DATETIME       NOT NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    CONSTRAINT [PK_C_EMPRESA] PRIMARY KEY CLUSTERED ([ID_EMPRESA] ASC),
    CONSTRAINT [uc_CL_EMPRESA] UNIQUE NONCLUSTERED ([CL_EMPRESA] ASC),
    CONSTRAINT [uc_NB_EMPRESA] UNIQUE NONCLUSTERED ([NB_EMPRESA] ASC)
);

