CREATE TABLE [ADM].[C_ESTADO] (
    [ID_ESTADO]               INT            IDENTITY (1, 1) NOT NULL,
    [CL_PAIS]                 NVARCHAR (10)  CONSTRAINT [DF_C_ESTADO_CL_PAIS] DEFAULT ('MEX') NOT NULL,
    [CL_ESTADO]               NVARCHAR (10)  NOT NULL,
    [NB_ESTADO]               NVARCHAR (100) NOT NULL,
    [FE_CREACION]             DATETIME       NOT NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    CONSTRAINT [PK_C_ESTADO] PRIMARY KEY CLUSTERED ([ID_ESTADO] ASC)
);

