CREATE TABLE [ADM].[C_FUNCION_INDICADOR] (
    [ID_FUNCION_INDICADOR]    INT           IDENTITY (1, 1) NOT NULL,
    [ID_INDICADOR]            INT           NOT NULL,
    [ID_PUESTO_FUNCION]       INT           NOT NULL,
    [ID_PUESTO_COMPETENCIA]   INT           NOT NULL,
    [FE_CREACION]             DATETIME      NOT NULL,
    [FE_MODIFICACION]         DATETIME      NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50) NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50) NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50) NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50) NULL,
    CONSTRAINT [PK_C_FUNCION_INDICADOR] PRIMARY KEY CLUSTERED ([ID_FUNCION_INDICADOR] ASC),
    CONSTRAINT [FK_C_FUNCION_INDICADOR_C_INDICADOR_DESEMPENO] FOREIGN KEY ([ID_INDICADOR]) REFERENCES [ADM].[C_INDICADOR_DESEMPENO] ([ID_INDICADOR]),
    CONSTRAINT [FK_C_FUNCION_INDICADOR_C_PUESTO_COMPETENCIA] FOREIGN KEY ([ID_PUESTO_COMPETENCIA]) REFERENCES [ADM].[C_PUESTO_COMPETENCIA] ([ID_PUESTO_COMPETENCIA]),
    CONSTRAINT [FK_C_FUNCION_INDICADOR_C_PUESTO_FUNCION] FOREIGN KEY ([ID_PUESTO_FUNCION]) REFERENCES [ADM].[C_PUESTO_FUNCION] ([ID_PUESTO_FUNCION])
);

