CREATE TABLE [ADM].[C_GRUPO_PREGUNTA] (
    [ID_GRUPO_PREGUNTA]       INT            NOT NULL,
    [CL_GRUPO_PREGUNTA]       NVARCHAR (20)  NOT NULL,
    [NB_GRUPO_PREGUNTA]       NVARCHAR (200) NULL,
    [ID_PREGUNTA]             INT            NULL,
    [FE_CREACION]             DATETIME       NOT NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    CONSTRAINT [FK_C_GRUPO_PREGUNTA_C_PREGUNTA] FOREIGN KEY ([ID_PREGUNTA]) REFERENCES [ADM].[C_PREGUNTA] ([ID_PREGUNTA])
);

