CREATE TABLE [ADM].[C_IDIOMA] (
    [ID_IDIOMA]               INT            IDENTITY (1, 1) NOT NULL,
    [CL_IDIOMA]               NVARCHAR (20)  NOT NULL,
    [NB_IDIOMA]               NVARCHAR (200) NOT NULL,
    [FG_ACTIVO]               BIT            CONSTRAINT [DF_C_IDIOMA_FG_ACTIVO] DEFAULT ((1)) NOT NULL,
    [FE_CREACION]             DATETIME       NOT NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    CONSTRAINT [PK_C_IDIOMA] PRIMARY KEY CLUSTERED ([ID_IDIOMA] ASC),
    CONSTRAINT [UC_CL_IDIOMA] UNIQUE NONCLUSTERED ([CL_IDIOMA] ASC),
    CONSTRAINT [UC_NB_IDIOMA] UNIQUE NONCLUSTERED ([NB_IDIOMA] ASC)
);

