CREATE TABLE [ADM].[C_INDICADOR_DESEMPENO] (
    [ID_INDICADOR]            INT            NOT NULL,
    [NB_INDICADOR]            NVARCHAR (200) NOT NULL,
    [DS_INDICADOR]            NVARCHAR (200) NOT NULL,
    [FE_CREACION]             DATETIME       NOT NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    CONSTRAINT [PK_C_INDICADOR_DESEMPENO] PRIMARY KEY CLUSTERED ([ID_INDICADOR] ASC)
);

