CREATE TABLE [ADM].[C_NIVEL_ESCOLARIDAD] (
    [ID_NIVEL_ESCOLARIDAD]    INT            IDENTITY (1, 1) NOT NULL,
    [CL_NIVEL_ESCOLARIDAD]    NVARCHAR (100) NOT NULL,
    [DS_NIVEL_ESCOLARIDAD]    NVARCHAR (200) NOT NULL,
    [FG_ACTIVO]               BIT            CONSTRAINT [DF_C_NIVEL_ESCOLARIDAD_FG_ACTIVO] DEFAULT ((1)) NOT NULL,
    [FE_CREACION]             DATETIME       NOT NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    [CL_TIPO_ESCOLARIDAD]     NVARCHAR (20)  NULL,
    CONSTRAINT [PK_C_NIVEL_ESCOLARIDAD] PRIMARY KEY CLUSTERED ([ID_NIVEL_ESCOLARIDAD] ASC)
);

