CREATE TABLE [ADM].[C_PARIENTE] (
    [ID_PARIENTE]             INT            IDENTITY (1, 1) NOT NULL,
    [NB_PARIENTE]             NVARCHAR (200) NOT NULL,
    [CL_PARENTESCO]           NVARCHAR (20)  NOT NULL,
    [CL_GENERO]               NVARCHAR (1)   NULL,
    [FE_NACIMIENTO]           DATE           NOT NULL,
    [ID_EMPLEADO]             INT            NULL,
    [ID_CANDIDATO]            INT            NULL,
    [ID_BITACORA]             INT            NULL,
    [CL_OCUPACION]            NVARCHAR (50)  NULL,
    [FG_DEPENDIENTE]          BIT            CONSTRAINT [DF_C_PARIENTE_FG_DEPENDIENTE] DEFAULT ((0)) NOT NULL,
    [FG_ACTIVO]               BIT            CONSTRAINT [DF_C_PARIENTE_FG_ACTIVO] DEFAULT ((1)) NOT NULL,
    [FE_CREACION]             DATETIME       NOT NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    CONSTRAINT [PK_C_PARIENTE] PRIMARY KEY CLUSTERED ([ID_PARIENTE] ASC)
);

