CREATE TABLE [ADM].[C_PERIODO] (
    [ID_PERIODO]              INT            NOT NULL,
    [CL_PERIODO]              NVARCHAR (32)  NOT NULL,
    [NB_PERIODO]              NVARCHAR (100) NOT NULL,
    [DS_PERIODO]              NVARCHAR (200) NULL,
    [FE_INICIO]               BIT            CONSTRAINT [DF_C_PERIODO_FE_INICIO] DEFAULT ((0)) NOT NULL,
    [FE_TERMINO]              NVARCHAR (200) NULL,
    [CL_ESTADO_PERIODO]       NVARCHAR (20)  NOT NULL,
    [XML_CAMPOS_ADICIONALES]  XML            NULL,
    [FE_CREACION]             DATETIME       NOT NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    CONSTRAINT [PK_C_PERIODO] PRIMARY KEY CLUSTERED ([ID_PERIODO] ASC)
);

