CREATE TABLE [ADM].[C_PLANTILLA_FORMULARIO] (
    [ID_PLANTILLA_SOLICITUD]  INT            IDENTITY (1, 1) NOT NULL,
    [NB_PLANTILLA_SOLICITUD]  NVARCHAR (100) NOT NULL,
    [DS_PLANTILLA_SOLICITUD]  NVARCHAR (500) NOT NULL,
    [CL_FORMULARIO]           NVARCHAR (20)  NOT NULL,
    [FG_GENERAL]              BIT            CONSTRAINT [DF_C_PLANTILLA_FORMULARIO_FG_GENERAL] DEFAULT ((0)) NOT NULL,
    [XML_PLANTILLA_SOLICITUD] XML            NOT NULL,
    [FE_CREACION]             DATETIME       NOT NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    CONSTRAINT [PK_C_PLANTILLA_FORMULARIO] PRIMARY KEY CLUSTERED ([ID_PLANTILLA_SOLICITUD] ASC)
);

