CREATE TABLE [ADM].[C_PUESTO_RELACIONADO] (
    [ID_PUESTO]               INT            NOT NULL,
    [ID_PUESTO_RELACIONADO]   INT            NOT NULL,
    [CL_TIPO_RELACION]        NVARCHAR (20)  NOT NULL,
    [DS_PUESTO_RELACIONADO]   NVARCHAR (500) NULL,
    [FE_CREACION]             DATETIME       NOT NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    CONSTRAINT [FK_C_PUESTO_RELACIONADO_M_PUESTO] FOREIGN KEY ([ID_PUESTO]) REFERENCES [ADM].[M_PUESTO] ([ID_PUESTO]),
    CONSTRAINT [FK_C_PUESTO_RELACIONADO_S_TIPO_RELACION_PUESTO] FOREIGN KEY ([CL_TIPO_RELACION]) REFERENCES [ADM].[S_TIPO_RELACION_PUESTO] ([CL_TIPO_RELACION])
);

