CREATE TABLE [ADM].[C_PUESTO_FUNCION] (
    [ID_PUESTO_FUNCION]       INT            IDENTITY (1, 1) NOT NULL,
    [CL_PUESTO_FUNCION]       NVARCHAR (20)  NULL,
    [NB_PUESTO_FUNCION]       NVARCHAR (100) NOT NULL,
    [DS_PUESTO_FUNCION]       NVARCHAR (500) NULL,
    [ID_PUESTO]               INT            NOT NULL,
    [XML_DETALLE]             XML            NULL,
    [XML_NOTAS]               XML            NULL,
    [FE_CREACION]             DATETIME       NOT NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    CONSTRAINT [PK_C_PUESTO_FUNCION] PRIMARY KEY CLUSTERED ([ID_PUESTO_FUNCION] ASC)
);

