CREATE TABLE [ADM].[C_PUESTO_COMPETENCIA] (
    [ID_PUESTO_COMPETENCIA]   INT           IDENTITY (1, 1) NOT NULL,
    [ID_PUESTO]               INT           NOT NULL,
    [ID_COMPETENCIA]          INT           NOT NULL,
    [ID_NIVEL_DESEADO]        INT           NULL,
    [ID_PUESTO_FUNCION]       INT           NULL,
    [CL_TIPO_COMPETENCIA]     NVARCHAR (20) NULL,
    [FE_CREACION]             DATETIME      NOT NULL,
    [FE_MODIFICACION]         DATETIME      NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50) NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50) NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50) NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50) NULL,
    CONSTRAINT [PK_C_PUESTO_COMPETENCIA] PRIMARY KEY CLUSTERED ([ID_PUESTO_COMPETENCIA] ASC),
    CONSTRAINT [FK_C_PUESTO_COMPETENCIA_C_COMPETENCIA] FOREIGN KEY ([ID_COMPETENCIA]) REFERENCES [ADM].[C_COMPETENCIA] ([ID_COMPETENCIA]),
    CONSTRAINT [FK_C_PUESTO_COMPETENCIA_C_PUESTO_FUNCION] FOREIGN KEY ([ID_PUESTO_FUNCION]) REFERENCES [ADM].[C_PUESTO_FUNCION] ([ID_PUESTO_FUNCION]),
    CONSTRAINT [FK_C_PUESTO_COMPETENCIA_M_PUESTO] FOREIGN KEY ([ID_PUESTO]) REFERENCES [ADM].[M_PUESTO] ([ID_PUESTO])
);

