CREATE TABLE [ADM].[C_RESPUESTA] (
    [ID_RESPUESTA]            INT            IDENTITY (1, 1) NOT NULL,
    [CL_RESPUESTA]            NVARCHAR (32)  NOT NULL,
    [NB_RESPUESTA]            NVARCHAR (100) NOT NULL,
    [DS_RESPUESTA]            NVARCHAR (200) NULL,
    [NO_VALOR]                DECIMAL (8, 3) CONSTRAINT [DF_C_RESPUESTA_NO_VALOR] DEFAULT ((0)) NOT NULL,
    [FG_ACTIVO]               BIT            CONSTRAINT [DF_C_RESPUESTA_FG_ACTIVO] DEFAULT ((1)) NOT NULL,
    [FE_CREACION]             DATETIME       NOT NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    CONSTRAINT [PK_C_RESPUESTA] PRIMARY KEY CLUSTERED ([ID_RESPUESTA] ASC)
);

