CREATE TABLE [ADM].[C_ROL_FUNCION] (
    [ID_ROL]     INT NOT NULL,
    [ID_FUNCION] INT NOT NULL,
    CONSTRAINT [FK_C_ROL_FUNCION_C_ROL] FOREIGN KEY ([ID_ROL]) REFERENCES [ADM].[C_ROL] ([ID_ROL]),
    CONSTRAINT [FK_C_ROL_FUNCION_S_FUNCION] FOREIGN KEY ([ID_FUNCION]) REFERENCES [ADM].[S_FUNCION] ([ID_FUNCION])
);

