CREATE TABLE [ADM].[C_USUARIO] (
    [CL_USUARIO]              NVARCHAR (50)  NOT NULL,
    [NB_USUARIO]              NVARCHAR (300) NOT NULL,
    [NB_CORREO_ELECTRONICO]   NVARCHAR (300) NOT NULL,
    [NB_PASSWORD]             NVARCHAR (100) NOT NULL,
    [FE_CAMBIAR_PASSWORD]     DATETIME       NULL,
    [CL_CAMBIAR_PASSWORD]     NVARCHAR (100) NULL,
    [FG_CAMBIAR_PASSWORD]     BIT            NOT NULL,
    [XML_PERSONALIZACION]     XML            NULL,
    [ID_ROL]                  INT            NOT NULL,
    [ID_EMPLEADO]             INT            NULL,
    [FG_ACTIVO]               BIT            NOT NULL,
    [FE_INACTIVO]             DATETIME       NULL,
    [FE_CREACION]             DATETIME       NOT NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    CONSTRAINT [PK__C_USUARI__70851B1EF9507A51] PRIMARY KEY CLUSTERED ([CL_USUARIO] ASC),
    CONSTRAINT [UC_NB_CORREO_ELECTRONICO] UNIQUE NONCLUSTERED ([NB_CORREO_ELECTRONICO] ASC)
);

