CREATE TABLE [ADM].[H_DEPARTAMENTO] (
    [ID_DEPARTAMENTO_H]       INT            IDENTITY (1, 1) NOT NULL,
    [CL_PERIODO_INICIO]       INT            NOT NULL,
    [CL_PERIODO_TERMINO]      INT            CONSTRAINT [DF_H_DEPARTAMENTO_CL_PERIODO_TERMINO] DEFAULT ((299912)) NOT NULL,
    [ID_DEPARTAMENTO]         INT            NOT NULL,
    [FG_ACTIVO]               BIT            CONSTRAINT [DF_H_DEPARTAMENTO_FG_ACTIVO] DEFAULT ((1)) NOT NULL,
    [FE_INACTIVO]             DATETIME       NULL,
    [CL_DEPARTAMENTO]         NVARCHAR (30)  NOT NULL,
    [NB_DEPARTAMENTO]         NVARCHAR (100) NOT NULL,
    [XML_CAMPOS_ADICIONALES]  XML            NOT NULL,
    [FE_CREACION]             DATETIME       NOT NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    CONSTRAINT [PK_H_DEPARTAMENTO] PRIMARY KEY CLUSTERED ([ID_DEPARTAMENTO_H] ASC)
);

