CREATE TABLE [ADM].[H_EMPLEADO] (
    [ID_EMPLEADO_H]           INT            IDENTITY (1, 1) NOT NULL,
    [CL_PERIODO_INICIO]       INT            NOT NULL,
    [CL_PERIODO_TERMINO]      INT            CONSTRAINT [DF_H_EMPLEADO_CL_PERIODO_TERMINO] DEFAULT ((299912)) NOT NULL,
    [ID_EMPLEADO]             INT            NOT NULL,
    [CL_EMPLEADO]             NVARCHAR (20)  NOT NULL,
    [NB_EMPLEADO]             NVARCHAR (100) NOT NULL,
    [FG_ACTIVO]               BIT            CONSTRAINT [DF_H_EMPLEADO_FG_ACTIVO] DEFAULT ((1)) NOT NULL,
    [FE_INACTIVO]             DATETIME       NULL,
    [ID_PUESTO]               INT            NOT NULL,
    [ID_DEPARTAMENTO]         INT            NOT NULL,
    [ID_EMPLEADO_JEFE]        INT            NULL,
    [CL_RUTA_FOTOGRAFIA]      NVARCHAR (255) NULL,
    [XML_CAMPOS_ADICIONALES]  XML            NOT NULL,
    [FE_CREACION]             DATETIME       NOT NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    CONSTRAINT [PK_H_EMPLEADO] PRIMARY KEY CLUSTERED ([ID_EMPLEADO_H] ASC)
);

