CREATE TABLE [ADM].[K_AREA_INTERES] (
    [ID_CANDIDATO_AREA_INTERES] INT           IDENTITY (1, 1) NOT NULL,
    [ID_CANDIDATO]              INT           NOT NULL,
    [ID_AREA_INTERES]           INT           NOT NULL,
    [FE_CREACION]               DATETIME      NOT NULL,
    [FE_MODIFICACION]           DATETIME      NULL,
    [CL_USUARIO_APP_CREA]       NVARCHAR (50) NOT NULL,
    [CL_USUARIO_APP_MODIFICA]   NVARCHAR (50) NULL,
    [NB_PROGRAMA_CREA]          NVARCHAR (50) NOT NULL,
    [NB_PROGRAMA_MODIFICA]      NVARCHAR (50) NULL,
    CONSTRAINT [PK_K_AREA_INTERES] PRIMARY KEY CLUSTERED ([ID_CANDIDATO_AREA_INTERES] ASC),
    CONSTRAINT [FK_C_AREA_INTERES] FOREIGN KEY ([ID_AREA_INTERES]) REFERENCES [ADM].[C_AREA_INTERES] ([ID_AREA_INTERES])
);

