CREATE TABLE [ADM].[K_CUESTIONARIO_PREGUNTA] (
    [ID_CUESTIONARIO_PREGUNTA] INT            IDENTITY (1, 1) NOT NULL,
    [ID_CUESTIONARIO]          INT            NOT NULL,
    [ID_PREGUNTA]              INT            NOT NULL,
    [NB_PREGUNTA]              NVARCHAR (300) NOT NULL,
    [NB_RESPUESTA]             NVARCHAR (300) NULL,
    [NO_VALOR_RESPUESTA]       DECIMAL (8, 3) NULL,
    [FE_CREACION]              DATETIME       NOT NULL,
    [FE_MODIFICACION]          DATETIME       NULL,
    [CL_USUARIO_APP_CREA]      NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA]  NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]         NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]     NVARCHAR (50)  NULL,
    CONSTRAINT [PK_K_CUESTIONARIO_PREGUNTA] PRIMARY KEY CLUSTERED ([ID_CUESTIONARIO_PREGUNTA] ASC),
    CONSTRAINT [FK_K_CUESTIONARIO_PREGUNTA_C_PREGUNTA] FOREIGN KEY ([ID_PREGUNTA]) REFERENCES [ADM].[C_PREGUNTA] ([ID_PREGUNTA]),
    CONSTRAINT [FK_K_CUESTIONARIO_PREGUNTA_K_CUESTIONARIO] FOREIGN KEY ([ID_CUESTIONARIO]) REFERENCES [ADM].[K_CUESTIONARIO] ([ID_CUESTIONARIO])
);

