CREATE TABLE [ADM].[K_CUESTIONARIO] (
    [ID_CUESTIONARIO]         INT           IDENTITY (1, 1) NOT NULL,
    [ID_EVALUADO]             INT           NULL,
    [ID_EVALUADO_EVALUADOR]   INT           NULL,
    [FE_CREACION]             DATETIME      NOT NULL,
    [FE_MODIFICACION]         DATETIME      NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50) NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50) NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50) NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50) NULL,
    CONSTRAINT [PK_K_CUESTIONARIO] PRIMARY KEY CLUSTERED ([ID_CUESTIONARIO] ASC),
    CONSTRAINT [FK_K_CUESTIONARIO_K_EVALUADO_EVALUADOR] FOREIGN KEY ([ID_EVALUADO_EVALUADOR]) REFERENCES [ADM].[K_EVALUADO_EVALUADOR] ([ID_EVALUADO_EVALUADOR])
);

