CREATE TABLE [ADM].[K_EMPLEADO_COMPETENCIA] (
    [ID_EMPLEADO_COMPETENCIA] INT            IDENTITY (1, 1) NOT NULL,
    [ID_EMPLEADO]             INT            NOT NULL,
    [ID_COMPETENCIA]          INT            NOT NULL,
    [NO_CALIFICACION]         DECIMAL (8, 3) NOT NULL,
    [FE_CREACION]             DATETIME       NOT NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    CONSTRAINT [PK_K_EMPLEADO_COMPETENCIA] PRIMARY KEY CLUSTERED ([ID_EMPLEADO_COMPETENCIA] ASC),
    CONSTRAINT [FK_K_EMPLEADO_COMPETENCIA_C_COMPETENCIA] FOREIGN KEY ([ID_COMPETENCIA]) REFERENCES [ADM].[C_COMPETENCIA] ([ID_COMPETENCIA])
);

