CREATE TABLE [ADM].[K_ERROR] (
    [ID_ERROR]            UNIQUEIDENTIFIER NOT NULL,
    [CL_CLAVE]            INT              NOT NULL,
    [DS_ERROR]            NVARCHAR (250)   NOT NULL,
    [FE_CREACION]         DATETIME         NOT NULL,
    [CL_USUARIO_APP_CREA] NVARCHAR (50)    NOT NULL,
    [NB_PROGRAMA_CREA]    NVARCHAR (50)    NOT NULL,
    CONSTRAINT [PK_K_ERROR] PRIMARY KEY CLUSTERED ([ID_ERROR] ASC)
);

