CREATE TABLE [ADM].[K_EVALUADO_EVALUADOR] (
    [ID_EVALUADO_EVALUADOR]   INT            IDENTITY (1, 1) NOT NULL,
    [ID_PERIODO]              INT            NOT NULL,
    [ID_EVALUADOR_PERIODO]    INT            NOT NULL,
    [ID_PUESTO_EVALUADOR]     INT            NOT NULL,
    [NO_VALOR]                DECIMAL (8, 3) NULL,
    [FE_CREACION]             DATETIME       NOT NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    CONSTRAINT [PK_K_EVALUADO_EVALUADOR] PRIMARY KEY CLUSTERED ([ID_EVALUADO_EVALUADOR] ASC),
    CONSTRAINT [FK_K_EVALUADO_EVALUADOR_C_PERIODO] FOREIGN KEY ([ID_PERIODO]) REFERENCES [ADM].[C_PERIODO] ([ID_PERIODO]),
    CONSTRAINT [FK_K_EVALUADO_EVALUADOR_K_EVALUADO_PERIODO] FOREIGN KEY ([ID_EVALUADOR_PERIODO]) REFERENCES [ADM].[K_EVALUADO_PERIODO] ([ID_EVALUADOR_PERIODO])
);

