CREATE TABLE [ADM].[K_REQUISICION] (
    [ID_REQUISICION]          INT            IDENTITY (1, 1) NOT NULL,
    [NO_REQUISICION]          NVARCHAR (20)  NOT NULL,
    [FE_SOLICITUD]            DATETIME       NOT NULL,
    [FE_REQUERIMIENTO]        DATETIME       NULL,
    [ID_PUESTO]               INT            NOT NULL,
    [CL_ESTADO]               NVARCHAR (20)  NOT NULL,
    [CL_CAUSA]                NVARCHAR (20)  NOT NULL,
    [DS_CAUSA]                NVARCHAR (100) NULL,
    [ID_NOTIFICACION]         INT            NULL,
    [ID_SOLICITANTE]          INT            NULL,
    [ID_AUTORIZA]             INT            NULL,
    [ID_VISTO_BUENO]          INT            NULL,
    [ID_EMPRESA]              INT            NOT NULL,
    [FE_CREACION]             DATETIME       NOT NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    CONSTRAINT [PK_K_REQUISICION] PRIMARY KEY CLUSTERED ([ID_REQUISICION] ASC),
    CONSTRAINT [uc_NO_REQUISICION] UNIQUE NONCLUSTERED ([NO_REQUISICION] ASC)
);

