CREATE TABLE [ADM].[M_DEPARTAMENTO] (
    [ID_DEPARTAMENTO]         INT            IDENTITY (1, 1) NOT NULL,
    [FG_ACTIVO]               BIT            CONSTRAINT [DF_M_DEPARTAMENTO_FG_ACTIVO] DEFAULT ((1)) NOT NULL,
    [FE_INACTIVO]             DATETIME       NULL,
    [CL_DEPARTAMENTO]         NVARCHAR (30)  NOT NULL,
    [NB_DEPARTAMENTO]         NVARCHAR (100) NOT NULL,
    [XML_CAMPOS_ADICIONALES]  XML            NULL,
    [FE_CREACION]             DATETIME       NOT NULL,
    [FE_MODIFICACION]         DATETIME       NULL,
    [CL_USUARIO_APP_CREA]     NVARCHAR (50)  NOT NULL,
    [CL_USUARIO_APP_MODIFICA] NVARCHAR (50)  NULL,
    [NB_PROGRAMA_CREA]        NVARCHAR (50)  NOT NULL,
    [NB_PROGRAMA_MODIFICA]    NVARCHAR (50)  NULL,
    CONSTRAINT [PK_M_DEPARTAMENTO] PRIMARY KEY CLUSTERED ([ID_DEPARTAMENTO] ASC),
    CONSTRAINT [uc_CL_DEPARTAMENTO] UNIQUE NONCLUSTERED ([CL_DEPARTAMENTO] ASC)
);

