CREATE TABLE [ADM].[S_CATALOGO_TIPO] (
    [ID_CATALOGO_TIPO] INT             IDENTITY (1, 1) NOT NULL,
    [NB_CATALOGO_TIPO] NVARCHAR (100)  NOT NULL,
    [DS_CATALOGO_TIPO] NVARCHAR (1000) NULL,
    CONSTRAINT [PK_S_CATALOGO_TIPO] PRIMARY KEY CLUSTERED ([ID_CATALOGO_TIPO] ASC)
);

