CREATE TABLE [ADM].[S_CONFIGURACION] (
    [XML_CONFIGURACION]    XML           NOT NULL,
    [FE_MODIFICACION]      DATETIME      NOT NULL,
    [CL_USUARIO_MODIFICA]  NVARCHAR (50) NOT NULL,
    [NB_PROGRAMA_MODIFICA] NVARCHAR (50) NOT NULL
);

