CREATE TABLE [ADM].[S_FUNCION] (
    [ID_FUNCION]        INT            NOT NULL,
    [CL_FUNCION]        NVARCHAR (30)  NOT NULL,
    [CL_TIPO_FUNCION]   NVARCHAR (100) NOT NULL,
    [NB_FUNCION]        NVARCHAR (100) NOT NULL,
    [ID_FUNCION_PADRE]  INT            NULL,
    [NB_URL]            NVARCHAR (500) NULL,
    [XML_CONFIGURACION] XML            NULL,
    [NO_ORDEN]          TINYINT        CONSTRAINT [DF_S_FUNCION_NO_ORDEN] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_S_FUNCION] PRIMARY KEY CLUSTERED ([ID_FUNCION] ASC)
);

