CREATE TABLE [ADM].[S_TIPO_RELACION_PUESTO] (
    [CL_TIPO_RELACION] NVARCHAR (20)  NOT NULL,
    [NB_TIPO_RELACION] NVARCHAR (100) NOT NULL,
    [DS_TIPO_RELACION] NVARCHAR (200) NOT NULL,
    CONSTRAINT [PK_S_TIPO_RELACION_PUESTO] PRIMARY KEY CLUSTERED ([CL_TIPO_RELACION] ASC)
);

