CREATE TABLE [ADM].[S_TIPO_COMPETENCIA] (
    [CL_TIPO_COMPETENCIA] NVARCHAR (20)  NOT NULL,
    [NB_TIPO_COMPETENCIA] NVARCHAR (100) NOT NULL,
    [DS_TIPO_COMPETENCIA] NVARCHAR (200) NOT NULL,
    [FG_ACTIVO]           BIT            CONSTRAINT [DF_S_TIPO_COMPETENCIA_FG_ACTIVO] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_S_TIPO_COMPETENCIA] PRIMARY KEY CLUSTERED ([CL_TIPO_COMPETENCIA] ASC),
    CONSTRAINT [uc_CL_TIPO_COMPETENCIA] UNIQUE NONCLUSTERED ([CL_TIPO_COMPETENCIA] ASC),
    CONSTRAINT [uc_NB_TIPO_COMPETENCIA] UNIQUE NONCLUSTERED ([NB_TIPO_COMPETENCIA] ASC)
);

