-- =============================================
-- Author:		Julio Díaz
-- Create date: 25/11/2015
-- Description:	Función para crear los mensajes comunes de error
-- =============================================
CREATE FUNCTION [dbo].[F_ERROR_MENSAJES]
(
	@PIN_NO_ERROR INT
	,@PIN_ERROR_MENSAJE NVARCHAR(250)
)
RETURNS XML
AS
BEGIN
	DECLARE @XML_RESULTADO XML
		-- EL XML DEVUELVE EL ERROR INDICADO POR SQL Y UN MSJ DE ERROR GENÉRICO

	IF @PIN_NO_ERROR = 2627 BEGIN
		SET @XML_RESULTADO = DBO.F_ERROR_CREAR_ENCABEZADO( @@ROWCOUNT, @PIN_NO_ERROR, 'WARNING')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'Este campo ya se encuentra en uso.', 'ES')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'Este campo ya se encuentra en uso.', 'EN')
	END ELSE IF @PIN_NO_ERROR = 547 BEGIN
		SET @XML_RESULTADO = DBO.F_ERROR_CREAR_ENCABEZADO( @@ROWCOUNT, @PIN_NO_ERROR, 'WARNING')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'No se puede eliminar porque tiene datos relacionados.', 'ES')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, 'No se puede eliminar porque tiene datos relacionados.', 'EN')
	END ELSE BEGIN
		SET @XML_RESULTADO = DBO.F_ERROR_CREAR_ENCABEZADO( @@ROWCOUNT, @PIN_NO_ERROR, 'ERROR')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, @PIN_ERROR_MENSAJE, 'ES')
		SET @XML_RESULTADO = DBO.F_ERROR_INSERTAR_MENSAJES(@XML_RESULTADO, @PIN_ERROR_MENSAJE, 'EN')
	END

	RETURN @XML_RESULTADO

END
